### ISSUE TITLE
JS event handler broken after redirect

### ISSUE THREAD

**Issue by mattficke** [ga-wdi-exercises/project2#100]
I have a "get location" button that's displayed on every page. Clicking it changes the URL.

This event handler works fine in my development environment, but on the deployed version (cunningham.herokuapp.com) it won't work after a redirect until I reload the page, at which point it works as expected.

My guess is that `$(document).ready()` doesn't work with `window.location.replace`, but I'm not sure how to fix it, and since the error doesn't show up on my local machine it's hard to debug.

Any thoughts?

```
function success(pos) {
  var crd = pos.coords;
  window.location.replace('/feeds/?lat='+ crd.latitude + '&lng=' + crd.longitude)
};

$(document).ready(function() {
  $("#get").on("click", function() {
    // console.log("#get clicked")
    navigator.geolocation.getCurrentPosition(success, error, options);
  })
})
```

**Comment by adambray** [comment]
It's definitely an issue with turbolinks. See here:
http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

**Comment by adambray** [comment]
Feel free to re-open this if you have more questions about this issue.
