### ISSUE TITLE
User agent style sheets

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project2#101]
Am trying to create a navigation bar at the top of my screen to store my logo to the left and links to the right.  Trying to make the logo(which is just a h1) an inline-block, but the user-agent stylesheet is blocking my style sheet and keeping it as a block, killing me with margin-right.  Not sure how to reorder it b/c of the rails tag: 

```
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
```

which is making the application take precedence in the cascade.  Is there a way to reorder the cascade within the tag???  Do I need to hard code the links?

**Comment by RobertAKARobin** [comment]
You shouldn't need to do anything with that `stylesheet_link_tag`; you can just leave it alone. All you should need to do is edit the CSS in `app/assets/stylesheets/application.css` (or whatever the file name is). Anything you put in there will override the default/user-agent stylesheet.

Note that you can add classes to links like so:

```
<%= link_to "Whatever", artist_path(@artist), class: "bigass_link" %>
```

**Comment by Ryan-321** [comment]
Worked, thx Robin!
