### ISSUE TITLE
Sub Question

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project2#103]
```
<% if session[:user] %>
  <a href="/sign_out"><%= session[:user]["username"] %>: sign out</a>
  <%= link_to "Home" , recipes_path %>
  <%= link_to "User Home" , user_recipes_path %>
  <%= link_to "Create New Recipe" , new_recipe_path(@recipe) %>
            <% if   "on new.html.erb"%>
            add links below???
<% else %>
  <a href="/sign_in">Sign in</a>
  <a href="/sign_up">Sign up</a>
<% end %>
```

Given the above code can I add another if statement within that if statement, adding links based on what page they are on?

**Comment by RobertAKARobin** [comment]
You can have as many nested `if` as you want!

**Comment by andrewsunglaekim** [comment]
when you find yourself nesting `if` statements on your view layer, you may be starting to have too much logic in your view. Try taking some of that logic out of the view and into the controller or model instead.

**Comment by RobertAKARobin** [comment]
One thing you might consider doing is using `app/helpers/application_helper.rb`. That lets you define methods you can use in views. For instance:

```
module ApplicationHelper

  def is_signed_in?
    if session[:user]
      return true
    else
      return false
    end
  end

  def my_name
    return "Robin"
  end

end
```

...and then in my view:

```
<% if is_signed_in? %>
  <h1>Hi, <%= my_name %>!</h1>
<% end %>
```

**Comment by Ryan-321** [comment]
Makes sense, thanks guys!!!
