### ISSUE TITLE
issue with many to many relationships

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#105]
I tried to create a many to many relationship between tags and photos using a join table called Category/Categories. The models are correct, but my error is occurring when I try to click a tag from the tag#index. I expected to see a list of all the photos with that tag but the error I got was
ActiveRecord::RecordNotFound in TagsController#show

```
Couldn't find Photo with 'id'=

  def show
    @tag = Tag.find(params[:id])
ERROR LINE    @photo = Photo.find(params[:photo_id])
  end
```

  #update

**Comment by amaseda** [comment]
What does your route for that page look like?

**Comment by walter-0** [comment]
<p>
  <% @tags.each do |tag| %>
  <%= link_to tag.tag_name, tag_path(tag) %>
  <% end %>
</p>
goes to
http://localhost:3000/tags/5

**Comment by amaseda** [comment]
Looks like you're trying to access a :photo_id value that does not exist.
Your URL only has an :id for a tag. Perhaps you can access a tag's photos
using ActiveRecord methods that make use of your model associations? Let me
know if you need help with that.

**Comment by walter-0** [comment]
I changed the show page to

```
  def show
    @tag = Tag.find(params[:id])
    @photo = @tag.photos
  end
```

and now the show page has hard coded text. Will update if more progress is made.

**Comment by amaseda** [comment]
Sounds good, let us know if you have any other questions on this.

**Comment by walter-0** [comment]
I'm confused on how to use the add_photo action in order to associate the photos and tags in the category join table.

**Comment by RobertAKARobin** [comment]
Oops! Make sure you click the "Reopen" button or we won't see this.

**Comment by RobertAKARobin** [comment]
What is this `add_photo` action you speak of?

**Comment by walter-0** [comment]
In the tag controller, I have an action add_photo

```
def add_photo
    @photo = Photo.find(params[:photo_id])
    @tag = Tag.find(params[:id])
    @tag.categories.create(photo_id: params[:photo_id])
    redirect_to photo_path(@photo)
  end
```

It's supposed to add a photo and tag to a join table called categories.

**Comment by RobertAKARobin** [comment]
Cool! When you say "you're confused how to use it", can you tell me where and how you're intending to use it?

**Comment by walter-0** [comment]
I want to use it on the photo show page to be able to type in a tag name and add the photo and its tag to the join table category.
