### ISSUE TITLE
Join Table Concept Idea

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#106]
I currently have users and posts. I want to include categories. Categories would have many posts and posts belong to many categories. I know that posts would have a category column. I am having trouble figuring out what would go in the categories table. I don't believe it would be post_id because I don't want all posts, I just want to filter the through the posts. 

I then think a join table is needed. I would have nested routes of categories and posts. The join table would pull a post id and a category id. Is my line of thinking on the right path?

**Comment by andrewsunglaekim** [comment]
so basically you would want posts to have many categories and categories to have many posts? I don't think you would need a nested resource neccessarily, depends on how you handle your domain model

**Comment by malissaromero** [comment]
Yes. My idea is users can learn command shortcuts like "Command C". Users can write many posts. Posts belong to user. Categories have many posts like Ruby shortcut or terminal shortcut. Posts belong to many categories such as Ruby or Beginner categories.

**Comment by andrewsunglaekim** [comment]
You don't even necessarily have to pigeon whole yourself into using nested resources or even resources. Your controller actions and routes can be mapped however you want them to be, just like we did when we ported sinatra tunr to rails.

**Comment by malissaromero** [comment]
Can join tables filter? I would want my category to filter through posts using a category column in my posts table or would a user have to submit a number that references a category like 1 is Ruby, 2 is Terminal.

**Comment by andrewsunglaekim** [comment]
Pure join tables offer an ability for us to query the database more effectively for many-to-many associations.

Do you already have an MVP? If so I would go for it. The many to many relationship. If you don't have an MVP yet, i would recommend doing a normal category `has_many` posts association instead. But you are thinking about it correctly.

**Comment by malissaromero** [comment]
I have my MVP. I am not sure how to do it without a join table because posts belong to many categories.
