### ISSUE TITLE
current_user

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-wdi-exercises/project2#109]
Hey guys, 
Just finished with users and authentication. 
Trying to set the current user with:
`def current_user
   return unless session[:user_id]
   @current_user ||= User.find(session[:user_id])
 end`
in the application_controller. 
Keeps returning nil as the value of @current_user, regardless if I am signed in or not. 
Wondering if you could help troubleshoot, or had any advice.

**Comment by adambray** [comment]
@phantomhaircuts :
1. Are you calling the method, using `current_user`? If you reference the instance variable `@current_user`, it won't ever get set. Only the `current_user` method works here. The instance variable is only used in that method for performance reasons.
2. Make sure your sign in functionality is setting `session[:user_id]`.

-Adam

**Comment by adambray** [comment]
Closing this, but feel free to reopen if you have followup questions.
