### ISSUE TITLE
project 2 planning and topic

### ISSUE THREAD

**Issue by nolds9** [ga-wdi-exercises/project2#11]
Repo: https://github.com/nolds9/wdi_project_2

Topic:

Building an education platform where uses can take courses through video lessons.

**Comment by mattscilipoti** [comment]
Looking good. 

Feel free to link to your User Story file in your readme: https://github.com/nolds9/wdi_project_2/blob/master/planning/user_stories.md

I'm looking forward to seeing how you will present/manage the lessons and choices.
