### ISSUE TITLE
I need help with my css styling.

### ISSUE THREAD

**Issue by Thesheik** [ga-wdi-exercises/project2#110]
I am trying to make my web app look nice and decent but I am having issues getting there. I have downloaded the bootstrap but no luck still.

**Comment by mattscilipoti** [comment]
Could you be more specific.  What problem are you trying to solve?  Why did you feel Twitter Bootstrap would solve it?

**Comment by Thesheik** [comment]
I am trying to have a nav bar or main bar

**Comment by RobertAKARobin** [comment]
Can you share the code you have tried so far, and tell us what isn't working about it?

It's hard for us to respond to just "I am having issues"!

**Comment by Thesheik** [comment]
Based on some of my classmates bootstrap will give you better css layout

**Comment by Thesheik** [comment]
```
  here is the code 
 @import "bootstrap-sprockets";
  @import "bootstrap";

#head{
  float: right;
  border-style: solid;
  width: 100%;
  height: 10em;
  padding: 5px;
  display: inline-flex;
}

li{
  display: block;
}
```

**Comment by RobertAKARobin** [comment]
That looks good! Can you be more specific about what isn't working?

That is: What about your nav bar doesn't look the way you want it to?

**Comment by Thesheik** [comment]
Sorry that was my css code but here is my html code
  <header>
    <div id="head">
      <div class="primary">

```
    <div id="logo">
      <h1>Healthy Taste</h1>
    </div>

  </div>
<ul>
    <li>
      <%= button_to "Home", root_path, method: :get %>
    </li>
      <% if user_signed_in? %>
      <li>
        Welcome <%= current_user.email %>
      </li>
    <li>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </li>

    <% else %>
    <li>
      <%= button_to "Login",  new_user_session_path %>
      or
      <%= button_to "Signup",  new_user_registration_path, method: :get %>
    </li>
    <% end %>
```

**Comment by Thesheik** [comment]
I am trying to have the signup/ login/ logo and home links to show within the main bar at the top of the page

**Comment by RobertAKARobin** [comment]
Can you take a screenshot? Just press Command + Shift + 4 on your keyboard. That'll save a picture to your desktop. Then just drag and drop it onto the comment box on this page. (See how it says "Attach images by dragging & dropping") below.

**Comment by RobertAKARobin** [comment]
If you include a screenshot and your code the next time you submit a CSS issue, we should be able to solve the problem much more quickly!

**Comment by RobertAKARobin** [comment]
Command + Shift + 3 will take a picture of your entire screen.

Command + Shift + 4 will let you drag and drop your mouse to select and take a picture of an area of your screen.

**Comment by Thesheik** [comment]
Got u.

<img width="1280" alt="screen shot 2015-08-05 at 1 02 59 pm" src="https://cloud.githubusercontent.com/assets/12532629/9092163/6107b26e-3b72-11e5-8639-250ab61ec080.png">

**Comment by RobertAKARobin** [comment]
Oh, I'm sorry. I meant a screenshot of how the webpage shows up.

**Comment by mattscilipoti** [comment]
Please be more specific.  What do you mean by "I am trying to have a nav bar or main bar"?  What instructions are you following?

**Comment by RobertAKARobin** [comment]
I believe Andy worked this out with Cheikh, so I'm going to close it for now. If there are continued issues, please reopen it!
