### ISSUE TITLE
Updating a User model

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#111]
I currently have the same user functionality that is in the Users and Auth lesson. 

I want to be able to edit and update a user, as of right now I have created an edit and update actions in the users_controller 

```
def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(
      first_name: params[:first_name],
      last_name: params[:last_name],
      photo_url: params[:photo_url],
      password_digest: BCrypt::Password.create(params[:password])
      )
      redirect_to "/"
    else
      render 'edit'
    end
  end
```

and the edit.html.erb view

```
<%= form_for :user, url: user_path(@user), method: :put do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <%= link_to 'Delete This Post', user_path(@post), method: :delete %>
<% end %>
```

but the only way I can get the editing functionality to work is if I fill in ever single field. If I don't fill in every fill, it's as if nothing ever happened. Also when I do successfully update a user, views (like a users name, that is being accessed from the db) specific to that user do not update on the page.

**Comment by adambray** [comment]
Do you have validations on your user model?

If you're using has_secure_password, that adds a validation on the password field.

**Comment by adambray** [comment]
(Validations might prevent your user from updating unless all fields are present)

**Comment by ghost** [comment]
Yeah, a way I figured I could do this is if, on the users edit view: edit.html.erb, I filled in the input fields to their current value, then a user can just edit what they want, then hit submit and all fields are filled in. Do I just use value for that ? For example `value="<%= @user.first_name %>"`

**Comment by ghost** [comment]
Got it

**Comment by adambray** [comment]
Just as a heads up, the best practice here would be to use form_for as it's intended:

in your edit form:

``` ruby
<%= form_for @user do |f| %>
# rather than
<%= form_for :user, url: user_path(@user), method: :put do |f| %>

# the rest of the form would stay the same, but would auto populate values
```

then in your controller:

``` ruby
 def update
    @user = User.find(params[:id])

    if @user.update( params.require(:user).permit([:first_name, :last_name, :photo_url, :password) )
      redirect_to root_path
    else
      render 'edit'
    end
  end
```

**Comment by adambray** [comment]
(you can extract the `params.require(...).permit(...)` out into a method to be shared with the `create` action.
