### ISSUE TITLE
ids / associations

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#112]
I am stuck trying to create a recommendation for a specific location. I am trying to reference the location id, but the id is not recognized and I'm not sure where I am going wrong. The error message and the line of code that is receiving the error is below. 

ActiveRecord::RecordNotFound in RecommendationsController#create
Couldn't find Location with 'id'=

```
@location = Location.find(params[:location_id])
```

**Comment by andrewsunglaekim** [comment]
seems like it's blank. Can you tell me which route  and controller actions hit that database query you just posted code for?

**Comment by ghost** [comment]
location_recommendations POST   /locations/:location_id/recommendations(.:format)          recommendations#create

The above is what I was going for…

But just took another look at my routes and see that I also have the route below ….. does the line below indicate that I have a duplicate route for recommendations that is not nested under locations? 

 recommendations  POST   /recommendations(.:format)                                 recommendations#create

rut ro...

**Comment by ghost** [comment]
Maybe I am working in a duplicate unnested route somehow so that is why location_id is not recognized?
