### ISSUE TITLE
Not getting syntax for join table query

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#113]
I am trying to find categories that a photo belongs to.  My code is returning the category indexes from the CategoryEntry join table but I don't know how to get through to the category_title values from the Categories table.

queries (failing)

```
    @photo = Photo.find(params[:id])
    @categories = CategoryEntry.where(photo_id: @photo.id)
```

migrations

```
class CreateCategories < ActiveRecord::Migration
  def change
    create_table :categories do |t|
      t.string :category_title
      t.timestamps null: false
    end
  end
end

class CreateCategoryEntries < ActiveRecord::Migration
  def change
    create_table :category_entries do |t|
      t.references :photo, index: true, foreign_key: true
      t.references :category, index: true, foreign_key: true
      t.integer :ranking
      t.timestamps null: false
    end
  end
end

class CreatePhotos < ActiveRecord::Migration
  def change
    create_table :photos do |t|
      t.references :user, index: true, foreign_key: true
...
    end
  end
end
```

**Comment by andrewsunglaekim** [comment]
You're really close, I think.

Really when you do `CategoryEntry.where(photo_id: @photo.id)` you're getting all of the CategoryEntry Objects not category objects. Then you can just iterate through each category_entry and call `.category.category_title` on it.

OR

if your associations are setup correctly you can do something like this.

```
@photo = Photo.find(params[:id])
@categories = @photo.categories
```

**Comment by malissaromero** [comment]
Sorry to butt in but Tom, is this the syntax for generating a join table: 

rails g migration CreateJoinTable post:references category:references

**Comment by tomBeach** [comment]
Still not working.  I tried this code in the index page to find groups for each photo listed:

```
            <% @groups = GroupEntry.where(photo_id: photo.id) %>
            <% binding.pry %>
            <% @groups.each do |group| %>
              <%= group.group_title %>
            <% end %>
```

Error that shows in the "group.group_title" line:

```
undefined method `group_title' for #<GroupEntry:0x007fc2a4c1d810>
            <% @groups.each do |group| %>
              <%= group.group_title %>
```

**Comment by RobertAKARobin** [comment]
What is this `GroupEntry` model? We haven't seen that before.

**Comment by RobertAKARobin** [comment]
More importantly, does the `groupentries` table have a `group_title` column?

**Comment by tomBeach** [comment]
GroupEntry is the join table (Photos to Groups).  I think I might have fixed this though...  This code seems to work:

```
            <% @group_entries = GroupEntry.where(photo_id: photo.id) %>
            <!-- <%# binding.pry %> -->
            <% @group_entries.each do |group_entry| %>
              <% group_title_group = Group.find_by(id: group_entry.group_id) %>
              <%= group_title_group.group_title %>
            <% end %>
```

Seems like lots of groups and group_groups and group_ group_ groups.groups...  Works though!
