### ISSUE TITLE
Issue with methods after adding devise 

### ISSUE THREAD

**Issue by chrislovett03** [ga-wdi-exercises/project2#114]
I tried adding the current_user to my lead model at the index controller. 
I expected the current_user.leadmodels to show up in the index view

NoMethodError in CarpentersController#index
undefined method `carpenters' for nil:NilClass
![screen shot 2015-08-05 at 1 40 54 pm](https://cloud.githubusercontent.com/assets/12041606/9093007/9f965bd4-3b77-11e5-9bdf-63e9b52e9642.png)
happened instead.

**Comment by RobertAKARobin** [comment]
Did you specify that a user has_many carpenters in your User model?

**Comment by jshawl** [comment]
the `NoMethodError` is telling you that `current_user` is nil. Are you coming to the devise lesson? Should shed some light on why currentuser is nil here

**Comment by chrislovett03** [comment]
Yes I did specify -- Ok i'll be there!
![screen shot 2015-08-05 at 1 57 07 pm](https://cloud.githubusercontent.com/assets/12041606/9093384/df40eefa-3b79-11e5-874e-a2a7b81a42ab.png)

**Comment by RobertAKARobin** [comment]
I'm going to close this for now. Feel free to re-open it when you've given things a whirl after the class!

**Comment by chrislovett03** [comment]
Sounds good. Thanks Robin.
