### ISSUE TITLE
Issue with deleting from a join table

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#116]
I have two models, tags and photos, that are in a many to many relationship in a join table, category. I'm trying to delete the join table entry when either the picture or the tag is deleted.
If a picture is deleted, all its tags lose that picture.
If a tag is deleted, all its pictures lose that tag.

Which file should I look in to accomplish this?

**Comment by jshawl** [comment]
I think you're looking for `dependent: :destroy` in your model files. 

http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to

Closing but please reopen if I can help further!

**Comment by Walter-0** [comment]
test
