### ISSUE TITLE
heroku database 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#117]
To reset my database, I did: 
$rake db:migrate:reset  
$rake db:seed  
git add and commit

Then I tried to edit it on heroku by doing: 
$heroku pg:reset DATABASE_URL 
$heroku run rake db:migrate 
$git push heroku master

Information from the database did not show up on heroku while it shows up on localhost. How do I get it to also show up on heroku? Is there something similar to $rake db:seed on heroku?

**Comment by RobertAKARobin** [comment]
There is! Just put `heroku run` before any commands. For instance, if you want to run `rake db:seed` on Heroku, just do `heroku run rake db:seed`.

**Comment by ghost** [comment]
yay it worked! thank you!

**Comment by RobertAKARobin** [comment]
Woooo
