### ISSUE TITLE
Can't find link_to edit path

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#118]
I have a model Location that has many recommendations. Recommendations is a resource nested inside locations.

On the Location show page I list all its recommendations. By each recommendation, I want to have a link to its "Edit" page.

I have this:

```
<% @location.recommendations.each do |recommendation| %>
  <p>
    <%= recommendation.body %>
    <%= link_to 'Edit', edit_location_recommendation_path(@location, recommendation) %>
  </p>
<% end %>
```

However, I get this error:

```
ActionController::UrlGenerationError in Locations#show
No route matches {:action=>"edit", :controller=>"recommendations", :id=>nil, :location_id=>"1"} missing required keys: [:id]
```

**Comment by amaseda** [comment]
Is it possible that this particular `@location` doesn't have any recommendations saved to it?

**Comment by RobertAKARobin** [comment]
Good point! If so, it might be a good idea to drop the database and re-create it.

**Comment by ghost** [comment]
Thanks - got help from Robin and Adam!

**Comment by RobertAKARobin** [comment]
For posterity: the problem was `@recommendation = @location.recommendations.new` in the controller was causing a "dummy" Recommendation with no ID to be created.
