### ISSUE TITLE
Reopening iusse #102

### ISSUE THREAD

**Issue by segheysens** [ga-wdi-exercises/project2#119]
Here's the original issue for reference: https://github.com/ga-dc/pbj-project2/issues/102
*(I commented on the original about an hour or two ago because, as far as I can tell, I don't think the students can reopen tickets once they've been closed. Here's my progress!)

So I tried moving the before_action authenticate_user! to my application controller, and it didn't resolve the issue. I think it's because I'm rendering that index file as my root, and it's skipping the application controller? (Unless the application controller runs no matter what, I can't find a clear answer on that...)

Also, I tried making this change in my StaticPagesController to no eval (it's still throwing the "no method for nil" error in reference to @user:

``` ruby
class StaticPagesController < ApplicationController

  def index
    if user_signed_in?
      @user = User.find(session[:user]["id"])
    end
  end
```

Maybe some side-by-side pair programming will do the trick.

**Comment by RobertAKARobin** [comment]
I wonder if it's caused by the app thinking a previous user is signed in. Try opening your app in an "Incognito" or "Private" window, which don't store cookies.

**Comment by segheysens** [comment]
I tried and it's not :confused: if I put the before_action authenticate! in the application controller, it creates an infinite redirect loop
