### ISSUE TITLE
Distinguishing checked and unchecked group selections

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#121]
The code below works on my photo edit form for matching photos with the groups assigned to them (via the GroupEntry join table).  This puts checkboxes on the edit form for these assigned groups.  But what about unassigned groups?  (Another user might want to assign a photo to a previously unassigned group.)  Group.all would pull all groups whether assigned or not.  My goal is to list checkboxes for all groups, but have only selected boxes checked.

```
    <% @group_entries.each do |group_entry| %>
      <tr><td> --- </td>
        <% group_title_group = Group.find_by(id: group_entry.group_id) %>
        <td><%= label_tag(group_title_group.group_title, group_title_group.group_title) %>
        <%= check_box_tag(group_title_group.group_title) %>
```

Seed data to give an idea of table columns:

```
Group.create(group_title: "AlleyCatHouse")
GroupEntry.create(photo_id: 3, group_id: 1, ranking: 1)
```

**Comment by mattscilipoti** [comment]
Look at your goal again "My goal is to list checkboxes for all groups, but have only selected boxes checked."  You are listing all `group_entries`, not all groups.  Once you list all groups, you must check the appropriate ones (using group_entries).

**Comment by tomBeach** [comment]
Group entries will have the checked groups only (which I want -- they will be "pre-checked" on the form).  But then I still need to see all the other non-checked groups as well (so the user can check them if he/she wants to later).  I'm thinking of putting checked-only groups into an array, then comparing the array contents with an all-groups array.  Any groups in both arrays will be checked, any others will be unchecked.  Would love to find a simpler way though...

**Comment by RobertAKARobin** [comment]
`group_title_group.group_title` sure is confusing.

```
<%= check_box_tag(group_title_group.group_title) %>
```

...will yield this, if `group_title_group.group_title` is "hello":

```
<input id="hello" name="hello" type="checkbox" value="1" />
```

---

I suspect you want the `value` to be something different, in which case you'd need an additional argument.

```
<%= check_box_tag(group_title_group.group_title, group_title_group.id) %>
```

...will yield this, if `group_title_group.group_title` is "hello" and the id is 26:

```
<input id="hello" name="hello" type="checkbox" value="26" />
```

---

You can have a checkbox checked by default by passing `true` as a 3rd argument:

```
<%= check_box_tag(group_title_group.group_title, group_title_group.id, true) %>
```

```
<input id="hello" name="hello" type="checkbox" value="26" checked="checked" />
```

---

So if I had a method called `is_daytime?` that returned `true` if it's currently daytime, I could make a checkbox that was checked by day and unchecked by night:
You can have a checkbox checked by default by passing `true` as a 3rd argument:

```
<%= check_box_tag(group_title_group.group_title, group_title_group.id, is_daytime?) %>
```

**Comment by tomBeach** [comment]
Good news / bad news... the 3rd argument was the key; checked/unchecked is now working to show the checkboxes in their correct state (true or false).  I am unable to record the results of the checkboxes when submitting the form however.  If I check a previously unchecked box, how does the database know to create a new entry in the join table based on the (now) true state of the group?

**Comment by andrewsunglaekim** [comment]
It won't until you program it. You'll have to make each of those check boxes link to routes that will change the database

**Comment by RobertAKARobin** [comment]
Woo! Progress!

Instead, use this:

```
<%= check_box_tag("groups[#{group_title_group.group_title}]", group_title_group.id, is_daytime?) %>
```

That will yield:

```
<input id="hello" name="groups[hello]" type="checkbox" value="23" checked="checked" />
```

When you submit that, your params will be like this:

```
{
...
  groups: {
    "hello" => "23"
  }
}
```

...whereas if a box is unchecked it won't show up in `groups` at all.

Now you can do something like:

```
params[:groups].each do |group_id|
  Thing.create(group_id: group_id)
end
```
