### ISSUE TITLE
Issue with submitting a predetermined value

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#122]
I'm trying to allow photos to have a score determined by the number of upvotes minus the number of downvotes. I want to make make the upvote and downvote links add one upvote or downvote to its respective counter. I'm currently getting a routing error,  No route matches [GET] "/photos/10/upvote"
views/photos/show.html.erb.
  <%= link_to "Upvote", photo_upvote_path(@photo) %>
  <%= @photo.score %>
  <%= link_to "Downvote", photo_downvote_path(@photo) %>  

controllers/photos_controllers.rb
def upvote
    @photo = Photo.find(params[:id])
    @score = @photo.score
    @score + 1
    redirect_to photo_path(@photo)
  end

**Comment by andrewsunglaekim** [comment]
so what I'm seeing here is @score is changing, but is that changing anything in your model. You `.score` as a setter method. then call `.save` on it. 

Additionally there's a great gem out there for voting, it's called acts as votable
