### ISSUE TITLE
User Input Displays Incorrectly

### ISSUE THREAD

**Issue by kristingreenslit** [ga-wdi-exercises/project2#123]
I tried to display on the page the user input that's been entered into the form.
I expected the same phrase that the user entered to display on the page.
The entry shows up in the db, but the page's path is displaying on the page instead of the user input (which also can't be edited or deleted yet as well).

I've tried  <%variable.inspect%>, changing methods in different controllers after moving the form to a different page and/or _form.html.erb. 

<img width="718" alt="screen shot 2015-08-05 at 3 37 32 pm" src="https://cloud.githubusercontent.com/assets/5890436/9096086/058228d6-3b89-11e5-908d-ab1bb4feed43.png">

**Comment by mattscilipoti** [comment]
Please share the appropriate line(s) of view code.  A link to the code on github is fine too.

**Comment by kristingreenslit** [comment]
this is the form so far:

```
  <%= form_for([current_user, current_user.computers.build]) do |f| %>
    <p>
      <%= f.label :name, "Please enter a name for your computer: " %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

    <% @computers.each do |computer| %>
      <%= link_to computer.name %> -->
      <%= link_to 'Delete', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

  <%@computer.inspect%>
```

**Comment by RobertAKARobin** [comment]
`<%= link_to computer.name %>` will generate this:

```
<a href="/computers">Robin's Laptop</a>
```

Note that's `/computers`, not a specific computer.

To have it go to that specific computer, you want:

```
<%= link_to computer.name, computer %>
```

**Comment by kristingreenslit** [comment]
Robin: Matt helped me figure this out - the issue was beyond just this code and extended into the controller primarily. Thanks for your help though!
