### ISSUE TITLE
error on show page with link_to for non-favorited posts

### ISSUE THREAD

**Issue by pdavies88** [ga-wdi-exercises/project2#124]
sorry guys again having some trouble with the favorites if the post is not favorited the show page for posts is giving me this error: ActionController::UrlGenerationError in Posts#show
Showing /Users/pdavies/wdi/projects/project_2_preston/app/views/posts/show.html.erb where line #45 raised:
No route matches {:action=>"destroy", :controller=>"favorites", :id=>nil, :user_id=>"2"} missing required keys: [:id]
Extracted source (around line #45):
43
44
45
<%= link_to "unfavorite", user_favorite_path(@user, @user.favorites.find_by(post_id: @post.id)), method: :delete %> 
in my favorites controller my delete method looks like this:     def destroy
      @user = User.find(session[:user]["id"])
      @favorite = Favorite.find(params[:id])
      @favorite.destroy unless @favorite.blank?
      redirect_to posts_path
    end

It works if a post is already favorited by the user and so does the show page. Issue is coming in when the show page is trying to be loaded by the user but they have not yet previously favorited it. I'm assuming I have a syntax error in my link_to which is causing the error but I'm not sure where to look to fix it

**Comment by jshawl** [comment]
what is the value of `@user.favorites.find_by(post_id: @post.id)` in your view?

**Comment by pdavies88** [comment]
"id"=>"5"

**Comment by pdavies88** [comment]
http://localhost:3000/posts/5
