### ISSUE TITLE
adding API content via a ruby gem

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project2#125]
I want to access the full text of Guardian articles via their api, which is available through this gem: https://github.com/tomtt/contentapi-ruby

I have "bundle installed" the gem, and I have an API key with the Guardian, but the documentation for using the gem isn't great. It just says to use this line, but (having never used an API in ruby) I'm not sure where to put this or what to do with it:

`articles = GuardianContent::Content.search("your search term")`

I tried putting it in my controller, but it gives an error saying "can't add a new key into hash during iteration." 

I'm actually not even sure if using the API works for this project, because I currently have article data stored in my database but this would just be retrieving and displaying it, right?

**Comment by andrewsunglaekim** [comment]
I'd have to look at the documentation, but i'll come over and look at it.
