### ISSUE TITLE
Issue with password authentication for pre-seeded user (not Devise)

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#127]
I created an admin account in my seeds, and it's having trouble recognizing the password through the app.

To make matters worse, the @user variable in the users#show view seems to be picking up the currently logged in user, not the users whose profile is supposed to be showing. I think the two issues may be related.

I've futzed with the controller and the view, but am not quite seeing what's going on. Help!

Here's the relevant code from the User controller:

```
  def show
    @user = User.find( params[:id] )
    if session[:user]
      @current_user = User.find(session[:user]["id"])
    else
      @current_user = "None"
    end
    @posts = @user.posts
  end
```

**Comment by RobertAKARobin** [comment]
`@user` will pick up whichever user corresponds to the ID in the URL of that page. So if the URL is `/users/123`, it'll get the user with the ID of 123.

Did you use Devise, or did you "hand-roll" your authentication?

**Comment by jkoul** [comment]
Hand-rolled.

**Comment by RobertAKARobin** [comment]
Do you hash passwords? If so, the password seeded into your database is probably plain text. Thus, when you try to sign in, you're going to be trying to compare "123abcxyzadjkfahsdlkjf" against the plain text password, which will fail. I wouldn't seed in an admin user.

**Comment by jkoul** [comment]
Ok that could work. Sounds good. I'm noticing another problem around the same place now and will open a new issue.
