### ISSUE TITLE
@current_user global?

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#131]
I set this up in my ApplicationHelper module:

```
module ApplicationHelper
  def current_user
    @current_user = User.find(session[:user]["id"]) if session[:user]
  end
end
```

But it doesn't seem to be translating when I call the variable elsewhere. Can you tell me where I'm going wrong???

**Comment by RobertAKARobin** [comment]
Helpers are only available in views. Put that in your ApplicationController.

**Comment by jkoul** [comment]
Ok thanks!
