### ISSUE TITLE
reopening current_user problem

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#132]
I set this up in my ApplicationController:

def current_user
@current_user = User.find(session[:user]["id"]) if session[:user]
end

But it doesn't seem to be translating when I call the variable elsewhere. Can you tell me where I'm going wrong???

**Comment by RobertAKARobin** [comment]
Can you be more specific? Are you getting an error? If not, see what the output of current_user.inspect is.

**Comment by RobertAKARobin** [comment]
You also might try using an incognito window which will clear your cookies.

**Comment by RobertAKARobin** [comment]
You also might try using an incognito window which will clear your cookies.

**Comment by jkoul** [comment]
I'll go ahead and close the issue. I'm not 100% satisfied with my solution, but it seems like it's working now. Thanks Robin!
