### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by silviascript** [ga-wdi-exercises/project2#133]
I'm trying to incorporate comments on the print (similar to post) page to avoid creating a comment new page that redirects to the show page. I've checked all my models, migrations and the data tables, they seem to be correct. However, when I look in pry, it seems to receive all the comments, I have to use the singular instead of the plural.

![Image of Error](http://cl.ly/c9zI/Screen%20Shot%202015-08-05%20at%208.49.18%20PM.png)

Because of it, it's affected my destroy method since the print has many comments.

Here are my models.

``` ruby
# User
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prints, dependent: :destroy
  has_many :comments, dependent: :destroy
end

# Print
class Print < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
end

# Comment
class Comment < ActiveRecord::Base
  belongs_to :print
  belongs_to :user
end
```

Here are my migrations.

``` ruby
# Prints
class CreatePrints < ActiveRecord::Migration
  def change
    create_table :prints do |t|
      t.belongs_to :user
      t.string :category
      t.string :creator_individual
      t.string :creator_company
      t.string :title
      t.string :photo
      t.string :series
      t.string :purchase_year
      t.string :purchase_price
      t.timestamps null: false
    end
  end
end

# Comments
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.belongs_to :prints
      t.integer :user_id
      t.string :content
      t.string :username
      t.timestamps null: false
    end
  end
end
```

``` ruby
# Comments Controller
  def create
    @print = Print.find(params[:print_id])
    @comment = @print.comments.create(comment_params)

    # Redirect it to the show page of the print.
    redirect_to print_path(@print)
  end

# Comments in the print show page.
<h2>Add Comments</h2>
<%= form_for ([@print, @print.comments.build]) do |f| %>
  <p>
    <%= f.label :name  %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
<p> <%= f.submit %> </p>

<% end %>
```

Help.

**Comment by RobertAKARobin** [comment]
When referring to the model itself — that is, whenever you're using a capital letter — it will always be singular. So you'll always do `Comment.new`.

This is confusing, because when you're referring to _instances_ that belong to something else, then you do the sensible English thing and use plurals, as in: `@post.comments.all`.

Your code all looks fine... Are you getting an error?

**Comment by silviascript** [comment]
@RobertAKARobin When I add my form, I receive this type of error.

![Image of Error](https://dl.dropboxusercontent.com/u/9772835/Screen%20Shot%202015-08-06%20at%209.14.19%20AM.png)

**Comment by silviascript** [comment]
@RobertAKARobin It prevents me from viewing my show page and editing the details of the printed item.

**Comment by RobertAKARobin** [comment]
My guess is that it's because you have `t.belongs_to :prints`, as opposed to `t.belongs_to :print` (singular). I'll be if you do `Comment.first.inspect` or check out the comments table in psql, it'll show a `prints_id` column, but not a `print_id` column.

Change it to `t.belongs_to :print`, remigrate, and you should be ready to rock.

**Comment by silviascript** [comment]
@RobertAKARobin I changed it to print and I see the correction in the data table. When I migrated, I lost all my devise input fields.

**Comment by RobertAKARobin** [comment]
By "lost", do you mean they're no longer in your database, or they're physically not showing up on the page in the browser anymore?

**Comment by silviascript** [comment]
Sorry, not showing up anymore. I inspected my HTML on the browser and they are not hidden. Just not being rendered.

**Comment by RobertAKARobin** [comment]
This shouldn't have affected Devise is any way... I'll come visit in a sec.

**Comment by silviascript** [comment]
K! Thanks!
