### ISSUE TITLE
undoing a commit

### ISSUE THREAD

**Issue by rewarren** [ga-wdi-exercises/project2#135]
I'd like to undo a commit. the instructions i'm reading give directions by whether or not the commit is published, but i'm unsure if they mean pushed (which, in my case, i did push it already), or by published they mean its been deployed to a website already.

i attempted to start the many to many relationship and started playing around with my model name in a few different files and I want to go back to before i started that and start fresh.

**Comment by RobertAKARobin** [comment]
No problem! Just type `git revert HEAD~1`. This does the exact same thing as if you had manually gone through and undid all your changes, added, and committed.

**Comment by rewarren** [comment]
Robin, it says I have conflicts that need to be resolved before reverting. I don't have any uncommitted changes hanging around, so don't think that's the conflict...  I'm working in a branch other than master, could it be that I need to merge the branches first?

Rachels-MacBook-Pro:fetch rachelwarren$ git revert HEAD~1
error: could not revert cb0a295... started manytomany associations
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

**Comment by jshawl** [comment]
what is the output of `git status` ?

**Comment by rewarren** [comment]
This is how i'm reading this: it actually did do my revert, and the "changes to be committed" are from my new-last commit? and the "unmerged paths" are the commits i'm trying to get rid of? if so, i should do: 
git reset HEAD .
to get rid of them?  ...maybe?

achels-MacBook-Pro:fetch rachelwarren$ git status
On branch devise
You are currently reverting commit cb0a295.
  (fix conflicts and run "git revert --continue")
  (use "git revert --abort" to cancel the revert operation)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

```
modified:   app/controllers/animals_controller.rb
modified:   app/controllers/likes_controller.rb
new file:   app/models/like.rb
modified:   app/models/user.rb
modified:   app/views/animals/show.html.erb
modified:   app/views/layouts/application.html.erb
deleted:    app/views/likes/show.html.erb
modified:   config/routes.rb
deleted:    db/migrate/20150805222834_add_foreign_key_to_animals.rb
modified:   db/schema.rb
modified:   db/seeds.rb
```

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

```
both modified:   app/models/animal.rb
deleted by them: app/models/like_animal.rb
both modified:   db/migrate/20150805155630_create_likes.rb
deleted by them: db/migrate/20150805222309_add_foreign_key_to_likes.rb
```

**Comment by rewarren** [comment]
sorry i don't know about the formatting for the copy/paste!!!

**Comment by rewarren** [comment]
oops sorry -

git rm . 

instead of 

git reset HEAD .

**Comment by jshawl** [comment]
im gonna come help.
