### ISSUE TITLE
submit form goes through but doesn't update item

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project2#136]
When I submit form to update an item, the action sends me back to the item show page displaying all the values of the item except for no change in the one value I was trying to update.

I see this message in ruby log:
Unpermitted parameters: brand, item_type, price, total_measure, unit_of_measure, price_per_unit, notes, price_expiration

Which is strange, because when I call the record in psql, it returns exactly those columns and values.

If I can get update and create working, I'll have full CRUD in both of my classes.

**Comment by jshawl** [comment]
what do your strong parameters look like?

**Comment by adrianshep** [comment]
in views/items/edit.html.erb:

```
<form action="/stores/<%= @item.store.id %>/items/<%= @item.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
```

in application_controller: 
protect_from_forgery with: :exception

in application.rb:
config.active_record.raise_in_transactional_callbacks = true

**Comment by jshawl** [comment]
Do you have an ItemsController?

**Comment by adrianshep** [comment]
I think I may have the answer. In items_controller.rb under:

```
private
    def item_params
      params.require(:item).permit(:name)
    end
```

I believe I'm missing the additional parameters that make up item, correct?

**Comment by jshawl** [comment]
I see in your ItemsController, you're only letting through a name: https://github.com/adrianshep/price-parser/blob/e1db6a25a8c1c2474f84af1466d2b6028d774504/app/controllers/items_controller.rb#L46-L48

You should permit each of the unpermitted paramters:

> Unpermitted parameters: brand, item_type, price, total_measure, unit_of_measure, price_per_unit, notes, price_expiration

**Comment by adrianshep** [comment]
Yes, thank you. Will redo.

**Comment by adrianshep** [comment]
It works! Thanks!
