### ISSUE TITLE
User Id Bug and Category show pages

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#137]
I am having issues signing in. I have dropped my table and the sign in page error page will say that there is no user id of 1 until I delete all my history in chrome. 

I also have a user show page that shows all of the specific user's posts, but again I get an error page stating that there is no user id. 

I also have a separate question. I put a join table in yesterday for categories and posts to link together. How do I give each category a show page? I know the route would look something like this: /category/1.

**Comment by jshawl** [comment]
Does it give you a line number where the error occurs? any code you can share will help!

**Comment by jshawl** [comment]
> How do I give each category a show page?

You can define a resource for categories. What does your config/routes.rb look like?

**Comment by malissaromero** [comment]
I was able to get the categories to semi-work, but I keep getting stopped by the user_id bug. I just rested my posts in my categories and used the paths to help navigate. 

I just dropped my database and it keeps asking for past user ids. I usually have to close all my chrome and delete my history to again access the login page or work in an incognito window. 

![screen shot 2015-08-06 at 9 49 41 am](https://cloud.githubusercontent.com/assets/11203264/9113069/81260768-3c20-11e5-90fd-af99212d5a65.png)

**Comment by jshawl** [comment]
oo ok what if you open a new incognito window: command + shift + n in chrome?

**Comment by jshawl** [comment]
also are you using devise? You can use the `current_user` helper method if so. e.g. 

``` rb
@user = current_user
```

**Comment by malissaromero** [comment]
I can access my page using incognito but then I get this error, which tells me it has to probably do with a bug in the user id. I also hand rolled my user authentication. 

![screen shot 2015-08-06 at 9 52 10 am](https://cloud.githubusercontent.com/assets/11203264/9113149/e859ee68-3c20-11e5-952c-36864ac6dfe9.png)

**Comment by jshawl** [comment]
can you change the conditional to:

``` rb

<% if @user %>

# instead of

<% if session[:user_id]

```

**Comment by malissaromero** [comment]
That seem to work! Can you let me know what it was, if you have time but I will close the issue.

**Comment by malissaromero** [comment]
I am still seeing errors regarding the user id. This is my last one. Does it have to do with a problem with how I assigned a user id? This is my code in my users controller in my sign in method:

```
session[:user_id] = @user.id

```

![screen shot 2015-08-06 at 10 25 58 am](https://cloud.githubusercontent.com/assets/11203264/9114037/b26d0826-3c25-11e5-86fe-0c53252d5a6d.png)

**Comment by RobertAKARobin** [comment]
It looks like you have

```
return User.find(@user)
```

...but I don't see where you're defining @user?

**Comment by malissaromero** [comment]
sorry i changed it really quick to see if it would make a difference but it was like this before: 

  def current_user
    return User.find(session[:user_id])
  end

**Comment by malissaromero** [comment]
I define user in my sign in method here 

session[:user_id] = @user.id

**Comment by RobertAKARobin** [comment]
You should be getting a different error now. Can you show what it says?

**Comment by malissaromero** [comment]
This happens every time I drop my tables. It is still trying to find a user that no longer exists.

![screen shot 2015-08-06 at 10 43 35 am](https://cloud.githubusercontent.com/assets/11203264/9114452/04084e6e-3c28-11e5-84b4-47ba223f0cb8.png)

**Comment by RobertAKARobin** [comment]
Yup! So you need to have a "sign_out" method that clears all the session variables:

```
def sign_out
  reset_session
end
```

Also, you can try testing your app in an "Incognito" window if you're in Chrome (go to the File menu), or a "Private" window in Safari. When you close an incognito window, it clears any cookies that were added while you were using it. This will mean you're effectively logged out whenever you close the window.

**Comment by malissaromero** [comment]
I do have a sign out method 

```
  def signout
    flash[:notice] = "You're signed out."
    reset_session
    redirect_to root_url
  end
```

My incognito window gives me the same message: 
![screen shot 2015-08-06 at 10 56 38 am](https://cloud.githubusercontent.com/assets/11203264/9114828/dfbffb7c-3c29-11e5-8b26-2ebe2f65ae00.png)
