### ISSUE TITLE
Failing to find photo object based on photo_ids from join table

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#139]
I am trying to select photos by category.  I expected to be able to select these photos based on an array of category_entries (join table matching category_id to photo_id), which is supposed to happen in the photos#category action below:

```
  def category
  # def category(category_id)
    logger.warn "### photos#category"
    if session[:user_id]
      user = User.find_by(id: session[:user_id])
      @photos = Photo.where(user_id: user.id)
    else
      @photos = Photo.all
    end
    @category_entry_array = []
    @photos.each do |photo|
      category_entry = CategoryEntry.where(photo_id: photo.id, category_id: params[:id].to_i)
      # binding.pry
      @category_entry_array << category_entry
    end
  end
```

When I pass this array (@category_entry_array) to the view, I get an "undefined local variable or method `photo' for #<#Class:0x007fb888edd508:0x007fb88feaa750>" from the code below.  It fails to find "photo" in this line: photo = Photo.find_by(id: category_entry.photo_id.to_i).  

```
    <% if @category_entry_array.length > 0 %>
      <% @category_entry_array.each do |category_entry| %>
        photo = Photo.find_by(id: category_entry.photo_id.to_i)
        <% binding.pry %>
        <% if (photo) %>
          <tr><td><%= link_to photo.title, user_photo_path(@user.id, photo.id) %></td><td></td><td></td></tr>
          <tr>
            <td class="main_image"><%= image_tag photo.photo_source, alt: photo.title %></td>
            <td><%= photo.description %></td>
```

**Comment by andrewsunglaekim** [comment]
If you want all of the photos from a specific category and you have set your associations for your join table correctly, you should be able to do something like this:

```
category = Category.find(1)
category.photos
```

instead of trying to do that query

**Comment by tomBeach** [comment]
Is (1) in "category = Category.find(1)" the category id?  

As in: "category = Category.find(params[:id].to_i)"...

**Comment by RobertAKARobin** [comment]
Yep.
