### ISSUE TITLE
BoardTogether User Stories

### ISSUE THREAD

**Issue by kscoulter** [ga-wdi-exercises/project2#14]
Easy way to find other board game players and organize a gaming session:
https://github.com/kscoulter/board-together

ERD: https://drive.google.com/a/ucdavis.edu/file/d/0B2It0TBFUGm9MFNndGExdEEwV00/view?usp=sharing

**Comment by RobertAKARobin** [comment]
Neat idea for a project! I count 4 models: user, player, event, and game. That should be OK, I think!

I'm not sure if you're planning on adding in some kind of scheduling functionality, e.g. "see which players are available at 5pm on Friday". But if you are, I'd caution you against it. Just start off with being able to add players to arbitrary events.
