### ISSUE TITLE
Invite Signup Code & Devise

### ISSUE THREAD

**Issue by karldonus** [ga-wdi-exercises/project2#140]
Problem: My web app requires login to view sensitive info not available to public view. But there's no restrictions on who can sign up (sort of like leaving the door wide open). I want an invite code field, so only people with the code can register. Problem? It doesn't seem to want to work with Devise.

I've tried three different variants. 
Attempted Solutions: 
http://headynation.com/simple-invitation-access-code-using-rails-4-devise/
http://stackoverflow.com/questions/3704837/ruby-on-rails-devise-want-to-add-invite-code

Best Attempt:
http://stackoverflow.com/questions/28787615/add-invite-code-to-devise

The last one was the most promising. I got to the point where I had a field in sign up. HOWEVER, it was as if the invite code wasn't marked as an exception in the strong params area, since it appeared nothing was "taking". I couldn't include attr_accessible in my user model, since it'd error out as an unknown code.

Update: 

It seems as if attr_accessible has been replaced by controllers, but my config of user controller seems to conflict up the wazoo with devise. It throws an error regarding user routes.

**Comment by mattscilipoti** [comment]
`attr_accessible` is for previous versions of Rails.  This functionality has been replaced by "strong params" - which moved it out of the Model and into the Controller.  

Helpful references:
- http://easyactiverecord.com/blog/2014/04/01/rails4-strong-parameters-and-the-attr-accessible-macro/
- http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html

**Comment by karldonus** [comment]
Thanks for the speedy reply Matt! 

I attempted (not so successfully) to incorporate strong params by creating a registrations_controller.rb in a user folder in controllers....based on the server feedback :invite_code still isn't a valid parameter.

#Server Feedback:

```
Started POST "/users" for ::1 at 2015-08-06 09:46:00 -0400
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bxaWy9ghs94sr4MbUz/D6dlJXUTOAoq0M8oEBEOrT0GI9HSPoe8sxZSh5TocmnNkyxI7KcpsUwYg6y+LlRfykg==", "user"=>{"invite_code"=>"unicorn", "email"=>"spam@spam.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
Unpermitted parameter: invite_code
```

#app/controllers/users/registrations_controller.rb

```
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:invite_code,
        :email, :password, :password_confirmation)
    end
  end
end
```

#User Model:

```
class User < ActiveRecord::Base
  attr_accessor :invite_code

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_each :invite_code, :on => :create do |record, attr, value|
    record.errors.add attr, "Please enter correct invite code" unless
      value && value == "unicorn"
  end
end
```

**Comment by karldonus** [comment]
Also tried the standard strong params def:

```
private
    def registration_params
      params.require(:registration).permit(invite_code, :email, :password,   :password_confirmation, current_password)
    end
```

**Comment by karldonus** [comment]
Another variant (that doesn't work):

```
class Users::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
   after_action :verify_authorized, unless: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
         :username,
         :email,
         :password,
         :password_confirmation,
         :remember_me,
         :invite_code
     ) }
   end
 end
```

**Comment by mattscilipoti** [comment]
I believe you are fighting the right battle.  Looking into Devise customization to identify the specific issue.

**Comment by mattscilipoti** [comment]
These changes should have corrected the `Unpermitted parameter: invite_code` issue.  Are you getting a new error?

**Comment by mattscilipoti** [comment]
I prefer Andy's suggestion.  This is a class exercise.  It's your second project.  Focus on functionality, providing value to the user, rather than locking down how has access/when.  :)

**Comment by karldonus** [comment]
Thanks. Appreciate it!
