### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-wdi-exercises/project2#141]
Hello,

I've been having deployment issues. I need a one on one to troubleshoot this if you don't mind.

**Comment by jshawl** [comment]
Can we begin the troubleshooting here? I imagine others might have similar issues.

Any error messages?

**Comment by omarimayerswalker** [comment]
Hi Jesse,

The current error is: failed to push some refs to "#myapplink";
updates were rejected because a pushed branch tip is behind its remote;

FYI I have multiple branches that represent different states of progress of my app. I'm trying to push from my most resent branch.

The error I've been getting before I started making branches, was no error at all. Heroku said the app was successfully deployed but when you go to the app site, the app isn't there. And when I tried to push new changes, heroku says everything is up to date.

**Comment by jshawl** [comment]
which command are you using to push? 

Heroku depends on a master branch for deployment. If you want to push a local branch to master:

```
$ git push heroku nameOfLocalBranch:master
```

**Comment by omarimayerswalker** [comment]
Yes I've been using that command and I get the same error. I ran a git status and everything is up to date on the branch I'm trying to push.

**Comment by jshawl** [comment]
You could also try deleting the application on herokuapp.com and recreating!

**Comment by omarimayerswalker** [comment]
Ok, I'll give that a try.

**Comment by jshawl** [comment]
ok closing for now but please reopen if that doesn't fix!

**Comment by omarimayerswalker** [comment]
When I run: 

```
git push heroku nameOfmyBranch:master
```

Heroku says I have succesfuly deployed but I get a warning stating no Procfile detected.
