### ISSUE TITLE
new transaction controller

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-wdi-exercises/project2#142]
Hello, 
trying to call a method from either the model or model application_controller, 

```
def subtract_from_timebank(amount)
    self.time_bank = self.time_bank - amount
    self.save
  end
```

```
def add_to_timebank(amount)
    self.time_bank = self.time_bank + amount
    self.save
```

via a new transactions_controller

```
class TransactionsController < ApplicationController
  def transaction
    @user = User.find(session[:user]["id"])
    @user.subtract_from_timebank
  end
end
```

I want to call the method when a form or link is clicked from the service page...

Been getting no method errors or nil class errors. 

Not sure the best way to approach this problem.

**Comment by jshawl** [comment]
I formatted this to have the three backticks on their own line. please do this in the future

**Comment by phantomhaircuts** [comment]
ah i'll make sure to do that next time.

**Comment by andrewsunglaekim** [comment]
are the `add_to_timebank` and `subtract_from_timebank` methods defined in a model?

If so then you need to have the link do a request to an action that executes those methods.

If it's updating a model than probably a put request.

**Comment by phantomhaircuts** [comment]
would that look something like 

```
  <%= form_for [@transaction, @user], method: :subtract_from_timebank, :html => {:class => "transaction-transaction"} do |f| %>
  <%= f.submit "Purchase" %>
  <% end %>
```

?

**Comment by adambray** [comment]
@phantomhaircuts Your `method` in a form can only be `:get`, `:put`, `:post`, or `:delete`.

I'll come over and help with this since there are a lot of pieces.

**Comment by adambray** [comment]
Hey @phantomhaircuts can you write up a summary of what we did during our pairing and then close this issue?

Thanks!
Adam
