### ISSUE TITLE
No route matches error 

### ISSUE THREAD

**Issue by lscottcook** [ga-wdi-exercises/project2#144]
I tried to specify a route to where information should be indexed after it is submitted
I expected that the information would be displayed
instead of received the following error message
"No route matches {:action=>"show", :controller=>"frowns", :id=>nil} missing required keys: [:id]"

My code is:

```
def create
  @frown = current_user.frowns.build(frown_params)
   redirect_to frown_path(@frown)
end
```

I suspect that the is a problem with how I set up my users but I am not sure.

**Comment by RobertAKARobin** [comment]
Can you show the code for the `_form` view and for the `def new` action?
