### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-wdi-exercises/project2#145]
Is there a way to reopen a closed issue? When I commented on the closed issue, the closed status doesn't change.

My issue:

When I run: 

```
git push heroku nameOfmyBranch:master
```

Heroku says I have succesfuly deployed but I get a warning stating no Procfile detected.

**Comment by jshawl** [comment]
which branch name are you trying to deploy? I'm going to try deploying your repo to reproduce the error

**Comment by jshawl** [comment]
and maybe not?! http://stackoverflow.com/a/21333938/850825

**Comment by omarimayerswalker** [comment]
I'm attempting to deploy the votable_branch

I just pushed the latest version to github.

**Comment by jshawl** [comment]
ok great. trying it out now.

**Comment by jshawl** [comment]
im sorry but i was able to deploy! https://thawing-savannah-2466.herokuapp.com/accounts/sign_in

**Comment by jshawl** [comment]
I got WARNING:
remote:        No Procfile detected,

but it still worked.

did you try `heroku open` after `git push herok votable_branch:master`?

**Comment by omarimayerswalker** [comment]
Wow, that's weird.

Yes I used `heroku open` and I get this link:

https://mum-app.herokuapp.com/accounts/sign_in

with the error:

We're sorry, but something went wrong. 
 FYI I was able to deploy the scribble app last week.

**Comment by RobertAKARobin** [comment]
I'm looking at the page you linked to right now, Omari, and it just says "Welcome to your app!" No error page. Maybe force-refresh your page? (Command + Shift + R)

**Comment by jshawl** [comment]
@omarimayerswalker perfect!  you need to run `heroku run rake db:migrate`

**Comment by omarimayerswalker** [comment]
Finally success!  I also noticed I wasn't logged in so I ran `heroku login` before deploying. You would think a warning would occur if you weren't logged in locally.

**Comment by jshawl** [comment]
YES! awesome.
