### ISSUE TITLE
Connecting users Qs

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#146]
Functionality I currently have:
-User can sign up and log in
-User can create a profile (edit: name, img, password, email)
-User can apply all CRUD functionality to a "hub" which is just an item, with a title, description, img, and a link to a specific page (ideally the site they described)
(so as of right now it's just a bookmarking application, so not very exciting.)

The profile, and hubs a user uploads are currently only visible to the user that is logged in. The user that is currently logged in cannot view the profile or hubs of another user. My question is how would I go about creating a relationship between various users? I feel as if the way my current users controller is set up wouldn't allow such functionality.

**Comment by RobertAKARobin** [comment]
Woo! Nicely done, Rosel!

You should be able to show all the hubs for a user the way you'd show, say, all the songs for an artist:

```
@hubs = User.find(params[:user_id]).hubs
```

```
<% @hubs.each do |hub| %>
...
<% end %>
```

Devise just makes sure users have logged in. It shouldn't affect your ability to see other users.

**Comment by ghost** [comment]
I feel like the problem lies in here somewhere:

```
def show
    @user = User.find(session[:user]["id"])
    @hubs = User.find(session[:user]["id"]).hubs
  end

  def edit
    @user = User.find(session[:user]["id"])
  end

  def update
    @user = User.find(session[:user]["id"])
    @user.update(user_params)

    reset_session
    redirect_to "/"
  end
```

I've made 2 users, but when I manually change a url from say...

`http://localhost:3000/users/1`
to
`http://localhost:3000/users/2`

which would be the profile show page, It always sends me to the the profile of the user  I'm currently logged in as.

**Comment by RobertAKARobin** [comment]
First things first: instead of:

```
def show
    @user = User.find(session[:user]["id"])
    @hubs = User.find(session[:user]["id"]).hubs
  end
```

...you can just do:

```
def show
    @user = User.find(session[:user]["id"])
    @hubs = @user.hubs
  end
```

**Comment by RobertAKARobin** [comment]
It's redirecting you to the logged in user because you're always getting the user from `session`. This is Rails's way of remembering who's currently logged in. If you want to get the user from the `/2` in the URL, you'd need:

```
def show
    @user = User.find(params[:id])
```

**Comment by ghost** [comment]
I see, that works perfectly. Thank you so much!
