### ISSUE TITLE
custom tagging implementation via has_many, through

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#147]
Okay this one is directly tied to the class material from Tuesday. I'm trying to set up a tagging system for users, and I'm stuck at the input stage. I get "NoMethodError in Users#new"

```
<%= f.text_field :tag_list, value: @user.tag_list.to_s %>
```

is the culprit line.

I also have the following in my users controller, along with :tag_list and :name included in 
user_params:

```
    def tag_list
      @user = User.find( params[:id] )
      @user.tags.map(&:name).join(", ")
    end

    def tag_list=(names)
      @user = current_user
      @user.tags = names.split(",").map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
      return @user.tags
    end
```

**Comment by RobertAKARobin** [comment]
Which is the method it's saying doesn't exist?

**Comment by jkoul** [comment]
tag_list

**Comment by RobertAKARobin** [comment]
What is `tag_list`? Is that a column in your User model? Is it coming from that Gem?

**Comment by jkoul** [comment]
I'm working without a gem. Do I need to overtly add tag_list to the schema as a column of the join table user_tags?

**Comment by jshawl** [comment]
because you're using `@user.tag_list`, you need to define these methods in the model, and not in the controller: 

``` rb
class User < ActiveRecord::Base
  def tag_list

  end
end
```

**Comment by RobertAKARobin** [comment]
I'm going to close this. Please feel free to open a new issue linking to this one if necessary.
