### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#149]
I ran across an error when attempting to deploy my application:

remote: ! Detected sqlite3 gem which is not supported on Heroku.

I walked through it with Matt on Tuesday and thought that I took all the steps necessary to make the change from SQLite to PSQL. Walked through the site provided in the error message. Tried everything they suggested, but no luck!

**Comment by andrewsunglaekim** [comment]
Do you have any more sqlite3 stuff in your `Gemfile.lock`?

**Comment by ghost** [comment]
I checked a few times, since that's what was suggested might be the the cause of it, but found nothing.

**Comment by RobertAKARobin** [comment]
Check out my last comment on here:

https://github.com/ga-dc/pbj-project2/issues/95

**Comment by RobertAKARobin** [comment]
Just make sure to change the name of the database where it's referenced in the code included in that comment. Melissa's was `tinboard`, which presumably yours isn't!

**Comment by mattscilipoti** [comment]
We identified that you needed to commit your changes before pushing to heroku.

**Comment by mattscilipoti** [comment]
Commit early!  Commit often!
