### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project2#15]
https://github.com/Ryan-321/recipe_box

ERD and Wireframes are in the image directory

**Comment by jshawl** [comment]
:+1: Excellent project idea! When you say "Users can comment on friends recipes", will there be a friending function? 

This is a challenging thing to do - but if you pursue it the thing to google is "self referential association".

Make sure you have a clear idea of and MVP in mind before you get too deep in code!

**Comment by Ryan-321** [comment]
Maybe after the first 1,000 users?  ha!  Something I would like to have a reference for, so thanks for the share on where to look it up.  Gonna keep this one more in the KISS methodology and use it to build up my foundational knowledge of the full-stack.

**Comment by jshawl** [comment]
:+1: Excellent!
