### ISSUE TITLE
devise/db issue

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/project2#150]
I am trying to add admins to my project and devise will only allow me to add users. When I do "$rails generate devise admin" it doesn't work. My db is also erroring on db:migrate as well. This time, I only have migrations for questions, answers, and devise_to_users. In postgres, I am able to connect to the magic_db and with \d see that there is only the users row (not an admin row). The error seems to be indicating there is already an admin row.:

```
magic_db=# \d
               List of relations
 Schema |       Name        |   Type   | Owner 
--------+-------------------+----------+-------
 public | answers           | table    | Laura
 public | answers_id_seq    | sequence | Laura
 public | questions         | table    | Laura
 public | questions_id_seq  | sequence | Laura
 public | schema_migrations | table    | Laura
 public | users             | table    | Laura
 public | users_id_seq      | sequence | Laura
(7 rows)
```

**Comment by LauraWN** [comment]
Okay, let me just add that my rails server is also giving an error.
Exiting
/Users/Laura/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:557:in `add_route': Invalid route name, already in use: 'new_user_session'  (ArgumentError)
You may have defined two routes with the same name using the`:as`option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with`resources` as explained here:

**Comment by RobertAKARobin** [comment]
Sorry, I got distracted by Anon Bot. Looking now!

**Comment by RobertAKARobin** [comment]
Hm. I'm going to say that at this point in the project, you probably shouldn't be trying to add Admin to your app. Authorization and user permissions can get very complicated.

If you want to "hack" it, you could just add in a method in all the "create", "edit", and "delete" paths that checks to see if the current user's username is, say, "laurawn", and if it isn't, don't do anything.

But using Devise for admin access is biting off rather a lot.

**Comment by LauraWN** [comment]
okay, so can i just move stuff under the admin folder to a regular and delete anything admin-related? or will devise complain?

**Comment by RobertAKARobin** [comment]
It shouldn't! Add and commit first, then try it. See what happens!

**Comment by LauraWN** [comment]
okay. I am going to also delete the db with the "add_devise_to_user" migration and redo the generation of the user class through devise. (rails generate devise user) although rails also seemed to have stopped working so I'm not sure this will work.

**Comment by RobertAKARobin** [comment]
Keep us posted!

**Comment by LauraWN** [comment]
okay. I was able to do the "rails generate devise user" command. yay! But weirdly, my rails server still won't start. it does the 4 lines of ====> as if it is starting okay, but then exits?

```
=> Booting WEBrick
=> Rails 4.2.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/Laura/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:557:in `add_route': Invalid route name, already in use: 'new_user_session'  (ArgumentError).
```

I did run bundle install before this. postgres is also open.

**Comment by RobertAKARobin** [comment]
Can you show your `config/routes.rb`?

**Comment by LauraWN** [comment]
omg. I was so focused on removed all traces of admin that I didn't notice I had this line duplicated twice in my config/routes.rb file. blah.
rails s started! :)

**Comment by RobertAKARobin** [comment]
Woo!
