### ISSUE TITLE
Issue with assigning comments to photos

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#151]
I'm having problems posting comments to the correct photo. I can log in as a user, comment on a picture, and have my username show up next to the comment. The problem is that the comments show up on all my pictures including the one I intended.
My models are set up as such: comments belong to users and photos, photos belong to users and have many comments, and users have many photos and comments. I think the issue is in the comment controller.
  #create
  def create
    @user = User.find(session[:user]["id"])
    @photo = Photo.find(params[:photo_id])
    @comment = @user.comments.create!(comment_params)
    redirect_to photo_path(@photo)
  end

Where @comment is assigned to @user.comments rather than @photo.comments.

**Comment by jshawl** [comment]
What does your photo controller show action look like?

**Comment by walter-0** [comment]
```
 #show/new comment
  def show
    @photo = Photo.find(params[:id])
    @user = User.find(session[:user]["id"])
    @comments = @user.comments
    @comment = Comment.new
    @tag = Tag.new
    @tags = @photo.tags
    @categories = @photo.categories
    @score = @photo.score
  end
```

**Comment by jshawl** [comment]
instead of `@comments = @user.comments` you should use `@comments = @photo.comments`

**Comment by jshawl** [comment]
or `@photo.comments.where(user: @user)`

**Comment by walter-0** [comment]
I changed @comment in the comment create path to 
@comment = @photo.comments.where(user: @user).create!(comment_params)

and @comment in the photo show path to
@comments = @photo.comments.where(user: @user)

and it works!
