### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project2#152]
I created a script.js file in assets for some event listeners, but it doesn't seem to link to my views.  I get it working if I put the JS in the view, but I can't hook it up to the one in assets like CSS does.   

Am I missing a step?

**Comment by jshawl** [comment]
do you have

``` js
$(function(){
  // your code here?
})
```

You have to wait for the DOM to load before your code executes. i.e. `document.ready`

**Comment by Ryan-321** [comment]
It works great, but only when I refresh in the page.  If i leave and come back to it, it stops working...

**Comment by andrewsunglaekim** [comment]
sounds like a turbo links issue or a document ready issue. ill come over and take a look!

**Comment by jshawl** [comment]
yes i too recommend removing turbo links - https://www.google.com/search?q=remove+turbolinks
