### ISSUE TITLE
Route to categories not working from dynamic drop-down

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#153]
My drop down menu links to selected category is not finding the path.  Drop-down is created dynamically from the Category table...  (undefined method `categories_path' for #<#Class:0x007fb888f4bcb0:0x007fb88d379db0>)

```
          <% Category.all.each do |category| %>
            <li><%= link_to category.category_title, categories_path(:id) %></li>
          <% end %>
```

Routes.rb file

```
Rails.application.routes.draw do
  root to: 'photos#random_photos'
  resources :users do
    resources :photos
  end
...
  get '/categories/:id',      to: 'photos#category'
end
```

**Comment by jshawl** [comment]
`categories_path` is undefined because you dont have resources for it.

instead in config/routes.rb use:

``` rb
resources :categories, only: [:show]
```

**Comment by RobertAKARobin** [comment]
I'm going to close this. Please open a new issue linking to this one if necessary.
