### ISSUE TITLE
Issue with conditional statement in the view

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/project2#154]
this is on github > branch :: ajax4sheezy 
I have a medication reminder application, with the main page showing all of the reminders that match a .where query interval = "morning".

in the display I have am trying to populate it so that upon load it checks to see if the reminder.taken = true (as in they have taken their medication) and if so a corresponding button called "taken?" would be given a style = display:none; attribute. 

here is the view code: 

```
 <ul class="nav nav-tabs nav-stacked">
        <% @morning_reminders.each do |f| %>
            <li>
            <%= f.medication.name %>, (<%= f.medication.dosage %>)
              <% if f.taken = true %>
              <% binding.pry %>
                  <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true,style:"display:none;"  %>
              <% else %>
                <%= button_to "Take?", medication_reminder_path(f.medication,f),method: :put,remote: true  %>
              <% end %>
            </li>
        <% end %> 
```

but when it loads it's just hiding all of the buttons. oddly also when I stuck a binding.pry in there and investigated it showed that the reminder taken property was "true" 

```
=> #<Reminder:0x007f8435aeaf90
 id: 17,
 interval: "morning",
 taken: true,
 medication_id: 5,
 created_at: Thu, 06 Aug 2015 15:10:15 UTC +00:00,
 updated_at: Thu, 06 Aug 2015 15:10:15 UTC +00:00>
[2] pry(#<#<Class:0x007f8436ade780>>)> exit

```

but I literally just created it so I knew it was false or nil and looked into the db : 

![screen shot 2015-08-06 at 11 34 54 am](https://cloud.githubusercontent.com/assets/7883907/9115932/9e2d0244-3c2f-11e5-8c33-ad1d8145f1b6.png)

and sure enough id: 17  is not true .

**Comment by edwardpark** [comment]
ignore need to clean this up. ugh

**Comment by jshawl** [comment]
You have a single equals sign: `<% if f.taken = true %>`

make it two! `<% if f.taken == true %>`

**Comment by edwardpark** [comment]
oh good lawd. haha thanks @jshawl !!
