### ISSUE TITLE
psql server startup failure

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-exercises/project2#155]
My laptop randomly shut itself down and when I tried to start postgres back up, I got errors about the server startup failing because some other server is running. I don't think there's another server running so I have no idea how to tackle this.

![screen shot 2015-08-06 at 11 36 59 am](https://cloud.githubusercontent.com/assets/6817544/9116050/3a6d0c30-3c30-11e5-810b-53a9080b151e.png)

![screen shot 2015-08-06 at 11 40 56 am](https://cloud.githubusercontent.com/assets/6817544/9116022/1c03110e-3c30-11e5-8405-6251a6607d48.png)

**Comment by RobertAKARobin** [comment]
Try this:

```
rm /usr/local/var/postgres/postmaster.pid
```

Then restart Postgres.

**Comment by nayana487** [comment]
I'm getting a message saying no such file or directory.

**Comment by adambray** [comment]
I'll come take a look!

**Comment by nayana487** [comment]
I'm not at GA at the moment. I'll head over now.

**Comment by adambray** [comment]
ah, ok! let us know when you're here

**Comment by nayana487** [comment]
hey, i'm here. outside the classrooms
