### ISSUE TITLE
deploying problem

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#156]
2 hour ago, I deployed to heroku, and it worked. And then, I put some CSS and run 
git add .
git commit -m "added some css"
git push heroku master

I do not see any error message on Terminal.
<img width="977" alt="screen shot 2015-08-06 at 11 40 58 am" src="https://cloud.githubusercontent.com/assets/11373012/9116167/e8b0ee06-3c30-11e5-8c29-675892384c9b.png">

and when I run 'Heroku open',  I got this error message.

<img width="1247" alt="screen shot 2015-08-06 at 11 40 47 am" src="https://cloud.githubusercontent.com/assets/11373012/9116171/ecbfc800-3c30-11e5-93e9-88d973482835.png">

It has been an hour that this message is shown.

**Comment by andrewsunglaekim** [comment]
`heroku config:set RAILS_ENV=development` run this command and refresh your heroku page to see errors

**Comment by RobertAKARobin** [comment]
Alternately, try this:

```
heroku logs --tail
```

This will show your Heroku server's log. It will update in real-time.

If that doesn't show you the problem, try this:

```
heroku run rails console
```

That will open the Rails console on your Heroku server. Often that tells you right away what the error is.

**Comment by ghost** [comment]
I tried heroku logs --tail, and the process stopped here.

<img width="935" alt="screen shot 2015-08-06 at 11 59 19 am" src="https://cloud.githubusercontent.com/assets/11373012/9116611/4677a456-3c33-11e5-9112-d32116e58b94.png">

so, I tried 'heroku run rails console' and found the error
<img width="1030" alt="screen shot 2015-08-06 at 12 00 24 pm" src="https://cloud.githubusercontent.com/assets/11373012/9116634/5aacf124-3c33-11e5-82fb-d4a375900907.png">

I tried to make login/logout flash message and made sessions_controller.rb file. The flash message did not work, so decided not to use the flash message and left the file in the folder. 
After I erased it, deploying works!

Thank you. Robin!

**Comment by RobertAKARobin** [comment]
Cool! Make sure you run `heroku run rake db:migrate` if you haven't yet.

**Comment by RobertAKARobin** [comment]
Cool! Make sure you run `heroku run rake db:migrate` if you haven't yet.
