### ISSUE TITLE
Controller Actions Not Working as Expected

### ISSUE THREAD

**Issue by kristingreenslit** [ga-wdi-exercises/project2#157]
I tried to 'show' an online quiz when a user clicks on the link to access the quiz.
I expected the form to show up on the page to the user but it won't appear.

I have a mentor session at 12:30, but I wanted to go ahead and submit this issue if I still need help afterward. Stephen took a look at this last night with me and we couldn't get it to work. We tried several times to alter the paths in the form, and also binding.pry in the controller and looking through past project examples.

Thanks!

**Comment by RobertAKARobin** [comment]
When you say it won't appear, do you mean it throws an error? Or it just doesn't appear? Can you share the code that you think should make it appear?

**Comment by kristingreenslit** [comment]
Robin - got this figured out. Still have one lingering issue but will submit another request. Thanks!
