### ISSUE TITLE
link_to text renders twice for each comment

### ISSUE THREAD

**Issue by kscoulter** [ga-wdi-exercises/project2#158]
here's my code 

```
<%if @event.comments.all.length > 0 %>
  <section class="comments">
  <%@event.comments.each do |comment|%>
    <p><%=comment.body%><p>
    <%= link_to 'Destroy Comment', [comment.event, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  <%end%>
  </section>
<%end%>
```

**Comment by RobertAKARobin** [comment]
Is it just the text rendering twice, or the whole `<a>` rendering twice?

**Comment by kscoulter** [comment]
The whole `<a>` But only one of them leads to the correct delete action.

**Comment by Curtismn87** [comment]
```
"<p> <%=comment.body%> <p> ..... close the </p> "??
```

I don't know why it's not showing everything I typed.. I think theres an open p tag

**Comment by kscoulter** [comment]
Good catch, the problem persists. For some reason the two links lead to two different paths.

**Comment by RobertAKARobin** [comment]
I'll come look.

**Comment by kscoulter** [comment]
I'm at home :(

**Comment by RobertAKARobin** [comment]
I won't, then. Can you show the rendered HTML for one of these pairs of links?

**Comment by kscoulter** [comment]
https://files.slack.com/files-pri/T0351JZQ0-F08N709R6/board-together-error.png?

**Comment by RobertAKARobin** [comment]
This event appears to have two comments, no?

**Comment by kscoulter** [comment]
Here's my branch: https://github.com/kscoulter/board-together/tree/add-comments

The event has only 1 comment. It seems like something else is getting into my comments table without me explicitly creating it.

**Comment by kscoulter** [comment]
@event.comments.all.length is 1

**Comment by RobertAKARobin** [comment]
Can you show the controller action for this page?

**Comment by kscoulter** [comment]
I ran binding.pry on the code. In the second iteration of the loop comment is `#<Comment:0x007fbdae7eb788 id: nil, commenter: nil, body: nil, event_id: 8, created_at: nil, updated_at: nil>`

**Comment by RobertAKARobin** [comment]
See previous question. :P

**Comment by kscoulter** [comment]
```class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = Event.all.order(:time)
  end

  def show
    @event = Event.find(params[:id])

```
if @event.attendances.find_by(user_id: current_user.id)
  @attendance = @event.attendances.find_by(user_id: current_user.id)
else
  @attendance = Attendance.new
end

@attendances = Attendance.all
```

  end```

```class CommentsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(comment_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end```

**Comment by kscoulter** [comment]
You can also see it in my repo: https://github.com/kscoulter/board-together/tree/add-comments

**Comment by kscoulter** [comment]
fixed it by changing my each loop to `<%@event.comments.all.each do |comment|%>`

**Comment by kscoulter** [comment]
Still don't know why that worked :(
