### ISSUE TITLE
No route matches [POST] "/comments"

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#159]
I'm getting this error every time I attempt to submit a new comment:

```
Routing Error
No route matches [POST] "/comments"
Rails.root: /Users/Justin/wdi/projects/faithbook
```

Everything looks fine to me in comparison examples from past projects, and I've made numerous changes to my comments controller to no avail.

**Comment by adambray** [comment]
Can you send the output of `rake routes`?

**Comment by RobertAKARobin** [comment]
Can you show the code for the form you're submitting?

**Comment by ghost** [comment]
YES sorry, forgot about that:

```
def create
    @profile = Profile.find(params[:profile_id])
    @comment = @profile.comments.create!(comment_params)

    redirect_to profile_path(@profile)
  end
```

**Comment by ghost** [comment]
my form:

```
<%= form_for @comment do |f| %>

  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </p>

  <p>
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>

  <p>
    <%= f.label :date_time %>
    <%= f.text_field :date_time %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>

  <p>
    <%=f.submit %>
  </p>

<% end %>
```

**Comment by RobertAKARobin** [comment]
Can you show your `config/routes.rb`?

**Comment by ghost** [comment]
Rails.application.routes.draw do

```
  root to: 'profiles#index'
  get 'comments', to: 'profiles#index'
  resources :profiles do
    resources :comments
  end
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'
```

**Comment by adambray** [comment]
You have nested routes for comments, so anywhere you're creating a path must be updated as well, including form_for. Try googling 'form_for with nested routes'

**Comment by ghost** [comment]
Thanks, @adambray. Still having issues.
I changed form_for to look like this:

```
<%= form_for [@post, @comment] do |f| %>
```

I thought that might do the trick, but nothing changed. Sorry if I'm missing something completely obvious!

**Comment by RobertAKARobin** [comment]
That's because comments are nested under Profiles, not Posts. If you want them to be nested under both, you'd need:

```
resources :profiles do
  resources :comments
end
resources :posts do
  resources :comments
end
```

**Comment by ghost** [comment]
GAH. Embarrassing. Thank you so much.
