### ISSUE TITLE
Issue with correct comment labeling on photos

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#160]
Right now users can choose to view only their photos, or all posted photos. Users can comment on all photos and have them saved. When I tried to view any photo, every comment shows the current user as the author and not the user who wrote it. If the user changes, the comment author changes on every comment as well. How can I get the comment to show the user who wrote it, and not the current signed-in user?

photos/show.html/erb

```
<% @comments.each do |comment| %>
  <ul>
    <%= link_to comment.id, photo_comment_path(@photo, comment) %>
    <%= @user.username %> wrote:
    <%=comment.content %>
  </ul>

<% end %>
```

photos_controller.rb
  #show/new comment

```
  def show
    @photo = Photo.find(params[:id])
    @user = User.find(session[:user]["id"])
    @comments = @photo.comments
    @comment = Comment.new
    @tag = Tag.new
    @tags = @photo.tags
    @categories = @photo.categories
    @score = @photo.score
  end
```

**Comment by RobertAKARobin** [comment]
That's because you're doing `@user = User.find(session[:user]["id"])`. This finds the user who's currently signed in. `session` is how Rails "remembers" who's signed in. If you want to find the photo's user, you'd use `@user = @photo.user`.

**Comment by walter-0** [comment]
I changed @user in the photos controller to @photo.user and now the comment shows only the user who posted the photo. I'm going to keep this issue open for a bit while I play around with the controllers.

**Comment by RobertAKARobin** [comment]
You'll basically need two different controller actions, then: one for when the user should only their own photos, and one for when they should see all photos.

**Comment by walter-0** [comment]
I have that working to view photos.

```
  #index, all photos
  def index
    @photos = Photo.all
  end

  #my_photos
  def my_index
    @photos = User.find(session[:user]["id"]).photos
  end
```

**Comment by RobertAKARobin** [comment]
Each action should change what `@user` is then, no? I can come look at it after our meeting.

**Comment by walter-0** [comment]
Solved by changing
<%= @user.username %> wrote:

in the photo show page to:
