### ISSUE TITLE
gem activerecord_reputation_system

### ISSUE THREAD

**Issue by rewarren** [ga-wdi-exercises/project2#161]
I installed this gem to use an upvote/downvote on my animals.  I'm sort of at a loss at how to tackle the error i'm getting below.. 

<img width="527" alt="screen shot 2015-08-06 at 12 15 54 pm" src="https://cloud.githubusercontent.com/assets/10967783/9116909/eb253efe-3c34-11e5-9b97-69402e7b2c0c.png">

**Comment by jshawl** [comment]
The documentation says to `rails generate reputation_system`..

did you run that command?

**Comment by RobertAKARobin** [comment]
Can you not use a Gem? It's a little late in the project to be installing new ones.

If you _really_ want upvote/downvote functionality and it's _absolutely_ essential to your MVP, I'd say instead to create a Vote model, that belongs to an animal.

**Comment by rewarren** [comment]
Jesse, yes i did, it created 9 migrations. 

its ok tho, maybe ill just scrap it all together
