### ISSUE TITLE
ActiveRecord (devise) issue with Heroku

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/project2#162]
My app functions the way it is supposed to on the local server, signin, signout, signup, user privileges etc. but once I deployed to heroku I got the following error:

PG::UndefinedTable: ERROR:  relation "users" does not exist

What relationships do I need to have in place. my three tables are users, stores, items.

Users - Has_many :stores .. Stores - Has_many :items , belongs_to :users , Items - belongs_to :stores

**Comment by jshawl** [comment]
Do you have a migration that creates the users table?

**Comment by Curtismn87** [comment]
Yes, the users table was created through a migration. I added the relationships after if that makes a difference.

**Comment by adambray** [comment]
Please see [the lesson plan for deploying to heroku (common pitfalls)](https://github.com/ga-dc/pbj/tree/master/05-mvc-with-rails/rails-deployment#common-pitfalls-20-minutes)...
I think you've hit one of the common pitfalls here.
