### ISSUE TITLE
issue with creating method to run on one instance of hash at a time, when the class is a hash

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project2#165]
I want to iterate through an object of articles and call a method that returns a particular value based on the length of each article. However, I can't figure out where to put the method or how to write it so that it doesn't return an error. 
This code:
![screen shot 2015-08-06 at 12 24 16 pm](https://cloud.githubusercontent.com/assets/7719096/9117129/4646494e-3c36-11e5-984e-5de37dade360.png)

gives me this error:
![screen shot 2015-08-06 at 12 23 17 pm](https://cloud.githubusercontent.com/assets/7719096/9117137/578befce-3c36-11e5-8d65-c827e1e85f76.png)

...because I can't call a method on a string? But the other way I tried—setting up the method to run on the entire thing, like `result.ext_length_class` —gives a different error:
![screen shot 2015-08-06 at 12 28 21 pm](https://cloud.githubusercontent.com/assets/7719096/9117218/c8ce1fea-3c36-11e5-8b6d-750c143664af.png)

The method I wrote (in the application helper file) is:
![screen shot 2015-08-06 at 12 30 20 pm](https://cloud.githubusercontent.com/assets/7719096/9117265/0f6da5a6-3c37-11e5-87d8-6307e188cdf7.png)

**Comment by andrewsunglaekim** [comment]
I think the issue here is you're calling `ext_length_class` whatever you define in the helper file has to be a self standing method not a method called on an object. You could maybe pass in the string as an argument instead of calling the method on a string.

**Comment by msteffan** [comment]
Yeeeeessssssss. Thank you!
