### ISSUE TITLE
Assistance needed with forcing a migration 

### ISSUE THREAD

**Issue by lscottcook** [ga-wdi-exercises/project2#166]
I am trying to remove a column (photo_url) from a database.  I have tried different methods which failed. The last one that I tried is  bin/rails generate migration RemovePhotoUrlFromFrowns photo_url:string.

This resulted in the following message

"Another migration is already named remove_photo_url_from_frowns: /Users/lscottcook/wdi/projects/smilz/db/migrate/20150805175133_remove_photo_url_from_frowns.rb. Use --force to replace this migration or --skip to ignore conflicted file."

I googled to find out how to force the migration it but did not come up with anything.   The column is still there.  I also tried the same process on another column that I want to delete and received the same message.

**Comment by adambray** [comment]
@lscottcook I'm guessing that you figured it out by the fact that you closed this issue... would you mind updating this issue with a short (1 - 2 sentences are enough) description of how you fixed it?

Thanks!

**Comment by lscottcook** [comment]
I'm not sure what actually corrected it.  I ran rake db:migrate again which might have fixed it but now I'm having the same problem with another column that is giving me the same error and I'm following the same steps.  Plus with the initial issue, a migration file did not generate .
