### ISSUE TITLE
ActiveRecord not recognizing Posts

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#167]
I am getting an error that says Categories Active Record is not recognizing my @posts object. I attached my ERD if that helps too. 

![img_9600](https://cloud.githubusercontent.com/assets/11203264/9118419/3944cd26-3c3e-11e5-83e2-000de7afad5c.JPG)

![screen shot 2015-08-06 at 1 17 32 pm](https://cloud.githubusercontent.com/assets/11203264/9118331/9e987ba6-3c3d-11e5-91b8-a51729f649a5.png)

**Comment by RobertAKARobin** [comment]
Can you show your `category.rb` model?

**Comment by malissaromero** [comment]
```
class Category < ActiveRecord::Base
  has_many :categories_posts
  has_many :posts, through: :categories_posts
end
```

**Comment by RobertAKARobin** [comment]
Can you also show the `posts#index` controller action?

**Comment by malissaromero** [comment]
```
class PostsController < ApplicationController
  before_action :authenticate

  def index
    @categories = Category.all
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create!(post_params)
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :category, :command, :description)
  end
  private
  def category_params
    params.require(:category).permit(:name, :category_id)
  end
end
```

**Comment by RobertAKARobin** [comment]
The problem is you're doing `@categories.posts`. Only a single category has posts; a _collection_ of categories doesn't have posts. I know that sounds kinda weird.

In Ruby a single category is one object, and a collection of categories is _also_ one object in the same way that an array of 47 names is one object. But that collection of categories is an object is of a different kind than the first one. If you do `Category.find(32).class`, you'll get "Category". If you do `Category.all.class`, you'll get "ActiveRecord_Relation".

Anyway, you want to show ALL the posts in the database, right? So instead of of `@categories.posts.each do`, just do `@posts.each.do`.

**Comment by malissaromero** [comment]
That does make sense. It does get me out of the error however it shows all posts and I want posts with that category ID which is why I thought @category.post

**Comment by RobertAKARobin** [comment]
Ah, gotcha. You _do_ want `@category.post`, but you had `@categories.post`. 

Modify your `def index` to include `@category`:

```
 def index
    @categories = Category.all
    @category = Category.find(params[:id])
    @posts = Post.all
  end
```

**Comment by malissaromero** [comment]
Either way, it gives me the save error message. 
![screen shot 2015-08-06 at 1 42 25 pm](https://cloud.githubusercontent.com/assets/11203264/9118802/fec8d482-3c40-11e5-93aa-48ba760570fb.png)

**Comment by RobertAKARobin** [comment]
You can't just change the name; you have to make `@category` actually equal something.

The way you had your action, `@category` wasn't defined anywhere, and so wasn't equal to anything:

```
 def index
    @categories = Category.all
    @posts = Post.all
  end
```

...which is why I suggest this:

```
 def index
    @categories = Category.all
    @category = Category.find(params[:id])
    @posts = Post.all
  end
```

**Comment by malissaromero** [comment]
I tried that too and it gives me a bogus message. The id is literally in the route and it gives me back the id in the parameters. 

![screen shot 2015-08-06 at 1 48 25 pm](https://cloud.githubusercontent.com/assets/11203264/9118951/e22b5df8-3c41-11e5-8502-89c0a6cb0ff5.png)

**Comment by RobertAKARobin** [comment]
Oh, cool! That's because it's a nested resource. You need `params[:category_id]`.

**Comment by malissaromero** [comment]
I'm so sorry. I feel like these errors are going on forever. 

I am now getting this error: 

![screen shot 2015-08-06 at 2 02 24 pm](https://cloud.githubusercontent.com/assets/11203264/9119288/e43f17f4-3c43-11e5-9c09-0e1075a18ae3.png)

I think it has to do with my posts controller:

```
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categories_posts
  has_many :categories, through: :categories_posts
end
```

I believe I messed up in nesting my routes because posts was already connected to categories through a  join table and then I went and nested posts in my categories like so 

```
  resources :users do
    resources :posts, only: [:index]
  end

  resources :posts do
  end

  resources :categories do
    resources :posts
  end
```

**Comment by RobertAKARobin** [comment]
Oops, sorry, Melissa! We missed this one. One sec.

**Comment by RobertAKARobin** [comment]
Can you show me your "posts#index" controller action now?

**Comment by malissaromero** [comment]
ok thank you

  def index
    @categories = Category.all
    @category = Category.find(params[:category_id])
    @posts = Post.all
  end

**Comment by malissaromero** [comment]
I'm sure you are really busy, but it is my last piece of my project. please help!

**Comment by jshawl** [comment]
en route!
