### ISSUE TITLE
Assistance needed with forcing a migration- somehow I resolved it once but unable to do it again

### ISSUE THREAD

**Issue by lscottcook** [ga-wdi-exercises/project2#168]
I previously submitted an issue for the same issue but with a different column.  Somehow that has been resolved. I am having the same issue with a a different column after following the same steps as the first column.  

I tried to remove a column (name) from a database. I have tried different methods which failed. The last one that I tried is bin/rails generate migration RemoveNameUrlFromFrowns name:string.

This resulted in the following message

"Another migration is already named remove_name_from_frowns: /Users/lscottcook/wdi/projects/smilz/db/migrate/20150805175149_remove_name_from_frowns.rb. Use --force to replace this migration or --skip to ignore conflicted file."

I ran rake db:migrate which did not result in any error but did not generate a migration file.

**Comment by andrewsunglaekim** [comment]
What was the original issue?

**Comment by RobertAKARobin** [comment]
https://github.com/ga-dc/pbj-project2/issues/166

**Comment by jshawl** [comment]
It looks like you have two migrations that try to remove the column.can you send a link to your repo?

**Comment by andrewsunglaekim** [comment]
If you don't care about your database, you could always delete all your migrations and recreate new ones with the appropriate columns

> Note that it's generally not good practice to do this and can be dangerous in production environments. It's OK to do during development so long as you're not losing any important data in your database. Again not the best practice, but it will solve your problem.

**Comment by lscottcook** [comment]
@jshawl 

Here is the link to my repo https://github.com/lscottcook/smilz.git

**Comment by lscottcook** [comment]
@RobertAKARobin - I finished fixing the migrations. You can come by when you are free or I can come to you.  Thank you

**Comment by RobertAKARobin** [comment]
OK! I'll be there in a mo'.
