### ISSUE TITLE
migration of db issue

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/project2#169]
I successfully added my devise to users and it created a db (AddDeviseToUsers). 

Then I ran a rake db:drop (success), rake db:create (success), but then rake db:migrate (no success). It shows it successfully migrating part of it, but then errored on the last part. 

```
Lauras-MacBook-Pro:magic8ball Laura$ rake db:migrate
== 20150804014258 CreateQuestions: migrating ==================================
-- create_table(:questions)
   -> 0.0072s
== 20150804014258 CreateQuestions: migrated (0.0073s) =========================

== 20150804020412 CreateAnswers: migrating ====================================
-- create_table(:answers)
   -> 0.0148s
== 20150804020412 CreateAnswers: migrated (0.0149s) ===========================

== 20150806172019 AddDeviseToUsers: migrating =================================
-- change_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "users" does not exist
: ALTER TABLE "users" ADD "email" character varying DEFAULT '' NOT NULL/Users/Laura/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
```

**Comment by andrewsunglaekim** [comment]
What do you mean by `AddDeviseToUsers`? did you run these commands in the terminal ever?:

```
$ rails generate devise:install
$ rails generate devise user
```

**Comment by LauraWN** [comment]
yes, (well instead of rails generate devise:install), I ran bundle install. upon running $rails generate devise:install, I was asked if I wanted to overwrite it. I did. 
$ rails generate devise user gave me a new error. It's the one where it it adding the extra line about have an extra path (what this equates to is it is adding devise_for :users in the config/routes.rb file when it is already there. I deleted the duplicate line from config/routes.rb that devise likes to add in there.

**Comment by jshawl** [comment]
can you please push your latest code so we can look at the migrations?

**Comment by LauraWN** [comment]
okay, pushed to github.

**Comment by jshawl** [comment]
https://github.com/LauraWN/Magic8Ball/blob/d5e8d2d343d14ebbdc43ec94067e786353b94018/db/migrate/20150806182400_add_devise_to_users.rb#L3

Should say `create_table` - didn't we work through this on Tuesday? Let me know if that fixes!

**Comment by LauraWN** [comment]
okay, per postgres and a succesful rake db:migrate (and another push to github), I have answers, questions, and users all in my table.
at some point (like now) do I run the $rails generate devise user to get the devise gem functionality in there?

**Comment by jshawl** [comment]
i think you're good to go!

What happens if you visit http://localhost:3000/users/sign_up ?

**Comment by LauraWN** [comment]
NoMethodError in Devise::Registrations#new
Showing /Users/Laura/wdi/Magic8Ball/app/views/devise/registrations/new.html.erb where line #8 raised:
undefined method `email' for #<User id: nil>

line 8 reads:
    <%= f.email_field :email, autofocus: true %>

**Comment by jshawl** [comment]
Can you try `rake db:migrate:reset`?

Your migratino looks good but your schema shows a missing email field

**Comment by RobertAKARobin** [comment]
We haven't heard from you in a bit, so I'm going to close this, Laura.

**Comment by LauraWN** [comment]
I just ran rake db:migrate:reset and it was successful after I rebooted postgres. 

However, my schema didn't auto-populate. I just pulled up a solution branch for one of the tunr's and there is a ton of info in the schema under create_table "users". I hesitate to manually add this info in.
