### ISSUE TITLE
Project 2 HW

### ISSUE THREAD

**Issue by englep10** [ga-wdi-exercises/project2#17]
https://drive.google.com/file/d/0BwuHABBLNANqWVBTT0RUT3BySzg/view?usp=sharing

https://trello.com/b/1td4WDWF/onlineaircraft

**Comment by andrewsunglaekim** [comment]
I like the idea. I would save favoriting for later in the week if you have time after you've finished commenting.

**Comment by englep10** [comment]
https://github.com/englep10/online_aircraft
