### ISSUE TITLE
Issue with sorting photos by score

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#170]
I tried using this code for the photos index to sort photos by descending score order:
<%= @photos.sort_by{|photo| -photo.score} %>
<% @photos.each do |photo| %>
  <p>
    <%= link_to photo.title, photo_path(photo) %>
    <%= image_tag photo.photo_url %>
    Score: <%= photo.score %>
  </p>
<% end %>

Displaying the first line with the = sign verified that this line is working, but the photos are not displaying in the correct order. Where do I put the first line in order to clear this up?

**Comment by jshawl** [comment]
I recommend doing this in your controller:

``` rb
@photos = Photo.all.order(score: :desc)
```

**Comment by jshawl** [comment]
you can also use binding.pry in your controller to debug the sorting.

Also, using active record to sort (with `order`) will be faster than ruby's `sort_by` i believe!

**Comment by walter-0** [comment]
It worked! Thanks.
