### ISSUE TITLE
Quiz score is not visible to user / "invalid authenticity token" error

### ISSUE THREAD

**Issue by kristingreenslit** [ga-wdi-exercises/project2#172]
I tried to show a user's score on a page after the user takes a quiz.

I expected the score to display on the user's view.

Instead the score is not visible to the user and I had to comment out  "protect_from_forgery with: :exception" and "before_action :authenticate_user!" in the Application Controller so that after submitting the quiz form I wouldn't get the error "Invalid Authenticity Token."

Screenshots of current error and code attached. Thanks!

<img width="573" alt="screen shot 2015-08-06 at 2 30 05 pm" src="https://cloud.githubusercontent.com/assets/5890436/9120108/6e167090-3c48-11e5-9ae3-bba7d4552e00.png">

<img width="552" alt="screen shot 2015-08-06 at 2 30 22 pm" src="https://cloud.githubusercontent.com/assets/5890436/9120118/77f0eb68-3c48-11e5-9f3f-75e3bb30193d.png">

**Comment by andrewsunglaekim** [comment]
Sounds like you aren't generating a token in the form when someone takes a quiz. `.score` is an undefined method because `@user` isn't defined because score looks like its being called on `nil`

**Comment by kristingreenslit** [comment]
what you're saying makes sense although I don't know how to fix it

**Comment by RobertAKARobin** [comment]
Try just removing the `@user.score` line.

**Comment by kristingreenslit** [comment]
Thanks Robin! That worked but the core issue is that I still can't get the score to display to a user.

**Comment by RobertAKARobin** [comment]
Do you have `<%= @user.score %>` in your view anywhere?
