### ISSUE TITLE
Help with moving button, front-end layout issue

### ISSUE THREAD

**Issue by petergcutler** [ga-wdi-exercises/project2#173]
I'm trying to move a button in my layout, using flexbox and bootstrap, and running into difficulty. It's the teal/green button below. Have tried lots of absolute/relative positioning approaches and am running into a wall.

In addition, I'm running into an issue trying to balance centering my four panes below while extending them to the edge of the browser window. I'm using {margin: 0 auto} to keep the four panes centered, but that's making it impossible to extend these panes towards the edge of the browser.

![screen shot 2015-08-06 at 2 46 53 pm](https://cloud.githubusercontent.com/assets/11398019/9120410/133569ea-3c4a-11e5-9903-4c096528b8aa.png)

**Comment by RobertAKARobin** [comment]
Are you here? I can come take a look. If not, push your code to Github and I'll look!

**Comment by petergcutler** [comment]
Thanks, I'm here, Adrian helped out.
