### ISSUE TITLE
Question about Heroku and Paperclip

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/project2#174]
I saw the AWS3 issue but when I deployed it showed the picture just fine, is this a matter that it'll work but anticipated that at some point Heroku will wipe the data off?

**Comment by RobertAKARobin** [comment]
Woah. Neither Heroku nor AWS should ever, ever, ever wipe memory. If they do, no-one will use their service again. Heroku's down for now, meaning they're just not letting people push to them, but your data should be safe!

**Comment by edwardpark** [comment]
oh awesome! k no I deployed a little earlier in the day I was just wondering  thanks @RobertAKARobin
