### ISSUE TITLE
LAYOUT HELP

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#176]
I'm having the worst time getting the header, left-hand nav bar and main content box to line up properly. Unfortunately learnlayout.com hasn't helped appreciably, although my css file is an awful lot more cluttered now.

Currently, I have:

```
header {
  color: white;
  display: inline-block;
  align-items: flex-end;
  position: fixed;
}
```

**Container is class covering whole main section***

```
.container {
  position: relative;
}
```

```
.blog-nav {
  float: left;
  display: inline-block;
  width: 20%;
  position: fixed;
  background: #e6e6e6;
  border: 1px solid black;
  padding: 10px;
  margin-top: 2em;
  margin-left: 10px;
  box-sizing: border-box;
}
```

```
.content {
  display: inline-block;
  position: ;
  width: 65%;
  margin: 0 10% 0 25%;
  background-color: white;
  color: #5E0000;
  border: 2px solid black;
  box-sizing: border-box;
  min-height: 30em;
  text-align: center;
}
```

**Comment by amaseda** [comment]
Can you send a link to your repo? Want to get an idea of what your site looks like.

**Comment by jkoul** [comment]
sure, lemme push right now. One sec

**Comment by jkoul** [comment]
https://github.com/jkoul/dcfuture/

**Comment by amaseda** [comment]
Let me know if you have any additional questions about this.
