### ISSUE TITLE
rake db:migrate:reset and schema not auto-populating

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/project2#177]
I just ran rake db:migrate:reset and it was successful after I rebooted postgres.

However, my schema still didn't auto-populate. I just pulled up a solution branch for one of the tunr's and there is a ton of info in the schema under create_table "users". I hesitate to manually add this info in.

**Comment by mattscilipoti** [comment]
Your hesitation is correct.  `db/schema.rb` is auto-generated.  If you make changes to it directly, they will be overridden the next time it is generated.  We need to look at the source - your database.  Your database is created from your migrations.  
I can think of 2 obvious causes:
1. It's likely that the `rake db:drop` did not work, therefore the following steps didn't do quite what you expect.  Please check the terminal to make sure.
2. The migrations are not doing exactly what you think.  Review each one, in order, to look for your specific issue.

**Comment by mattscilipoti** [comment]
ProTip: See every command that rake calls via "--trace" flag. `rake db:migrate:reset --trace`.

**Comment by LauraWN** [comment]
I added this to the model/user.rb:   belongs_to  :question, dependent: :destroy
with the trace on, I think it ran.
The last two lines are:
*\* Execute db:schema:dump
*\* Execute db:migrate:reset
the schema still didn't generate any user details.

**Comment by jshawl** [comment]
en route!
