### ISSUE TITLE
Melissa - Project 2 Repo & User Stories

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project2#18]
Repo: https://github.com/msteffan/tinboard

**Comment by RobertAKARobin** [comment]
Nice use of post-its. :) Cool idea! I would totally use an app that let me browser articles based on length. I hope you'll come back to this after we've gone over APIs so you can pull articles directly from news sources. (Unless you feel like trying to add in APIs now...!)

Please put the photos in a `planning/wireframes` directory.

**Comment by msteffan** [comment]
Wow, I came back to add a question, and you had already responded/closed the issue! So speedy. 

My question is: Does my ERD illustrate the correct way to set up a "has_many :through" association? That is, the "through" class will have 2 belongs_to attributes and thus the table will contain two foreign IDs per entry (one for each of the other classes with which it is associated). Later, I would then call something like User.articles, even though it's not a direct relationship. 

We didn't go over this type of association in class so I just wanted to confirm that the logic here works. Thanks!
