### ISSUE TITLE
cancancan setting user.id = to current_user.id

### ISSUE THREAD

**Issue by pdavies88** [ga-wdi-exercises/project2#180]
hey guys figured i'd send this in quick before everyone takes off for the day. implemented devise and cancancan on my app.  Having an issue where when i implement if can? to hide links to both edit and destroy actions for incorrect users they are being hidden for everyone instead. currently my code is below not sure how to say the current user that is logged = the user that created xyz post if that is the case. might be just overthinking but any hints would be appreciated. 

```
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:update, :destroy], Post do |post|
      user.id == post.user_id
    end

    can [:update, :destroy], Comment do |comment|
      user.id == comment.post.user_id
    end

    if user.admin
      can :manage, Post
    end
  end
end
```

**Comment by jshawl** [comment]
Not sure if this is related but your current code on github has a few misplaced ends - https://github.com/pdavies88/project_2_preston/blob/cancancan/app/models/ability.rb

**Comment by pdavies88** [comment]
yes I saw that have it fixed on my local to what it looks like above in the post need to add and push that up haven't done that yet was trying to fix on local before pushing and commiting

**Comment by pdavies88** [comment]
hey jesse not super important I will try to find someone tomorrow to chat about it with and see if I can resolve it overnight

**Comment by jshawl** [comment]
we are currently discussing!

**Comment by pdavies88** [comment]
cool thanks! it's more of a silver or gold mvp thing for me so not crazy pressing in the late hour

**Comment by adambray** [comment]
@pdavies88 cancancan expects a `current_user` method, it doesn't look like you have one! You want something like:

``` ruby
def current_user
  return User.find(session[:user_id]) if session[:user_id]
end
```

(this assumes you're setting session[:user_id] in your sign in method)

**Comment by pdavies88** [comment]
ah cool thanks adam think that'll do the trick appreciate the help
