### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-wdi-exercises/project2#182]
deployed to heroku completed, getting this when I go to the page... 

```
We're sorry, but something went wrong.
```

Logs show this...
but everything seems to be working when I test... can't seem to pinpoint the error.

```
2015-08-06T20:26:56.325527+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "services" does not exist
```

**Comment by amaseda** [comment]
Did you run `heroku run rake db:migrate`?

**Comment by phantomhaircuts** [comment]
ughhhhh its working now. wamp wamp.

**Comment by amaseda** [comment]
:+1:
