### ISSUE TITLE
Screencast

### ISSUE THREAD

**Issue by M00staff** [ga-wdi-exercises/project2#183]
whats the best/preferred way to do the screencast?

**Comment by jshawl** [comment]
Quicktime > File > New Screen Recording

is that what you mean?

**Comment by RobertAKARobin** [comment]
...and please upload to YouTube!

**Comment by RobertAKARobin** [comment]
https://github.com/ga-dc/pbj-project2/blob/master/presentations.md

**Comment by M00staff** [comment]
awesome - thanks!
