### ISSUE TITLE
Local connection no longer working

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/project2#184]
I am getting the error:
 could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Not sure what is happening. I am trying to run the rails server

**Comment by Curtismn87** [comment]
Nevermind... I closed Postgres and didn't realize it

**Comment by jshawl** [comment]
:+1:
