### ISSUE TITLE
Counter Issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#185]
I have a javascript counter on my project that starts at 0 and adds to the total by one when a button is clicked. That's all fine and dandy, but if I navigate away from the page and come back, the number reverts back to 0! I tried google, but I can't find any info on how I'd make the number stay even when I navigate away from the page!

**Comment by jshawl** [comment]
you could use localstorage!

when you click the button:

``` js
localStorage.setItem("numClicks", 3)
```

when the page loads

``` js
var numClicks = localStorage.getItem("numClicks")
// set your counter to numClicks
```
