### ISSUE TITLE
Heroku App Error!

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#186]
Getting the following error when I attempt to open my app at https://faith-book.herokuapp.com:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

Everything seems to be working fine locally and I have no idea what could have went wrong! I am terrified because the latest version of my app was working just fine.

**Comment by jshawl** [comment]
did you check the logs with `heroku logs`?

**Comment by RobertAKARobin** [comment]
First, try this:

```
heroku logs --tail
```

This shows everything the server is doing _as it's happening_, just like `rails server` on your computer.

If you can't find the error that way, try:

```
heroku run rails console
```

This opens the Rails console on Heroku. Sometimes, just launching it is enough to trigger the error. If not, at least you can poke around in your database and see what's going on.

Finally, make sure you have `heroku run rake db:migrate`!

**Comment by ghost** [comment]
Yes. Still can't quite tell what the issue is exactly, but terminal freezes whenever I run heroku run rake db:migrate. I'll only be here a few more minutes and I'm afraid I won't be able to get this sorted out by tomorrow morning.
