### ISSUE TITLE
more layout - header still moving with main content block

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#187]
every website has a fixed header and left-side nav bar with a moving main content container. What am I missing here?

```
header {
  color: white;
  display: block;
  position: fixed;
}

.blog-nav {
  float: left;
  display: inline-block;
  width: 20%;
  position: fixed;
  background: #e6e6e6;
  border: 1px solid black;
  padding: 10px;
  margin-top: 2em;
  margin-left: 10px;
  box-sizing: border-box;
}

.content {
  display: inline-block;
  position: relative;
  width: 65%;
  margin: 0 10% 0 25%;
  background-color: #f6f6f6;
  color: #5E0000;
  border: 2px solid black;
  box-sizing: border-box;
  min-height: 30em;
  text-align: center;
}
```

**Comment by RobertAKARobin** [comment]
You've specified the `positioning` for your header, but haven't specified the `position`. Try adding:

```
top:0px;
left:0px;
```

If `.blog_nav` is fixed, it doesn't need to float. Also, same thing as above.

Also, this may cause those elements to be hidden by others. You'll need to arrange how they appear "vertically" using z-index (as in x-axis, y-axis, and z-axis). An element with `z-index:1000;` will be on top of an element with `z-index:999;` or `z-index:-1;`, for example. Elements on which there is no specified `z-index` default to a `z-index` of 0.

**Comment by RobertAKARobin** [comment]
Oh, you also probably should specify a `width` and `height` for anything that's fixed.

**Comment by jkoul** [comment]
Hmmmm. Where would I put the z-index command?

**Comment by RobertAKARobin** [comment]
It's a CSS property, just like the rest.

**Comment by jkoul** [comment]
Ok thanks. I have so much wrong with this I don't even know where to start.

**Comment by RobertAKARobin** [comment]
CSS is a tricky beast.
