### ISSUE TITLE
foreign key violation

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#189]
I'm not sure if there is anyone left but I am getting an error that I can't find any good resources for. I am getting it when I try to delete a post. 

![screen shot 2015-08-06 at 5 55 42 pm](https://cloud.githubusercontent.com/assets/11203264/9124386/6a1336ec-3c64-11e5-97b3-968e0c58c8f6.png)

This is my post destroy: 

```
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
```

**Comment by RobertAKARobin** [comment]
Haven't seen that in a while! Try dropping and remigrating your database.

**Comment by malissaromero** [comment]
Nick just helped me figure it out! I had to put a dependent destroy in my post.rb next to my categorizations like so: 

```
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categorizations, :dependent => :destroy
  has_many :categories, through: :categorizations
end
```

Thank you for responding!

**Comment by RobertAKARobin** [comment]
Woo!
