### ISSUE TITLE
Justin's Repo, User stories, Wireframe, ERD.

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#20]
Repo - https://github.com/iamjustinprice/faithbook

Wireframe + ERD located in "wireframes" directory.

---

FAItHBOOK!

Faithbook is a Christian social networking app. Kinda like Christian Mingle, but also like Facebook. Faithbook users will be able to sign up, create profiles, add a photo, education history, and information about themselves. Users will also have a "prayers" counter on their profile, the number of which fellow users can affect by sending prayers, kinda like a measurement of popularity. Users will be able to leave comments on fellow users' profiles. Users can comment on their own profiles as well, if they want to reply to a comment someone else left, or if they're crazy.

USER STORIES

As a user, I should be able to:
1. Sign up, sign in, and sign out, so I can create a profile, make changes to my profile, and make sure no one else is messin' with my profile info, respectively.
2. Add information to a profile, so people can see what my name is, what I look like, where I was educated, and more about me.
3. Add comments to all users' profiles, including my own, so I can keep in touch with all of my buddies.
4. Send and recieve "prayers" that increase the number of the prayer counters, so I know how many people are praying for me, and so I can let others know that they are being prayed for.
5. Edit the information I entered in my profile, so I can change typos and other mistakes.
6. See all users' profiles from the homepage, so I can navigate to them easily.
7. Have the option to delete my profile, so I can overcome my social networking addiction.

![erd](https://cloud.githubusercontent.com/assets/13008720/9029663/440af2ac-3965-11e5-816e-4a1312ac2932.jpg)
![wireframe](https://cloud.githubusercontent.com/assets/13008720/9029664/44116ae2-3965-11e5-83ac-59285c6589cd.jpg)

**Comment by mattscilipoti** [comment]
Looks good. Great readme and supporting info.  Appropriate level for this project.

Should you have any stories for anonymous users?
