### ISSUE TITLE
QT will not record audio

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project2#235]
I've been to every message board for Mac/QT help and followed all suggestions: built-in mic, aggregate device, even tried downloading Sunflower. Nothing works. It's been over two hours now, so I'm calling it a night.

**Comment by RobertAKARobin** [comment]
Any luck, Adrian?

**Comment by adrianshep** [comment]
No. I saw other posts on the Mac QT message boards indicating other people
having this problem and the proposed solutions I tried (specifying built-in
mic, creating an aggregate audio device using MIDI, downloading Sunflower
patch) not working for them either.

**Comment by RobertAKARobin** [comment]
Can you grab one of the instructors? I'm pretty sure I saw you in Classroom 2. Matt and Adam are both outside the classrooms, I believe. If not, let me know.

**Comment by adrianshep** [comment]
Adam helped me get the audio going.

It's processing right now:

PriceParser

http://youtu.be/X0Q0LsmiGag

On Fri, Aug 7, 2015 at 8:34 AM, Robert Thomas notifications@github.com
wrote:

> Reopened #235 https://github.com/ga-dc/pbj-project2/issues/235.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project2/issues/235#event-376278094.

## 

Adrian
