### ISSUE TITLE
Project 2 Submission

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#239]
Git Hub Repo with URL: https://github.com/malissaromero/project_two_developer_tips

Video: https://youtu.be/OQrEs_U3jhc

Completeness: 5
Comfort Level: 5
I definitely learned a lot. I know I have much more to learn but appreciate the help and attention from the instructors. I also got a lot of help from the TAs and my peers. It was a very high stress week but in the end I was very happy with my application and would love to revisit it in the future.

**Comment by mattscilipoti** [comment]
Good job!  Create PR and updated status.didc.org.
