### ISSUE TITLE
project 2 idea

### ISSUE THREAD

**Issue by jaredarkin** [ga-wdi-exercises/project2#24]
https://github.com/arkinjb/photos_of_paul_db

user stories and description in readme
jpegs of wireframe, erd in wireframes folder

**Comment by adambray** [comment]
Hey Jared,

Hah! What a great / funny idea! Your user stories / ERDs / wireframes look good. 

One suggestion: cleanup the readme to remove the fluff that rails added by default at the bottom.

-Adam
