### ISSUE TITLE
Project 2: Special Needs Pets

### ISSUE THREAD

**Issue by puzzleboks** [ga-wdi-exercises/project2#249]
Repo: https://github.com/puzzleboks/Special_Needs_Pets

Site: https://special-needs-pets.herokuapp.com/

Comfort: 4
Many, many issues, but worked through most of them (with help).

Completeness: 4
As far as I know I achieved all the requirements for the project, put submitted the presentation late due to video issues. I also didn't reach all the goals I had for the project.

**Comment by mattscilipoti** [comment]
Created PR and updated status.wdidc.org.
