### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by rewarren** [ga-wdi-exercises/project2#25]
https://github.com/rewarren/project2

An animal shelter that takes a compatibility matching approach to helping humans and animals come together.

![20150802_223818](https://cloud.githubusercontent.com/assets/10967783/9030088/9f9f9d24-396b-11e5-8efa-3428cd780e4e.jpg)
![20150802_230059](https://cloud.githubusercontent.com/assets/10967783/9030099/ded26e4a-396b-11e5-8325-4ee3b5eb2b2f.jpg)
![20150802_230122](https://cloud.githubusercontent.com/assets/10967783/9030102/e3213364-396b-11e5-9ab1-d58d88b2906a.jpg)

**Comment by RobertAKARobin** [comment]
If you have separate models for each animal, you're going to have a LOT of models. Just have one "animals" table with a "species" text column, or something. Also, to stay scalable, I'd recommend just starting off with an app that lets you add animals to a shelter — two models. Work up from there.

**Comment by rewarren** [comment]
Robin - thanks. I think I'll take your advice and start with a much more attainable MVP like that...  While i was working before lunch I quickly got overwhelmed by my models because i created a model for characteristics that I wanted to use to match human and animals, but that went way over my head. (fortunately i realized before i even got started that i shouldn't make a model per animal like you explained. so, yay for that win!). anyways, i feel better about starting over now! thanks.

**Comment by RobertAKARobin** [comment]
Good thing we caught this on Monday! :)
