### ISSUE TITLE
Project 2 ERD, Wireframes, & User Stories

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#26]
An app that allows users to post photos of themselves or others wearing clothes. Photos are rated on their stylishness and fashionability by a system of upvotes and downvotes. Users can view all posted photos or just their posted photos.

https://github.com/Walter-0/rate_my_style

**Comment by adambray** [comment]
Hey Walter,

Love the idea! This seems like a great scope for Project 2.

-Adam
