### ISSUE TITLE
Project 2: Idea, Wireframes, ERD, User Stories

### ISSUE THREAD

**Issue by kristingreenslit** [ga-wdi-exercises/project2#27]
Idea: 
Online assessment tool for individual computers users that measures overall computer health.

Repository with User Stories: 
https://github.com/kristingreenslit/tech-assess.git

Link to Wireframes and ERD: 
https://drive.google.com/file/d/0B7OGbeW8U2_8bUMtRllBWHlaVUk/view?usp=sharing

**Comment by andrewsunglaekim** [comment]
I'm curious what attributes your models will have and how the website model will play into all of that. How will the assessing on a computer happen? Think of the different informations you might need to display for an MVP
