### ISSUE TITLE
Devise Migration Issue

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#321]
I am trying to add devise to my app. I am expecting it to work normally, but when i run rake db:migrate it gives me this error "rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: users: ALTER TABLE "users" ADD "email" varchar DEFAULT '"

I am following all the normal steps and don't know why it's not working to create devise

**Comment by RobertAKARobin** [comment]
Uh oh! It's because you did `rails new your-app` instead of `rails new your-app -d postgresql`. Note the `SQLite3` error.

At this point, you can certainly look up how to change a SQLite app to Postgres, but if you don't have much code it may instead be a good idea to just `rails new` again.

**Comment by mcgrodsky** [comment]
THANK YOU

**Comment by RobertAKARobin** [comment]
Wooo! Can you close this issue, then?

**Comment by amaseda** [comment]
Gonna go ahead and close this one. Re-open it if you're still dealing with this issue.
