### ISSUE TITLE
Devise FB authentication error

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#324]
I am trying to implement FB authentication through devise using this documentation - http://willschenk.com/setting-up-devise-with-twitter-and-facebook-and-other-omniauth-schemes-without-email-addresses/

When I go to localhost:3000 it redirects to http://localhost:3000/users/sign_in <which is what i want

However i'm getting "NoMethodError in Devise::Sessions#new" and it's highlighting a line in my views>devise>new

My welcome controller looks like this:

```
  class WelcomeController
    before_action :authenticate_user!
  def index

  end
end
```

My routes look like this:

```
Rails.application.routes.draw do
  devise_for :views
  get 'welcome/index'
  root 'welcome#index'

    devise_for :users
  resources :neighborhoods do
    resources :listings
end
```

**When i remove the html inside the supplied devise/views/sessions/new page I do not get an error, however it's odd to me that the generated code is not working.

**Comment by RobertAKARobin** [comment]
Can you post a screenshot of the error? I'd like to see more of it.

**Comment by mcgrodsky** [comment]
![screen shot 2015-11-16 at 2 34 44 pm](https://cloud.githubusercontent.com/assets/14894858/11192444/3e7f18ec-8c6f-11e5-8a20-6709498ab587.png)

**Comment by mcgrodsky** [comment]
It seems like i need to define/change "resource_name"?

**Comment by mcgrodsky** [comment]
@RobertAKARobin in my routes:

Rails.application.routes.draw do
  devise_for :views
  get 'welcome/index'
  root 'welcome#index'

    devise_for :users
  resources :neighborhoods do
    resources :listings
end

**Comment by RobertAKARobin** [comment]
Why do you have Devise both for views and users? That may be part of the problem. Also, do you have all the `do` and `end` you need? It's a little hard to tell with the indentation.

**Comment by RobertAKARobin** [comment]
Mia, I'm not actually seeing `devise_for :views` in [the tutorial](http://willschenk.com/setting-up-devise-with-twitter-and-facebook-and-other-omniauth-schemes-without-email-addresses/) you included. Where did that line come from?
