### ISSUE TITLE
Issue with Routes

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#325]
I think this is a fairly straightforward thing but I cannot figure it out.  I had been using nested resources so now that these two models are purposely not nested I cannot figure out how to link them.

Basically, when user clicks on the create new report, at this point all there is is a drop down menu with cities. User picks city and hits submit.  The app then directs to that report page (later there will be another model).  For now, though, I want that page to be under locations/:id/reports but instead it is just under reports/:id.  In my locations controller I have 

```
def show
    @location = Location.find(params[:id])
    @reports = @location.reports(params[:id])
  end
```

and I have in the locations show page

```
<% @reports.each do |report| %>
  <ul><%= link_to "#{report.location_id}", report_path(report) %></ul>
<% end %>
```

In my locations model.rb file it has that locations `has_many :reports`.

**Comment by amaseda** [comment]
Might have something to do with the `(params[:id])` attached to `@location.reports`. What exactly do you want `@reports` to equal?

**Comment by dan-ator** [comment]
The reports associated with that location.  I think the issue might actually stem from my form, which has a drop down menu.  It is:

```
  <%= f.collection_select(:location_id, Location.all, :id, :city) %>

```

**Comment by amaseda** [comment]
In that case `@reports = @location.reports`

Are you getting an error? If so, what is it?

Also, if you want to have a URL like `locations/:id/reports` then you will need to nest your resources.

**Comment by dan-ator** [comment]
I changed it to @location.reports and it didn't do anything.  No error messages, it just isn't showing what I thought it would where I thought it would.  I think it is in how the form is collecting information because when I run a pry console it shows nil for a location_id value of a completed form.

**Comment by RobertAKARobin** [comment]
Are you sure that location has any reports? What do you get when you test it out in the Rails Console? `rails c`
