### ISSUE TITLE
Making Seed Data

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project2#326]
I am trying to make seed data to display to test. I am suspicious of the schema or the way I am writing the seed data but I am not sure why they're not connecting.

Below is a pic of the seed data:
![image](https://cloud.githubusercontent.com/assets/12722650/11193896/1b75bc18-8c77-11e5-8ec3-4f13b251044b.png)

Below is a pic of the schema:
![image](https://cloud.githubusercontent.com/assets/12722650/11193925/4d23c386-8c77-11e5-977a-181ce9871383.png)

I tried:
Hard-coding the foreign key into my second model to link it to the first in several different ways.
I expected typing "Student.find(1).logs" in the rails console to give me the logs associated with the student but it said "NoMethodError: undefined method `logs' for #Student:0x007fa561ac0888" instead.

**Comment by amaseda** [comment]
Did you set up your associations in your ActiveRecord models?

Also, you don't want to set the primary key (`id`) of something in your seed file. That will be generated automatically. You can, however, do that for foreign keys.

**Comment by Ly900** [comment]
I just noticed that it said student has_many :pins instead of has_many :logs. Oops. Copy and paste error. But I am still getting error messages. Can you tell me which line I set a primary key? I thought I set a foreign key from logs to students.

**Comment by amaseda** [comment]
Copy 'n' paste strikes again!

You set the primary key here: `Student.create( id: 1 ....`

What error messages are you getting?

**Comment by Ly900** [comment]
OH if you are referring to the creation of the student with ID 1, I was trying to hard code that so that I can give the log I created a student_id of 1.

**Comment by Ly900** [comment]
![image](https://cloud.githubusercontent.com/assets/12722650/11194351/8ef2ea38-8c79-11e5-996a-0724ff884f26.png)

**Comment by amaseda** [comment]
If you remove `id: 1` do you still get that error?

**Comment by Ly900** [comment]
I assume I'll have to delete the student_id:1 from the log I created too? So I cannot link them this way?

**Comment by Ly900** [comment]
No more error when I removed the IDs... what is the correct way to link them then?

**Comment by Ly900** [comment]
Also tried this way...
![image](https://cloud.githubusercontent.com/assets/12722650/11194433/10c1acc0-8c7a-11e5-8726-df7485684c27.png)

Same error:
![image](https://cloud.githubusercontent.com/assets/12722650/11194448/21907482-8c7a-11e5-8651-8a1ce7d012a8.png)

**Comment by amaseda** [comment]
No need to delete `student_id: 1`. You're allowed to set a foreign key. Just not a primary key.

You can also create a `log` for `andy` using the same method in your last screenshot.

Is it working now?

**Comment by Ly900** [comment]
OK for whatever reason, I just got it to work in Active Record. I will see if I can print them out normally. Thanks Adrian!

**Comment by Ly900** [comment]
I still have a question though- you say that I could leave student_id: 1 for the log (I assume in my first screenshot of how I created the student and log). But when I reseed my data, they give the student a new ID. How will I be able to match the log to the student if I don't give the student an ID?

**Comment by Ly900** [comment]
So I was able to do Student.find(1).logs and get the log I had made associated with that student. But when I now run rake db:seed, I still get the same error below. So... not completely fixed. Why can't I reseed?

![image](https://cloud.githubusercontent.com/assets/12722650/11194690/8f0d2b76-8c7b-11e5-9181-6b75937e119a.png)

**Comment by Ly900** [comment]
I think I figured it out? 
Added the dependent thing to

``` ruby
class Student < ActiveRecord::Base
  has_many :logs, dependent: :destroy
end
```

and not having the issue right now.
