### ISSUE TITLE
How can I create a root page that is not XXXXX#index

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project2#327]
I am trying to create a default page that people can log in, log out. Once they are logged in, they go into user specific page. Can you please guide me how I can do so? Can I create index erb in layout folder?

**Comment by RobertAKARobin** [comment]
Just use `root to: "controller#action"` in your `config/routes.rb`. You can use this to make any page the default page.

**Comment by onesick** [comment]
I changed it to the above and I am getting routing error called: uninitialized constant ControllerController

**Comment by RobertAKARobin** [comment]
Don't ACTUALLY write `controller#action` -- replace those words with the appropriate controller and the appropriate action within that controller, like `artists#index`.

**Comment by RobertAKARobin** [comment]
It's been a while so I'm going to close this. Feel free to open a new issue if need-be!
