### ISSUE TITLE
attributing data type to the select_country helper 

### ISSUE THREAD

**Issue by matiamin** [ga-wdi-exercises/project2#328]
I'm trying to attribute data-type to the select_country helper method (using the carmens-rails gem) in my model file. Would it be t.string :country?

**Comment by matiamin** [comment]
Here is my model file

``` rb
class CreateEntries < ActiveRecord::Migration
  def change
    create_table :entries do |t|
      t.string :title
      t.date :deadline
      t.text :institute
      t.srting :link
      t.text :description
      t.string :country

      t.timestamps null: false
    end
  end
end
```

**Comment by amaseda** [comment]
What exactly do you mean by attribute data-type? I'm not familiar with this gem, but if you're trying to store a country name as a string then yes you can do `t.string :country`.

**Comment by matiamin** [comment]
The gem allows for a drop-down menu to let a user select a country when creating a post. Country is a column, and I assume the data-type for it in the model file is 'string'.

**Comment by amaseda** [comment]
Then sounds like you can save the value from the drop-down menu to a model attribute, in this case `country`. 

Have you tried it out yet? I don't know how this gem in particular works but take a look through their documentation.

**Comment by amaseda** [comment]
@matiamin 

Good to go here? If so, can you please close the issue. Thx!
