### ISSUE TITLE
issue with finding members that belong to a group through a joined table called memberships

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project2#331]
I tried to create a list of the members that belong to a group by using the membership table. I expected to see a list of group members but I am getting an error that says I am looking for every ID listed at two when I just want the ones that have a group ID of two.

My repo link ishttps://github.com/murgia/taskager and my question is about my index controller for members as well as the index view for members

**Comment by amaseda** [comment]
``` rb
def index
  @members = Membership.find(params[:group_id])
end
```

You're using a `group_id` to look up the primary key (`id`) of a Membership.

I think you're trying to do something along the lines of...

``` rb
Membership.find_by( group_id: params[:group_id] )
```

**Comment by RobertAKARobin** [comment]
I'm going to close this since it's been a while. Feel free to open a new one!
