### ISSUE TITLE
Editing a Nested Model

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project2#332]
I'm trying to edit a log which belongs to a student.

I tried changing the variables in the logs controller and changing the arguments in the edit_student_log_path parameters.
I expected to be sent to the page to edit the log.
I got the following error instead: 

![image](https://cloud.githubusercontent.com/assets/12722650/11196474/31024cdc-8c85-11e5-8f03-b7c475d9c7ae.png)

Here's my logs controller:
![image](https://cloud.githubusercontent.com/assets/12722650/11196485/41f59d28-8c85-11e5-9901-a80cff30fa0b.png)

What the link helper looks like:
![image](https://cloud.githubusercontent.com/assets/12722650/11196501/58553970-8c85-11e5-8b68-0528f653faea.png)

Thanks in advance.

**Comment by RobertAKARobin** [comment]
You're forgetting the `link_to`. :)

**Comment by Ly900** [comment]
_sobs_
