### ISSUE TITLE
Invalid User Controller

### ISSUE THREAD

**Issue by ascreven** [ga-wdi-exercises/project2#333]
Hey I keep getting an error that says 
ActiveRecord::RecordNotFound in UsersController#sign_in!

after I press sign-in. How do I get ActiveRecord to recognize my username?

My repo is located at: https://github.com/ascreven/All-About-Chew

Thank you!!

**Comment by amaseda** [comment]
Can you include a screenshot of your error plz? Will take a look at your repo now. Thx!

**Comment by RobertAKARobin** [comment]
It's been a long time, so I'm going to close this. Feel free to open a new issue, Alex!
