### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/project2#334]
can anybody tell me how I can start over without deleting my entire projects 2 file. I am having a hard time with the uninitialized user error. I want to start fresh without deleting my folder because it is connected to github already?

**Comment by RobertAKARobin** [comment]
You could just create a new repo on Github. But I'd recommend trying to work through this error. Please open a new GH Issue with a descriptive title and a screenshot of the error you're getting!

**Comment by MohamedGood** [comment]
I keep getting this error. I dont know how to fix it:

```
Users/generalassembly/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant User (NameError)
```

**Comment by RobertAKARobin** [comment]
Can you take a screenshot of the whole page with the error? If you press `Command` + `Shift` + `3` it'll take a screenshot of your whole window and save it to your desktop as something like `Screen Shot 2015-11-17 at 9.16.06 AM.png`. Then, you can just drag and drop it onto this box on Github to upload it.

**Comment by MohamedGood** [comment]
Yesterday I could log on the rails server. Now I am getting this error message when I try to log on to the rails server.  The screenshot is posted below

![screen shot 2015-11-17 at 9 22 02 am](https://cloud.githubusercontent.com/assets/15020378/11213928/b1fb4c94-8d0c-11e5-809a-4033a8bb9d67.png)

**Comment by mattscilipoti** [comment]
That error usually comes from a partial removal of devise.  Do you see anything from devise in the routes file?

**Comment by mattscilipoti** [comment]
If you commit often, you could just look at the difference from the last commit and see what has changed during your devise installation and configuration.

**Comment by MohamedGood** [comment]
it says this in my routes.rb

``` rb
Rails.application.routes.draw do
  devise_for :users
```

But that might be a problem because I deleted my user files because a classmate told me devise would create those files for me

**Comment by mattscilipoti** [comment]
Exactly.  `devise_for :users` was added when you configured devise with `rails generate devise User`.  It expects a User model, which you have deleted.  They were there when that line was added.

**Comment by MohamedGood** [comment]
now my server is up... Now I have this error:

![screen shot 2015-11-17 at 9 57 04 am](https://cloud.githubusercontent.com/assets/15020378/11214893/a00b6f78-8d11-11e5-8925-34b719317a83.png)

**Comment by RobertAKARobin** [comment]
You need to run `rake db:create`.
