### ISSUE TITLE
issue with accessing user_id using current_user

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project2#335]
I am having an issue with trying to use the devise helper method "current_user". I expected current_user to allow me to access and reference the id of the signed-in usr, but whenever I try to use current_user, I receive a Rails error message like: "unknown attribute 'user' for Apartment." I've been reading the Devise documentation on github [https://github.com/plataformatec/devise#controller-filters-and-helpers], but I can't seem to figure out what I'm doing wrong. 

Here is the code from my Apartment controller:    

``` rb
def new
    @apartment = Apartment.new
end

def create
    @apartment = current_user.apartment.new(apartment_params)
    if @apartment.save
      flash[:notice] = "#{@apartment.name} was successfully created!"
      redirect_to apartments_path(current_user, @apartment).
    else
      render :new
    end
end
```

The link to my github repo is: https://github.com/schersh/Project-2 (please refer to the "temp" branch). Thank you!

**Comment by RobertAKARobin** [comment]
I think the trouble here is `redirect_to apartments_path(current_user, @apartment)`. The way the routes are set up, every model you need is right in the route's name. The only model in this route's name (`apartments_path`) is `Apartment`, so it should probably only take one argument, `@apartment`.

**Comment by andrewsunglaekim** [comment]
Also, if apartments belong to a user, check your association helper. You may also need to use `.build` for that as well.

**Comment by schersh** [comment]
Okay, it still seems to not be finding the current_user though, now I am getting the following error: 

undefined method `new' for nil:NilClass

``` rb
def create
   @apartment = current_user.apartment.new(apartment_params)
    if @apartment.save
      flash[:notice] = "#{@apartment.name} was successfully created!"
      redirect_to apartments_path(@apartment).
```

Currently, my users belong to an apartment - apartments can have many users, but users can only have one apartment. Do you think that might be the issue? Where is my association helper located? 

Thank you!

**Comment by andrewsunglaekim** [comment]
Maybe something like this?

```
@apartment = Apartment.new(apartment_params)
@apartment.user = current_user
if @apartment.save
  ...
```

I `.apartment` is an attribute of a user model. Therefore if it isn't defined yet, it's value is nil. Because of that, when we call `.new` on nil, we get the above error

**Comment by schersh** [comment]
That looks right to me, but I still get an error: undefined method `user=' for #<Apartment id: nil, name: "The V St House">

@apartment = Apartment.new(apartment_params)
@apartment.user = current_user
if @apartment.save
  ...

Do I need to add something to my Apartment schema for it to be capturing the user information?

**Comment by schersh** [comment]
Sorry, the error message got clipped, it reads: 
`undefined method `user=' for #<Apartment id: nil, name: "The V St House">`

**Comment by andrewsunglaekim** [comment]
oh right, `@apartment.user_id = current_user.id`

**Comment by schersh** [comment]
Still the same type of error, `undefined method `user_id=' for #<Apartment id: nil, name: "The V St House">`

**Comment by schersh** [comment]
Maybe I need to define `@user = current_user` in each controller? I'm a little confused about what the helper method is actually doing. 

My index method is working when I say `def index
    authenticate_user!
    @user = current_user
    if current_user
      @apartment = current_user.apartment
    else
      redirect_to new_user_session_path
    end
  end`

**Comment by andrewsunglaekim** [comment]
in your schema, do you have a column for user_id in your apartment?

**Comment by andrewsunglaekim** [comment]
errr.. other way around

**Comment by RobertAKARobin** [comment]
Andy's on his way!

**Comment by andrewsunglaekim** [comment]
do user's have an apartment_id?

**Comment by schersh** [comment]
That might be the issue, the users table has a foreign key column for apartment_id, but I don't think my apartment table has a column for user_id - is it necessary to have both? I

**Comment by andrewsunglaekim** [comment]
It can't. Basically if you create an apartment and you want to associate user's to it. You have to store that association on the user model end, not in the apartment. The good news, is you can create your apartment however you want! The bad news is you have to update every user's apartment id to that new apartment you created

**Comment by schersh** [comment]
These are the only two foreign keys I have currently: 

```
add_foreign_key "expenses", "users"
add_foreign_key "users", "apartments"
```

Is that correct?

**Comment by andrewsunglaekim** [comment]
I'm not familiar with the `add_foreign_key` syntax, but check your `db/schema.rb` file to look at what it generated for you.

**Comment by schersh** [comment]
Does that mean I shouldn't worry about associating the apartment with user's once it's created? How will the program store the knowledge that the current logged in user is the one who created the apartment? I'm sorry, I'm a little turned around on this. I can experiment a bit more and check in with you later.

**Comment by andrewsunglaekim** [comment]
are you in the building today?

**Comment by schersh** [comment]
I'm working at home this morning, but I'll be in before the Outcomes trip.

**Comment by andrewsunglaekim** [comment]
If you want to associate the user to the apartment as one that belongs to the apartment, you can do that by updating the apartment_id on the user. If you want to know which user created that apartment, you could put a foreign key on the apartment for a creator_id aliased from the user class

**Comment by andrewsunglaekim** [comment]
In other words it won't know unless you code an id into the apartment representing that id

**Comment by schersh** [comment]
Ah, okay - I will try to untangle this, I think I was approaching it backwards. thanks!

**Comment by RobertAKARobin** [comment]
If you're good to go, please close this issue! You can always open more.
