### ISSUE TITLE
Issue with Comments

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#337]
Right now I have a model for Reports, and nested under that in my routes.rb is InfoItems.  Now I am adding a model for comments.  One info_item has many comments.  The idea is each report can have many info_items and each info_item can have many comments.  Comments is not nested since I read it is bad to nest more than one deep.  Right now comments are not showing up under each info_item as I think they should.  This is my code in the reports show page, where info items exist:

``` erb
<% @report.info_items.each do |info_item| %>
  <h4><%= "#{info_item.category}" %>
    <%= link_to "Edit", edit_report_info_item_path(@report,info_item) %>
    <%= link_to "Delete", report_info_item_path(@report, info_item), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
  </h4>
  <p><%= "#{info_item.body}" %></p>

  <% info_item.comments.each do |comment| %>
    <h2>hi world</h2>
    <%= link_to "Comment", new_comment_path(info_item,comment) %>
    <%= comment.title %> <%= comment.body %>
  <% end %>
<% end %>
```

The info_items show up but neither the new comment button nor the "hi world" show up.  There are no error messages though.

**Comment by RobertAKARobin** [comment]
Nested resources are different from associations. Nested resources just means you can write URLs like `/artists/32/songs` -- it has no bearing on whether you can do `@artist.songs` or `@song.artists`. They're separate things.

What lets `info_item` have `.comments` is that the `Info_Item` model `has_many :comments`. It looks like you've defined that, or else `info_item.comments` would throw an error.

So it seems this particular `info_item` just doesn't have any comments associated with it. Hence, when you do `info_item.comments.each`, nothing inside that shows up.

If you think it should have comments associated with it, either put a `binding.pry` in your controller, or look up this particular `info_item` in your Rails console (`rails c`).

**Comment by RobertAKARobin** [comment]
Also, you can write `<%= "#{info_item.category}" %>` as just `<%= info_item.category %>`.

`<%= %>` converts whatever's inside it to a string (as opposed to `<% %>`, which doesn't). `""` also converts whatever's inside it to a string. So if all you're doing is writing out a string, you don't really need both.

**Comment by dan-ator** [comment]
I think the issue was that no comments were created because I put the "create comments" button in the each loop so it wasn't showing up for me to create a comment.  So I moved it up a few lines and the link appears but is not connecting to the form.  Now it is giving me error related to not being able to find Report with ID.  But for the comments controller, the ID should just be :id because that is how it shows up  in rake routes.

**Comment by RobertAKARobin** [comment]
That shouldn't affect the fact that `hi world` isn't showing up. That's caused by Rails thinking your `info_item` doesn't have any comments.

However, there is also an issue with this:

```
<%= link_to "Comment", new_comment_path(info_item,comment) %>
```

The name of this route is `new_comment_path`. Routes' names tell you what models you need in order to make that route work. The only model in `new_comment_path` is `comment`, so you would write `new_comment_path(comment)`.

This is as opposed to if it was `new_post_comment_path`, in which case you would write something like `new_post_comment_path(post, comment)`.

**Comment by dan-ator** [comment]
Thanks.  Now I can pull up the new comment form but when I try and submit it gives me a "couldn't find report with id=" error.  my code is as follows in the comments controller: 

``` rb
  def create
    @report = Report.find(params[:id])
    @info_item = @report.info_item
    @comment = @info_item.comments.create(comment_params)
    redirect_to report_path(@report)
```

I also tried using "params[:report_id]" but that also gave the same error.

**Comment by RobertAKARobin** [comment]
What ID is it using? Is it actually the ID of the thing you're trying to show? If not, it must be getting the ID from some other variable. Figure out what that variable is, and you should be ready to rock.

**Comment by dan-ator** [comment]
Sounds like a riddle.  I'm still confused.

**Comment by RobertAKARobin** [comment]
If your error says "Couldn't find Report with id=32", that 32 has to be coming from somewhere. Once you figure out what has that ID of 32, you'll figure out what needs fixing.

Can you show what the code in your view looks like now?

**Comment by dan-ator** [comment]
Code in view is 

```
<h3>Info Items</h3>
<% @report.info_items.each do |info_item| %>
  <h4><%= info_item.category %>
    <%= link_to "Edit", edit_report_info_item_path(@report,info_item) %>
    <%= link_to "Delete", report_info_item_path(@report, info_item), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
  </h4>
  <p><%= info_item.body %></p>

    <%= link_to "Comment", new_comment_path(info_item.comments) %>

  <% info_item.comments.each do |comment| %>
    <h2>hi world</h2>
    <%= comment.title %> <%= comment.body %>
  <% end %>
<% end %>
```

**Comment by dan-ator** [comment]
In comments controller code route is:

```
  def create
    @report = Report.all
    @info_item = InfoItem.params[:id]
    @comment = Comment.create(comment_params.merge(info_item: @info_item))
    redirect_to report_path(@report)
  end
```

**Comment by dan-ator** [comment]
But that gives me the error "Couldn't find Report with 'id'=#Report::ActiveRecord_Relation:0x007fd34248a9f0" in reports controller.

**Comment by dan-ator** [comment]
and the reports controller was previously working fine.  it is

```
def show
    @report = Report.find(params[:id])
    @locations = @report.location
  end
```

**Comment by RobertAKARobin** [comment]
Ah-HAH! That's because `@report = Report.all`. `Report.all` returns an array of reports. Even if you just have one report, it'll still return an array of reports. `report_path` has to take a _single_ report as its argument.

**Comment by dan-ator** [comment]
It does the same error though when I put in `@report = Report.find(params[:id])`  I thought putting in the .All would atleast not give an error because I know that exists.
