### ISSUE TITLE
Saving Token

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#338]
I'm using Omniauth to handle logins to github. I've got my application registered (https://github.com/settings/applications/new) and the corresponding Client ID and Client Secret saved in an application.yml file hidden by figaro. Omniauth somehow passes this to github presumably by a file I created config/initializers/omniauth.rb

``` ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :github, ENV['GITHUB_KEY'], ENV['GITHUB_SECRET']
end
```

 When a user logs in Omniauth sends back a bunch of stuff, including a auth hash (accessed by `request.env['omniauth.auth']`). This hash includes some info on the user like name, image(avatar), and a token. This token according to the schema (https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema) is supplied by OAuth and OAuth 2.0 providers, is the access token. I've got a callback method in my User model that creates a entry in my User table and populates it with info from the Omniauth auth_hash.

``` ruby
class User < ActiveRecord::Base

  def self.create_from_omniauth(auth_hash)
    self.create(
      provider: auth_hash[:provider],
      uid: auth_hash[:uid],
      name: auth_hash[:info][:name],
      nickname: auth_hash[:info][:nickname],
      image: auth_hash[:info][:image],
      url: auth_hash[:extra][:raw_info][:html_url],
    )
  end
end
```

I'm also storing the current user id in a session

``` ruby
class SessionsController < ApplicationController
  def new
    redirect_to '/auth/github'
  end

  def create
    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_from_omniauth(auth_hash)
    if @user
      session[:user_id] = @user.id
      redirect_to root_url
    binding.pry
    else
      redirect_to root_url
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  protected
    def auth_hash
      request.env['omniauth.auth']
    end
end
```

I want to manipulate the github Api which has a pretty low rate limit unless users are authenticated. It looks like I can pass a token to Httparty using something that looks kind of like this -

``` ruby
response = HTTParty.get(
            "https://api.github.com/user", 
            :headers => {
                "Authorization" => "token #{token}",
                "User-Agent" => "codecademy"
                })
```

I've been struggling with how these pieces fit together. How can I save the `token` in a way that I can access with HTTParty and also be safe?

**Comment by RobertAKARobin** [comment]
You access Figaro's environment variables in the `ENV` constant. As in: `ENV["this_is_my_variable"]`.

But yeah, I ran into the same thing earlier with Garnet. Sorry to tell you that my solution was to use Octokit:

https://github.com/ga-dc/garnet/blob/master/app/controllers/users_controller.rb#L122
https://github.com/ga-dc/garnet/blob/master/app/models/github.rb

Note that I made a Github model (that is _not_ connected to ActiveRecord) in order to clean up the controller a bit. You can't access environment variables inside models, so I explicitly passed them in from the controller with `Github.new(ENV)`.

**Comment by tylercrosse** [comment]
What's the advantage to not using something like Omniauth to handle logins to github?
I'm also starting to to sweat the clock on my lack of tangible progress and considering scarping everything and starting over on a simpler project.

**Comment by andrewsunglaekim** [comment]
3rd party auth is really jsut so users don't have to register for yet another site. Also you can parse information from where you auth from like profile pics and stuff. Other than that, not really any benefits.

**Comment by RobertAKARobin** [comment]
It's kinda like using Devise: when it works, it's great. When it doesn't, it's a royal PITA. You could totally just put together your own little Omniauth thing, which is what we've done with Garnet. Sure, you miss out on some of the conveniences of Omniauth -- but trying to get those conveniences can be really inconvenient, and we didn't need them anyway for our purposes.
