### ISSUE TITLE
Cameron's Project 2 Idea with User Stories, 2 wireframes, and and ERD 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#34]
Comfort: 3/5

Completeness: 5/5

https://github.com/cameronfry11/prompt

I'm going to create an app called "Prompt" that helps people with writer's block quickly get ideas down on paper (or into the computer). It is also for anything that requires responding to a series of questions to create a draft. Basically, this app will store questions submitted by the user in an object called a prompt. When the prompt is called, each question within the prompt is displayed to the page one at a time while the user responds to that one question with no distractions on the page. Then once the user returns the answer to the first question, the second question seamlessly pops to the screen without having to touch the mouse such that the user can quickly work through a series of pre-programmed questions to create a draft. Upon completion of the questions, the draft is stored in the database and displays to the screen in paragraph form (maybe table form or others depending on the prompt but feature creep. . . ) to be used for any project the user is working on. Users can share prompts with others globally and add other prompts to their collection. 

I backed off another idea I had that I felt like may be too challenging that I want to try in the future.

**Comment by andrewsunglaekim** [comment]
Your erd's aren't working, i'm curious what your models will be. I like the idea though!

**Comment by ghost** [comment]
Yeah, I realized you can only open them if your using the sketch application for mac. Sorry about that.
