### ISSUE TITLE
issue with devise (i think)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#340]
I am building an app with many-to-may relationships.

vets > appointments < pets

I expected
When I create a new Vet(user) on /users/new, I expect to see the Vet name added to the list on the users/index page.   

This happened instead
users/index displays information created from the users/sign_up page.  (I've temporarily set the page to display user.email to confirm this.)

Devise seems to be preventing me from implementing the Appointment join table.

My repo link is 
https://github.com/thomhouseholder/project2-vet

And my question is about lines
users_controller.rb lines 15-22
environments/development.rb line 42

**Comment by RobertAKARobin** [comment]
I believe the problem here is that with Devise, you can only create new users/vets by _signing up_ as a new user/vet -- you can't use one user to create another user.

So I'd suggest removing Devise altogether, _or_ having a Vet model that is separate from the User model.

**Comment by ghost** [comment]
I'd like to create a new vets model, make that ply well with pets through my appointments and then come back to devise/user login. 
Is that a smart play if I leave users alone, create new vets, and make the necessary changes to move from current users and pets to vets and pets?

```
_____________________________
```

**Comment by RobertAKARobin** [comment]
Sounds good to me!

**Comment by ghost** [comment]
Thanks robin

On Tue, Nov 17, 2015 at 11:12 AM -0800, "Robert Thomas" notifications@github.com wrote:

Sounds good to me!
