### ISSUE TITLE
Application.css disappeared?

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#341]
Lost stylesheet! When i try and make a new application.css is my "assets" it says it already exists. 

![screen shot 2015-11-17 at 11 53 44 am](https://cloud.githubusercontent.com/assets/14894858/11218234/0b2fec2e-8d22-11e5-93f8-d55ddd64daec.png)

**Comment by ebirving** [comment]
Yikes! Did you mean to delete the `application.css`, or did it spontaneously disappear? Are the styles still applying?

**Comment by ebirving** [comment]
Follow-up: What were you doing when you noticed that it had disappeared?

**Comment by RobertAKARobin** [comment]
Before anything, I'd suggest just quitting and restarting Atom. It can be a little weird. While you're at it, use the Finder (or Terminal or something other than Atom) to actually go look for that file. It may be there!

**Comment by mcgrodsky** [comment]
@RobertAKARobin you got it. Finder found it in a sub-folder (must have moved it acceidentally during a coding frenzy) and i was able to move it back over where it belongs!
