### ISSUE TITLE
Filter by Tag

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project2#343]
I am trying to create a form on my books index page to filter the books by tag. I think I have a form that works but when I try to submit the tag I want to filter by I think rails is taking the params and trying to make a new book.  

Here is the code for my form:

``` erb
<%= form_tag books_path do %>
       <%= select_tag "tags", options_for_select(tag_names.uniq) %>
       <%= submit_tag "Filter by Tag" %>
<% end %>
```

And my books index controller:

``` rb
def index
    @tags = Tag.all

    if(params[:tags])
      @tags = Tag.where(name: params[:tags])
      @taggings = []
      @book = []
      @tags.each do |tag|
        @taggings << tag.taggings

        @taggings.each do |tagging|
          @books << tagging.book
        end
      end

    else
    @books = Book.all
    end
  end
```

I am not sure this logic will work but I cant test it until the form is working correctly.

Here is the error:

param is missing or the value is empty: book              

```
  def book_params
      params.require(:book).permit(:title, :author, :genre, :image_url, :no_pages, :synopsis, :condition)
  end
end
```

**Comment by RobertAKARobin** [comment]
Cool! Try looking at the source code of that page with the form on it (`Command` + `Option` + `U`). What are the `action` and `method` of the form tag?

**Comment by lewis2ba** [comment]
``` html
<form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="fLjV02K5mva7C8rNhenXfjMDEWfOD7R2c/d2OJaxQjz2DHLf3MCxbHHPn1f1IBkyKLHgQksyVZWQY+ub1sDXzA==" />
       <select name="tags" id="tags"><option value="Funny">Funny</option>
<option value="Comedy">Comedy</option>
<option value="Satire">Satire</option>
<option value="War">War</option>
<option value="Love">Love</option></select>
       <input type="submit" name="commit" value="Filter by Tag" />
</form>
```

It looks like the action is "/books" and the method is "post"

**Comment by lewis2ba** [comment]
Hmm copying and pasting the html caused it to spit out the tags hah

**Comment by lewis2ba** [comment]
May have figured it out, form_tag({:action=>"index"},{:method=>"get"})

**Comment by RobertAKARobin** [comment]
Hah, yeah, it does that unless you wrap it in backtics.

So you can see that the method for the form is `post`...

Oh. Yeah, you got it. :+1:

**Comment by RobertAKARobin** [comment]
Hey, if this is solved, could you close it?
