### ISSUE TITLE
Created a dummy controller called home_controller

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project2#344]
Hi there,
I am getting the following error:
Unable to autoload constant HomeController, expected /Users/wonsikjeong/wdi/exercises/project2/CRM_project/app/controllers/home_controller.rb to define it

Am I supposed to create Dummy model as well? If i do, how can I create the relation for the model?

I created a dummy controller called home_controller which inherits ApplicationController.
Within the class, I have the following.

``` rb
class HomesController < ApplicationController

  def index

  end

end
```

I have created index.html.erb as the following:

``` html
<h1>Hello this is a home page</h1>
```

in the routes.rb I created the following:
  root to: "home#index"

**Comment by RobertAKARobin** [comment]
It's because it says `class HomesController`, rather than `class HomeController`. Check the pluralization and you should be good!

**Comment by onesick** [comment]
Yeah it worked! I thought we are supposed to plurize the controller class name. Because I did like that for every single one...

**Comment by RobertAKARobin** [comment]
You are, and you're supposed to pluralize the name of the file (`homes_controller.rb`) and the route (`homes#index`) as well.

**Comment by onesick** [comment]
But it was not working with class HomesController. Why is that?

**Comment by onesick** [comment]
NVM that was a dumb question. I reworked the whole home files changed to plurals

**Comment by onesick** [comment]
Thank you.
