### ISSUE TITLE
Heroku app works but can't seed data - seed works fine on local machine

### ISSUE THREAD

**Issue by ckib16** [ga-wdi-exercises/project2#345]
# Problem:

my heroku app runs. But Heroku can't load the seed.rb data I have built
My seed.rb file works flawlessly on my local Mac.
Heroku link: https://pilot-tracker.herokuapp.com/
Github link: https://github.com/ckib16/pilot_tracker
## Heroku deployment steps I took:

```
git push heroku master
git run rake db:migrate
git run rake db:seed
```
## Main error I get when running `heroku run rake db:seed`:

```
[14:53]~/wdi/projects/pilot_tracker > heroku run rake db:seed
Running rake db:seed on pilot-tracker... up, run.6160
  ActiveRecord::SchemaMigration Load (2.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  Location Load (3.3ms)  SELECT "locations".* FROM "locations"
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'emblem_url' for Location.
```
### Full errors:

Bash: https://gist.github.com/ckib16/87136c3ad9a6bcd9aa05
Heroku logs: https://gist.github.com/ckib16/2f80ca6389644bff9190
## Troubleshooting:
- ran through Heroku troubleshooting checklist from lesson multiple times
- tried `heroku restart --app pilot-tracker` - see http://stackoverflow.com/questions/8139578/activerecordunknownattributeerror
- ensured the app loads and runs correctly in Heroku (just can't load seed data)

Note: I did unintentionally push from a branch instead of master for my 1st Heroku deployment. But I fixed it and got the app working.

**Comment by RobertAKARobin** [comment]
Dang. Nice markdown, Chris!

**Comment by RobertAKARobin** [comment]
I think the problem may be that it's `heroku run rake db:migrate`, not `git run rake db:migrate`.

**Comment by ckib16** [comment]
Ah sorry - that was a typo - I did use `heroku run rake db:migrate` & ``heroku run rake db:seed`

**Comment by RobertAKARobin** [comment]
I'm going to try cloning it down myself and pushing to my own Heroku. One sec.

**Comment by ckib16** [comment]
Ok copy that. Standing by.

**Comment by RobertAKARobin** [comment]
As I'm waiting for it to upload, my guess would be that you changed one of the migration files on your computer, and haven't since tried creating the database from scratch (i.e. DCMS). So this error may have been there a while; you just didn't encounter it since you didn't run old migrations.

**Comment by mattscilipoti** [comment]
Check out the history of the Location migration: https://github.com/ckib16/pilot_tracker/commits/master/db/migrate/20151115210926_create_locations.rb

**Comment by andrewsunglaekim** [comment]
Seems like you edited your migration in your version control for git. Maybe try to drop the production DB and recreate/remigrate/reseed

**Comment by ckib16** [comment]
Ah yes. OK I can see that. 

Am I stuck now because Heroku won't let you drop the DB?
Or should I just DCMS my local DB and re-push to Heroku?

**Comment by mattscilipoti** [comment]
Once a migration has been run, it is not run again (therefore, it won't use the new changes).

**Comment by RobertAKARobin** [comment]
It actually worked perfectly fine for me on Heroku. https://enigmatic-bastion-9011.herokuapp.com/

**Comment by mattscilipoti** [comment]
How about `heroku run rake db:migrate:redo`?

**Comment by mattscilipoti** [comment]
@RobertAKARobin That's because you didn't run the migration before he changed it.

**Comment by ckib16** [comment]
@RobertAKARobin Waaaa? Yes, that's what I want. Not working on my machine though.

Ok @mattscilipoti - I'll try that.

**Comment by RobertAKARobin** [comment]
@mattscilipoti I cloned it down just now.

**Comment by mattscilipoti** [comment]
Sorry.  It's changed a bit.  `heroku run rake db:rollback`

**Comment by ckib16** [comment]
Ok guys working!

@mattscilipoti - I actually used your 1st one and it worked `heroku run rake db:migrate:redo`

Thanks!

**Comment by RobertAKARobin** [comment]
Great, Chris! If it's solved, could you close this issue?

**Comment by ckib16** [comment]
Yes will do, thanks!

**Comment by mattscilipoti** [comment]
@RobertAKARobin Look at the history I linked above.  Chris ran the migration on Heroku, then added 'emblem_url' after that migration was run.  You ran the migration with the latest code, not the one before the change (without emblem_url).

**Comment by ckib16** [comment]
@mattscilipoti Just to clarify. Since I changed the DB after the original migration was run, AND we can't drop Heroku DB, I had to run `heroku run rake db:migrate:redo` to essentially say:

"Hey Heroku, do ALL my migrations from scratch again!"

Is that correct?

**Comment by RobertAKARobin** [comment]
Got it, Matt.

Almost! `redo` "undoes" or "rolls-back" _one_ migration, and then runs it again.

http://edgeguides.rubyonrails.org/active_record_migrations.html#rolling-back

**Comment by ckib16** [comment]
Ah, I see.

Is there a way to do ALL the migrations at once? Or you just have to go one at a time?

**Comment by RobertAKARobin** [comment]
That would be `rake db:migrate:reset`.

**Comment by ckib16** [comment]
Perfect, thanks. Closing again now. Much appreciated.
