### ISSUE TITLE
Suggestions for dealing with Merge Conflicts?

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#346]
I've been working in a branch called "first-day" and want to merge this entire branch into my master. I received the following merge conflicts and am confused as how to deal with them. Is there a way to "hard" merge the branch I want into master?
![screen shot 2015-11-17 at 3 38 13 pm](https://cloud.githubusercontent.com/assets/14894858/11224180/a68fc9a4-8d41-11e5-9f35-4339ca65cc04.png)

**Comment by RobertAKARobin** [comment]
Yes! If you're _sure_ that's what you want to do, then first you want to stop your current merge:

```
git merge --abort
```

Then, you use the `-X` option:

```
git checkout master
git merge -X theirs other-branch-name
```

In this context, `theirs` means "the other branch" and `ours` would mean "the branch I'm currently on".

**Comment by mcgrodsky** [comment]
hmm this is still presenting a merge conflict. It doesn't like that i've been messing with the file extension of my stylesheet. 

![screen shot 2015-11-17 at 3 45 29 pm](https://cloud.githubusercontent.com/assets/14894858/11224308/556c139c-8d42-11e5-989a-bffa34c1876a.png)

**Comment by andrewsunglaekim** [comment]
just go into the files causing the conflict. Get rid of the parts you don't want, then stage and commit changes.

**Comment by RobertAKARobin** [comment]
Yep. You'll see scary stuff like `<<<<<<<<<<<<<<< HEAD` and `==== 12387498237489324`. Just imagine those were any other lines of text, and then delete the lines of text you don't want (which presumably will include those two).

**Comment by mcgrodsky** [comment]
Cool, this worked. Thanks!
