### ISSUE TITLE
Passing token into session

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#347]
I've got a Class (Github) that uses HTTParty to get info from the github API, which requires a username and token. I'm trying to figure out how to pass that info into this method.

Here is where I'm trying to get the token and username into the session

``` ruby
class SessionsController < ApplicationController
  def create
    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_from_omniauth(auth_hash)
    @token = auth_hash[:credentials][:token]
    if @user
      session[:user_id] = @user.id
      session[:token] = @token
      redirect_to root_url
    binding.pry #session is what I want here and session[:token] => d969283683c5ae05576b6......
    else
      redirect_to root_url
    end
  end
```

and here is where I'm trying to pass the session into the Github.rb Class. This is where I'm currently stuck. How do I get that user_id and token here, and how can I get that into Github.new( :8ball: ) ?

``` ruby
class ReposController < ApplicationController
  def index
    @session = session
    binding.pry #session is still one of these  #<ActionDispatch::Request::Session:0x007fa3bbb380d8 ...> 
           #(whatever that is called) and session[:token] => nil
    Github.new(@session).get_user
  end
end
```

This is the Github Class where a bunch of stuff probably won't work but hopefully I'll be able to troubleshoot if I could figure out how to get the token and user into it.

``` ruby
class Github
  include HTTParty
  base_uri 'https://api.github.com'
  # attr_reader :last_updated

  def initialize
    @headers = {"Authorization" => "token #{session[:token]}",
                "User-Agent" => User.find_by(id: session[:user_id]).nickname }
  end
  binding.pry

  def get_user
    response = HTTParty.get("https://api.github.com/user", :headers => @headers)
    # response = self.class.get
  end
end
```

**Comment by andrewsunglaekim** [comment]
You're very close. All you need to do change your initialize method to take an argument

**Comment by andrewsunglaekim** [comment]
Something like this: 

In repos ctrl:

``` ruby
def index
    github_info = {user_id: session[:user_id], token: session[:token]
    Github.new(@session).get_user
end
```

Then in `github.rb`:

``` ruby
attr_reader :user_id, :token
def initialize(information)
    @user_id = information[:user_id]
    @token = session[:token]
    @headers = {"Authorization" => "token #{@token}",
                "User-Agent" => User.find_by(id: @user_id.nickname }
end
```

**Comment by andrewsunglaekim** [comment]
Basically the model itself, can never know about the session, so we pass in things from the session as arguments of the initialize method for the `Github` class

**Comment by tylercrosse** [comment]
Are sessions unique to each controller? I don't really get why they work sometimes and others not. I stuck a binding.pry to troubleshoot and I'm still confused.

```
    2: def index
    3:   github_info = {user_id: session[:user_id], token: session[:token]}
 => 4:   binding.pry
    5:   Github.new(github_info).get_user
    6: end

[1] pry(#<ReposController>)> github_info
=> {:user_id=>nil, :token=>nil}
```

**Comment by andrewsunglaekim** [comment]
nope, sessions get instantiated whenever you set a variable within it. And don't get deleted unless u manually delete it or the session it self is otherwise cleared. Once a session variable is set, you have access to it in all controller actions and views
