### ISSUE TITLE
issue with deleting attendances

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project2#348]
I tried various ways to delete rows from the join table database called attendances, both modeled off of the tunr many_to_many code and my own attempts. I expected it to work but I just got errors. For lines 62 and 63, I got type errors of "Cannot visit User" and "Cannot visit Concert" respectively, and for line 64 I got a syntax error.

My repo link is https://github.com/rebeccaestes/project2 and my question is about lines 62-64 in the concerts controller, which should be called by lines 9-10 in the concerts/show.html.erb file.

**Comment by RobertAKARobin** [comment]
I'ma come take a look.

**Comment by RobertAKARobin** [comment]
The issue was using `.where(user = @user)` instead of `.where(user: @user)`.
