### ISSUE TITLE
devise login stopped working

### ISSUE THREAD

**Issue by ArmaniH** [ga-wdi-exercises/project2#350]
I'm not sure exactly what happened, but when I attemt to login the page just goes back to the login page

![screen shot 2015-11-17 at 4 09 07 pm](https://cloud.githubusercontent.com/assets/13981641/11225021/e9d6e5d6-8d45-11e5-9346-79b3b36d92b5.png)

**Comment by RobertAKARobin** [comment]
Could you show me what your `application_controller.rb` looks like?

**Comment by ArmaniH** [comment]
Sure thing
![screen shot 2015-11-17 at 4 16 24 pm](https://cloud.githubusercontent.com/assets/13981641/11225196/d6e389ce-8d46-11e5-94b9-a70241e60906.png)

**Comment by RobertAKARobin** [comment]
Cool; thanks. Have you specified a `root` in your `config/routes.rb`?

**Comment by ArmaniH** [comment]
I do... I'm re-raking my routes

**Comment by ArmaniH** [comment]
We're good! Thanks!

**Comment by RobertAKARobin** [comment]
Wooooo
