### ISSUE TITLE
Model/Migration Question

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#351]
No specific error, just adding a model/migration and want to make sure I have the right association built in.  So basically a User has many Reports and a Report belongs to Location.  Now I am adding Profile in a one to one association with User.  The question is, I want to make a column in Profile that will be a link to the Reports created by that User.  So is the link between User and Reports enough for this, or is it wise to include a foreign key for Reports?

**Comment by RobertAKARobin** [comment]
Gotcha. So to be sure, you want to be able to say `@profile.reports`, correct?

You would do this with a "has many through". Here's an example: https://github.com/ga-dc/garnet/blob/master/app/models/group.rb#L14

**Comment by dan-ator** [comment]
Well it would be on the particular user's profile page.  Not sure if that is the same.  But it sounds like you are saying that as long as the profile has an associated User then I should be able to easily link to the Reports on the profile page?

**Comment by RobertAKARobin** [comment]
Yeah. In fact, since it's one-to-one between the profile and user you don't even need the "has many through". If the profile belongs to one user, and the user has many reports, you should be able to just call `@profile.user.reports` to get all of that profile's user's reports.

**Comment by dan-ator** [comment]
Cool.  Thanks.
