### ISSUE TITLE
Books have tags through taggings, having a hard time getting to books from the tags

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project2#352]
Books have tags. On my index page I have a form to filter the books by tag. I cant seem to get to the books from the tags and taggings. My code: 

``` rb
def index
    @tags = Tag.all

    if(params[:tags])
      @tags = Tag.where(name: params[:tags])
      @taggings = []
      @book = []

      @tags.each do |tag|
        @taggings << tag.taggings
      end
      @books = Book.all

      @taggings.each do |tagging|
        @books << tagging.book
      end

    else
    @books = Book.all
    end
  end
```

I am trying to build arrays of taggings and then iterate over that array to select the book via taggings.book put those books in an array and then display them on the index page.

The error:
undefined method `book' for #<ActiveRecord::Associations::CollectionProxy []>
  @taggings.each do |tagging|
        @books << tagging.book
      end

I didn't think that the |tagging| were collections but it looks like they are, so I cant select one book from a collection.

**Comment by lewis2ba** [comment]
Oh, and that first 

```
      @books = Book.all
```

is just for debugging

**Comment by andrewsunglaekim** [comment]
Can you link all of your associations in your model definitions?

**Comment by lewis2ba** [comment]
```
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
end
```

```
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :books, through: :taggings
end
```

```
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :book
end
```

```
class User < ActiveRecord::Base
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
```

**Comment by andrewsunglaekim** [comment]
Basically you want to list all of the books for one tag? or all the books for multiple tags?

**Comment by lewis2ba** [comment]
Yeah

**Comment by andrewsunglaekim** [comment]
Maybe something like this:

``` ruby
def index
  if params[:tags]
    @books = Tag.find_by(name: params[:tags]).books
  else
    @books = Book.all
  end
end
```

**Comment by andrewsunglaekim** [comment]
If you want to list books for multiple tags, that will look a little different
