### ISSUE TITLE
issue with time zone

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project2#354]
I tried adding the following code to my config/application.rb file `config.time_zone = 'Eastern Time (US & Canada)'
    config.active_record.default_timezone = :local`

I expected to get Eastern Time when I used created_at but it remained in UTC time instead.
My repo link is https://github.com/jacohen10/Project2/blob/master/config/application.rb and my question is about line 11.

**Comment by andrewsunglaekim** [comment]
https://github.com/ga-dc/garnet/pull/251/files check out this PR!
