### ISSUE TITLE
Associating models with User

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#355]
Ok, i've been stuck on this ALL day so i'm reaching out for help! I have a model called "listings" which is where logged in users can create a listing. pretty simple. Just trying to make it so that only the user who created that listing can edit/delete the listing. I know we did this in Scribble but i don't think mine ever worked. In my listing_controller I have tried doing the following code for UD functions but it doesn't seem to be working. What am I missing?

``` rb
  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @listing = @neighborhood.listings.create!(listing_params.merge(user: current_user))
    redirect_to neighborhood_path(@neighborhood), notice: "Your listing was successfully created!!"
  end
```

also tried the following code above the re-direct

``` rb
 @listing.user = current_user
    @listing.save
```

**Comment by elisekain** [comment]
It may not be the most elegant solution...but I used an if...else statement in my view that only let the user see the edit/delete buttons if its their listing (in the "show" view):

``` erb
<div class="actions">
  <%= link_to "My Lyricks", cards_path, class: "lyrick_action" %>
  <%= link_to "Browse Lyricks", cards_browse_path, class: "lyrick_action" %>
  <% if current_user.id == @card.user_id %>
    <%= link_to "Edit", edit_card_path(@card), class: "lyrick_action" %>
    <%= link_to "Delete", card_path(@card), method: :delete, class: "delete lyrick_action" %>
  <% else %>
    <%= "Lyrick by: #{@card.user.username}" %>
  <% end %>
</div>
```

**Comment by RobertAKARobin** [comment]
:+1: for Elise's solution!

**Comment by mcgrodsky** [comment]
@elisekain ELISE you are brilliant!!
