### ISSUE TITLE
Making Users Seed Data

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project2#356]
I am trying to make fake users and associate objects with them so I don't have to recreate them myself while playing around with my app.
I tried creating them in seeds.rb and in ActiveRecord. 
I expected them to be created.
I keep getting a rollback in ActiveRecord instead. So I did DCM to reset the database but it still says a user exists for any user I try to create.

This is the error I'm getting in ActiveRecord along with how I tried to make the user.
![image](https://cloud.githubusercontent.com/assets/12722650/11228435/7aad0158-8d5a-11e5-98e7-ed470b6165df.png)

**Comment by elisekain** [comment]
Hey Ly... I had this problem too... here's the code that's working now in my seed file...I think its easier to pass in the password and password_confirmation rather than trying to pass in the encrypted_password: 

```
users = User.create!([
  {email: "rebecca@example.com", username: "rebecca", password: "rebeccapassword", password_confirmation: "rebeccapassword"},
  {email: "john@example.com", username: "john", password: "johnpassword", password_confirmation: "johnpassword"},
  {email: "darren@example.com", username: "darren", password: "darrenpassword", password_confirmation: "darrenpassword"},
  {email: "susan@example.com", username: "susan", password: "susanpassword", password_confirmation: "susanpassword"},
  {email: "tyler@example.com", username: "tyler", password: "tylerpassword", password_confirmation: "tylerpassword"},
  {email: "paul@example.com", username: "paul", password: "paulpassword", password_confirmation: "paulpassword"},
  {email: "christy@example.com", username: "christy", password: "christypassword", password_confirmation: "christypassword"},
  {email: "michael@example.com", username: "michael", password: "michaelpassword", password_confirmation: "michaelpassword"},
  {email: "andrew@example.com", username: "andrew", password: "andrewpassword", password_confirmation: "andrewpassword"},
  {email: "bonnie@example.com", username: "bonnie", password: "bonniepassword", password_confirmation: "bonniepassword"},
])
```

Ignore the username: "bonnie" and similar if you haven't added a username column to your devise table.

**Comment by Ly900** [comment]
I'm going to give it a try. I got it to work once and I couldn't remember how. It might have been the exclamation point but not sure. Thanks!
