### ISSUE TITLE
Creating Comments in my Post Index

### ISSUE THREAD

**Issue by brittonwalker** [ga-wdi-exercises/project2#357]
So I'm having a problem understanding how to start this idea. My page is routed to the post/index page that displays all blog posts. I want to attach a form at the bottom of each post where you can write in a comment right there and never leave the index page. The only other way I could think to implement comments is to take it to the individual show page. I do not want to do this. I basically want to make the same functionality as a facebook post with comments.

**Comment by RobertAKARobin** [comment]
So you want the comments to show up on the post's show page?

How about something like:

``` erb
<% @post.comments.each do |comment| %>
  <p><%= comment.text %></p>
<% end %>
```

That's like this from Tunr: https://github.com/ga-dc/tunr_rails_deployment/blob/master/app/views/artists/show.html.erb#L8

**Comment by nolds9** [comment]
@brittonwalker, I think what you are looking for is to render a partial view, in this case for a new comment.  Say if you had new comment form in `app/views/comments/_form.html.erb`, you could render that view inside another view with something like: `<%= render partial:"comments/form" %>`

For more info, I'd check out the [guides](http://guides.rubyonrails.org/layouts_and_rendering.html)

**Comment by RobertAKARobin** [comment]
I'm going to close this, but feel free too open a new one!
