### ISSUE TITLE
Utilizing Devise and users

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project2#358]
The first step I did for user authentification was creating devise gem, and used it to create views, and models.
After a while, I tried to follow steps from this resource: https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-sessions-and-auth

```
rails generate migration create_users
# db/migrate/[timestamp]_users.db

class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :username
      t.string :password_digest
    end
  end
end
```

and was having duplicate users error. So I erased that migration file.

I think devise gem handled everyting including creating model, migration and validation. I tried to use

```
  # before_action :authenticate
  #
  # private
  # def authenticate
  #   if !session[:user]
  #     redirect_to "/users/sign_in"
  #   end
  # end
```

this in application_controller.rb and I was stuck in loop redirect error. So is all I have to do manually create users_controller and and skip_before_action :authenficate ??
I am thinking devise gem did everything for me. Am I interpreting it correctly?

Thank you.

**Comment by RobertAKARobin** [comment]
I'm afraid you were actually looking at the incorrect readme. This is our fault: we had one folder named `rails-sessions-and-auth-with-devise` and one named `rails-sessions-and-auth`, which is very confusing. I just changed it so now there's just one folder. Please refer to the readme here:

https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-sessions-and-auth

**Comment by RobertAKARobin** [comment]
I'm going to close this, but feel free too open a new one!
