### ISSUE TITLE
Continued problems with Tag/Tagging - using if statements to create tags and/or taggings

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project2#359]
Hi, I am still having troubles implementing my Tag/Tagging system. Andy was helping me and I think I am close but am running into some difficulties. I want to add tags to my books so that the user can filter by tag on the index page. I created a new tag page and form that takes one param, name. I am trying to write an if else statement in my controller to create a new tag and tagging if that name param doesn't exist. Or just create a tagging if the name param entered into the form does exists, and use the existing tags id. 

Here is my code:

```
  def create
    @user = User.find(params[:user_id])
    @book = Book.find(params[:book_id])

    if Tag.find_by(params[:name]).present?
      exists = Tag.find_by(params[:name])
      @tagging = Tagging.create(book_id: @book.id,tag_id: exists.id)

    else

      doesnt = Tag.create(tag_params)
      @tagging = Tagging.create(book_id: @book.id, tag_id: doesnt.id)

    end
```

This variation creates a new tag and tagging every time so there are tags that have duplicate names. 

If I intentionally break my code the params I see are:

```
{"utf8"=>"✓",
 "authenticity_token"=>"RjZqp1YMdXdlLpXw/6GvNqYfUUqvnSQ90loVQi0al8KH9kfGR3U9LuG3p7oSUfMqh9e9x5wK6MMQvgzyWO6beg==",
 "tag"=>{"name"=>"sadfsdf"},
 "commit"=>"Submit",
 "user_id"=>"2",
 "book_id"=>"9"}
```

Could it have something to do with the "tag"=>{"name"? Maybe I cant directly access the name param.

Thanks!

**Comment by RobertAKARobin** [comment]
Bingo! It's because `name` is inside `tag`. Try `params[:tag][:name]`. Might need to futz around with trying combinations of strings and symbols of that doesn't work.

ORRRR you could create a `tag_params` method!

**Comment by lewis2ba** [comment]
AHHHHHH IT WORKS! THANKS! I already had a tag_params method but didn't realize I could use it. Now I can sleep. Thanks again
