### ISSUE TITLE
sqlite3 vs postgresql

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project2#360]
It seems like no matter what i do, always end up with sqlite3 in my gem file instead of postgresql...
why is this and how can i change it?
 (yes even when I run 'rails new (name) postgresql' and no I am not using scaffolding)

**Comment by amaseda** [comment]
Are you including that `-d` in the command line? Should look like: `rails new appname -d postgresql`.

Although if you don't want to create a new application, you can (1) add the `pg` gem to your `Gemfile`, (2) run `bundle install` and (3) modify your `database.yml` file so it looks something like this...

``` rb
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: appname_development

test:
  <<: *default
  database: appname_test

production:
  <<: *default
  database: appname_production
```

> Make sure you replace `appname` above with whatever you used when running `rails new appname`.

**Comment by amaseda** [comment]
Gonna close this one but feel free to re-open if the issue resurfaces!
