### ISSUE TITLE
User Agent Stylesheet Overwrite

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#361]
I'm trying to style the background of a text_area field and it is getting overwritten in my browser. I've done some research and installed a normalize-rails gem but it doesn't seem to be helping?

Is the best option inline styling?

**Comment by amaseda** [comment]
What sort of selectors are you using when styling the text areas? Could be an issue of [specificity](https://css-tricks.com/specifics-on-css-specificity/). Don't need to resort to inline styling or a gem.

You can also see how exactly browser styling is overriding your CSS by inspecting the element. Make sure that the specificity of the browser's selectors is less than yours.

**Comment by ghost** [comment]
Thanks Adrian, it looks like you're right. 

It was an invalid property value. I guess I'll look in to that some more!

**Comment by amaseda** [comment]
:+1:
