### ISSUE TITLE
Can't figure out this error

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project2#362]
It may just be that I'm still sleepy, but I can't seem to get past this routing error "uninitialized constant controller"

I'm trying to merge multiple lesson plans and screencasts to create my app and I think I got tripped up along the way...

<img width="1440" alt="screen shot 2015-11-18 at 8 23 49 am" src="https://cloud.githubusercontent.com/assets/13460389/11242154/f502cb68-8dcd-11e5-8460-5222fce00b8a.png">

**Comment by amaseda** [comment]
Have you created a `works_controller.rb` that corresponds to this `WorksController` yet?

**Comment by kaustly** [comment]
I haven't, but I thought that was supposed to be created when I ran 
"rails g model Work public:boolean media_type:string user:references" or does that just create the work.rb?

**Comment by amaseda** [comment]
Nope, that'll just create the model and migration!

**Comment by kaustly** [comment]
... maybe I should get some coffee... 

Thanks!

**Comment by amaseda** [comment]
☕️☕️☕️
