### ISSUE TITLE
issue with rendering data on show page

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#364]
I tried _____. 
To render a list of pending appointments on each vet's show page, /vets/someID.

```
<ul>
  <% @vet.appointments.each do |appointment| %>
    <li>
      <%= link_to "#{appointment.pet} (#{appointment.appointmenttime})", pet_appointment_path(@pet, appointment) %>
    </li>
  <% end %>
</ul>
```

I expected _____ to happen.
Expected a list of pending appointments listed by pet name and time.

_____ happened instead.
No content displayed.  Have successfully created appointments for several vet/pet combos.

My repo link is ___ 
https://github.com/thomhouseholder/project2-vet

and my question is about lines ___.
/views/show.html.erb 18-24.

**Comment by RobertAKARobin** [comment]
It looks like your vet doesn't have any appointments. To test, I'd recommend going into the Rails console (`rails c`), pulling up that particular vet (`Vet.find(32)`), and then seeing if it has any appointments (`Vet.find(32).appointments`). If it doesn't, your problem is elsewhere.

**Comment by ghost** [comment]
Okay, think I've got it.  

`<%= link_to "#{@pet.name} (#{appointment.appointmenttime})", pet_appointment_path(@pet, appointment) %>`

show action uses @pet.find_by(params[:pet_id])
