### ISSUE TITLE
issue with declaring variables in my controller so I access a join table properly

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project2#365]
I tried listing the tasks for each member within a group but it is displaying the task bases on group_id for every member and not the member_id. I expected each task to show up to each individual person to happen. Each job showed up next to every person instead happened instead.  I do not know if there is a way to access the tasks without specifically finding the member_id from the URL params.  I feel like if I nested tasks within members I would be able to click on a link for the member to go to the tasks and use the params for the group and member to list the tasks.  We spoke yesterday about not triple nesting so I am wondering if there is a way to access the tasks through the join table that requires group_id and member_id without doing that.

My repo link is https://github.com/murgia/taskager and my question is about lines 1-6 on the member controller.

**Comment by RobertAKARobin** [comment]
Can you show a screenshot of what it looks like on your page? I'm having trouble visualizing this.

**Comment by RobertAKARobin** [comment]
Your `@group.members.all` and `@group.members.all` both are correct. You don't actually need `.all` on them -- only when you're doing `Group.all` or similar -- but it shouldn't hurt.

**Comment by murgia** [comment]
![screen shot 2015-11-18 at 10 25 15 am](https://cloud.githubusercontent.com/assets/14044951/11245049/c3795d3a-8dde-11e5-8e13-19a7645ab79a.png)
