### ISSUE TITLE
cancancan 

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#366]
I am trying to implement cancancan and am stuck.  I understand enough to implement the `<% if can? :create, @report.info_items %>` etc. for create, edit, delete, but defining the actual users is confusing me( and I know this only hides the buttons so I need to implement things in the controllers and User model.  So I put this in my ability model:

```
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role? :admin
      can :manage, :all
    else
    can :read, :all
    can [:create, :update, :destroy], [Report, InfoItem, Comment], :active => true, :user_id => user.id
    end
  end
end
```

But the first error is that the :admin role is not defined.  I used Devise for my users so I don't have a users_controller and so this doesn't seem to fit with the directions provided here: https://github.com/CanCanCommunity/cancancan/wiki/Role-Based-Authorization

**Comment by RobertAKARobin** [comment]
`if user.role? :admin` is looking for a `role` column on your Users table. For instance, if you wanted only Users with an age greater than 32 to be able to manage all, then you would write:

``` rb
if user.age > 32
  can :manage, :all
```

If you wanted to do the same for users with the e-mail of "billgates@ms.com", you would do:

``` rb
if user.email == "billgates@ms.com"
  can :manage, :all
```

If you didn't define a `role` column it doesn't exist, in the same way that if you didn't define an `email` column it doesn't exist.

**Comment by RobertAKARobin** [comment]
The first line in the documentation is:

> "CanCanCan is decoupled from how you implement roles in the User model, but how might one set up basic role-based authorization?"

CanCanCan doesn't define roles; it defines permissions. In a lot of apps permissions are grouped together into a different model called Role, but CanCanCan doesn't do that for you.

**Comment by dan-ator** [comment]
so i added a column called 'roles' to the User table.  But it seems like I need a users_controller.  If I used devise, will adding this mess with functionality built in there?

**Comment by RobertAKARobin** [comment]
Introducing roles is going to add a good amount of complexity to your app, so I would advise against it. Can you tell me in English what you want CanCan to do here?

**Comment by dan-ator** [comment]
I want to make it so that users can only create reports/info_items/comments if they are signed up and logged in(I think this is done by devise) and then I want to make it so that users can only update or destroy reports/info_items/comments that they created.  Also, creating a role of admin for me to have total control sounds like a good idea too.

**Comment by RobertAKARobin** [comment]
Yes, that first part's done by Devise. For the second part, you _could_ use CanCanCan, but it would be MUCH simpler to just put that logic in your controller, or if you're feeling a bit fancy, to create a [custom validation](https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/error-handling#custom-validations-10-min).

I'd only use CanCanCan if there are LOTS of different permissions you need to manage -- like, more than 10 -- otherwise it's going to make your app extremely difficult to develop.

At any rate, this sounds very much like a "gold" goal. If your app has full functionality, and it has a good-looking front-end, then I'd say go for the permissions stuff. But if not, save it for down the road.

**Comment by dan-ator** [comment]
Well the functionality is all there for users, reports, locations, info_items, and comments.  I just need to add profile for each user.  I am planning on doing all of my css tomorrow for front end design.  But I think it is part of MVP that people can only edit/delete their own posts and comments. I was under the impression that using cancancan makes permissions simpler and centralized.

**Comment by RobertAKARobin** [comment]
Nah. "User authentication" is part of the MVP, which just means people should be able to log in and log out. See here:

https://github.com/ga-dc/project2#technical-requirements
