### ISSUE TITLE
issue with remembering how to access a foreign key rather than passing in params

### ISSUE THREAD

**Issue by jenpen** [ga-wdi-exercises/project2#367]
I tried looking it up in nesting documentation and have just been passing in different methods, but I can't remember. 

I expect to have a link of all my notecards with links to each individual notecard (currently nested within a board)

My repo link is https://github.com/jenpen/daily_scrum/tree/corrected_code_1 and my question is about the notecards_controller (lines 3-7) and the notecards/all view (line 5). (screenshots below)

Notecards_Controller
![screenshot 2015-11-18 11 11 58](https://cloud.githubusercontent.com/assets/4039780/11246419/99711954-8de5-11e5-92c5-b17ca0738890.png)

Notecards/All
![screenshot 2015-11-18 11 12 39](https://cloud.githubusercontent.com/assets/4039780/11246426/9d061434-8de5-11e5-8ae3-a0043ce92570.png)

**Comment by amaseda** [comment]
Might have something to do with Line 5 in your NotecardsController. Looks like you're trying to find a particular board, but instead what you're doing is looking up a notecard in `@notecards` that has the same `id` as `board_id`.

On top of that, doesn't look like just `board_id` will contain any value. You'll have to pull it from the URL with `params[:board_id]`. And remember that with `find_by` you need to pass in a key-value pair(s) that lets the method know what exactly you are searching for.

Let me know if that helps!

**Comment by jenpen** [comment]
Thanks Adrian. I don't have a board ID in the URL coming from this all page which just shows a list of all notecards (like a page that lists all songs regardless of Artist in Tunr). 

Since I don't have that value to pass into params, what I'm struggling with is how to grab that value to build my link to an individual card - the path to a card looks like (boards/2/notecard/2). I was thinking I could pull it from the notecard record since the board_id is a FK column within notecards. 

I started with the following: 
'''

  def all
    @board = Board.find(params[:board_id])
    @notecards = Notecard.all
  end
'''

but got an error that AR could not find Board with a nil id (which makes sense since there is no id to pass into params.)

... And since them I've been trying to set it to the board_id value within the Notecard, but without success.

**Comment by amaseda** [comment]
Ah, well you should have access to both the notecard and its board in your view. In your view, you can access each notecard via the `notecard` iteration variable in your each statement. On top of that, you can access the board a notecard belongs to using `notecard.board`. I think that should be enough to start building links.

So you wouldn't actually need to define a board in your `all` controller action!

Let me know if that doesn't help -- can come by and take a look.
