### ISSUE TITLE
issue with _sign up, login, and logout functionality___

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/project2#368]
I tried **running devise_**. I expected **the signup button_** to happen.**Nothing_** happened instead.

**Comment by amaseda** [comment]
What do you mean by "running devise" -- installing it? If so, how exactly did you go about doing that?

A checklist for installing Devise is...
1. Including the `devise` gem in your Gemfile
2. Running `rails g devise:install` via Terminal inside of your app directory.

From there, if you run `rake routes` you should see a bunch of new routes that correspond to sign up, sign in, etc.

More information on the installation process can be found [here](https://github.com/plataformatec/devise).

**Comment by MohamedGood** [comment]
I ran the devise commands... I ran my migrations... I dont know what else I need to do to show sign up, login and logout functionality on my welcome page

**Comment by amaseda** [comment]
The sign up / login / logout links don't automatically show up on your welcome page. You need to create links in your views using the path helpers that `rake routes` provides. If you run `rake routes` in the Terminal you should see a long list of them. Are they showing up for you?

Your "sign up" link will end up looking like the below code. Try creating similar ones for "sign in" and "log out"...

```
<%= link_to "Sign In", new_user_session_path %>
```

> new_user_session_path is one of the path helpers you'll see in rake routes

**Comment by MohamedGood** [comment]
Ok thanks that helps a lot... 

Now do I have to create a _form.html.erb page for the link to work

**Comment by RobertAKARobin** [comment]
If you're using Devise, it should have created that form for you. You may not actually see it in your views because it sort-of hides those from you. But just try testing the link in your web browser.

**Comment by MohamedGood** [comment]
thanks you... I created a _form view page
