### ISSUE TITLE
Heroku Migrate Not Working

### ISSUE THREAD

**Issue by ascreven** [ga-wdi-exercises/project2#369]
rake db:migrate is working and all of my databases in psql look correct but when I run 
heroku run rake db:migrate 
I get the following error: 

```
-- change_table(:users)
   (0.8ms)  ALTER TABLE "users" ADD "email" character varying DEFAULT '' NOT NULL
PG::UndefinedTable: ERROR:  relation "users" does not exist
: ALTER TABLE "users" ADD "email" character varying DEFAULT '' NOT NULL
   (0.4ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "users" does not exist
: ALTER TABLE "users" ADD "email" character varying DEFAULT '' NOT NULL/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
```

I've gone through all the trouble shooting but I'm getting a little nervous with the solutions because they keep changing my local databases. What should I do?

**Comment by RobertAKARobin** [comment]
It looks like your migrations are out of order! Kelly was actually having almost the exact same issue. I'd take a look at my response to her issue:

https://github.com/ga-dc/project2/issues/363#issuecomment-157736224

And don't worry about the database. As long as you're committing and branching and stuff -- and don't have live data on Heroku that you're trying to preserve -- you'll be fine.

**Comment by ascreven** [comment]
Thank you Robin. I'll take a look. I really want it to be useable though
and I feel like it won't be if it doesn't save information.

**Comment by RobertAKARobin** [comment]
This won't have any impact on your ability to save data! It may just delete data that you have in your database right now. Presumably that's only test data, which doesn't matter, or is seed data, which you can generate again with `rake db:seed`.

**Comment by ascreven** [comment]
I read through Kelly's error but all that is working on mine. It's just not
working when I'm deploying to Heroku.

**Comment by RobertAKARobin** [comment]
First, check to make sure it's working locally: run `rake db:drop` and rebuild the database from scratch.

If there are no errors there, then I would delete your current Heroku app (`heroku apps:destroy your-app-name`) and `heroku create your-app-name` it again.

**Comment by ascreven** [comment]
Oh whoops, that was the problem. It's not running locally either. How
should I get it back to my last successful run? My schema.rb file looks
exactly how I want it to right now.

**Comment by RobertAKARobin** [comment]
What error are you getting? If it's the "table does not exist" one, then it's because you just need to switch around the order of some of your migration files.

If you're at GA and want me to take a look in-person, feel free to find me at the table outside the bathrooms.

**Comment by ascreven** [comment]
I'm at home right now but can get there by 2. Will you still be around?

**Comment by RobertAKARobin** [comment]
Nah, if you're at home, not to worry. We can fix it from here. What's the text of the error?

**Comment by ascreven** [comment]
Thank you Robin! Here is a screenshot of the error I'm getting after
dropping the database

**Comment by ascreven** [comment]
Is there a way to use rake db:schema:load to get the migrations back to how
they should be?

**Comment by RobertAKARobin** [comment]
I'm not seeing the screenshot, Alex.

You shouldn't do `schema:load` -- you should always create your database from the migration files. Otherwise, it's going to cause a lot of integration headaches down the road since other developers/platforms will be expecting `migration` to work.

**Comment by ascreven** [comment]
Oh that makes sense. Sorry about that, here it is!

**Comment by ascreven** [comment]
Hey Robin, thank you for all your help! I just figured it out by commenting
out sections in different migrations to pinpoint the problem. It's good to
know I shouldn't rely on db:schema:load!

**Comment by RobertAKARobin** [comment]
Wooo! I'm glad you got it! :)
