### ISSUE TITLE
Project2

### ISSUE THREAD

**Issue by Thesheik** [ga-wdi-exercises/project2#37]
I chose to do a Recipe sharing app. Please let me know if the project idea is feasible. Also my wireframes are in a file into my rails app call wireframe.

HealthyRecipes is a recipe social networking app. Users from HealthyRecipes will
be able to join in for free and get to share their recipes with friends and families.
Social media have been tremendously growing and we've all heard the old saying “you are what you eat.”
What a better way to cut the junk, start eating healthy with the help of friends through share recipes
in with HealthyRecipe to share clean and healthy recipes with your love ones.

As a user I would be able to

1.SignUp/SignIn/Signout
2.create a profile
3.create a new recipe
4.upload an image
5.edit a recipe
6.destroy a recipe
7.add new ingredient
8.comment on friends recipes
9.Share and Receive recipes
Repo link:
https://github.com/Thesheik/Cheikh_project2

**Comment by mattscilipoti** [comment]
Looks good.  Appropriate for this week's project.

I would add a story for viewing all recipes (no login required).  

I recommend that your first pass allows users to share an image via an image url (they upload to an image hosting service: https://www.google.com/search?client=safari&rls=en&q=image+hosting&ie=UTF-8&oe=UTF-8).  Once ALL of it is working, then fight with uploading images.
