### ISSUE TITLE
issue with form_for 

### ISSUE THREAD

**Issue by ajohnson052** [ga-wdi-exercises/project2#370]
I tried 

``` erb
<% form_for [@escapade, @commit] do |f| %>
        <%= f.hidden_field :status, value: true %>
        <%= f.submit "I'll be there!" %>
```

I expected 
params[:commit] = [ status: true ]

Instead
params[:commit] = "I'll be there!"

End goal
Make a button that will create or update commits with a single click

My repo link is https://github.com/ajohnson052/escapades and my question is about app/views/escapades/show_event.html.erb line 19-28.

**Comment by RobertAKARobin** [comment]
Hah! First time I've seen this error. The trouble is that `params` actually already gets a field by default that happens to be called `commit`. It's the value of the submit button (as in `<input type="submit" value="This is the value" />`).

You can pass an argument to `form_for` that makes it use a different name for the model -- so you could do `my_commit` or something. Check out this answer: http://stackoverflow.com/questions/11248670/custom-name-for-params-hash-from-rails-form-for

Note that you'll need to update your strong params with the new name you choose.

**Comment by ajohnson052** [comment]
Haha, that clears up some of the confusion! 
But even with new_commit as the new instance variable I'm getting the error: 

param is missing or the value is empty: new_commit

and the params: 

```
{"utf8"=>"✓",
 "authenticity_token"=>"gQoSzeXCNpSbYi6uicTbik7jI7otZ10P+yFIasrmvTxX1gwvl1W0W1w25bjCKkHNSFTzjPMxnPMwSRrYV+GzXw==",
 "commit"=>"I'll be there!",
 "controller"=>"commits",
 "action"=>"create",
 "escapade_id"=>"5"}
```

**Comment by RobertAKARobin** [comment]
Can you show me what your `form_for` looks like?

**Comment by ajohnson052** [comment]
``` erb
<%= form_for [@escapade, @new_commit] do |f| %>
        <%= f.hidden_field :status, value: true %>
        <%= f.submit "I'll be there!"%>
        <% end %>
```

**Comment by RobertAKARobin** [comment]
You need to put in the `as:` argument mentioned in that StackOverflow answer.

**Comment by ajohnson052** [comment]
I'm confused by this because the form needs to be passed two arguments. I have tried 

```
form_for([@escapade, @commit], as: [:escapade, :new_commit])
form_for([@escapade, @commit], as: [@escapade, @new_commit])
form_for([@escapade, @commit, as : :new_commit])
form_for([@escapade, @commit, as: @new_commit])
```

With all returning the same error

For the above, I defined @commit = Commit.new in the controller (in the method that passes the instance variable to the form), and required :new_commit in the strong params.

When I tried this without the :as argument, I was using @new_commit = Commit.new in the controller.

**Comment by RobertAKARobin** [comment]
Try this:

``` erb
form_for [@escapade, @commit], as: :new_commit do |f|
```

**Comment by ajohnson052** [comment]
This seems to be working! But I can't get all the way through the form. I think it's because "status" is set to be a boolean rather than a string. :( 

And so I'm stuck with the error 

```
undefined method `permits' for {"status"=>"true"}:ActionController::Parameters
```

I feel like I've made this way more difficult than it need be!

**Comment by RobertAKARobin** [comment]
Are you at GA today? If so, I'm at the table outside the bathrooms if you want to meet up.

Otherwise, could you push your code up to Github and post the link so I can take a look?
