### ISSUE TITLE
Create migration for joining tables

### ISSUE THREAD

**Issue by CBanks813** [ga-wdi-exercises/project2#371]
I'm trying to create a migration for joining my Appointments and Services tables by running:
rails g migration CreateAppointmentsServices

and I get the following error message

```
$ rails g migration CreateAppointmentsServices
/Users/m/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:260:in `block (2 levels) in check_controller_and_action': '' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use (ArgumentError)
```

**Comment by RobertAKARobin** [comment]
I think the problem here is that it's trying to create a table called `appointments_services`.

Try naming your migration something different -- like `addServicesToAppointments` or something:

```
$ rails g migration addServicesToAppointments
```

**Comment by CBanks813** [comment]
Ok Thanks Robin!

**Comment by CBanks813** [comment]
Soooooo I tried that and still got an error message. :( The exact same message.
