### ISSUE TITLE
unknown attribute error in users controller#signup!

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project2#372]
not sure why username isn't being recognized

<img width="1440" alt="screen shot 2015-11-18 at 11 50 09 am" src="https://cloud.githubusercontent.com/assets/13460389/11247670/13c724aa-8deb-11e5-930e-eb8e894c78cc.png">

**Comment by RobertAKARobin** [comment]
Hmm. Did you use Devise? If so, it doesn't have a `username` field.

**Comment by kaustly** [comment]
I did... I'm confused. What does it have and not have?

this is what I have:
<img width="1440" alt="screen shot 2015-11-18 at 12 04 30 pm" src="https://cloud.githubusercontent.com/assets/13460389/11247961/8a04248c-8dec-11e5-9134-c41e3b0dd7d1.png">

**Comment by RobertAKARobin** [comment]
Take a look at the schema and see what fields it defined for Devise. By default, it only has e-mail and password (and a bunch of other stuff that you don't really use).

**Comment by kaustly** [comment]
so this is my complete schema file... I don't see anything about devise.
yet it's in my gem file 

<img width="1440" alt="screen shot 2015-11-18 at 12 11 43 pm" src="https://cloud.githubusercontent.com/assets/13460389/11248137/8a66f0c0-8ded-11e5-8e19-fa8a22fe5647.png">

**Comment by RobertAKARobin** [comment]
Devise is what created the `users` table for you.

**Comment by RobertAKARobin** [comment]
It's been a little bit, so I'm going to close this. Feel free to open a new one!
