### ISSUE TITLE
form_for issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#373]
I tried _____. 
Implementing a form on vets/show that allows user to create an appoinment.  

Fields are pet name, appointment time. (Am also trying to create drop-down of pet names.  That may be another issue once I fix this current issue - where form delivers input.)

I expected _____ to happen.
Want to pass this information to the appointment table to create appointment.

_____ happened instead.
NoMethodError in vets#show

My repo link is ___ 
https://github.com/thomhouseholder/project2-vet

and my question is about lines ___.
/vets/show.html.erb lines 32-44
vets_controller.rb lines 25-30

**Comment by RobertAKARobin** [comment]
What's the text of the error?

**Comment by ghost** [comment]
Showing /Users/thom/wdi/projects/vet-scheduler/app/views/vets/show.html.erb where line #32 raised:

undefined method `appointment_path' for #<#Class:0x007ffa428a8678:0x007ffa42e31158>

**Comment by RobertAKARobin** [comment]
I'm not seeing a `views/vets`, Thom -- just a `views/users` and `views/pets`.

**Comment by RobertAKARobin** [comment]
Any chance you could just copy and paste the line that has `appointment_path` in it?

**Comment by ghost** [comment]
It would help if I saved the file when I made my last changes!  But don't understand why views/vets/show.html.erb isn't showing.

I added resources :appointments, now have an appointment_path, and my error is a no method error in the show action for the form.  

undefined method `appointment'

 <%= f.text_field :appointment %>

I'm starting to put what seems like too much stuff in 'show'

``` rb
def show
    @vet = Vet.find(params[:id])
    @pet = Pet.find_by(params[:pet_id])
    @appointment = Appointment.create(params[:pet_params])
    # @pet = Pet.create!(params[:pet_id])
  end
```

**Comment by RobertAKARobin** [comment]
Hmm. Can you take a screenshot of the error page? It's `Command` + `Shift` + `3`.

**Comment by ghost** [comment]
![screen shot 2015-11-18 at 1 41 38 pm](https://cloud.githubusercontent.com/assets/13954451/11250351/2cb4c92c-8dfa-11e5-972c-c2bc571825d2.png)

I keep working at this to try to solve.  now using form_for [:vet, @appointment]

**Comment by RobertAKARobin** [comment]
Why are you using `:vet` instead of `@vet` or some such thing?

**Comment by ghost** [comment]
I started with @vet but then went down the rabbit hole of the rails documentation.  Now using @vet, @appointment and still hung up with the way I'm defining appointment in vets_controller - show

**Comment by RobertAKARobin** [comment]
Part of the problem is that you're attempting to create an appointment whenever someone looks at your show page:

```
# vets_controller.rb
@appointment = Appointment.create(params[:appointment_params])
```

You either want `.new` or `.build`, but definitely not `.create`.

Replace this line with:

```
@appointment = @vet.appointments.build
```

Also, `params[:appointment_params]` doesn't exist. If you're going for strong params, it will look something like `model.create(model_params)`, not `model.create(params[:model_params])`.

**Comment by ghost** [comment]
hmm. am i even tackling/defining this correctly?  this is how i'm outlining the process in my bean.

completing the form should build a new appointment by passing vet, pet, appointment time values to appointment, like this

Appointment.create(vet: marty, pet: perdie, appointmenttime: "Monday 3p")

so the vet value is delivered because i'm on the vets/show page; pet name is captured in :name, and appointment time in :appointmenttime.

then i want the values in the created appointment to be added to the list i'm generating on vets/show.

**Comment by RobertAKARobin** [comment]
`.build` is almost the same thing as `.new` -- it doesn't actually save anything to the database.

Completing the form should create a new appointment, yes. But the `show` route is **not** the route that does stuff when the form completes.

Are you here today? I'd be happy to sit with you for a bit on this one!
