### ISSUE TITLE
Trying to get upload to AWS to work

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#374]
I was trying to follow the tutorial on adding an image to AWS but I'm getting a weird error and would love some suggestions on how to troubleshoot.

Here is the error
![image](https://cloud.githubusercontent.com/assets/10747860/11248381/db7e06e6-8dee-11e5-9898-f7b837728512.png)

Here's part of my CommitController

``` ruby
  def create
    @user = current_user
    @repo = Repo.find(params[:repo_id])
    @commit = @repo.commits.find(params[:id])
    @commit.create(commit_params)
  end

  def edit
    @user = current_user
    @repo = Repo.find(params[:repo_id])
    @commit = @repo.commits.find(params[:id])
  end

  def update
    @user = current_user
    @repo = Repo.find(params[:repo_id])
    @commit = @repo.commits.find(params[:id])
    @commit.update(commit_params)
  end

  private
    def commit_params
      params.require(:commit).permit(:image)
    end
```

and my commits/index.html.erb

``` ruby
    <%= form_for([@user, @repo, commit]) do |f| %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.submit %>
```

**Comment by tylercrosse** [comment]
<img width="779" alt="screen shot 2015-11-18 at 12 20 31 pm" src="https://cloud.githubusercontent.com/assets/10747860/11248914/b5765f68-8df1-11e5-9c0a-4719d5e4cb9f.png">

**Comment by RobertAKARobin** [comment]
Alexis had the exact same problem! Check out https://github.com/ga-dc/project2/issues/370 .
