### ISSUE TITLE
continued issue - Robin

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project2#375]
Sorry about that.
So, I think I'm confused because I'm trying to go off of multiple lesson plans and screencasts...
After meeting with Adam yesterday, he said I should install devise first, works second, and digs third- which I did. Now I'm kind of lost because we've only installed devise after having other models already set up.

**Comment by kaustly** [comment]
I'm looking to the tunr_rails_deployment repo as a reference. Should I not be doing that?

**Comment by RobertAKARobin** [comment]
The order doesn't really matter -- you can just run into errors and stuff if you install Devise last. What you have looks really good!

Yep, that's the repo I'd use as a reference.

Are you at GA today? I'm by the bathrooms if you want to sync up.

**Comment by kaustly** [comment]
I was planning on coming in between 2-3 since my one on one with Adam is at 4, but I would so so appreciate sitting down with someone. My head just feels like scrabbled eggs at this point... but I know I'm not far off!
Would you be available at 3:15?

**Comment by RobertAKARobin** [comment]
That's progress! I'll just stay here when I'm not meeting with someone, so feel free to come on over.

Can you specify what error you're getting now? Is it the same thing about `username` not being defined?

**Comment by kaustly** [comment]
Well, I'm getting this because I deleted my whole users_controller.rb since I figured I didn't do it right

<img width="1440" alt="screen shot 2015-11-18 at 12 57 54 pm" src="https://cloud.githubusercontent.com/assets/13460389/11249310/13785d94-8df4-11e5-9883-c010e6905f5e.png">

**Comment by RobertAKARobin** [comment]
Well, that's a problem!

Here's what I'd recommend... basically following Adam's suggestion:
1. Breathe.
2. In a whole new folder, `rails new your-app-name -d postgresql`. Just leave your existing repo alone for now.
3. Install Devise. [Here's a link to a walkthrough in the lesson plan.](https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-sessions-and-auth#devise-we-do-codealong-50m). Note that this includes Devise creating a migration file for you.
4. Create your other migrations: do `rails g migration` for each one, and then just copy and paste the contents from your old repo.
5. Copy over your whole `app` folder from your old repo.

**Comment by kaustly** [comment]
Hah, yes. 
Okay.
That will be my _fourth_ attempt at a project 2 repo, but C'est la vie... Will do!
Thanks, Robin! You're always so patient with me. I can't tell you how much I appreciate that.

**Comment by RobertAKARobin** [comment]
Better to get it now than later!
