### ISSUE TITLE
issue loading jquery-ui-rails

### ISSUE THREAD

**Issue by cpgruber** [ga-wdi-exercises/project2#376]
I'm trying to use [this gem](https://github.com/kristianmandrup/gmaps-autocomplete-rails) to implement an autocomplete search bar for google maps in my app. I've loaded the gems per the install instructions, but when I edit my `javascripts/application.js` file, I receive an error that looks like this 
![screen shot 2015-11-18 at 1 06 43 pm](https://cloud.githubusercontent.com/assets/11283135/11249511/4a273fe4-8df5-11e5-9b9d-1ca47e8b658d.png)
Any ideas?

**Comment by RobertAKARobin** [comment]
Did you take a look at this? http://stackoverflow.com/questions/17830313/couldnt-find-file-jquery-ui

**Comment by cpgruber** [comment]
I'm an idiot. Forgot to restart my server. Is there a time travel gem so I can get that hour back?

**Comment by RobertAKARobin** [comment]
Wooo
