### ISSUE TITLE
migration not being added to schema

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project2#377]
I generated a migration and filled it in.  like this: 

```
class CreateBookworks < ActiveRecord::Migration
  def change
    create_table :bookworks do |t|
      t.datetime :created_at
      t.datetime :updated_at
      t.integer :unique_id
      t.string :image_url
      t.string :author
      t.string :title
    end
  end
end
```

but in my schema, it looks like this, even after I ran rake db:migrate:

```
  create_table "bookworks", force: :cascade do |t|
  end
```

I feel like I've forgotten a step somewhere but I can't think what it is.

**Comment by andrewsunglaekim** [comment]
did you accidentally run a migration before updating and saving it by chance?

**Comment by solowt** [comment]
yeah, it looks like I created the table already somehow.

I deleted it from psql with DROP and removed it from the schema file and then just ran the migration again and it worked.

thanks
