### ISSUE TITLE
Devise/Git

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#378]
Was trying to add username to user...ended up breaking my ability to log in!

Trying to revert to previous git commit where devise was working using this command:

git checkout -b devise-working-version f8cdb22b10ac23a1496155bbae1c33c454a42d93

However when it switches me to a new branch it is NOT the old commit! It still has all of the devise views folders (which i want to get rid of) and newer code that shouldn't be there. Is there another way to revert to a previous commit that i'm missing?

**Comment by andrewsunglaekim** [comment]
the command you used is the right way to time travel in git, I think you just picked the wrong `sha`. ie that big ass group of letters and numbers

**Comment by mcgrodsky** [comment]
@andrewsunglaekim mmk thanks! got it working again

**Comment by mcgrodsky** [comment]
Alright...Devise is acting really weird. It started working again but now i'm having the exact same issue. I have previous git commits where login was working, but when i'm branching to them its still showing the Devise Views and not letting me log in?

**Comment by RobertAKARobin** [comment]
Remember that if you have un-committed changes, those are carried with you whenever you switch to another branch. Perhaps that's the problem.

**Comment by mcgrodsky** [comment]
I don't think that's the problem - i've been committing before i switch branches. Doesn't it force you?

What's weird to me is that every time i revert to a previous branch, it is still including my Devise Views files in my atom that i only added this morning (which is think are what is breaking Devise)

**Comment by mcgrodsky** [comment]
@RobertAKARobin going back to a suuuuuper old commit still produces the same Devise error not letting the user log-in. Again, it's odd that this error is being carried between versions. Do you think it's worth it to just start over and copy all my files?

Gah sorry for all the comments! Just going to close this and work through :)
