### ISSUE TITLE
Application.yml file not showing up in atom - Heroku deploy fail

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project2#379]
I cannot see my application.yml file in directories in atom but I can see it in terminal. When I deploy to heroku it says my I am missing api keys are these two things related?

**Comment by codedre** [comment]
the keys are referenced in my app.yml

**Comment by andrewsunglaekim** [comment]
yes, if the keys are working locally, and you're using the figaro gem. Follow these instructions for [deployment with figaro](https://github.com/laserlemon/figaro#deployment)

**Comment by joe-gz** [comment]
Thanks for asking this Andre, and answering it Andy! I was just having this problem and almost submitted a new issue

**Comment by andrewsunglaekim** [comment]
Did this work for you guys? can i close this issue?
