### ISSUE TITLE
issue with signup/login and new post

### ISSUE THREAD

**Issue by matiamin** [ga-wdi-exercises/project2#380]
Adam, we worked on it this morning but running into the following issue. 

When I'm on my /entries page, it showing me all the entries. I've a "New Entry" link that should take me to def new in the entries_controller.rb, and then to new.html.erb where I render to the _form.html.erb to create a new entry. But instead, it is directing me to the user show page. 

Secondly, on the /entries page, I've login and signup options. They also go to the user show page. I tried to figure it out but hitting a wall. 

Thanks for your help!

Mati

**Comment by andrewsunglaekim** [comment]
check your `link_to` helper thats directing you to a show page. Make sure the path is `new_entry_path`. If your application routes or redirects somewhere, its because you coded it that way. Trace it back to the link or form that executes that request, and see if the path helpers you've specified are accurate.

Additionally, if you screenshot your error message, and what you did that generates the error message, it can be really helpful. As all I can really give you is advice to fix your potential problem, rather than a solution to your actual bug.

**Comment by matiamin** [comment]
![screen shot 2015-11-18 at 2 37 54 pm](https://cloud.githubusercontent.com/assets/15004248/11252035/1fc67316-8e02-11e5-8731-e01bdc2e49bb.png)

**Comment by matiamin** [comment]
This one for example. This is the edit option, this clearly should open the partial form, and should also show the 'Back' link to all the entries. But instead takes me to the user's show page.

**Comment by andrewsunglaekim** [comment]
Is the problem you're not hitting this view? or its not generating the right stuff? Can you tell me the error message your getting and what you did that got you that error message?

**Comment by matiamin** [comment]
It is not giving me error. it's just not doing what it is suppose to be doing, which is to show me the entry form by rendering the partial _form.html.erb. It simply takes me to the User's show page. 

Basically, when I click 'Edit' it takes me to this page - see the url.

**Comment by matiamin** [comment]
![screen shot 2015-11-18 at 2 57 12 pm](https://cloud.githubusercontent.com/assets/15004248/11252545/beab7808-8e04-11e5-98fc-714bd36afa58.png)

**Comment by matiamin** [comment]
![screen shot 2015-11-18 at 2 57 12 pm](https://cloud.githubusercontent.com/assets/15004248/11252565/d45648a4-8e04-11e5-9a08-225248b9033b.png)

**Comment by matiamin** [comment]
![screen shot 2015-11-18 at 2 58 14 pm](https://cloud.githubusercontent.com/assets/15004248/11252568/d9af57d2-8e04-11e5-82af-5fd42e7b3a7b.png)

**Comment by matiamin** [comment]
In the index file, i specify the path for 'Edit' to edit_entry_path(entry).

```
<td><%= link_to 'Edit', edit_entry_path(entry)%></td>
```

**Comment by matiamin** [comment]
Robin suggested that it might be because I dont have a logout functionality. I've devise for signup/login. Where should I be looking to incorporate the logout functionality ?

**Comment by RobertAKARobin** [comment]
Here's an example:

https://github.com/ga-dc/garnet/blob/master/app/controllers/users_controller.rb#L114

The only really important part is `reset_session`.

**Comment by matiamin** [comment]
Thanks so much Andy and Robin!! Much appreciated!!
