### ISSUE TITLE
using figaro with httparty

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project2#381]
I used figaro with one api without any issues, that api was wrapped in some ruby and I just ran some code in an initializer file.

But without that, I'm unsure how to access the ENV{'key'} or where to place it.

**Comment by andrewsunglaekim** [comment]
All the keys/tokens go in the `config/application.yml` file in a format like this

```
some_key: some_key_with_1232t31_numbers_here
```

to access it in your application:

```
ENV["some_key"]
```

**Comment by solowt** [comment]
Oh, I tried to refer to it with curly braces.

Thanks
