### ISSUE TITLE
image resize on click

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project2#382]
I'm trying to create a click function where the image increases and the padding decreases on click. The button has id "plus" and the image to resize has id "mindfulness-img". Nothing I try seems to work. Here is my CSS.

```
#mindfulness-img{
  width: 100px;
  padding: 100px;
}
```

and my javascript

```
$('#plus').click(function() {
    if($('#mindfulness-img').css('width') == '100px') {
        $('#mindfulness-img').css({
          'width': '150px',
          'padding': '75px'
        });
    } else if($('#mindfulness-img').css('width') == '150px') {
        $('#mindfulness-img').css({
          'width': '200px',
          'padding': '50px'
        });
    } else if($('#mindfulness-img').css('width') == '200px') {
        $('#mindfulness-img').css({
          'width': '250px',
          'padding': '25px'
        });
    } else {
      $('#mindfulness-img').css({
        'width':'300px',
        'padding': '0px'
      });
    }
});
```

**Comment by andrewsunglaekim** [comment]
Hmm, this looks right , are you getting any initial errors in the console?

**Comment by tkentor** [comment]
I thought so too. Nope, nothing in the console. I've been able to get just
the padding or just the width to change, but not both simultaneously.

**Comment by andrewsunglaekim** [comment]
are you in the building today?

**Comment by tkentor** [comment]
yeah I am. at the big desks in the back

**Comment by tkentor** [comment]
so that works now, but I now want when you click the +/- (plus-ind and
minus-ind) next to a given image "#{practice.image}", it changes that image
size.

```
  <button type="button" id="minus-ind">–</button>
  <%= image_tag "#{practice.image}" %>
  <h2><span><%= link_to "#{practice.title}", practice_path(practice)
```

%></span></h2>
    <button type="button" id="plus-ind">+</button>

but I can't put rails into my javascript file, so how do I tell it what
#{practice.image} I want changed?
