### ISSUE TITLE
issue with drop-down menu to filter via cities

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project2#383]
I am trying to make a drop-down menu on my main homepage, so you can see only the concerts taking place in a chosen city (or see them all, if you want). It displays correctly, but I can't seem to translate the sort-by example from sessions onto my project. I'm pretty sure I have it set up wrong in the concerts controller. (Well, I know it's set up wrong in the controller right now, but I had to get rid of some of my attempts in order for the page to display properly so I could work on something else.)

My repo link is https://github.com/rebeccaestes/project2 and my question is about lines 6-16 in the concerts controller, and lines 24-33 in views/concerts/index.

(Also I'm going to the lesson at 3, so you can wait until it's over to come look for me! Thanks.)

**Comment by mattscilipoti** [comment]
Thanks for the helpful info.  I’ll have some suggestions soon.  Have fun in the lesson.

**Comment by RobertAKARobin** [comment]
I'm going to assume this has been resolved. Please re-open if not!
