### ISSUE TITLE
Carrierwave / FOG conversion for upload to S3

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#384]
I've been trying to follow the tutorial on AWS to upload images. Something weird with fog or carrierwave and googling it hasn't helped much. Submitting an issue incase you've seen this before.

<img width="791" alt="screen shot 2015-11-18 at 1 30 00 pm" src="https://cloud.githubusercontent.com/assets/10747860/11252365/db9f822a-8e03-11e5-9931-e967df89ab42.png">

**Comment by tylercrosse** [comment]
When I hit the submit button it places the file in a directory created by either carrierwave or fog public/uploads/tmp Nothing in my bucket though.

``` ruby
<%= form_for [@user, @repo, @commit], as: :new_commit do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>
```

**Comment by RobertAKARobin** [comment]
Sorry for the delay, Tyler. I don't know anything about AWS, and so am pinging the other instructors to see if one of them does.

**Comment by adambray** [comment]
@tylercrosse can we see your application.yml? Please **make sure to censor the secret key values!**

**Comment by adambray** [comment]
Also, can you send `config/initializers/s3.rb`

**Comment by adambray** [comment]
I suspect you have the wrong `region` value. So if you can share what's in your ruby file and what you see in the AWS web console for the region for your bucket

**Comment by adambray** [comment]
PS, if this is the issue I think it is, I encountered the same one in my carrierwave lesson. You can see me struggle with it in the last 5 minutes, and then solve it in the last minute of the [screencast](https://www.youtube.com/watch?v=7QfGvVRhUEs&list=PLyLfZkguidRPxknJm2oBjQ0HE_rxVK22r&index=39)

**Comment by tylercrosse** [comment]
No worries, thanks Robin & Adam! Sorry for not providing more info in this issue. I wasn't sure where to even start. I'm watching the scrrencast now :+1: 

my `application.yml` file

``` yml
aws_access_key_id: "AKIA*******************"
aws_secret_access_key: "O7v40uyYD**********************************"
aws_bucket: "git-preview"
```

and the `config/initializers/s3.rb` file

``` ruby
CarrierWave.configure do |config|
  config.fog_credentials = {
      :provider               => 'AWS',
      :aws_access_key_id      => ENV['aws_access_key_id'],
      :aws_secret_access_key  => ENV['aws_secret_access_key'],
      :region                 => 'us-east-1'
  }
  config.fog_directory  = ENV['aws_bucket']
end
```

**Comment by tylercrosse** [comment]
That's exactly what the problem was. I had changed the Region but I didn't restart my server :grimacing: I'm now at least getting a different error :tada: :smile: !
