### ISSUE TITLE
Another Devise Issue :)

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project2#386]
On my local:host my app is working fine, users can log-in and log-out. After i deployed to Heroku, this function is now broken. 

I have pushed all local changes to heroku master. Any ideas?

This has been an issue all day (Devise breaking, and restarting the server, going to old branch and restarting server again seems to fix it)

**Comment by RobertAKARobin** [comment]
How is the function broken? Do you get an error?

**Comment by mcgrodsky** [comment]
After filling out sign-up form and clicking sign-up the page refreshes and displays this error:

![screen shot 2015-11-18 at 3 42 32 pm](https://cloud.githubusercontent.com/assets/14894858/11253683/0e7c1094-8e0b-11e5-9b86-e427ad741825.png)

**Comment by RobertAKARobin** [comment]
Sorry for the delay, Mia. This is a dumb question, but just to clarify: it doesn't work even when you've filled something out in the email field?
