### ISSUE TITLE
Destroy Error

### ISSUE THREAD

**Issue by qadriyyah119** [ga-wdi-exercises/project2#387]
I have an option to destroy a recipe on my app and when I hit destroy I get the following error.
I can't figure out what I'm missing.

param is missing or the value is empty: recipe

Extracted source (around line #51):
49
50
51
52
53

  private
    def recipe_params
      params.require(:recipe).permit(:title, :serving, :total_time, :prep_time, :cook_time, :photo_url, :level , :ingredients)
    end
end

**Comment by nolds9** [comment]
Can you show what you have in your  `destroy` action in the `recipes_controller.rb`?

**Comment by qadriyyah119** [comment]
def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

  redirect_to recipe_path
  end

**Comment by nolds9** [comment]
Awesome, so a way we can test whats going on is to see if the recipe you deleted, was removed from the list of all recipes.

**Comment by qadriyyah119** [comment]
When I get the error I go back to the recipes page and the recipe I tried to delete is still there.

**Comment by nolds9** [comment]
Interesting, I think it has to do with your redirect. Where are you currently redirecting?
