### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/project2#389]
Hi, I'm using AWS to load some photos. I had everything working earlier, but i just started getting the below error whenever I try to load in a file:
Broken pipe (Errno::EPIPE)

I looks like it is occurring on the .update method after I submit the photo. Any thoughts?

Thank you!!

**Comment by joe-gz** [comment]
if i try to load in a different photo, i get another error:
Excon::Errors::Forbidden in UsersController#update

**Comment by adambray** [comment]
@joe-gz Can you peek at this issue?

The latter error you mentioned sounds like the same one tyler had.

The former issue I believe is related to either:
1. The image is too big
2. transient nextwork issues

**Comment by joe-gz** [comment]
@adambray Thanks! I actually literally just figured it out, and was about to close this, so I'm all good. Sorry about that!
