### ISSUE TITLE
Project2

### ISSUE THREAD

**Issue by mosesadg** [ga-wdi-exercises/project2#39]
https://github.com/mosesadg/Project2

**Comment by jshawl** [comment]
:+1: Excellent project idea! Are you planning on letting users upload their own images or videos? I recommend starting with an image url and keeping user-uploads in the ice box.

**Comment by mosesadg** [comment]
Thanks, Jesse. Yes, will start with allowing users to upload just the URLs.
I am not yet ready to try out file uploads.
