### ISSUE TITLE
issue with filtering concerts

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project2#390]
I am still having problems getting my concerts to be filterable by their venues' cities. My params appear to be {"city"=>"Baltimore, MD"} - I'm putting those on the page so I can see them changing as I select different things. I don't know if I should be including that entire string, or just the city though.

In addition, I'm trying to assign @concerts to the concerts in a particular city. I currently have          @concerts = Concert.venue.where(city: 'Baltimore, MD') and I'm not getting an error, but nothing is happening. @concerts.length returns an error.

My repo link is https://github.com/rebeccaestes/project2 and my problems are on the concerts controller, lines 11 to 23. The form it's referring to is on concerts/index, lines 24 to 33. At the bottom of the index file I've been trying different variables to see what displays.

**Comment by RobertAKARobin** [comment]
To clarify, are you getting an error with the filtering thing? Or is it just that nothing is happening?

With `Concert.venue.where(city: 'Baltimore, MD')`, are you trying to get all the venues belonging to all the concerts in Baltimore? If so, I would do something like:

``` rb
@venues = Venue.all.select{|venue| venue.concert.city == "Baltimore" }
```

That's not an efficient way of doing it, but it'll certainly work. If you have time and bandwidth to find the more efficient way, you'll want to look up the `.join` method.

**Comment by RobertAKARobin** [comment]
I'm going to assume this has been resolved. Please re-open if not!
