### ISSUE TITLE
issue with forms - creating and posting and destroying

### ISSUE THREAD

**Issue by jenpen** [ga-wdi-exercises/project2#391]
Github: https://github.com/jenpen/daily_scrum/tree/corrected_code_1

My forms were working at one point, and I've tried to retrace my steps to that point to see changed. I've also been looking at StackOverflow based on Google results (http://stackoverflow.com/questions/9690818/rails-tutorial-10-2-6-nomethoderror-in-usersedit). I've checked to make sure the params I want to pass in are corrected. I've run rake routes to verify my routes, I've commented stuff out and added it back in. 

I'm confused between the errors I'm getting which indicate there is no route or no method, but since I have both, I could use some help working my way through the error. I've gone back to the pages where I included the path, and played with code there but without a change in the errors. 

![screenshot 2015-11-18 16 44 37](https://cloud.githubusercontent.com/assets/4039780/11255500/844b588a-8e14-11e5-8b8d-03e890994f1c.png)
![screenshot 2015-11-18 16 46 02](https://cloud.githubusercontent.com/assets/4039780/11255499/844a6254-8e14-11e5-8f7b-47296bed5d1f.png)
![screenshot 2015-11-18 16 46 52](https://cloud.githubusercontent.com/assets/4039780/11255502/844e7344-8e14-11e5-9440-26f077b0842d.png)
![screenshot 2015-11-18 16 47 22](https://cloud.githubusercontent.com/assets/4039780/11255501/844b6fb4-8e14-11e5-81fa-2f8e1d88d810.png)

**Comment by RobertAKARobin** [comment]
I believe the problem is that in your `edit` action there's no `@board` defined, whereas you reference `@board` in your `form_for`.

**Comment by jenpen** [comment]
I have it set as a before_action

``` rb
  before_action :set_board, except: [:all, :new, :edit, :update]

  def set_board
    @board = Board.find(params[:board_id])
  end
```
