### ISSUE TITLE
where.not

### ISSUE THREAD

**Issue by alifrumin** [ga-wdi-exercises/project2#393]
I have this set up to display all the users in the system, I would like it to display only users who are not in the club. Memberships is a join table between user_ids and club_ids. 

``` erb
<%= form_for @club.memberships.build do |f| %>
    <%= f.label :Users %>
  <%= f.collection_select(:user_id, User.all, :id, :email) %>
  <%= f.hidden_field(:club_id)%>
    <%= f.submit 'Add Members', class: 'enter' %>
<% end %>
```

I tried User.where.not(@club) but it says it won't accept the @ symbol. It appears one could also do something along these lines User.where("club_id != ? )

**Comment by RobertAKARobin** [comment]
Try `User.where.not(club: @club)`

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to close this. Feel free to re-open!

**Comment by alifrumin** [comment]
I appreciate your dedication to the github issues concept
