### ISSUE TITLE
issue with git

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#394]
I tried _____. 
I am having a db issue, and tried deleting and altering a couple of migration files to address the issue.  Doesn't seem to be working, so I'd like to get back to the devil I know.

git revert abcdefg

I expected _____ to happen._____ 
to roll back to the previous commit. 

happened instead.
I'm not quite sure what happened, so I think this is a good stopping place!

My repo link is ___ 
https://github.com/thomhouseholder/project2-vet

and my question is about lines ___.
I'd like to return to the commit with comment "tested appointment pulldown"

**Comment by RobertAKARobin** [comment]
Can you be more specific about what you mean by "it isn't working"? Are you getting an error?

**Comment by ghost** [comment]
I'm not getting an error, but I'm unsure whether I'm completing the process.

I git revert c123503234, which opens a .git file in atom with instructions to enter comments.  Uncertain what next step is.  The prompt in terminal seems to be waiting for further action.

Success would mean that the deleted files have reappeared, correct?

**Comment by RobertAKARobin** [comment]
Same as whenever Atom opens while you're doing something in Git: just save and close the window! If it's asking for some kind of a message, write a commit message.

**Comment by RobertAKARobin** [comment]
...and yes, that should make the deleted files reappear.

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to close this. Feel free to re-open!

**Comment by ghost** [comment]
Thanks robin. I'm snarled but will pick up in the morning. Tons of help today. Got my money's worth!

On Wed, Nov 18, 2015 at 5:18 PM -0800, "Robert Thomas" notifications@github.com wrote:

It's been a while, so I'm going to close this. Feel free to re-open!
