### ISSUE TITLE
No Method

### ISSUE THREAD

**Issue by ArmaniH** [ga-wdi-exercises/project2#395]
I am getting a No Method error on "color" and, yeah, I am lost as to why. I'm trying to use a JS color picker form with simple form.

![screen shot 2015-11-18 at 5 40 53 pm](https://cloud.githubusercontent.com/assets/13981641/11256813/13f85dc8-8e1c-11e5-88ec-27f1f653f36c.png)
![screen shot 2015-11-18 at 5 41 26 pm](https://cloud.githubusercontent.com/assets/13981641/11256818/1eac0a30-8e1c-11e5-80a5-9f0cc0eeeecb.png)
![screen shot 2015-11-18 at 5 41 53 pm](https://cloud.githubusercontent.com/assets/13981641/11256820/20bf8b30-8e1c-11e5-9008-a38631fad594.png)

**Comment by RobertAKARobin** [comment]
It's because your `responses` table has a `color` column, but your `questions` table does not.

**Comment by ArmaniH** [comment]
For purposes of functionality, would having them both have a color column work? Functionality being users being able to choose a color in response to a question, and having the question and color response be associated with the individual user, PLUS color responses being associated with individual questions?

**Comment by RobertAKARobin** [comment]
Yep, that'd work!

**Comment by ArmaniH** [comment]
Awesome! I'll go work on that and hopefully not break something for at least 15 minutes. Thanks!
