### ISSUE TITLE
Post Route 

### ISSUE THREAD

**Issue by BMahoney08** [ga-wdi-exercises/project2#396]
I am attempting to use a standard form that posts to a nested route but am getting the error:

No route matches [POST] "/schedule/1/shifts".

My form page:

```
<form method='post' action="/schedule/<%= params[:schedule_id] %>/shifts">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type='text' name='name' placeholder="Employee">
  <input type='text' name='hours' placeholder="Hours">
  <input type='submit'>
</form>
```

My routes:

```
  post '/schedules/:id/shifts', to: 'shifts#create'

  resources :users
  resources :schedules do
   resources :shifts, except:[:create]
  end

```

Thanks, guys!

**Comment by RobertAKARobin** [comment]
That's because you have `except: [:create]`. That prevents a POST route from existing for `/schedule/:schedule_id/shifts`.

**Comment by BMahoney08** [comment]
Hi, Robin, I had actually done that because I thought there might be an error with it be created twice, since I was creating it explicitly in the first line. Turned out it was just a pluralization error in my route. Thank you, though!
