### ISSUE TITLE
Submitted responses not displaying

### ISSUE THREAD

**Issue by ArmaniH** [ga-wdi-exercises/project2#397]
When I submit form input it doesn't display on any other page.

![screen shot 2015-11-18 at 8 10 32 pm](https://cloud.githubusercontent.com/assets/13981641/11259615/0300248c-8e31-11e5-9361-dab4d6946164.png)
![screen shot 2015-11-18 at 8 11 21 pm](https://cloud.githubusercontent.com/assets/13981641/11259616/0300ef3e-8e31-11e5-87e6-893875bbb89d.png)
![screen shot 2015-11-18 at 8 13 25 pm](https://cloud.githubusercontent.com/assets/13981641/11259617/03020842-8e31-11e5-889d-8004f930c630.png)

**Comment by RobertAKARobin** [comment]
Check your server log. If it's working, you should see a `COMMIT` SQL query in there. If you see `ROLLBACK`, that means it's trying to save, but is failing a validation. If you don't see either of those, then it may not be reaching your `update` action at all. To make things easier to spot, I recommend adding `puts "*" * 50` to your `update` action to print an easy-to-see line of asterisks in your server log.

**Comment by ArmaniH** [comment]
![screen shot 2015-11-18 at 8 30 01 pm](https://cloud.githubusercontent.com/assets/13981641/11259836/4b91b632-8e33-11e5-954a-ebf5ac16a5cb.png)

I see commit

**Comment by RobertAKARobin** [comment]
You see that `unpermitted parameter: color` line? That means `:color` isn't in your strong params -- the `question_params` at the bottom of your controller.

**Comment by ArmaniH** [comment]
Color is working! Well, the hex color code is. The question still isn't showing up.

**Comment by RobertAKARobin** [comment]
When you say "the question", do you mean `@question` isn't showing up at all, or just a particular field inside it isn't showing up?

**Comment by ArmaniH** [comment]
Whatever Ii input into 'f.text_field :body' isn't showing up.

**Comment by RobertAKARobin** [comment]
Isn't showing up on the page, or in the database, or both?

**Comment by ArmaniH** [comment]
I'll double check when I get off the train, but I'm pretty sure it's both.

**Comment by ArmaniH** [comment]
Yup, when run Questions.all in the rails console, the body value for the question id is 'nill'.

**Comment by RobertAKARobin** [comment]
Try submitting the form, and then take a screenshot of the `Parameters: {"utf8"=>√...` part in your server log, like you included in your screenshot up above. I want to check whether the `body` field is actually being submitted.

**Comment by ArmaniH** [comment]
Got it.

![screen shot 2015-11-19 at 9 30 33 am](https://cloud.githubusercontent.com/assets/13981641/11273267/4add13fe-8ea0-11e5-87ca-2371b46e1b4d.png)

**Comment by RobertAKARobin** [comment]
It should start with `Started POST "/questions" for...`

**Comment by ArmaniH** [comment]
![screen shot 2015-11-19 at 9 34 52 am](https://cloud.githubusercontent.com/assets/13981641/11273352/d4332990-8ea0-11e5-949e-ec44a5e0ced6.png)

**Comment by RobertAKARobin** [comment]
You have two forms on your page:

![forms](https://cloud.githubusercontent.com/assets/13981641/11259617/03020842-8e31-11e5-889d-8004f930c630.png)

Are you sure you're submitting the right one?

**Comment by ArmaniH** [comment]
I had one too many ends. Fixed it. Thank you!

**Comment by RobertAKARobin** [comment]
Woo!
