### ISSUE TITLE
psql problem

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project2#398]
I believe I have a back log of postgresql databases in my system. So many that now when I run my local page, I get this error.

```
 def connect
          @connection = PGconn.connect(@connection_parameters)
```

I've looked a many difference articles and can't find a solution.

**Comment by RobertAKARobin** [comment]
Is that the full text of the error? Could you take a screenshot of it?

**Comment by clarktsc39** [comment]
Additionally, these two errors are at the top of the page

```
PG::ConnectionBad
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by RobertAKARobin** [comment]
Is your blue elephant running?

**Comment by clarktsc39** [comment]
OMG!!! WOW

**Comment by RobertAKARobin** [comment]
:)

**Comment by clarktsc39** [comment]
I thought I was doomed. Fixed it in one second. Thank you!
