### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project2#399]
I'm running db:migrate, and this is showing at the top of my page:

```
ActiveRecord::PendingMigrationError
Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=development
```

This error shows in the extracted source menu on the same page:

```
raise ActiveRecord::PendingMigrationError if ActiveRecord::Migrator.needs_migration?(connection)
```

As it proposes, I ran bin/rake db:migrate RAILS_ENV=development and got this error in the terminal:

```
create_table(:bars)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "bars" already exists
: CREATE TABLE "bars" ("id" serial primary key, "name" character varying, "description" text, "picture" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

**Comment by RobertAKARobin** [comment]
When you get that, I'd recommend dropping, creating, and then migrating.

**Comment by clarktsc39** [comment]
I tried bin/rake db:drop and got this:

```
Couldn't drop ABS_development
```

I've generated and deleted my app quite a few times. Is there a way to just start over completey clean? I feel like when I remove the file I'm loading my app in there are still things left over (maybe saved in the termainal or somewhere else in my machine).

**Comment by RobertAKARobin** [comment]
NO! Don't start over completely clean.

**Comment by RobertAKARobin** [comment]
If you're getting that error, it's almost certainly because you have `rails s` running somewhere, or `psql`.

**Comment by clarktsc39** [comment]
ok. Closed the server and now it dropped. I'll go throug the CMS part of DCMS now.
