### ISSUE TITLE
Project 2 planning HW

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#40]
Comfort: 4.5
Completeness: 5

https://github.com/jkoul/dcfuture/

The front page wireframe is actually a real shell of a real website. See http://dcfuture.com/. A screen cap is also included in the planning/wireframes folder of the linked repo, along with two other hand-drawn wireframes. The other image in the "planning" folder is of a poorly drawn ERD. User stories are included in the repo's main README file.

This is a pre-existing passion project that I started a year ago, but in terms of the actual website, the home page is about as far as I got with it.....until now. I wasn't planning to pick this back up as a WDI project, but then you all went and dropped a user-generated blog framework into my lap last week, and I couldn't resist the opportunity. This plan is ambitious, but keep in mind I'm not starting from scratch conceptually and that should help make the lift easier. Happy to discuss and tighten the scope as needed.

**Comment by jshawl** [comment]
:+1: User stories look good! be sure to have a clear MVP in mind and a schedule for this week! Happy to answer any questions if you have them.

**Comment by jkoul** [comment]
Thanks Jesse! I'll try out the Trello thing today....my MVP is a user-generated blog with full CRUD, without all the bells and whistles (Facebook sharing and whatnot) but looking reasonably like the rest of what I've planned for the broader site.
