### ISSUE TITLE
issue with creating an edit page

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project2#400]
I tried create a link to my "Edit Tasks" page using the instance variable @memberships = Membership.find(params[:membership_id]) to identify the membership. I expected the page to link to the edit page for tasks.  An error showing:

```
Couldn't find Membership with 'id'=#
<Membership::ActiveRecord_Associations_CollectionProxy:0x007ff7a2b2a0b0>
```

 happened instead.
My repo link is https://github.com/murgia/taskager and my question is about lines 15 and 16 in the tasks_controller.

Thank you

**Comment by RobertAKARobin** [comment]
Are you sure `membership_id` is being passed in the URL? Check your `rake routes`.

**Comment by murgia** [comment]
/memberships/:membership_id/tasks/:id/edit(.:format)

I think I might be onto something.  Since I am already iterating through memberships and we are talking about a specific membership for the task, I removed the @memberships instance variable from the task list iteration and I have gotten a new error so I am going to see if I can trouble shoot that really quick.

**Comment by murgia** [comment]
got it

**Comment by murgia** [comment]
Thanks Robin
