### ISSUE TITLE
Issue with migrating my database from sqlite3 to postgresql

### ISSUE THREAD

**Issue by JohnWPark** [ga-wdi-exercises/project2#402]
I tried to host my app on Heroku last night for testing purposes and realized I forgot to create my app with a postgres database and defaulted to sqlite3.  I found some tutorials online on how to fix, including using a gem called 'taps' but I just ended up wasting a lot of time and unable to fix my issues. I even considered punting and starting over from scratch, but figured out how to use access older versions on github instead.

I expected my database to migrate over to postgresql.  The opposite happened instead.
My repo link is https://github.com/JohnWPark/paws.  Some hands-on help is greatly appreciated.

**Comment by RobertAKARobin** [comment]
Hey, John, I'm pretty sure this is an easy fix, just testing it out on my computer first.

**Comment by RobertAKARobin** [comment]
Alright, got it. Here are the steps:
1. Go into `config/database.yml`. Replace the bits ending with `.sqlite3` with the appropriate database name. It should end up something like this:
   
   ```
   default: &default
     adapter: postgresql
     pool: 5
   
   development:
     <<: *default
     database: myapp_development
   
   # Warning: The database defined as "test" will be erased and
   # re-generated from your development database when you run "rake".
   # Do not set this db to the same as development or production.
   test:
     <<: *default
     database: myapp_test
   
   production:
     <<: *default
     database: myapp_production
   ```
2. In `Gemfile`, replace `gem 'sqlite3'` with `gem 'pg'`.
3. `bundle install`
4. `git push heroku master` and continue as usual.

You should be good!

**Comment by JohnWPark** [comment]
Thanks, Robin!
