### ISSUE TITLE
Problems getting my project on Heroku

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/project2#403]
I'm trying to get my project up on Heroku but I'm receiving a "We're sorry but something went wrong" page. I checked Heroku logs in my terminal and this pops gets logged when I try to access the site:

2015-11-19T15:22:54.246236+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=the-food-life.herokuapp.com request_id=abdfa5b3-5f74-496f-8c2b-3cba21bcb8b9 fwd="173.69.171.55" dyno=web.1 connect=0ms service=3ms status=200 bytes=228

Here are the steps I followed to upload to Heroku:
heroku create the-food-life
git push heroku master
heroku run rake db:migrate
heroku open

I also tried a heroku run rake for DCMS but it didn't work.

Here's the link to my GitHub:
https://github.com/jordanbrauner/project-2

**Comment by RobertAKARobin** [comment]
The favicon.ico thing isn't an issue -- it's just an annoying thing that clogs up your server log. I'm going to try this on my own compy.

**Comment by jordanbrauner** [comment]
I'm going to close this as I now see the problems. I just realized I was looking at the wrong log because I forgot to include Rails 12 Factor. There appears to be numerous bugs that need to be fixed in order to get the site working with an empty database. Sorry to waste your time.

**Comment by RobertAKARobin** [comment]
Don't crap on yourself, man!
