### ISSUE TITLE
issue with devise setup

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#404]
I tried _____. 
adding authenticate_user! to vets_controller index action, which works fine.  but of course possible to get around it by entering urls manually (/vets/2, for example).

so I'm trying to configure before_action in vets_controller to require login before any actions can be taken:
before_action :set_vets, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :show, :create, :edit, :update, :destroy]

I expected _____ to happen.
expected to be presented with login/signup page if user is not signed in.

_____ happened instead.
no method errror in vets_controller index action
undefined method set_vets

*\* Have I solved this by defining set_vets as a strong param?  I'm not referring to it in any actions but it seems to restrict site access unless a user session is created.  **

My repo link is ___ 
https://github.com/thomhouseholder/project2-vet

and my question is about lines ___.
vets_controller 3-4 and 62-63
pets_controller 3-4 and 56-57

**Comment by RobertAKARobin** [comment]
`set_vets` needs to be explicitly defined somewhere in your controller; something like:

``` rb
private
def set_vets
  @vet = Vet.find(params[:id])
end
```

**Comment by ghost** [comment]
So adding that definition returns a record not found error in the index, whereas (fancy word!) creating the def but not defining it renders the signup/login page.

It appears that defining set_vets will have a ripple effect in terms of needing to update other actions.  Is this true, and preferable to leaving set_vets undefined?

**Comment by RobertAKARobin** [comment]
If it's going to cause a problem, I would just not have `set_vets` anywhere. I don't see it in your code on GitHub... is that code current?

**Comment by ghost** [comment]
Think I'll leave it out, then.

I forgot to push the devise branch I'm working in on this part.  Just pushed it.

**Comment by RobertAKARobin** [comment]
Sorry, Thom, I've been busy with meetings. How's this going?

**Comment by ghost** [comment]
Think this one is done. Forgot to close it

On Thu, Nov 19, 2015 at 11:39 AM -0800, "Robert Thomas" notifications@github.com wrote:

Sorry, Thom, I've been busy with meetings. How's this going?
