### ISSUE TITLE
routing error

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project2#405]
I manually created a new folder within the views folder called 'Welcome', and welcome has an index.html.erb file with html that I'd like users to see when they go to the root. But I keep getting this Routing Error:

```
Routing Error
No route matches [GET] "/welcome"
```

This is what my routes.rb looks like:

```
Rails.application.routes.draw do

 root :to => redirect('/bars')
  resources :bars
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'
```

**Comment by clarktsc39** [comment]
I know this should be a simple fix, but I've tried several different things -- no avail.

**Comment by amaseda** [comment]
Try using something similar to the example that comes with the `routes.rb` comments: `bars#index`.

Also make sure you only have one active `root` statement.

**Comment by nolds9** [comment]
If you created a view for welcome#index, you are also going to need to create a `welcome_controller.rb` with an index action.  Additionally I think you are going to want to remove the `root :to => redirect('/bars')` line in your `routes.rb`, and replace with a root that maps to your welcome controller's index action
