### ISSUE TITLE
issue with seeds

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project2#406]
For some reason my seeds are iterating 3 times and then displaying all their information. I'm sure the issue is right under my nose, but I've spent too much time on this issue.

here is a screenshot of my localhost3000/works
<img width="1440" alt="screen shot 2015-11-19 at 10 57 11 am" src="https://cloud.githubusercontent.com/assets/13460389/11275593/4e93bcd0-8eac-11e5-9c9c-8ce6d143e5c9.png">

here's a screen shot of my seed file:
<img width="1440" alt="screen shot 2015-11-19 at 10 58 54 am" src="https://cloud.githubusercontent.com/assets/13460389/11275630/8bb69a24-8eac-11e5-82df-31f8f66fba43.png">

**Comment by andrewsunglaekim** [comment]
Every time you run your seeds file, its not deleting the thigns that already exists. So it just created everything on top of what's already there. I would put the following lines of code at the top:

``` ruby
User.destroy_all
Work.destroy_all
```

**Comment by kaustly** [comment]
Thanks Andy! Also, If one of my attributes of my works is a boolean value, how would I represent that in my seeds? I'm trying to make public and private works

**Comment by kaustly** [comment]
It's still showing all the info though:

<img width="1440" alt="screen shot 2015-11-19 at 12 34 36 pm" src="https://cloud.githubusercontent.com/assets/13460389/11278626/f26eeed0-8eb9-11e5-9d23-ed786f382ba5.png">

**Comment by andrewsunglaekim** [comment]
probably something like this: 

``` ruby
Work.new(boolean_attribute: true  #rest of attributes here)
```

**Comment by kaustly** [comment]
thank you! ... aaannd about my seed code showing in the browser?

**Comment by andrewsunglaekim** [comment]
I don't think its your seed file, but I think it is information in your database generated from a seed file. Can you see in if you have `<%= %>` or `<% %>` when you're using the each method in that view?

**Comment by andrewsunglaekim** [comment]
Looks like you probably have an equals sign where you shouldn't

**Comment by kaustly** [comment]
would that be in my show.html.erb?

**Comment by kaustly** [comment]
AH! found it jesus christ
it was in my index
thank you!

**Comment by andrewsunglaekim** [comment]
Great! Going to close this issue now!
