### ISSUE TITLE
Repeating code, partials

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#409]
I have a show page  for Report.  Within that there is a partial for creating and displaying info items and within that a partial for displaying comments for each info item.  I am not sure what happened but now when I create an info item it is creating multiples of them.  For instance, if there are already three info items, now creating one creates 4 of that one and adds another of each info item already created.  My show page is:

``` erb
<h1 class="title"><%= @locations.city %></h1>

<!-- Delete Repoort -->
<div class="destroy">
  <% if can? :destroy, @report %>
  <%= link_to "Delete", report_path(@report), method: :delete, data: {confirm: "Are you sure you want to delete the whole report?"} %>
<% end %>
</div>
<!-- Create Info Item -->

<br><h3 class="subtitle"></h3>
<div id="new">
<% if can? :add_info_item, @report %>
  <%= link_to "Add Topic", new_report_info_item_path(@report) %>
<% end %>
</div>
<%= render @report.info_items %>
```

my info items partial is 

``` erb

<!-- List Info Items -->
<% @report.info_items.each do |info_item| %>

<br><h2><%= info_item.category %></h2>
    <div class="edit">
      <% if can? :update, info_item %>
        <%= link_to "Edit", edit_report_info_item_path(@report,info_item) %>
      <% end %>
    </div>
    <div class = "destroy">
    <% if can? :destroy, info_item %>
      <%= link_to "Delete", report_info_item_path(@report, info_item), method: :delete, data: {confirm: "Are you sure you want to delete this info item?"} %>
    <% end %>
  </div>
  <p><%= info_item.body %></p>

  <%= render info_item.comments %>
  <!-- New Comment -->
  <div class = "links">
    <%= link_to "Comment", new_info_item_comment_path(info_item) %>
  </div>
<% end %>
```

and the comments partial is 

``` erb
<div class = "comments"><strong><%= comment.title %> - <%= comment.user.email %></strong>

<div class = "edit_delete">
  <% if can? :update, comment %>
    <%= link_to "Edit Comment", edit_info_item_comment_path(comment.info_item, comment) %>
  <% end %>

  <% if can? :destroy, comment %>
    <%= link_to "Delete Comment", info_item_comment_path(comment.info_item, comment), method: :delete, data:{confirm: "Are you sure you want to delete this comment?"} %>
  <% end %>
</div>

<p><%= comment.body %></p>
</div>
```

When I read through my code I can't find what would make things get created multiple times.  Before I took the info items out into a partial everything was working alright I think, so I suppose the answer lies somewhere in my info items partial.

**Comment by andrewsunglaekim** [comment]
what does `<%= render @report.info_items %>` do?

**Comment by dan-ator** [comment]
Makes rails look at my info items partial.

**Comment by andrewsunglaekim** [comment]
what does the instance method `info_items` do for the report model?

**Comment by dan-ator** [comment]
what do you mean?

**Comment by andrewsunglaekim** [comment]
are `info_items` a resource in your application. ie is it a model?

**Comment by dan-ator** [comment]
Oh.  `info-items` is a model that is nested within Report.

**Comment by andrewsunglaekim** [comment]
What is your partial files called? can you link your repo?

**Comment by dan-ator** [comment]
partial for info item is `_info_item.html.erb` and comments one is `_comment.html.erb`

**Comment by andrewsunglaekim** [comment]
Because you're looping in your partial, it's repeating way more than it needs to. When you render the partial for info item, it renders that partial for each of the info items. So essentially you loops through all the info items, for each info item.

**Comment by andrewsunglaekim** [comment]
So basically, when i call `<%= render @report.info_items %>`

Its really saying:

``` ruby
<% @report.info_items.each do |info_item| %>
<%= render info_item %>
<% end %>
```

**Comment by andrewsunglaekim** [comment]
I think that may or may not be the heart of the problem why multiple ones are being created

**Comment by dan-ator** [comment]
well, i undid the partial and put the code back in the Report show page and now it works normally.  I am trying to wrap my head around what you are saying, but I still don't really understand.

**Comment by dan-ator** [comment]
do you mean just because the naming of my partial render?
