### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by ebirving** [ga-wdi-exercises/project2#41]
For my Project 2, I am going to build an app for recording erg scores. For the MVP, users will be able to create workouts, submit their scores for different workouts, and see how they stack up against other users. As a stretch goal, I would like to add tools for coaches to manage their rowers' assigned workouts. Scout's honor, ERD and wireframes are imminent.

https://github.com/ebirving/erg-scores

comfort_level: 3
completeness: 2

**Comment by andrewsunglaekim** [comment]
I really like this idea, i'm curious what your domain model will look like!
