### ISSUE TITLE
Showing my database table

### ISSUE THREAD

**Issue by ArmaniH** [ga-wdi-exercises/project2#410]
I've seeded my DB as well as submitted some sample data through the forms I created and when I check the rails console with a Question.all, I can see that the data is being saved in the DB, but I it isn't displaying on my index.html.erb.
![screen shot 2015-11-19 at 1 11 29 pm](https://cloud.githubusercontent.com/assets/13981641/11279546/452d1d72-8ebf-11e5-97b3-bb134fd296a4.png)
![screen shot 2015-11-19 at 9 34 52 am](https://cloud.githubusercontent.com/assets/13981641/11279549/48feb816-8ebf-11e5-8035-2fd1df8d4ea7.png)

**Comment by amaseda** [comment]
Can you include a screenshot of the view rendered in the browser?

Might be because you're placing a `<div>` directly inside a `<table>`. You can, however, put a `<div>` inside `<td>` and `<th>`.

Does changing that fix anything?

**Comment by ArmaniH** [comment]
I tried moving the `<div>` and taking it out completely, to no avail.
[screen shot 2015-11-19 at 1 28 53 pm](https://cloud.githubusercontent.com/assets/13981641/11279970/8af712ac-8ec1-11e5-8265-b5f5ca620730.png)

**Comment by amaseda** [comment]
How about closing that last `</td>` in your 2nd `<tr>?

What does your corresponding `index` controller action look like? Have you run `binding.pry` in there to make sure that `@questions` equals what it should?

**Comment by ArmaniH** [comment]
SIlly me on the `</td>`. Closed it, but to no avail.

![screen shot 2015-11-19 at 2 12 56 pm](https://cloud.githubusercontent.com/assets/13981641/11281221/ad8cf6e6-8ec7-11e5-802c-6455b0462e00.png)

**Comment by RobertAKARobin** [comment]
Are you sure `session[:sort_by]` is what you want it to be? Try putting a `puts sesson[:sort_by]` the line after `authenticate_user!`.

**Comment by ArmaniH** [comment]
I got nothing :-\

**Comment by RobertAKARobin** [comment]
Can you be more specific? What does it `puts` out?

**Comment by ArmaniH** [comment]
Sorry!

Nothing in the console, nothing on the page.

**Comment by RobertAKARobin** [comment]
Well, there's your problem: you're trying to sort by something that doesn't exist. Where are you setting the value of `session[:sort_by]`?

**Comment by ArmaniH** [comment]
![screen shot 2015-11-19 at 3 35 58 pm](https://cloud.githubusercontent.com/assets/13981641/11283554/4e1750e2-8ed3-11e5-9923-e9924a8d7488.png)

**Comment by RobertAKARobin** [comment]
Can you push your code to Github? I'd like to take a look.

**Comment by ArmaniH** [comment]
With pleasure!

https://github.com/ArmaniH/project-2

**Comment by RobertAKARobin** [comment]
I'm finding a different problem, which is that you seem to have done `rails new project2`, instead of `rails new project2 -d postgresql`. Take a look at my response to this issue for instructions on how to fix it:

https://github.com/ga-dc/project2/issues/402

Once that's done, try dropping, creating, migrating, and seeding your database again. I think you'll run into a migration issue which needs to be fixed.

If you have other parts of your app that aren't functioning yet, make sure you get those taken care of before you work on sorting! Deploy to Heroku as soon as you possibly can.

**Comment by ArmaniH** [comment]
I took care of switching to postgresql this afternoon when and have reset my db and reseeded. `rails c` is showing my db has been seeded. Sorting still isn't working, but everything else seem to be working save for sorting. I'm going to try to deploy.
