### ISSUE TITLE
Migrating after Devise

### ISSUE THREAD

**Issue by dttruong** [ga-wdi-exercises/project2#411]
After I install devise, the next step for me was to migrate.  I put in "rake db:migrate" and I am getting errors in my command line.  I looked through my code but cannot figure out what is wrong.

**Comment by nolds9** [comment]
Did you run `rails g devise User` after the devise install. That is the command that generates the migration files.

**Comment by dttruong** [comment]
I did!
gem 'devise'
bundle install
rails generate devise:install
rails generate devise user

I get the migration table, and then I try to rake db:migrate but its giving out errors

**Comment by ebirving** [comment]
Can you take a screenshot of the errors?

**Comment by dttruong** [comment]
![screen shot 2015-11-19 at 1 57 21 pm](https://cloud.githubusercontent.com/assets/14103826/11280779/891fa288-8ec5-11e5-88c4-895bee3ee814.png)

**Comment by andrewsunglaekim** [comment]
make sure you're loading the migrations in the right order. Sounds like you're creating a foreign key on a different table that requires users to already exist. Delete that column from that migration, add another migration that adds the column. Then drop your database and remigrate.

**Comment by andrewsunglaekim** [comment]
Alternatively you could change the timestamp for the migration for the devise to earlier than the other migration. Drop the database and rerun migrations

**Comment by dttruong** [comment]
Got it!  Thanks Andy!
