### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project2#412]
I get this error message on the seemingly last step up pushing to heroku:

[remote rejected] master -> master (pre-receive hook declined)

**Comment by andrewsunglaekim** [comment]
Could you provide some more information or context? Is that the only thing you see when you push to heroku error wise?

**Comment by tkentor** [comment]
Not sure what other context to provide... I did $ heroku create app-name
and then $ git push heroku master. I have the rails_12factor gem installed.
Everything seems to go fine, objects load 100%, bunch of remotes are
installed, and then it doesn't finish and this error displays:

To https://git.heroku.com/ful-mindfulness-app.git

 ! [remote rejected] master -> master (pre-receive hook declined)

error: failed to push some refs to '
https://git.heroku.com/ful-mindfulness-app.git'

**Comment by RobertAKARobin** [comment]
I believe Andy's working on this, so I'm going to close it.
