### ISSUE TITLE
Rails s not running 

### ISSUE THREAD

**Issue by roshanad** [ga-wdi-exercises/project2#415]
Please help!

**Comment by andrewsunglaekim** [comment]
We need a bit more information. What error did you get when you ran rails s? Did you change anything from when it was working to now?

**Comment by roshanad** [comment]
Fixed it! Thanks!

**Comment by mattscilipoti** [comment]
config/database.yml wasn’t formatted correctly.  (She was sitting next to me, while I was supporting another issue).
