### ISSUE TITLE
Multiple associations with user

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project2#416]
I wanted 2 different features that seem to conflict in the models:

1) Users can favorite recipes

``` ruby
class User
has_many :favorites
has_many :recipes, through: :favorites

class Recipe
has_many :favorites
has_many :users, through: :favorites
```

When I had that feature working, I was unable to create recipes associated with a user.

2) Recipes are each associated with a user

``` ruby
class User
has_many :recipes

class Recipe
belongs_to :user
```

---

I seem to only be able to have one feature or the other, but not both. I am assuming this is because I can't have:

``` ruby
class Recipe
belongs_to :user

has_many :favorites
has_many :users, through: :favorites
```

Is there a way I can have these 2 associations working at once?

**Comment by RobertAKARobin** [comment]
Try this:

``` rb
class User
  has_many :favorites
  has_many :recipes
  has_many :favorite_recipes, through: :favorites, source: :recipe
end
class Recipe
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
end
```

The name doesn't matter -- you could do `:users_by_whom_it_was_favorited` or `:wombat` or whatever instead of `:favorite_users`.
