### ISSUE TITLE
issue with installing rails on different laptop

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project2#418]
I had a traumatic experience with my laptop and a cup of coffee this morning (:sob:) so I have to use my old laptop to finish up the project. I'm getting an "extconf failed, exit code 1" error whenever I try to install rails, and can't open the server. Please help??

**Comment by RobertAKARobin** [comment]
Oh no! Have you run Installfest on that computer? https://github.com/ga-dc/installfest

**Comment by RobertAKARobin** [comment]
...and thank goodness for Git!

**Comment by rebeccaestes** [comment]
I'm getting some errors trying to install homebrew - the brew doctor code
doesn't work. I'm upgrading to XCode 7, but I have several ""config"
scripts exist outside your system or Homebrew directories' -type messages
coming up too.

**Comment by RobertAKARobin** [comment]
That's no problem. Go into `installfest.yml` and remove the `homebrew` line. Then, run `rake installfest:start` again.

**Comment by rebeccaestes** [comment]
Andy is getting me a loaner laptop, so I should be OK for now. I'll try
again this weekend while my regular laptop is being fixed.

**Comment by RobertAKARobin** [comment]
:+1:
