### ISSUE TITLE
Jordan Brauner - Project 2 Presentation Video

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/project2#419]
https://youtu.be/f1Cn3tYDmaY

https://github.com/jordanbrauner/project-2

**Comment by RobertAKARobin** [comment]
Awww, snap!

**Comment by jordanbrauner** [comment]
Here's the link to a higher quality version. I'll slack it to you as well in case you aren't notified of this comment.

https://youtu.be/k0vrkt3ZshI
