### ISSUE TITLE
Displaying User Email in Index View

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project2#420]
I have an index of profiles.  For the show page for each, I am able to display the email associated with is through the user.  But I can't get it to show on the index.  The best I can get is the user_id.  In my models, a Profile belongs_to User and User has_one profile.  in my Schema, the profiles table has user_id as a foreign key.  In my show page I have `<%= @profile.user.email %>` and it shows the proper email.  In my index I have 

```
<% @profiles.each do |profile| %>
<ul><%= link_to "#{profile.user_id}", profile_path(profile) %></ul>
<% end %>
```

I have also tried in the index `profile.user_id.email`, `profile.user.email` and `@profiles.user.email` but have not had any luck.  The error message I get is a no method error.

**Comment by dan-ator** [comment]
When I try `profile.user.email`, the error states undefined method for nil:nilclass, and I suppose that is because there are not any profiles yet when that is being done.  But now there are profiles and those profiles do reflect user_id information, so I don't get why it can't also display the email, which is a column in the users table.

**Comment by RobertAKARobin** [comment]
Are you sure the profiles are actually associated with users? I'd recommend using `rails c` to investigate all your profiles and make sure each one has a `user_id`. If any of them don't, it will throw an error.

**Comment by dan-ator** [comment]
A few of them did not, so I deleted all of them and now I get the same error, using `profile.user.email` in the index view.  The error is "undefined method `email' for nil:NilClass".

**Comment by dan-ator** [comment]
Actually, I tried deleting them all but for some reason when none show up on my site, one does show up in the console when I hit Profile.all.  And it has user_id of nil.

**Comment by RobertAKARobin** [comment]
Maybe you did `Profile.new` or something, which would cause one to show up in Profile.all.

In fact, that may be the problem here. Do you have a `Profile.new` or `Profile.build` anywhere on this page?

**Comment by dan-ator** [comment]
I do in the controller for the def new route.

**Comment by dan-ator** [comment]
Ok, problem seems to be solved, after I went in the console and deleted every profile.
