### ISSUE TITLE
redirecting to new path after sign up 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#422]
I'm having trouble forcing devise to go to a new route after someone signs up on the site.  I read online that you have to make a new controller and point to it then it should work. 

I made the controller:

```
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/profiles/:id/edit'
  end

end
```

and I changed "register" to "registrations" on the route 

```
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "registrations" }

  root 'pages#welcome'


get 'about'  => 'pages#about'
get 'help' => 'pages#help'

resources :users
resources :profiles

end
```

**Comment by RobertAKARobin** [comment]
What kind of trouble are you having? Are you getting an error?

**Comment by ghost** [comment]
it will automatically redirect to the root

**Comment by ghost** [comment]
the website says to modify it to 

```
devise_for :users, controllers: { registrations: "registrations" }
```

but devise_for uses path_names so I tried playing around with that and adding the controller, but it gives an error. 

This is the site i was looking at for reference https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-up-(registration)

**Comment by RobertAKARobin** [comment]
Try combining them:

```
devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "registrations" }, controllers: {registrations: "registrations}
```

**Comment by ghost** [comment]
er mer gerd thanks it worked.
