### ISSUE TITLE
categories for posts belonging to a user

### ISSUE THREAD

**Issue by matiamin** [ga-wdi-exercises/project2#424]
I've a category model and a post model. Posts belong to categories - and user has many posts. On the index page for post I can sort posts by category, but I can figure out a way to sort posts based on based on category  that belong to the user on his profile page.

This is what I have in the posts_controller-rb 

```
def index

  if (params[:filter])
    category = Category.find(params[:filter][:category_id])
    @entries = category.entries
  else
    @entries = Entry.all
  end
  @entries = @entries.order('created_at DESC')

  @categories = Category.all
end
```

This works, do I need to do something similar in the user controller?

**Comment by matiamin** [comment]
- I can't figure out ....

**Comment by RobertAKARobin** [comment]
I'm not sure what you mean by "sort posts based on based on category that belong to the user on his profile page". Could you give an example or maybe phrase it a different way?

**Comment by matiamin** [comment]
Thanks, Robin. I was able to filter/limit (not sort :) my posts by categories both in the posts index view page and in the user profile show page. 

Thanks again!
