### ISSUE TITLE
issue with background images on heroku

### ISSUE THREAD

**Issue by ddayporter** [ga-wdi-exercises/project2#439]
I deployed this morning but put off looking into my background images issue.. I'm getting this error in the heroku logs:

```
ActionController::RoutingError (No route matches [GET] "/assets/images/burgle-bros-lineup.png")
```

..the path it's showing is where the file is located.
my scss is set up like this:

```
.show-header {
  background-image: image-url("burgle-bros-lineup.png");
}
```

I tried just url() first but that didn't work. I tried changing the config to 

```
config.serve_static_assets = true
config.assets.compile = true
```

and then ran rake assets:precompile but that didn't work either. I removed the public directory and changed back the config to the original version (assets.compile = false).. 

Maybe too late but if anyone has any thoughts would love to figure this out!

**Comment by RobertAKARobin** [comment]
Did you include the 12factor gem?

Have you tried `rake assets:precompile`?

**Comment by ddayporter** [comment]
Thanks Robin - I actually got it working not too long ago, was just working on my video so forgot to come back and close this.
