### ISSUE TITLE
Issue - Update or Create with hardcoded data

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#442]
Most of the data in the columns in my Commit table is created automatically from an api response. I've been trying to hardcode each 'commit' entry with a image_url but I'm having a lot of trouble. 

Here is what the section in my github.rb model where the commits are created. All of the local @ variables are from the initialize method.

``` ruby
  def get_commits
    response = HTTParty.get("https://api.github.com/repos/#{@nickname}/#{@repo_name}/commits", :headers => @headers)
    response .each do |response|
      Commit.create(
        sha: response["sha"],
        committer_name: response["commit"]["committer"]["name"],
        committer_date: response["commit"]["committer"]["date"],
        committer_avatar_url: response["committer"]["avatar_url"],
        commit_message: response["commit"]["message"],
        url: response["url"],
        html_url: response["html_url"],
        user_id: @user_id,
        repo_id: @repo_id
      )
  end
```

I first tried simply adding a `screenshot: "https://goo.gl/a63WHE"` line into the .create corresponding to  my schema.

I then tried doing below the Commit.create with no luck.

``` ruby
Commit.update(this, screenshot: "https://goo.gl/a63WHE")
```

I also tried putting a after_create callback method in my commit controller but self.screenshot was simply a blank line in the log both before and after the update (maybe because it's nil??) and nothing happened.

``` ruby
class Commit < ActiveRecord::Base
  #...some other junk here...

  after_create :add_screenshot

  def add_screenshot
    @screenshot = "https://goo.gl/a63WHE"
    puts '*' * 50
    puts @screenshot
    puts self
    puts self.screenshot
    self.update(self, screenshot: @screenshot)
    puts self.screenshot
  end
end
```

I also ran a migration to change column names in the schema from 'image' to 'screenshot' and updated everything named 'image' in the entire project because I was afraid calling .image was conflicting with a rails method. At this point I'm out of ideas on what else to try and I'd love some suggestions. Hopefully it's just something silly I'm missing. Thanks!

**Comment by RobertAKARobin** [comment]
I've never seen `Commit.update(this...` before. That looks like some Javascript, which can't be right. Can you tell me what it's supposed to do?

**Comment by tylercrosse** [comment]
You're right that 'this' shouldn't be there. I noticed that sometimes .update needs 2 arguments and sometimes only 1 so I was playing around with adding a second argument trying to refer to the Commit being created.

**Comment by RobertAKARobin** [comment]
Unless `this` is something the Ruby documentation has told you will work, it pretty definitely won't work.

**Comment by RobertAKARobin** [comment]
What does your code look like now? Are you getting errors?

**Comment by tylercrosse** [comment]
I removed the Commit.update in both the github.rb model and in commit.rb model so I wouldn't have to worry about it making my screencast. I'm about to head into GA but I can show you more clearly what's going on when I get there if that's ok?

**Comment by RobertAKARobin** [comment]
Sure!
