### ISSUE TITLE
Seed Data Not Populating

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project2#443]
I entered all the fields in my seed data and they're not rendering in my browser...

**Comment by clarktsc39** [comment]
This is what my one seed looks like:

```
bars = Bar.create([{name: 'Clarendon Ballroom', description: 'Beautiful ballroom-style bar with large patio. Great for large groups', picture:""}])
```

It was rendering before with a link on the "bars" page, but it's no longer rendering.

**Comment by andrewsunglaekim** [comment]
did you run your seed file? `rake db:seed`

**Comment by clarktsc39** [comment]
Yes.

**Comment by clarktsc39** [comment]
The only problem with my seed data loading is that the images don't show
up. The name and description are working well.

**Comment by RobertAKARobin** [comment]
Include the 12factor gem: https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-deployment#the-rails_12factor-gem

Also, run `rake assets:precompile`, then push again.

**Comment by clarktsc39** [comment]
I worked on it with Andre and we fixed it. It was a roundabout way, but it
works.

**Comment by RobertAKARobin** [comment]
Cool!
