### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by M00staff** [ga-wdi-exercises/project2#45]
Keto (low-carb) cook book.  

Users will submit pictures and recipes and be able to comment on them. 

https://github.com/M00staff/Project-2-KetoCookBook 

ERD and wireframes are in the planning folder

**Comment by andrewsunglaekim** [comment]
Love it. Great project idea for your first full stack project. I'm curious what you mean by embedding the photos though.

**Comment by M00staff** [comment]
so im not sure how i would do this but i was hoping there was a way that if someone posts an Imgur link - my code could auto embed it into the post - like the way the reddit enhancement suite works ... Although after looking into this I'm thinking it might not be as possible as i thought.
