### ISSUE TITLE
SGheysens - Project 2 initial hw

### ISSUE THREAD

**Issue by segheysens** [ga-wdi-exercises/project2#46]
Repo: https://github.com/segheysens/bewze_web/tree/working_branch

Check the "prework" folder for all pre-coding work!

**Comment by andrewsunglaekim** [comment]
You may want to look into a 4th model for "deals" or something. The model would be a join table that allows you to view the best deals. I have a sinatra app that's very similar to this app that I wrote for my first project in wdi if you want to have a look. Like the idea! Additionally i saw in your wireframes you might be using maps. Leaflet it a good api for that

**Comment by segheysens** [comment]
Awesome, thanks! Following up on Slack now, just easier to communicate this
type of conversation than emails :D

On Mon, Aug 3, 2015 at 10:08 AM, Andrew Kim notifications@github.com
wrote:

> You may want to look into a 4th model for "deals" or something. The model
> would be a join table that allows you to view the best deals. I have a
> sinatra app that's very similar to this app that I wrote for my first
> project in wdi if you want to have a look. Like the idea! Additionally i
> saw in your wireframes you might be using maps. Leaflet it a good api for
> that
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project2/issues/46#issuecomment-127254333.

## 

Stephen Gheysens

## WDI Student @ *General Assembly *

UMD Economics '14
SEE President
Hinman CEOs
www.sgresu.me
