### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by beckybeauchamp1** [ga-wdi-exercises/project2#475]
http://www.youtube.com/watch?v=Yhs82IStMls

^ Sadly, I tried call morning to get this up and running and the volume still doesn't work

**Comment by andrewsunglaekim** [comment]
Could u be in the room to narrate when we show your video?

**Comment by beckybeauchamp1** [comment]
Yes! I’m sorry I don’t know why I struggled so much with this...

-- 
Becky Beauchamp
Sent with Airmail

On November 20, 2015 at 11:34:39 AM, Andrew Kim (notifications@github.com) wrote:

Could u be in the room to narrate when we show your video?
