### ISSUE TITLE
Project Two

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#49]
Comfort: 4
Completeness: 5

https://github.com/leighvarley/triply

I got a little confused on the erd - please see my notes in the readme.

**Comment by jshawl** [comment]
:+1: Closing to keep issues open for the project - but you will receive feedback shortly!

**Comment by RobertAKARobin** [comment]
Let me know if you want to meet up earlier, Leigh! Wednesday's a long time to wait.

**Comment by ghost** [comment]
Hey Robin,

I would love to meet earlier - thanks!

I am a little confused on my set up. I think I need to use has_many :though based on what I’ve read, but I’ve love to talk through it with you before I spend tons of time going down that route in case it’s not the right approach for my project.

Are you able to meet this morning? And is it ok to set this up through email or should I submit an issue in the repo?

Thanks!
Leigh
