### ISSUE TITLE
issue with _css - two classes for a div___

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#496]
I gave two classes for a div____. I expected  to be able to style using both classes but I'm not seeing changes_____ to happen._____ happened instead.
My repo link is _https://github.com/Bneupane/memory-game.git__ and my question is about lines _17-44__.

also, is this a good practice if I'm looking to use JS and have unique class for each div?

**Comment by RobertAKARobin** [comment]
`.card1` will select an element with `class="card1"`.

`.cards.6` will select an element with `class="cards 6"`.

`.cards` will select an element with `class="cards"`.

Note that `.cards` will ALSO select `class="cards 6"`.
