### ISSUE TITLE
Christine Movius D&Dr

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project2#499]
Linking this now in case I forget over the weekend: https://github.com/cmmovius/dndr

For this project, I am creating a Dungeons and Dragons app (D&Dr) where users can CRUD a campaign, characters, a dungeon master (DM), and adventure chapters.

**Comment by RobertAKARobin** [comment]
@cmmovius Sorry Christine -- could you submit it here instead?

https://github.com/ga-dc/wdi8-project2-gallery

I didn't think about how asking people to submit things as issues on here would make doing tech support with issues complicated!

**Comment by christine-sm** [comment]
No worries. Just posted the issue in the project 2 gallery!
