### ISSUE TITLE
How To on Join Table

### ISSUE THREAD

**Issue by alexbannon** [ga-wdi-exercises/project2#50]
I'm trying to figure out join tables for my project and just want to make sure i'm doing it right. I created the two independent tables for users and events and then ran rails g migration create_join_table :users, :events which gave me this in the empty migration file:

```
create_join_table :, : do |t|
      # t.index [:_id, :_id]
      # t.index [:_id, :_id]
    end
```

Do I just have to do:

```
  t.references :user, index: true, foreign_key: true
  t.references :event, index: true, foreign_key: true
```

Basically I need a primer on join tables.

**Comment by jshawl** [comment]
It depends on how you'll be using this join table. Your "do I have to..." looks right - but try it out! 

See http://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-join-table for reference.

Closing for now but please reopen if you like!

**Comment by alexbannon** [comment]
Yeah I'm still hitting a wall. This is my first time actually using a join table so I'm not sure how it works.

After setting up the migrations, I expected a simple way to create instances and have them reference each other, but I'm not quite sure how to go about that. Typically, when not many to many, I would just write user_id as a parameter of my User.Create(). But I don't really know how to do 

Basically, I have users and events. A user has many events that they belong to and an event has many users that are a part of the event. EventsUsers.create() because it's not a model, it's just a table.

Here's my CreateUsers migration: 
    create_table :users do |t|
      t.string :first_name
      t.string :last_name
      t.string :username
      t.string :email
      t.string :password_digest
    end
and here's my CreateEvents migration:
    create_table :events do |t|
      t.string :title
      t.string :event_content
      t.datetime :created_at
      t.datetime :updated_at
    end
and finally my join table migration:
    create_join_table :users, :events do |t|
      t.references :user, index: true, foreign_key: true
      t.references :event, index: true, foreign_key: true
    end

Blah!
