### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project2#500]
Error mseesge:

Template is missing
Missing template oils/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in: \* "/Users/hh747hh/wdi/projects/oils_remedies/app/views"

Stackoverflow said I need to redirect in the create method of my controller.

this is my controller looks like:

class OilsController < ApplicationController

  def index
    @oils = Oil.all
    render :index
  end
  def create
    @oil  = Oil.create!(oil_params)
    redirect_to "/oils/#{@oil.id}"
  end
  private
  def oil_params
    params.require(:oil).permit(:name, :photo_url, :benefits)
  end
end

Can you tell me why am I getting error?

**Comment by joe-gz** [comment]
Looks like you're missing a view file!

**Comment by RobertAKARobin** [comment]
Figured it out: `oils` was written `olis`. Grooooooaaaan.
