### ISSUE TITLE
Issue trying to add heart buttons

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/project2#502]
Hello! I'm trying to add some heart buttons to my blog posts.

A little background: I now have two controllers, one handling the three pages of my website that are not associated with my database, and the fourth that is handling my data (the blog/forum). I have a feeling that, because I am now attempting to add the heart code to the partial _post file it will not recognize the post has_many :hearts association I established in my ruby code.

Any help would be appreciated!

I've attached a screen shot of the error as well as a link to my github repo. THANKS! :)

https://github.com/Dibbledl01/project2_calledtobecreative

![screen shot 2016-03-22 at 4 49 24 pm](https://cloud.githubusercontent.com/assets/15970793/13967632/a3c09ada-f04e-11e5-95af-6d861ef537b5.png)

**Comment by RobertAKARobin** [comment]
This error means that `@post` is nil. That is: you didn't define `@post` in the `def index` in your PostsController.
