### ISSUE TITLE
Updating teams that display on my index page 

### ISSUE THREAD

**Issue by Ceisen9** [ga-wdi-exercises/project2#505]
https://github.com/Ceisen9/bestbet/blob/master/app/controllers/teams_controller.rb

After redefining  one instance of @teams  to @teamsc in the teams_controller I do not have the ability to sort teams by conference (AFC/NFC). Is there a way to incorporate this newly defined instance into the code on my app/views/teams/index.html.erb file?

**Comment by RobertAKARobin** [comment]
How about something like this:

``` rb
  if @division
    @teams = Team.find_all_with_divison(@division)
  else
    @teams = Team.find_all_with_conference(@conference)
  end
```

**Comment by Ceisen9** [comment]
Now it's telling me that "find_all_with_division" is an undefined method

**Comment by RobertAKARobin** [comment]
Probably because I forgot an `i` :stuck_out_tongue:

**Comment by Ceisen9** [comment]
Ugh I should've caught that. Still not working filtering correctly. No worries though, I can resolve with someone here or tomorrow. Thanks for the help!

**Comment by RobertAKARobin** [comment]
I think using a conditional like this is the direction in which you should be moving. Good luck!

**Comment by nolds9** [comment]
@Ceisen9 it's because `@conference` is not defined! You can just pass in `@division` to `find_all_with_conference` since its coming from `params`.
