### ISSUE TITLE
ActiveRecord_Associations_CollectionProxy Error

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project2#507]
I have a list of tasks that are assigned to a user and I want to be able to click on the tasks to display more info but I'm getting the following error: 

![snip20160323_1](https://cloud.githubusercontent.com/assets/16657107/13985783/0c201cd2-f0d5-11e5-93fa-2f5fc4defba5.png)

Here is the code inside of my index.html:
![snip20160323_2](https://cloud.githubusercontent.com/assets/16657107/13985888/bee0621e-f0d5-11e5-813f-5560a37b8222.png)

**Comment by RobertAKARobin** [comment]
Note that the helper is `user_task_path` -- with `task` being singular. That means the helper expects a single Task to be passed in. You seem to be passing several tasks, as `@tasks`.

**Comment by winishahines** [comment]
I was under the impression that that refers back to my index method in the controller, which I defined as:

![snip20160323_3](https://cloud.githubusercontent.com/assets/16657107/13986057/9bc3948a-f0d6-11e5-9cb4-f153d66be4f5.png)

so if I change @tasks to @task would I need to updated my def index too?

**Comment by RobertAKARobin** [comment]
Don't change your variable names. Variable names almost never do anything -- they're just there to help you remember what things are -- and are not the issue here.

The problem is that `user_task_path` only accepts a single task. So you need to pass a single task into it.

Hint: You have `task.title` in the first argument in `link_to`, but `@tasks` in the second argument. One of these two is correct.

**Comment by winishahines** [comment]
I changed @tasks to @task in the index.html but I'm getting an error saying that the id cannot be found. It looks the user_id can be found so I think this is referring to the task id. When I do a 'rails c' and print all tasks they all have id's assigned. 

![snip20160323_4](https://cloud.githubusercontent.com/assets/16657107/13986956/966ba86a-f0db-11e5-80a7-ae0c8a2ece64.png)

**Comment by RobertAKARobin** [comment]
I think you're thinking that the things you put in the `_path` helpers have to be instance variables. They don't. Try just `task`. This is the `task` you get from `@tasks.each do |task|`.

**Comment by winishahines** [comment]
What?!...I wish I knew that last night. I was following the rails guide example for nested routes. Thanks, it worked!

**Comment by RobertAKARobin** [comment]
I can't really think of any situations in which something _has_ to be an instance variable.
