### ISSUE TITLE
page renders not working

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project2#508]
Backend is almost entirely done. I'm using a gem called simple_calender. I played with it on own time and it seemed to work well for me. The issue I'm having now is it's not rendering the calender.html.erb file on the meetings#index pageI get the  ActionView::MissingTemplate in Meetings#index error

**Comment by RobertAKARobin** [comment]
Can you show a screenshot of the error?

**Comment by Crunchwrap78** [comment]
<img width="1075" alt="screen shot 2016-03-23 at 9 07 01 am" src="https://cloud.githubusercontent.com/assets/14954458/13986069/ab629846-f0d6-11e5-9d1f-6d8ac0dd94f4.png">

Here you go

**Comment by Crunchwrap78** [comment]
The thing is the file is there, so it should render

**Comment by RobertAKARobin** [comment]
Did you include the `_` at the beginning of the file name?

**Comment by Crunchwrap78** [comment]
yup

**Comment by RobertAKARobin** [comment]
Is it `.html.erb`? Is the folder called `meetings`?

**Comment by Crunchwrap78** [comment]
yes

**Comment by RobertAKARobin** [comment]
Can you push your code to Github?

**Comment by RobertAKARobin** [comment]
Push your code to Github, please, and link to it here.

**Comment by Crunchwrap78** [comment]
https://github.com/Crunchwrap78/Beach-Body-Season/tree/Isaac_solution/app/views/meetings

**Comment by RobertAKARobin** [comment]
You misspelled "calendar" in your file name.

**Comment by Crunchwrap78** [comment]
are you sure?

**Comment by RobertAKARobin** [comment]
Yep. It's calend**a**r. Not calend**e**r.

**Comment by Crunchwrap78** [comment]
yup you're right
