### ISSUE TITLE
undefined method `check_completed' for nil:NilClass

### ISSUE THREAD

**Issue by khenry10** [ga-wdi-exercises/project2#509]
Hello,

I'm building a checklist app and have a model method to try and only display tasks that are not complete.  The interaction being you do a task, select the checkbox, click the submit button, render the page without that task there.  However, I'm getting an undefined method for nil:NilClass error.

Controller: 

``` rb
def show
    @list = List.find(params[:id])
    @tasks = @task.check_completed
  end
```

Task Model:

``` rb
def self.check_completed
    todo_tasks = []
    NilClass.instance_methods.include?
    task.each do |task|
      if task.complete == false || task.complete == nil
        todo_tasks << task
      end
    end
    return todo_tasks
  end
```

thank you!

**Comment by RobertAKARobin** [comment]
Please make sure you use 3 backtics, instead of 1. I've fixed it here.

Can you show a screenshot of the error?

**Comment by khenry10** [comment]
Will do, thanks for changing!  
<img width="1020" alt="screen shot 2016-03-23 at 9 34 06 am" src="https://cloud.githubusercontent.com/assets/11139044/13986757/88308d70-f0da-11e5-9958-4258b6ea63ac.png">

**Comment by RobertAKARobin** [comment]
You need to define `@task` somewhere in your `show` method. You're trying to reference a variable that doesn't exist.

**Comment by khenry10** [comment]
Thanks Robin.  After defining the variable (update detailed below), I keep getting "undefined method error".

updated controller:

```
def show
    @list = List.find(params[:id])
    @task = Task.all
    @tasks = @task.check_completed
  end
```

new error:
<img width="1030" alt="screen shot 2016-03-23 at 9 40 13 am" src="https://cloud.githubusercontent.com/assets/11139044/13986972/b241bc3c-f0db-11e5-9540-c8a7e528706f.png">

**Comment by RobertAKARobin** [comment]
Your variables are misnamed now. `Task.all` returns a collection of tasks, so it doesn't make sense to save it into a variable called `task`.

Also, it's individual tasks that have the method `check_completed`. An array of tasks does not.

**Comment by khenry10** [comment]
I see what you're saying.  Fixed variable mismatched.

Should i make the model method able to accept an array of tasks?  In my app, tasks belongs to lists, and this show page is on the list show page -- so I don't have task params available.

**Comment by RobertAKARobin** [comment]
What's the purpose of `check_completed`?

**Comment by khenry10** [comment]
<img width="1126" alt="screen shot 2016-03-23 at 10 18 29 am" src="https://cloud.githubusercontent.com/assets/11139044/13988102/dc66e4c4-f0e0-11e5-8ec5-0c91a220035a.png">
Here is a screenshot of my app.  As you can see some tasks are already checked off, and I want the completed tasks to disappear when you click the "Complete Task" button.  The intent is that the check completed model will do this.

**Comment by RobertAKARobin** [comment]
Gotcha. In that case, yes, I think a class method that accepts an array of tasks is the way to go here.

**Comment by RobertAKARobin** [comment]
It's been a while so I'm going to close this. Feel free to re-open or open a new issue!
