### ISSUE TITLE
NoMethodError in Oils#show

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project2#510]
I created the comment table inside of oils table. When I click #1 oil it shows this error NoMethodError in Oils#show

Here is where the error occured.

``` erb
<h3>Comments</h3>
<% @oil.comments.each do |comment| %>
  <p>
    <strong>Name:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Said:</strong>
    <%= comment.body %>
  </p>
<% end %>


<h3>Add a comment:</h3>
<%= form_for([@oil, @oil.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :said %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
```

**Comment by hh747hh** [comment]
![screen shot 2016-03-23 at 9 42 45 am](https://cloud.githubusercontent.com/assets/16959988/13986964/ab1bce48-f0db-11e5-834f-a1334bf44ec7.png)

**Comment by RobertAKARobin** [comment]
Please remember to put 3 backtics at the beginning and end of code snippets in here. I've fixed it this time.

Check the schema for your Comment model. Does it have a `name` field?

**Comment by hh747hh** [comment]
Ha! It was commenter(not a name)! Works now! Thanks!
