### ISSUE TITLE
Problem with params in controller

### ISSUE THREAD

**Issue by Ceisen9** [ga-wdi-exercises/project2#513]
https://github.com/Ceisen9/bestbet

On my show page for teams I am trying to filter the games a team played by the season that they occured. In my teams controller I am trying to enable and @season variable by passing in the season params. I have noticed through using binding.pry that this is not working the way I want it to and the @season variable is routinely nil, although the terminal is showing that it is registering the click. Please let me know what is wrong with my code on line 25 of my teams_controller.

**Comment by RobertAKARobin** [comment]
I suspect the problem is in where you're getting the value for `@season`. I'd recommend checking the `params` at the beginning of that route to see what's really in there.

Keep in mind that when you're submitting a form for, say, an Artist, the params usually looks like this:

``` rb
{"utf8"=>"✓", "authenticity_token"=>"3T/AqUeCm9Gk5ciZQwhADXRjH3KmWmiKBAL5+99dp8kHk3Fb2LW1m9ja6VW4USzGRLeq6v8Skjj1MUDtlRkcHA==", "artist" => {"name" => "Billy Joel"}}
```

That is, in order to get the Artist's name you'd need `params[:artist][:name]`, not just `params[:name]`.

**Comment by Ceisen9** [comment]
`@season = params[:games][:season]` or `@season = params[:game][:season]`  is throwing  a "undefined method `[]' for nil:NilClass" error.

Note that when I select the season that I want to show my terminal reads:   Parameters: {"games.season"=>"2000", "id"=>"65"}.

**Comment by RobertAKARobin** [comment]
What does the form for `season` look like in your HTML?

**Comment by Ceisen9** [comment]
``` erb
<% @seasons.each do |year| %>
          <a href='/teams/<%=@team.id%>?games.season=<%= year %>'
            type='button'
            class='btn btn-default
            <%= 'btn-primary btn-active' if @season == year %>
            btn-sm'
          ><%= year %></a>
<% end %>
```

**Comment by RobertAKARobin** [comment]
That's because you're putting in in your URL as `games.season` here:

```
<a href='/teams/<%=@team.id%>?games.season=<%= year %>'
```

If instead it was:

```
<a href='/teams/<%=@team.id%>?wombat=<%= year %>'
```

...you would access it with `params[:wombat]`. You can call it whatever you want.

**Comment by Ceisen9** [comment]
Thanks, it's working now!
