### ISSUE TITLE
Last thing hopefully

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project2#514]
<img width="479" alt="screen shot 2016-03-23 at 11 18 27 am" src="https://cloud.githubusercontent.com/assets/14954458/13990005/15313d06-f0e9-11e5-8b91-847577902c51.png">

Last thing

My data in the details isn't showing anything when I try to display it. 

I've checked the database in postgres and it's in there.

This is what the show.html.erb code looks like 

```
<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
<strong>Details</strong> <br>
<%= @meeting.event %>
</p>

<% if current_user %>
<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>
<%end%>
```

the @meeting.event isn't showing up. How can I fix this. Do you think it's because I have event as an attribute?

**Comment by RobertAKARobin** [comment]
Having it as an attribute is fine. Can you copy and paste your Meeting model and migration?

**Comment by Crunchwrap78** [comment]
``` rb
class Meeting < ActiveRecord::Base  
  belongs_to :user
end

```

and

``` rb
class CreateMeetings < ActiveRecord::Migration
  def change
    create_table :meetings do |t|
      t.string :name
      t.text :event
      t.datetime :start_time
      t.timestamps null: false
    end
  end
end

```

**Comment by RobertAKARobin** [comment]
Are you sure it has an event?

**Comment by RobertAKARobin** [comment]
I mean: Are you sure there's text in that event? I'd recommend checking with `rails c`.

**Comment by RobertAKARobin** [comment]
Been a while so I'm going to close this. Feel free to re-open or create a new issue!
