### ISSUE TITLE
Missing required keys [:id]

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project2#516]
I'm struggling with the nested routes today...I'm getting the following error. I tried passing in 'tasks' and ':task_id' also. Can someone point me in the right direction with this one?

![snip20160323_7](https://cloud.githubusercontent.com/assets/16657107/13991614/42bccae6-f0ef-11e5-9b26-f4e16b559e10.png)

![snip20160323_6](https://cloud.githubusercontent.com/assets/16657107/13991747/aa32a2d6-f0ef-11e5-9e6c-a30923e3fef8.png)

**Comment by RobertAKARobin** [comment]
You need to pass in a User as well as a task. Here's how you tell: run `rake routes`. You need one variable for each thing that begins with a colon in the URL. For instance, if you have `/users/:user_id/tasks/:id(.:format)`, then you need to pass in both a User and a Task. If you have `/tasks/:id`, you just need to pass in a Task.

**Comment by RobertAKARobin** [comment]
Been a while so I'm going to close this. Feel free to re-open or create a new issue!
