### ISSUE TITLE
Product Created for All Companies

### ISSUE THREAD

**Issue by yinkaagiri** [ga-wdi-exercises/project2#517]
The app allows Companies to track inventory of the Products they buy.
I am trying to **add a product for a particular company**. However, the **product is created for all company**. I initially forgot to link the database tables  but I fixed it by  added the company_id to the schema using `rails g migration add_company_id_to_products company:references`  

and ran
`rake db:migrate`

it added the following information to the products table

```
t.integer "company_id"
  end

  add_index "products", ["company_id"], name: "index_products_on_company_id", using: :btree

  add_foreign_key "products", "companies"
end
```

Here's the code in my products_controller.rb

```
def create
  @company = Company.find(params[:company_id])
  @product = @company.products.create!(product_params)
  redirect_to company_products_path
end
```

**Comment by RobertAKARobin** [comment]
The backtics need to be on a line by themselves.

Can you link to your project repo? Your products table migration looks very strange.

**Comment by yinkaagiri** [comment]
https://github.com/yinkaagiri/inventory_tracker

**Comment by RobertAKARobin** [comment]
What is "BTree"?

**Comment by yinkaagiri** [comment]
I have no clue

**Comment by RobertAKARobin** [comment]
You have some ENORMOUS images in there. Could you resize them, or host them on Imgur or something? It just takes a while to clone down your repo because they're so big!

**Comment by RobertAKARobin** [comment]
One problem may be that you have SQL in your `seeds.rb` file. The only thing that should be in a `.rb` file is Ruby code. Take a look at this file for an example. (Ignore the `require` on the first line.)

https://github.com/ga-wdi-lessons/sinatra-walkthrough/blob/code/seeds.rb

**Comment by yinkaagiri** [comment]
I deleted the content of the seeds but the problem persists.

**Comment by joe-gz** [comment]
can you post an image of the error you're getting?

**Comment by yinkaagiri** [comment]
I figures it out. It was my Product index controller. Thanks!

**Comment by joe-gz** [comment]
cool! Ima go ahead and close this out then
