### ISSUE TITLE
issue with database query failing

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#52]
I tried to select a photo's title (photo.title) based on its groups.group_title using sql statements in psql. The first select statement below works (correctly returns "Photo2 Title"; the second one fails (ERROR:  column "House" does not exist).  I am puzzled because the search is for a value ("House") in the column groups.group_title.  The database was set up successfullly via rake db:drop...create...migrate...seed.

```
works: SELECT photos.title FROM photos INNER JOIN groups ON photos.id=groups.photo_id WHERE groups.photo_id=2;

fails: SELECT photos.title FROM photos INNER JOIN groups ON photos.id=groups.photo_id WHERE groups.group_title="House";
```

Here are the migrations:

```
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :username
...
    end
  end
end

class CreatePhotos < ActiveRecord::Migration
  def change
    create_table :photos do |t|
      t.references :user, index: true, foreign_key: true
...
      t.string :title
...
  end
end

class CreateGroups < ActiveRecord::Migration
  def change
    create_table :groups do |t|
      t.references :photo, index: true, foreign_key: true
      t.string :group_title
...
    end
  end
end
```

Here are the routes:

```
Rails.application.routes.draw do
  root to: 'photos#index'
  resources :users do
    resources :photos
  end
  # resources :photos
  # resources :users
end
```

**Comment by RobertAKARobin** [comment]
Checking now!

**Comment by RobertAKARobin** [comment]
Try single quotes:

```
SELECT photos.title FROM photos INNER JOIN groups ON photos.id=groups.photo_id WHERE groups.group_title='House';
```

http://stackoverflow.com/questions/5800230/simple-postgresql-statement-column-name-does-not-exists

**Comment by mattscilipoti** [comment]
In most SQL languages double-quotes are reserved for indicating column names: http://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql (don't miss the comments).

**Comment by RobertAKARobin** [comment]
Out of curiosity, why are you doing pure SQL queries? I'm hoping it's just out of curiosity!

**Comment by tomBeach** [comment]
Thanks for the answer and glad it was so simple.  I'm just testing things in psql that I plan to do later in rails.  (Since rails remains a dark vortex, I want to at least make sure my anticipated database functions are working before plunging into the abyss...)

**Comment by RobertAKARobin** [comment]
Sounds good! You're a regular ray of sunshine, Tom.
