### ISSUE TITLE
strange active record stuff being displayed

### ISSUE THREAD

**Issue by khenry10** [ga-wdi-exercises/project2#520]
Created a custom route "/tasks" to display all tasks, "tasks" belong to "list".  I'm using tasks views index.html.erb.

Here is the tasks controller:

```
def index
    @task = Task.where(complete: [nil, false])
  end
```

<img width="1097" alt="screen shot 2016-03-23 at 2 59 51 pm" src="https://cloud.githubusercontent.com/assets/11139044/13997414/55444dba-f108-11e5-8a30-c162b24cc57e.png">

**Comment by RobertAKARobin** [comment]
Can you paste the relevant snippet of ERB from this view?

**Comment by khenry10** [comment]
```
<div class="content">
  <h2> All Tasks <h2>

  <ul>
    <%= @task.each do |task| %>
      <% if task.complete == nil  %>
        <li><%= check_box_tag :complete, 1, task.complete %>
          <%= task.name  %></li>
      <% end %>
    <% end %>
  </ul>
</div>
```

**Comment by RobertAKARobin** [comment]
It's because you have `<%= @task.each`. Lose the `=`

**Comment by RobertAKARobin** [comment]
It's because you have `<%= @task.each`. Lost the `=`

**Comment by khenry10** [comment]
omg.

thank you and closing.
