### ISSUE TITLE
Feeling ID 

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/project2#522]
<img width="855" alt="screen shot 2016-03-23 at 6 03 41 pm" src="https://cloud.githubusercontent.com/assets/15219375/14002339/c7d00a4a-f121-11e5-8012-4378403e4c4c.png">

This one is so hard to explain!!!

**Comment by RobertAKARobin** [comment]
Did you hardcode any IDs, or re-seed your database recently?

**Comment by LaFrish** [comment]
I did not hardcode it and I did reseed but that isnt the issue in this case. 

When generating a new cheerup , it goes to this error. This is upon redirecting to the index page. It shouldn't be using the feeling id to figure out what page it needs to go to :(

**Comment by RobertAKARobin** [comment]
Ahhh. Can you show me the code you're using to redirect?
