### ISSUE TITLE
Heroku issue 

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project2#524]
I'm trying to deploy to Heroku and I think my seed file was causing the issues because my seed files didn't have a user. The error I get in heroku logs is

```
ActionView::Template::Error (undefined method `username' for nil:NilClass):
```

So I deleted my seeds and tried git push heroku master again but it still gives me the same "undefined method 'username'" error in heroku logs.

How should I go about fixing this issue? Thank you

**Comment by RobertAKARobin** [comment]
Have you run DCMS on your computer (not on Heroku) recently? If it's an issue with your seed file, then after running DCMS you should encounter the same error. If we can reproduce this problem on your computer, it'll be easier to fix!
