### ISSUE TITLE
mohamed's project 2

### ISSUE THREAD

**Issue by mohamedrchalal** [ga-wdi-exercises/project2#525]
youtube: https://www.youtube.com/watch?v=8aIG5VFsLcE <low level sound bcuz microphone sucks>
Heroku: https://gamr-mohamed.herokuapp.com/
GitHub: https://github.com/mohamedrchalal/GamR/tree/deploying

**Comment by RobertAKARobin** [comment]
Yo, Mo, this is great, but please submit it to the wdi8-project2-gallery repo instead! https://github.com/ga-wdi-exercises/project2#deliverables
