### ISSUE TITLE
Heroku Deployment Issue.

### ISSUE THREAD

**Issue by arsm800** [ga-wdi-exercises/project2#527]
I have successfully pushed my database to Heroku, but I have since input more data into my seed file.  When I run heroku rake db:seed I receive the following error:

```
rake aborted!
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "locations" violates foreign key constraint "fk_rails_8b0ec5fbbd" on table "plates"
DETAIL:  Key (id)=(10) is still referenced from table "plates".
: DELETE FROM "locations" WHERE "locations"."id" = $1
```

"Georgia" has the location id "10", so I checked my ids and found that there was an incorrect reference in the location_id field for plates from Georgia.  I saved, commited, re-pushed to Heroku, re-migrated, but there error does not go away.  Any suggestions?

**Comment by RobertAKARobin** [comment]
My guess is you have a `Location.destroy_all` in your seed file and a validation on your `Plate` model that keeps Locations from being destroyed if any Plates belong to them (or vice-versa).

**Comment by arsm800** [comment]
Hmm.  I have both `Location.destroy_all` and `Plate.destroy_all` in my seed file.  All my plate model has is the belongs_to relationship: 

```
class Plate < ActiveRecord::Base
  belongs_to :location
end
```

Do I need to add a validation to the Plate model?

**Comment by RobertAKARobin** [comment]
Can you push your code to Github and link to it here?

**Comment by arsm800** [comment]
https://github.com/arsm800/license_plates

**Comment by RobertAKARobin** [comment]
Try switching the order of the two `destroy_all`s.

**Comment by arsm800** [comment]
That seems to have worked.  Thank you for walking me through this issue!
