### ISSUE TITLE
Heroku issues

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/project2#528]
<img width="840" alt="screen shot 2016-03-24 at 1 29 19 pm" src="https://cloud.githubusercontent.com/assets/15219375/14025538/faecbb00-f1c4-11e5-8b10-3d244b73bbc5.png">

**Comment by RobertAKARobin** [comment]
Did you `heroku run rake db:migrate` and `heroku run rake db:seed`?

**Comment by LaFrish** [comment]
Doing it now. Ill keep  you posted.

**Comment by RobertAKARobin** [comment]
If you decide to work on this a bit more in the future, maybe upload your images to Imgur instead of including them in the repo. That way I don't have to download 200MB of images!

**Comment by RobertAKARobin** [comment]
Oh, man, it must also mean pushing to Heroku takes forever. Ah well.

**Comment by LaFrish** [comment]
Got the same error message.

**Comment by LaFrish** [comment]
I also some how deleted rails so now I am installing that...

**Comment by RobertAKARobin** [comment]
Hm. Yeah, that could be problematic.

**Comment by LaFrish** [comment]
ahaha yea.... sorry abt all the files. It was over the limit at first but then I deleted some and made it....

**Comment by RobertAKARobin** [comment]
Woah, there's a limit?

**Comment by RobertAKARobin** [comment]
I ran `heroku logs -t` and got this error:

```
2016-03-24T17:46:54.784335+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': /app/app/controllers/tags_controller.rb:38: syntax error, unexpected ']', expecting ')' (SyntaxError)
2016-03-24T17:46:54.784337+00:00 app[web.1]:     @tags = @feeling.cheerups.where(:feeling_name])
```

Looks like it's just a syntax error in your Tags controller.

**Comment by LaFrish** [comment]
lol Can I just delete it bc I didn't end up using it.

**Comment by RobertAKARobin** [comment]
`¯\_(ツ)_/¯`

**Comment by LaFrish** [comment]
IT WORKED. THANKS!
