### ISSUE TITLE
Issue with form submission.  

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project2#531]
I tried to submit the text from a form. I expected the content to show up, an ActiveModel::ForbiddenAttributesError  appeared instead.
My repo link is https://github.com/JoshNezi/Cheerups.git  and my question is about line 5 in my cheerup controller.

Thanks

**Comment by tylercrosse** [comment]
Met with 1-on-1, passing in params to .new instead of strong_params
