### ISSUE TITLE
WDI 9 Project 2

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/project2#534]
ERDs written, but I don't believe they're complete or correct.  I'm planning on a "happy thoughts" board (the first idea listed) with authors, posts, and comments visible.  My question: should I create a fourth model for Users with login abilities?  Or should this be rolled into Authors?

**Comment by lelandjordon** [comment]
Link!
https://github.com/lelandjordon/motov8

**Comment by tylercrosse** [comment]
Hey Leland, can you please resubmit this on https://github.com/ga-dc/wdi9-project2-gallery instead?Thanks!
