### ISSUE TITLE
Trouble Syncing Local and Remote Repos

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project2#535]
I tried: git push --set-upstream origin master.
I expected: my local repo to push seamlessly up to my remote repo.
Instead, the following appeared in my CLI:

Counting objects: 65, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (65/65), 16.63 KiB | 0 bytes/s, done.
Total 65 (delta 2), reused 0 (delta 0)
Connection to github.com closed by remote host.
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

My repo link is https://github.com/MichaelNahum/TwitterScraper

**Comment by jshawl** [comment]
what is the output of `git remote -v`?

**Comment by MichaelNahum** [comment]
origin  git@github.com:MichaelNahum/TwitterScraper.git (fetch)
origin  git@github.com:MichaelNahum/TwitterScraper.git (push)

**Comment by adambray** [comment]
What happens if you do `git pull origin master`? or `git push -v origin master`

**Comment by MichaelNahum** [comment]
$ git pull origin master  
fatal: Couldn't find remote ref master

git push -v origin master seems to have worked, though. right? it outputted the following:

 git push -v origin master
Pushing to git@github.com:MichaelNahum/TwitterScraper.git
Counting objects: 65, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (65/65), 16.63 KiB | 0 bytes/s, done.
Total 65 (delta 2), reused 0 (delta 0)
To git@github.com:MichaelNahum/TwitterScraper.git
- [new branch]      master -> master
  updating local tracking ref 'refs/remotes/origin/master'
  ~/wdi/2ndProject/TwitterScraper (master)

**Comment by adambray** [comment]
Yeah, that looks right!

**Comment by adambray** [comment]
I suspect it was just more network hiccups.
