### ISSUE TITLE
Cannot find params with ids in 5.8 of Getting Started with RoR.

### ISSUE THREAD

**Issue by mvaden** [ga-wdi-exercises/project2#536]
I'm doing this exercise again to be my project guide. The problem is this error in the browser: 
ActiveRecord::RecordNotFound in ArticlesController#show
Couldn't find Article with 'id'=

Extracted source (around line #7):
`  def show
    @article = Article.find(params[:id])
  end

  def new`

When I perform rake routes, these are my results: 
`Prefix Verb   URI Pattern              Controller#Action
     articles POST   /articles(.:format)      articles#create
 new_articles GET    /articles/new(.:format)  articles#new
edit_articles GET    /articles/edit(.:format) articles#edit
              GET    /articles(.:format)      articles#show
              PATCH  /articles(.:format)      articles#update
              PUT    /articles(.:format)      articles#update
              DELETE /articles(.:format)      articles#destroy
         root GET    /                        welcome#index`

Obviously, the ids are missing from each path containing articles. I'm wondering if anyone could perhaps guide me the second of the exercise where I might have entered something wrong, and specifically how to edit or update to correct this problem. Thank you!

**Comment by jshawl** [comment]
what is the contents of your `config/routes.rb` file?

**Comment by mvaden** [comment]
This was the problem: Resources was singular when it should have been pluralized!
ails.application.routes.draw do
  # get 'welcome/index'
    resources :articles

  root 'welcome#index'
end
