### ISSUE TITLE
Josh's Project 2 -Partials

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project2#537]
I tried to refactor my page and I created partials for my comments. 
I expected to not break my app. My app broke instead. My repo link is  https://github.com/JoshNezi/Cheerups.git  and my question is about line 12 in my show.html.erb file in the cheerups view.

**Comment by jshawl** [comment]
do you get any errors?

**Comment by JoshNezi** [comment]
![screen shot 2016-04-26 at 9 10 02 am](https://cloud.githubusercontent.com/assets/8755620/14819158/c3964d4a-0b8e-11e6-9fcb-ff2741f98c3f.png)

I got this error message.

**Comment by jshawl** [comment]
It looks like there is no file `app/views/comments/_comment.html.erb` - should there be a file there?

**Comment by JoshNezi** [comment]
Thanks, that was the problem.
