### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#538]
I tried to start my local server.
I expected it to run.
The error message pasted below happened instead. (I can't even find a file with 651 lines
I'd link to my repo, but am having some issues with git commands in my terminal  that I need to fix first.

error
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Extracted source (around line #651):
649
650
651
652
653
654

```
# connected server's characteristics.
def connect
```

   (this is line 651)   @connection = PGconn.connect(@connection_parameters)

```
  # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of
  # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision
```

**Comment by RobertAKARobin** [comment]
Blue elephant!

**Comment by andrewsunglaekim** [comment]
start the postgres app

**Comment by andrewsunglaekim** [comment]
is this issue resolved?

**Comment by afm2105** [comment]
yes

**Comment by afm2105** [comment]
Didn't mean to close it. but yes, it's resolved.

**Comment by andrewsunglaekim** [comment]
its cool, you can close your own issues
