### ISSUE TITLE
another error message

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#540]
I tried to start my Ruby server.
I expected it to work.
I got an error message instead (pasted below)
Can't link to a current repo because am having some issue with git in my Terminal.

_Error_

FATAL: database "coaching_facts_development" does not exist

Extracted source (around line #661):
659
660
661
662
663
664

```
    rescue ::PG::Error => error
      if error.message.include?("does not exist")
      (this is the highlighted line)  raise ActiveRecord::NoDatabaseError.new(error.message, error)
      else
        raise
      end
```

**Comment by andrewsunglaekim** [comment]
`$ rake db:create`

**Comment by andrewsunglaekim** [comment]
is this issue resolved?

**Comment by afm2105** [comment]
yes
