### ISSUE TITLE
Attempted Social Login

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project2#541]
I tried to add social authentication to my app. I expected to test it out, but I'm receiving an error in my command line. 
My repo link is https://github.com/JoshNezi/Cheerups.git. 
![44dee332-0bb5-11e6-8609-867417f865ee](https://cloud.githubusercontent.com/assets/8755620/14828680/04cc8a6e-0bb6-11e6-8fb7-8e580334791f.png)

**Comment by andrewsunglaekim** [comment]
What is does social authentication do?

**Comment by andrewsunglaekim** [comment]
What did you run that got you that error?
