### ISSUE TITLE
Sqlite/

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project2#543]
I'm having some trouble with my database. I have a reference to sqlite, but I can't find it.

**Comment by andrewsunglaekim** [comment]
what trouble are you having?

Did you get any errors? what did you try that got you an error?

**Comment by JoshNezi** [comment]
I did a new migration for authentication, but I forgot to add some strings to my table. I updated the table migration and dropped the db and attempted to create a new one, but I could not.
![screen shot 2016-04-26 at 4 47 21 pm](https://cloud.githubusercontent.com/assets/8755620/14833741/b78c500e-0bce-11e6-8712-84855fb64fce.png)

**Comment by tylercrosse** [comment]
Weird formatting in database.yml. Resolved
