### ISSUE TITLE
Create function returning empty space

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project2#544]
The create function in my accounts_controller will instantiate a new account object, but it looks as though it's not saving the user name. 

I entered:

 def create
    @account = Account.create(params[:id])
    redirect_to @account
  end

I expected the account show page to return a nearly blank account page with the username at the top.

Instead, on redirect, it showed only a blank space. The relevant lines are 18-21 of accounts_controller.rb and line 2 of accounts/show.html.erb: https://github.com/MichaelNahum/TwitterScraper

**Comment by tylercrosse** [comment]
Can you push again, currently lines 18-20 are blank in the accounts_controller

**Comment by MichaelNahum** [comment]
Sorry, wrong link: https://github.com/MichaelNahum/TwitterScraper/tree/deploying

**Comment by MichaelNahum** [comment]
nm, we got it. thanks anyway!
