### ISSUE TITLE
no method error

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#545]
1. I am following along with http://guides.rubyonrails.org/getting_started.html#adding-a-second-model to create my project and and created show.html.erb so that I could add names to the database.
2. I expected it to work
   3.I get a no method error instead.
3.  repo link: https://github.com/afm2105/project2

**My code with the error**

<p>
  <strong> Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong> Tidbits:</strong>
 (this is where the error is occurring) <%= @coach.tidbits %>
</p>

**The error message**

NoMethodError in Coaches#show
Showing /Users/antonyscmputer/wdi/project2/coaching_facts/app/views/coaches/show.html.erb where line #8 raised:

undefined method `tidbits' for #Coach:0x007fd3ca03adb8
Extracted source (around line #8):
6
7
8
9

<p>
  <strong> Tidbits:</strong>
  <%= @coach.tidbits %>
</p>

**Comment by tylercrosse** [comment]
Discussed in peson, data was saved as `tidbit` instead of `tidbits`
