### ISSUE TITLE
Issue with nested resource params

### ISSUE THREAD

**Issue by LOHankins** [ga-wdi-exercises/project2#546]
I tried creating a new record for my nested resource (Event_Activity). I expected a new completed record with foreign key from my Event table to happen. This happened instead:

ActionController::ParameterMissing in EventActivitiesController#create
param is missing or the value is empty: eventactivity

Extracted source (around line #53):
51
52
53
54
55

``` rb
  private
  def eventactivity_params
    params.require(:eventactivity).permit(:title, :description, :start_time, :end_time, :city, :state)
  end
end
```

Rails.root: /home/louis/wdi/projects/reunion

Application Trace | Framework Trace | Full Trace
app/controllers/event_activities_controller.rb:53:in `eventactivity_params'
app/controllers/event_activities_controller.rb:14:in`create'
Request

Parameters:

```
{"utf8"=>"✓",
 "authenticity_token"=>"wqaUm9du3xfROJruHqdguLmtvBSR/QHe/ygwk/rb8O5DMcbxe1wF4RizpransTueVV3EN/OIiWm0dCueTqo69g==",
 "event_activity"=>{"title"=>"oib iu",
 "description"=>"luy biu",
 "start_time"=>"noiu",
 "end_time"=>"niou",
 "city"=>"nliuyb",
 "state"=>"nliu"},
 "commit"=>"Create Event activity",
 "event_id"=>"1"}
Toggle session dump
Toggle env dump
Response
```

Headers:

None
x

It says my params are missing or empty yet it shows my params and its data.  
My repo link is https://github.com/LOHankins/Project-2.git and my question is about lines:

app/controllers/event_activities_controller.rb:53:in `eventactivity_params'
app/controllers/event_activities_controller.rb:14:in`create'

**Comment by tylercrosse** [comment]
Try removing `:event_id` from your `eventactivity_params` method

**Comment by LOHankins** [comment]
Removing :event_id from method has no effect.  Same outcome.

**Comment by tylercrosse** [comment]
Try changing `require(:eventactivity)` to `require(:event_activity)` to match the key returned in the params

**Comment by LOHankins** [comment]
I think that fixed it.  I will not be sure until i correct the next thing I have broken!

**Comment by tylercrosse** [comment]
Awesome! 👍
