### ISSUE TITLE
Issue adding file upload feature

### ISSUE THREAD

**Issue by lknapalolo** [ga-wdi-exercises/project2#547]
I followed the steps outlined in this lesson:
https://github.com/ga-wdi-lessons/rails-file-uploads

But I keep getting this error message:

`cannot load such file -- carrierwave`

my routes.rb file:

> Rails.application.routes.draw do
> root "items#index"
> resources :items do
>   require 'carrierwave'
>   get "closet", on: :collection
>   get "wishlist", on: :collection
>   put "add_to_wishlist", on: :member
>   put "add_to_closet", on: :member
>   resources :notes
> end
> end

**Comment by lknapalolo** [comment]
![screen shot 2016-04-27 at 10 24 18 am](https://cloud.githubusercontent.com/assets/17017604/14855535/5f8be448-0c62-11e6-9e6c-b9a7fd1be79c.png)
it alternates between the error above and this error... the gem 'carrierwave' is definitely installed

**Comment by lknapalolo** [comment]
![screen shot 2016-04-27 at 10 26 56 am](https://cloud.githubusercontent.com/assets/17017604/14855590/9692828a-0c62-11e6-95a8-8d354fe60112.png)

**Comment by andrewsunglaekim** [comment]
did you require the dependency in `config/application.rb`?

**Comment by andrewsunglaekim** [comment]
can you link your code for `config/application.rb`?
