### ISSUE TITLE
Users Controller/User Authentication

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project2#548]
I'm trying to add user authentication to my page and I've updated my controller. 
I expected to get a different error after my update, I received an unable to autoload constant. My repo link is https://github.com/JoshNezi/Cheerups.git and my question is about my Users controller. 

![screen shot 2016-04-27 at 1 24 36 pm](https://cloud.githubusercontent.com/assets/8755620/14861657/21ef3cce-0c7c-11e6-8b07-7edbdf0c58b5.png)

**Comment by andrewsunglaekim** [comment]
Can you post the code for your `users_controller.rb`?

**Comment by JoshNezi** [comment]
![screen shot 2016-04-27 at 1 52 24 pm](https://cloud.githubusercontent.com/assets/8755620/14862426/58e51bba-0c7f-11e6-83b7-83ad7d14b609.png)

**Comment by andrewsunglaekim** [comment]
Read the error message, then the read the top line of that file.
