### ISSUE TITLE
Can't load front page; RecordNotFound

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/project2#549]
Link to repo; currently on "deploying" branch:
https://github.com/lelandjordon/motov8/tree/deploying

I did a migration to remove `author` (as a string) and add the integer `author_id` to my Comments.  Dropped, migrated, and re-seeded, but now the index page won't load.  Rails is showing me line 8 of the application controller as the source of the error (here as `return Author.find(session[:author_id])`  )

```
def current_author
    if session[:author_id]
      return Author.find(session[:author_id])
    else
      return nil
    end
```

Rails also is saying it "Couldn't find Author with 'id'=2" despite having dropped the database several times.

**Comment by andrewsunglaekim** [comment]
Sounds like reseeding may have caused you to lose some data. What i would do is clear all your cookies from your browser and restart your server.

**Comment by andrewsunglaekim** [comment]
Then I would look into if you have any author's in your database using the rails console.

**Comment by lelandjordon** [comment]
Got it running by starting another browser.  Not sure if I want to delete all my cookies from my main browser yet; been a long time since I've had to enter passwords.

**Comment by lelandjordon** [comment]
Got a new error when trying to create a post; I'll start another issue if I get stuck.
