### ISSUE TITLE
Can't load show page, help

### ISSUE THREAD

**Issue by zanehmw** [ga-wdi-exercises/project2#550]
I am getting this error when trying to render my show page: 
ArgumentError in Restaurants#show
Showing /Users/zanehwilliams/wdi/projects/project2/app/views/restaurants/show.html.erb where line #23 raised:
First argument in form cannot contain nil or be empty

I think it has to do with my ratings controller. I have defined @restaurant multiple times in various ways in my code but I am not getting what I want. On the show page I created a form for the user to rate a restaurant from 1 to 10. Below is my form and ratings controller. 

FORM: 

``` html
<%= form_for [@restaurant,@rating] do |f| %>
  <%= f.select("rating", "value", (1..10)) %>
  <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
  <%= f.submit "Rate this Restaurant" %>
<% end %>
```

RATINGS CONTROLLER: 

``` ruby
class RatingsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:id])
    @rating = @restaurant.ratings.new :value => params[:value]
    if @rating.save
      redirect_to restaurant_ratings_path(@restaurant), :notice => "Rating successful."
    else
      redirect_to restaurant_ratings_path(@restaurant), :notice => "Something went wrong."
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @rating = Rating.find(params[:id])
    @rating.update_attribute :value, params[:value]
  end

end
```

**Comment by andrewsunglaekim** [comment]
can you post the controller and action that is rendering the view for the form?
