### ISSUE TITLE
can only save data in one input field

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#551]
1. I want to save data in 2 inout fields
2. I can only get one input field to save anything (note: I am following along with http://guides.rubyonrails.org/getting_started.html#adding-a-second-model)
3. I don't know what to try, really - I think i've followed along with the rubyonrails.org website
4. repo link: https://github.com/afm2105/project2

**Comment by andrewsunglaekim** [comment]
what have you tried and what errors are you getting?

**Comment by afm2105** [comment]
I'm not getting any errors with that (I've moved on in the hopes of just being able to fix that soon and am getting errors for different things). As for what I was trying, I just kept going over http://guides.rubyonrails.org/getting_started.html#adding-a-second-model to try to figure out what I screwed up.

**Comment by andrewsunglaekim** [comment]
the amount of input fields for a model is dependent upon how many attributes your model has. Which your schema defines through migrations.

**Comment by afm2105** [comment]
Here's what's in my db file with the timestamp as part of its name, Andy. As you can see, there's something for tidbit.

``` ruby
class CreateCoaches < ActiveRecord::Migration
  def change
    create_table :coaches do |t|
      t.string :name
      t.text :tidbit

      t.timestamps null: false
    end
  end
end
```

**Comment by andrewsunglaekim** [comment]
that looks right, what about the form for coaches?

**Comment by afm2105** [comment]
Embarrassing admission - not sure what file that'd be.

**Comment by andrewsunglaekim** [comment]
i took a look at your source, everything looks ok, i'm gonna head over
