### ISSUE TITLE
add_column in tweets db not passing

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project2#552]
I tried to add a created_at column to my "tweets" table in order to post tweet dates alongside their text.

To do so, I generated a new migration, and ran db:migrate: 

class CreateTweets < ActiveRecord::Migration
  def change
    add_column :tweets, :created_at, :datetime
  end
end

I expected this to change the schema, adding a ":created_at" column. It did not. 

Lines 1-5 of db/migrate/20160427182905_add.rb: https://github.com/MichaelNahum/TwitterScraper/tree/deploying

**Comment by andrewsunglaekim** [comment]
One issue is that the migrations class name is identical to one that already exists, try changing that first and see if the error persists.

**Comment by tylercrosse** [comment]
Try:

``` rb
class AddTimestampsToTweets < ActiveRecord::Migration
  def change
    add_timestamps(:tweets)
  end
end
```
