### ISSUE TITLE
issue with submitting and recovering data used by "collection_check_boxes" in ruby

### ISSUE THREAD

**Issue by 7ruth** [ga-wdi-exercises/project2#553]
I tried searching for how to link the form that uses collection_check_boxes to another submit unsuccessfully and also recovering checked data...but I don't think the checkbox info was submitted, these issues are probably related.. I expected IDs of the checked items to be assigned to an array for User class. User's didnt get this array, happened instead.
My repo link is github.com:7ruth/PadStats.git (martin_terskin_...etc branch) and my question is about lines 19-23 in views/pages/home.erb.

**Comment by tylercrosse** [comment]
I fixed the indentation of that file and added some comments to highlight some of the weird stuff happening. This probably won't fix your current problem but the ending `div`s for map-canvas & map-container should probably be after the form. search_options also needs a closing div

**Comment by tylercrosse** [comment]
``` erb
<% title("Home Page") %>

<div id="search_options"> <!-- There is no end to this div -->

  <div id="map-container">
    <div id="map-canvas"></div>

    <div id="geocoding_fields">

      <%= form_for([@user, @user.locations.build]) do |f| %>
        <%= f.text_field :address, :placeholder => "Enter a location!", class: 'search_box' %>


    </div> <!-- end of map-canvas -->
  </div> <!-- end of map-container -->

        <div class="field">
          <%= collection_check_boxes :user, :placetype_ids, Placetype.all, :id, :category do |b| %>
            <div class="collection-check-box">
              <%= b.check_box %>
              <%= b.label %>
            </div>
          <% end %>
        </div>

        <%= "User ID is :#{@user.id}" %>

      <% end %>
```
