### ISSUE TITLE
Issue creating error for file extension validation (carrierwave)

### ISSUE THREAD

**Issue by lknapalolo** [ga-wdi-exercises/project2#554]
I added this to the en.yml file:

>   errors:
>     messages:
>       extension_white_list_error: "You are not allowed to upload %{extension} files, allowed types: %{allowed_types}"

Instead of my error message in my program it redirects to this rails error message:
![screen shot 2016-04-27 at 4 34 03 pm](https://cloud.githubusercontent.com/assets/17017604/14867307/e4ed3636-0c95-11e6-8836-614e21b7996c.png)

I'm not sure how to add an error validation for carrierwave to my item controller

**Comment by tylercrosse** [comment]
Try having it not in quotes, based off [the docs](https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-validate-uploads-with-active-record)
