### ISSUE TITLE
sorting tweets by timestamp

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project2#555]
i'm trying to sort tweets on my index page by timestamp. currently they are displayed chronologically, but only within a single user. in my view page i tried:

  <%tweetarray = Tweet.all.sort_by { |tweet| tweet[:created_at] } %>
        <%tweetarray.each do |tweet| %>
        <li class="ArabicTweetie">
          <%= tweet.text %>

I expected them to sort, but nothing changed. 

Lines 23-25 of views/accounts/index.html.erb: https://github.com/MichaelNahum/TwitterScraper/tree/deploying

**Comment by andrewsunglaekim** [comment]
sort them in your controller first. checkout [`.order`](http://guides.rubyonrails.org/active_record_querying.html#ordering) in the rails docs

**Comment by MichaelNahum** [comment]
hmm. in the accounts_controller, I tried: 

def index
    @accounts = Account.all
    @tweets   = Tweet.order(:created_at)
  end

and the view page now reads:      <%@tweets.each do |tweet| %>
                                                       <%= tweet.text %>

Still no change, though.
