### ISSUE TITLE
issue with deploying Heroku 

### ISSUE THREAD

**Issue by wesareed** [ga-wdi-exercises/project2#556]
I tried and deployed earlier this week and then added a bunch of user features along with the faker gem. 

I expected to be able to deploy after merging my new features. 

I'm getting this message when running **heroku run rake db:seed**  _NameError: uninitialized constant Faker_ instead.

My repo link is https://github.com/wesareed/bookstore.

**Comment by tylercrosse** [comment]
try moving the `gem 'faker'` out of the development group (to the top of the Gemfile)
