### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#558]
I went to deploy my app on Heroku a little while ago and was following along with https://github.com/ga-wdi-lessons/rails-deployment. I I got up to heroku create (app name). I got "-bash: heroku: command not found" in Terminal. What gives?

**Comment by tylercrosse** [comment]
It sounds like you might need to install the toolbelt https://toolbelt.heroku.com/

**Comment by afm2105** [comment]
Thx Tyler.
