### ISSUE TITLE
another Heroku problem

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/project2#559]
1. I wanted to deploy my app to Heroku
2. I got up to git push heroku master and expected it to work
3. I didn't (I got the error message below)
4. Don't know what to try. Am watching a screencast on Heroku deployment hoping that'll help.

git push heroku master
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by tylercrosse** [comment]
try running `heroku create` again before `git push heroku master`
