### ISSUE TITLE
Heroku Migration issue, Uninitialized Constant

### ISSUE THREAD

**Issue by 7ruth** [ga-wdi-exercises/project2#563]
I tried and deployed earlier this week and then added a bunch of user features along with a join table migration.

I expected to be able to deploy after merging my new features.

I'm getting this message when running heroku run rake db:migrate "NameError: uninitialized constant CreateJoinTablePlaceTypeUser"

My repo link is https://github.com/7ruth/PadStats

**Comment by tylercrosse** [comment]
Why did you comment out the fields in [your most recent migration?](https://github.com/7ruth/PadStats/blob/5e6ce292b1a7ad6deb94676a8fbc751ce25a16b2/db/migrate/20160427195206_create_join_table_placetype_user.rb)

also it did you mean t.references instead of t.index?
