### ISSUE TITLE
add a default value to an existing column

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project2#566]
Thank you for your help I really want to know how to add and change columns - 
I did both:

rails g migration change_column :guests, :send_invitation, :boolean, :default => true

resulted in class ChangeColumn < ActiveRecord::Migration
  def change
  end
end

from the ruby on rails guide - change_column_default :guests, :send_invitation, false

class ChangeColumnDefault < ActiveRecord::Migration
  def change
  end
end

questions -  
what happened to all the parameters? 
since I created the column originally and not the default which one would I use?

if I have to add the code myself would it look like?

change_table :guests do |t|
      t.boolean :send_invitation
      t.boolean :thank_you_sent
end

**Comment by nolds9** [comment]
@marasanders so it looks like you are on the right track, just the code is in the wrong place...

So when you go to change a column, you need to first generate the migration:

```
$ rails g migration ChangeSendInvitationInGuests
```

This will create some migration file, inside that newly created file: 

you should see something like: 

``` ruby
class ChangeSendInvitationInGuests < ActiveRecord::Migration
  def change
        # change_column code goes here
  end
end
```

Inside the `change` method, is where you write the syntax about the updated column, i.e.:

``` ruby
def change
  change_column :guests, :send_invitation, :boolean, default: true
end
```

**Comment by nolds9** [comment]
@marasanders going to go ahead a close this since its been some time...feel free to reopen this
