### ISSUE TITLE
adding new data to seed data files

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project2#567]
I initially had 3 items in my seed data file just to test, but then I added a bunch to it and tried to drop the database and re-populate my db with the new seed data but it's only importing the original data I had put in there.

**Comment by nolds9** [comment]
@jschultz21 what does your `seeds`.rb look like?

**Comment by jschultz21** [comment]
```

require_relative './brewery_data.rb'
require_relative './beer_data.rb'

Brewery.destroy_all
Beer.destroy_all

brewery_data = get_brewery_data()
beer_data =  get_beer_data()

beer_data.each_pair do |brewery_name, beers|
  info = brewery_data[brewery_name]
  current_brewery = Brewery.create!({
    name:       info[:name],
    photo_url:  info[:photo_url],
    logo_img:    info[:logo_img],
    address:    info[:address],
    })

    beers.each do |beer|
      Beer.create!({
        name:       beer[:name],
        style:      beer[:style],
        photo_url:  beer[:photo_url],
        abv:        beer[:abv],
        brewery:    current_brewery
        })
      end
    end
```

**Comment by jschultz21** [comment]
the brewery_data is the file where I added new data

**Comment by nolds9** [comment]
Ok, and you don't get any errors after you run `rake db:seed`? Just not the data you were looking for? 
Can you push your code to github and send the link?

**Comment by jschultz21** [comment]
nope, no errors with rake db:seed. here's the link: https://github.com/jschultz21/dc-brew-circuit

**Comment by jschultz21** [comment]
ok not sure why but once I added new corresponding data to beers the new breweries all showed up.
