### ISSUE TITLE
add a default value to an existing column

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project2#568]
Not sure how to reopen - by adding comment or opening new issue I chose the latter please let me know
thanks.

so you write ChangeSendInvitationInGuests and get back 
class ChangeColumnDefault < ActiveRecord::Migration
  def change
        # change_column code goes here
  end
end
1. why do you have to specify send invitation if it doesn't return that in the migrate file?
2. since its generic can I put a few defaults in or do I have to do a new g migration for each field?

**Comment by jshawl** [comment]
> 1. why do you have to specify send invitation if it doesn't return that in the migrate file?

not sure; but modifying the code seems to work correctly

> 1. since its generic can I put a few defaults in or do I have to do a new g migration for each field?

You can put a few different things in here - try it out!

**Comment by marasanders** [comment]
okay so I did 
rails g migration ChangeSendInitationInGuests
and updated to:
class ChangeSendInitationInGuests < ActiveRecord::Migration
  def change
    change_column :guests, :send_invitation, :boolean, default: true
  end
end

rake db:mirgrate

and got 

Don't know how to build task 'db:mirgrate' (see --tasks)
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`eval'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by jshawl** [comment]
you have a typo. should be `migrate` and not `mirgrate`
