### ISSUE TITLE
Issue with rake db:seed

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project2#569]
https://github.com/adina-pollack/needtacos 

I am getting this error in my terminal when I try to run rake db:seed :

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/adinapollack/wdi/Projects/needtacos/db/seeds.rb:17:in `block in <top (required)>'
/Users/adinapollack/wdi/Projects/needtacos/db/seeds.rb:14:in `each_pair'
/Users/adinapollack/wdi/Projects/needtacos/db/seeds.rb:14:in `<top (required)>'
```

seeds.rb:17 references the :name value of my neighborhoods. When I've been trying to to is create variables for both my neighborhoods and restaurants. I'm not sure if it's been done correctly and why rails is not recognizing them. Do you spot any blatant errors or have some tips on how I should be structuring my seed files?

Thanks!

**Comment by jshawl** [comment]
what is the output of `puts info` re: https://github.com/adina-pollack/needtacos/blob/ee9a4a52fe0867deb9a7a712ac87a5ae6bba6f20/db/seeds.rb#L15

**Comment by jshawl** [comment]
also this will be easier to read if you keep all the seed data in one file

**Comment by adina-pollack** [comment]
I got it to seed by making some tweaks. The restaurant and taco data show up correctly, but not my neighborhood data.

**Comment by jshawl** [comment]
and no errors when you `rake db:seed`?

**Comment by adina-pollack** [comment]
None. But when I go into the console and do Neighborhood.all everything is 'nil'

**Comment by jshawl** [comment]
can you try putting in a binding.pry above this line - https://github.com/adina-pollack/needtacos/blob/ee9a4a52fe0867deb9a7a712ac87a5ae6bba6f20/db/seeds.rb#L16

what is the output of `info`?

**Comment by adina-pollack** [comment]
I actually took that line out already. I pushed my new code to github.

**Comment by jshawl** [comment]
neighborhood data is a hash:

``` rb
neighborhood_data = {
    "logancircle" => {
                    name: "Logan Circle",
                  },
    "dupontcircle" => {
                    name: "Dupont Cirlce",
                  }
    }
```

can you change it to be an array, like:

``` rb
neighborhood_data = [
    {
      name: "Logan Circle",
    },
    {

                    name: "Dupont Cirlce",
                  }
    ]
```

**Comment by jshawl** [comment]
also can you move all your seed data to a single file?

**Comment by adina-pollack** [comment]
So all of it in the seeds.rb file?

**Comment by jshawl** [comment]
yeah!

**Comment by nolds9** [comment]
going to go ahead and close this, feel free to reopen if issue persists
