### ISSUE TITLE
Undefined method `photo_path' in form with no paths

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#57]
I tried using a form partial that takes an @photo object. The error complains of an undefined 'photo_path' method but I don't see such a path on the form or on the edit.html.erb file into which the form embeds.  (The links in the edit file -- e.g. <%= link_to 'Show', user_photo_path(@photo.user, @photo) %> -- seem to work fine.)

_form.html.erb

```
<%= form_for(@photo) do |f| %>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
```

edit.html.erb

```
<h1>Editing Photo</h1>
<%= render 'form' %>
<%= link_to 'Show', user_photo_path(@photo.user, @photo) %> |
<%= link_to 'Back', user_photo_path(@photo.user, @photo) %>
```

**Comment by andrewsunglaekim** [comment]
in your controller for your edit action are you defining what `@photo` is?

**Comment by jshawl** [comment]
Shouldn't it be 

```
<%= form_for user_photo(@user, @photo) %>
```

etc.. since photos belong to users

**Comment by RobertAKARobin** [comment]
Looking back at Adrian's lesson plan:

```
<%= form_for [@artist, @song] do |f| %>
  # form contents
<% end %>
```

https://github.com/ga-dc/pbj/tree/master/05-mvc-with-rails/rails-routes-and-resources

**Comment by mattscilipoti** [comment]
Why the error?  The code for `form_for(@photo)` is attempting to create the url to that photo (@photo) using `photo_path(@photo)`.  You don't have that route, therefore the "undefined 'photo_path' method".  

You could also use the shortcut for for the nested user/photo route `form_for([@user, @photo])`.  I prefer the explicit method that Jesse recommends.

**Comment by RobertAKARobin** [comment]
No right answer: pick one!

**Comment by jshawl** [comment]
closing for now. please reopen if you'd like more assistance with this issue!
