### ISSUE TITLE
Cannot create new Rails App

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#570]
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'

**Comment by nolds9** [comment]
what's the output of `rails -v`

**Comment by dcordz** [comment]
$ rails -v
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'

**Comment by dcordz** [comment]
Pretty sure both ruby and rails are completely screwed up, any advice on how to uninstall/reinstall them?

**Comment by jshawl** [comment]
what is the output of `which ruby`

**Comment by dcordz** [comment]
/Users/david/.rvm/rubies/ruby-2.3.1/bin/ruby

**Comment by jshawl** [comment]
ok that is good. try `gem install rails` ?

**Comment by dcordz** [comment]
$ gem install rails
Successfully installed rails-5.0.0
1 gem installed
~ $ rails -v
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'
~ $

**Comment by jshawl** [comment]
try `gem uninstall rails` - select all versions, then `gem install rails`

**Comment by dcordz** [comment]
~ $ gem uninstall rails
Successfully uninstalled rails-5.0.0
~ $ rails -v
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'
~ $ gem install rails
Fetching: rails-5.0.0.gem (100%)
Successfully installed rails-5.0.0
1 gem installed
~ $ rails -v
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'
~ $

**Comment by dcordz** [comment]
$ cd wdi
~/wdi $ ls
Atokolibe   Lessons     Rakefile    playground.js
Exercises   Projects    installfest.yml wdi
~/wdi $ gem uninstall rails

Select gem to uninstall:
1. rails-4.2.1
2. rails-4.2.4
3. rails-4.2.5
4. rails-4.2.6
5. rails-5.0.0
6. All versions
   > 6
   Successfully uninstalled rails-4.2.1
   Successfully uninstalled rails-4.2.4
   Successfully uninstalled rails-4.2.5
   Successfully uninstalled rails-4.2.6
   Successfully uninstalled rails-5.0.0
   ~/wdi $ gem install rails
   Fetching: rails-5.0.0.gem (100%)
   Successfully installed rails-5.0.0
   1 gem installed
   ~/wdi $ rails -v
   bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
   from bin/rails:8:in`<main>'

**Comment by jshawl** [comment]
wtf

**Comment by dcordz** [comment]
$ cd wdi
~/wdi $ ls
Atokolibe   Lessons     Rakefile    playground.js
Exercises   Projects    installfest.yml wdi
~/wdi $ gem uninstall rails

Select gem to uninstall:
1. rails-4.2.1
2. rails-4.2.4
3. rails-4.2.5
4. rails-4.2.6
5. rails-5.0.0
6. All versions
   > 6
   Successfully uninstalled rails-4.2.1
   Successfully uninstalled rails-4.2.4
   Successfully uninstalled rails-4.2.5
   Successfully uninstalled rails-4.2.6
   Successfully uninstalled rails-5.0.0
   ~/wdi $ gem install rails
   Fetching: rails-5.0.0.gem (100%)
   Successfully installed rails-5.0.0
   1 gem installed
   ~/wdi $ rails -v
   bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
   from bin/rails:8:in`<main>'

**Comment by dcordz** [comment]
Yeah - pretty sure it got all screwed up - tried following some advice I found on stackoverflow... didn't work

**Comment by jshawl** [comment]
what is the output of `rvm requirements`

**Comment by dcordz** [comment]
Not done yet but it's running this:

~ $ rvm requirements
Checking requirements for osx.
Installing requirements for osx.
Updating system....
Installing required custom packages: homebrew/versions.
Installing required packages: gcc49........

**Comment by dcordz** [comment]
~ $ rvm requirements
Checking requirements for osx.
Installing requirements for osx.
Updating system....
Installing required custom packages: homebrew/versions.
Installing required packages: gcc49..........
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
~ $ rails -v
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'
~ $

**Comment by jshawl** [comment]
what about `rails new` <- does that give same error?

**Comment by dcordz** [comment]
Yeah

~ $ rails new
bin/rails:8:in `require': cannot load such file -- rails/commands (LoadError)
    from bin/rails:8:in`<main>'

**Comment by dcordz** [comment]
Looks like I have Time Machine enabled, I'm going to try restoring to this morning

**Comment by dcordz** [comment]
unless you'd advise against that

**Comment by jshawl** [comment]
yeah wanna come meet me? by the student tables

**Comment by jshawl** [comment]
what is the output of `ls -al ~/`
