### ISSUE TITLE
The advantage to setting default values

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project2#571]
there is a lot of chatter out there about the advantages of setting default values like in the tunr
  t.string :email,              null: false, default: ""

is there an advantage to default "" over default " "

what are the advantages and disadvantages - I have an urge to set everything to "" from what I've read.

**Comment by nolds9** [comment]
Um not quite sure I understand the question, do you mean is it considered a best practice to give all your fields a default? I would say no, its not necessary, and not doing it ultimately makes your data model more flexible to work with....in general I would say don't worry about getting everything right at first, just get something. Then you can always go back and changes thing as the need arises

**Comment by marasanders** [comment]
thanks!
just a quick other question - I just did my first git merge I think it went okay - marasanders@Maras-MacBook-Air-2:~/wdi/projects/Wedding-Planner/wedding_planner  $ git merge bootstrap
Updating 2f07cfa..0fe5160
Fast-forward
 .../db/migrate/20160701172228_change_send_initation_in_guests.rb           |  5 +++++
 .../db/migrate/20160701175816_change_thank_you_sent_in_guests.rb           |  5 +++++
 wedding_planner/db/migrate/20160701181321_change_print_in_place_cards.rb   |  5 +++++
 wedding_planner/db/schema.rb                                               | 16 ++++++++--------
 wedding_planner/db/seeds.rb                                                | 20 ++++++++++++++++++++
 wedding_planner/true                                                       |  2 ++
 6 files changed, 45 insertions(+), 8 deletions(-)
 create mode 100644 wedding_planner/db/migrate/20160701172228_change_send_initation_in_guests.rb
 create mode 100644 wedding_planner/db/migrate/20160701175816_change_thank_you_sent_in_guests.rb
 create mode 100644 wedding_planner/db/migrate/20160701181321_change_print_in_place_cards.rb
 create mode 100644 wedding_planner/true

**Comment by nolds9** [comment]
Looks good to me! As long as the output  of `git status` includes "working directory clean"
