### ISSUE TITLE
Can't make new Rails app

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#572]
Time Machined to this morning, back to the original error message:

Also getting this weird bash message before a new line, -bash: __git_ps1: command not found

~/wdi/Projects $ rails new . -d postgresql
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/david/.rvm/gems/ruby-2.3.1", "/Users/david/.rvm/gems/ruby-2.3.1@global"]}) was passed in from bin/rails:3:in `load'
Can't initialize a new Rails application within the directory of another, please change to a non-Rails directory first.
Type 'rails' for help.
-bash: __git_ps1: command not found
~/wdi/Projects $

**Comment by jshawl** [comment]
> Can't initialize a new Rails application within the directory of another, please change to a non-Rails directory first.

**Comment by dcordz** [comment]
cd'ed to home

~/wdi/Projects/did_that $ cd 
-bash: __git_ps1: command not found
~ $ rails new test
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/david/.rvm/gems/ruby-2.3.1", "/Users/david/.rvm/gems/ruby-2.3.1@global"]}) was passed in from bin/rails:3:in `load'
Can't initialize a new Rails application within the directory of another, please change to a non-Rails directory first.
Type 'rails' for help.
-bash: __git_ps1: command not found
~ $

**Comment by jshawl** [comment]
> __git_ps1: command not found

try `brew install bash-completion`

**Comment by dcordz** [comment]
Warning: bash-completion-1.3_1 already installed

**Comment by nolds9** [comment]
fwiw.....rails does not do well if any directory in the path is capitalized, i.e. `Projects`

**Comment by dcordz** [comment]
changed the directory name to projects from Projects, same error

**Comment by jshawl** [comment]
what if you `cd ~ && rails new pizza`

**Comment by dcordz** [comment]
same error

**Comment by jshawl** [comment]
what is the output of `ls -al ~/`

**Comment by dcordz** [comment]
~ $ ls -al ~/
total 624
drwxr-xr-x+ 73 david  staff   2482 Jul  1 14:43 .
drwxr-xr-x   5 root   admin    170 Apr 30 08:48 ..
-r--------   1 david  staff      7 Apr 23 18:47 .CFUserTextEncoding
-rw-r--r--@  1 david  staff  12292 Jul  1 14:24 .DS_Store
drwx------  34 david  staff   1156 Jun 30 09:53 .Trash
-rw-------   1 david  staff      0 May 24 13:58 .Xauthority
drwxr-xr-x  14 david  staff    476 May 25 08:22 .atom
-rw-r--r--   1 david  staff   7884 Jul  1 14:23 .bash_history
-rw-r--r--   1 david  staff   1137 Jun 28 07:15 .bash_profile
drwxr-xr-x  37 david  staff   1258 Jul  1 14:55 .bash_sessions
-rw-r--r--   1 david  staff     68 May 11 14:32 .bashrc
drwxr-xr-x   3 david  staff    102 Jul  1 13:47 .bundle
drwxr-xr-x   3 david  staff    102 May 24 13:57 .cache
drwx------   9 david  staff    306 May 23 14:32 .dropbox
drwxr-xr-x   3 david  staff    102 Jul  1 12:32 .gem
-rw-r--r--   1 david  staff     19 Jul  1 12:43 .gemrc
-rw-r--r--   1 david  staff    135 Jul  1 13:09 .gitconfig
-rw-r--r--   1 david  staff    687 Jul  1 13:09 .gitignore_global
drwxr-xr-x   5 david  staff    170 Jun 22 08:59 .idlerc
-rw-r--r--   1 david  staff    627 Jun 29 17:39 .irb-history
-rw-------   1 david  staff     35 Jun 22 16:36 .lesshst
-rw-r--r--   1 david  staff     68 May 11 14:32 .mkshrc
-rw-r--r--   1 david  staff     21 Jun 13 11:03 .node_repl_history
drwxr-xr-x  20 david  staff    680 Jun 13 12:06 .npm
drwxr-xr-x   3 david  staff    102 Jun 22 13:42 .oracle_jre_usage
-rw-r--r--   1 david  staff    186 May 11 14:32 .profile
-rw-------   1 david  staff  15052 Jun 30 11:41 .pry_history
-rw-------   1 david  staff   5499 Jun 29 17:49 .psql_history
-rw-------   1 david  staff   1024 May 24 13:57 .rnd
drwxr-xr-x  31 david  staff   1054 May 11 14:33 .rvm
drwx------   5 david  staff    170 May 24 15:55 .ssh
drwxr-xr-x   6 david  staff    204 May 11 14:36 .subversion
-rw-------   1 david  staff    651 Jun 12 11:51 .viminfo
-rw-r--r--   1 david  staff    182 Jun 22 08:57 .wget-hsts
-rw-r--r--   1 david  staff    118 May 11 14:32 .zlogin
-rw-r--r--   1 david  staff     68 May 11 14:32 .zshrc
drwx------   3 david  staff    102 Jul  1 14:31 Applications
drwxr-xr-x  18 david  staff    612 Jul  1 14:31 Atokolibe
drwx------@ 26 david  staff    884 Jul  1 14:22 Desktop
drwx------@  8 david  staff    272 Jul  1 14:31 Documents
drwx------@ 33 david  staff   1122 Jul  1 14:31 Downloads
drwx------@ 18 david  staff    612 Jul  1 14:54 Dropbox
drwxr-xr-x   4 david  staff    136 Jul  1 14:35 Fundamentals
-rw-r--r--   1 david  staff   1474 Jul  1 12:18 Gemfile
-rw-r--r--   1 david  staff   3817 Jul  1 12:18 Gemfile.lock
drwxr-xr-x@ 22 david  staff    748 Jul  1 14:35 Github_Profile_Page
drwxr-xr-x   5 david  staff    170 Jul  1 14:35 JS-Projects
drwx------@ 52 david  staff   1768 Jun 29 15:34 Library
drwx------@  3 david  staff    102 Jul  1 14:35 Movies
drwx------@  3 david  staff    102 Jul  1 14:35 Music
drwx------@ 17 david  staff    578 Jul  1 14:35 OneDrive
drwx------@  9 david  staff    306 Jul  1 14:41 Pictures
drwxr-xr-x@  6 david  staff    204 Jul  1 14:43 Pixart_files
drwxr-xr-x@ 10 david  staff    340 Jul  1 14:43 Public
-rw-r--r--   1 david  staff      0 Jul  1 14:43 README.md
-rw-r--r--   1 david  staff    249 Jul  1 12:16 Rakefile
drwxr-xr-x@  5 david  staff    170 Jul  1 14:43 Sites
drwxr-xr-x   3 david  staff    102 Jul  1 14:43 Udacity
drwxr-xr-x   8 david  staff    272 Jul  1 14:31 app
drwxr-xr-x   7 david  staff    238 Jul  1 14:31 bin
drwxr-xr-x  11 david  staff    374 Jul  1 14:31 config
-rw-r--r--   1 david  staff    153 Jul  1 14:31 config.ru
drwxr-xr-x   7 david  staff    238 Jul  1 14:31 db
drwxr-xr-x@ 22 david  staff    748 Jul  1 14:31 dcordz_GH_Page
-rw-r--r--@  1 david  staff  97163 Jul  1 14:35 jquery-1.12.4.min.js
-rw-r--r--@  1 david  staff  86341 Jul  1 14:35 jquery-3.0.0.min.js
drwxr-xr-x   4 david  staff    136 Jul  1 14:35 lib
drwxr-xr-x   4 david  staff    136 Jul  1 14:35 log
drwxr-xr-x   3 david  staff    102 Jul  1 14:43 raspberry_pi_python
drwxr-xr-x   9 david  staff    306 Jul  1 14:43 test
drwxr-xr-x   6 david  staff    204 Jul  1 14:43 tmp
drwxr-xr-x   3 david  staff    102 Jul  1 14:43 vendor
drwxr-xr-x  11 david  staff    374 Jul  1 15:05 wdi
-bash: __git_ps1: command not found
~ $

**Comment by jshawl** [comment]
you intialized a rails app in your home directory. to fix,:

```
cd ~ && rm -rf app bin db lib log test tmp vendor Gemfile Gemfile.lock Rakefile
```

**Comment by dcordz** [comment]
alright that worked

**Comment by dcordz** [comment]
that's pretty much what I did last time

**Comment by jshawl** [comment]
`¯\_(ツ)_/¯`
