### ISSUE TITLE
Problem with Edit Functionality

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project2#576]
When I click on edit for restaurants that were added with my seed file, I get no issues. When I create a new restaurant and try to edit, it appears that the neighborhood id and restaurant id are being switched in my path and I get an error.
 \https://github.com/adina-pollack/needtacos

**Comment by nolds9** [comment]
Got it! you need to switch the variables you are passing to your path helper for edit 
https://github.com/adina-pollack/needtacos/blob/master/app/views/restaurants/show.html.erb#L7

**Comment by nolds9** [comment]
Going to go ahead and close this, feel free to reopen if the problem persists
