### ISSUE TITLE
Passing Project id to new Team on Team create

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#579]
I have a one-to-one relationship between Project and Team and need to pass the Project id to a new Team upon creation. I think I have my models, migrations and strong params set up correctly so I'm struggling to figure out what I'm missing. Currently when a a new Team is created the Project id for the Project the Team is created on is not passed to the new Team. Should I nest the Teams under Projects?

https://github.com/dcordz/did_that

**Comment by nolds9** [comment]
@dcordz The problem is you need to handle the association in the controller when you create a new `team` https://github.com/dcordz/did_that/blob/master/app/controllers/teams_controller.rb#L13

**Comment by nolds9** [comment]
currently you're not associating the new `Team` at all

**Comment by dcordz** [comment]
I'm pretty confused about how to do that, if I try adding @project = Project.find(params[:id]) to the controller I get an id="" error for project id

**Comment by nolds9** [comment]
@dcordz yep in that case I would nest the routes so you have access to the `project_id` from the url

**Comment by dcordz** [comment]
Okay, that's what I was thinking but I'm a little worried about figuring this out later.

The idea is that X+ number of users will submit the same Project and then get placed into a Team. If a Team is nested under a specific Project, I'm a little worried that I won't be able to access those Projects to put Users into a Team. It kind of sounds like a one-to-many relationship but I'm not sure. I guess what I'm really struggling with are my associations, how each model should relate to the other.

Steps:
1 - User A creates a Project
2 - User B creates a Project with the same params as User A
3 - Users A and B are placed into a Team
4 - The Projects that each User created are... 
Merged into one Project? (one-to-one nested relationship between Project and Team?)
Ignored, Team refers to Project created only by User A (one-to-one unnested)
Each referenced by the Team? (one-to-many relationship between Team and Project?)

Any suggestions you have would be great

**Comment by nolds9** [comment]
I think you need a join table between `users` and `projects` and that will be your `team` model

**Comment by nolds9** [comment]
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by nolds9** [comment]
I would limit your scope, just get the many to many relationship working without worrying about the autojoining

**Comment by dcordz** [comment]
Would that allow Users to create Projects without a Team though?

**Comment by amaseda** [comment]
In this case, I would think of every project having a team. So whenever a user creates a project, it is initialized with a one-person team (i.e., a single row on the Teams join table, which has columns for `user_id` and `project_id`). 

As more users are added to a project, you will add more rows to the Teams table with the same `project_id` but different `user_id`s.

**Comment by amaseda** [comment]
So a one-person team would look like this on the Teams table...

| user_id | project_id |
| --- | --- |
| 1 | 5 |

> Where the first user has an id of 3 and the project has an id of 5.

And when that project grows to, say, a team of three users...

| user_id | project_id |
| --- | --- |
| 1 | 5 |
| 2 | 5 |
| 3 | 5 |

> Now the team includes three users, with ids of 1, 2 and 3. They are all working on a project with an id of 5.

**Comment by dcordz** [comment]
Okay I think I see where you're going with this - I'm not sure that's my ultimate goal, since I'd like for users to create their own projects that are only visible to them and would then have their own unique IDs on creation (right?), but I'll try out the join table idea and see how it goes

**Comment by dcordz** [comment]
Could I do something like:
If new project creation params == params of project in the db already, add user to team with project id of what's in the db already?

**Comment by nolds9** [comment]
@dcordz Active Record has a helpful class method `.find_or_create`

**Comment by dcordz** [comment]
okay thanks I'll check it out
