### ISSUE TITLE
Association of Model (Book) in App

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project2#581]
I have not been able to get my associations correct and I am stuck going over creating models…  I’m not sure what to do… I recreated my ORM diagram… I have a one to many relationship with books and authors… I have gone through the tutorial several times… I’m not sure what to google… I’m getting a sense that my solution may involve an additional command in terminal… I would really like to figure out what to do without starting over...

**Comment by nolds9** [comment]
@ayespi happy to talk about this, but hard to help unless you have a specific error

**Comment by nolds9** [comment]
whats not working?

**Comment by ayespi** [comment]
That's an issue... When I get an error, I'll let you know... Thanks!

**Comment by jshawl** [comment]
any updates @ayespi ?

**Comment by amaseda** [comment]
@ayespi Going to close this issue since we haven't heard from you. You can re-open it if you're still dealing with the same issue.
