### ISSUE TITLE
each do is iterating once, even when no instances of the variable exist

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project2#583]
I have the below code on a show page, it's supposed to display every review. When there are no reviews, it's iterating once and displaying empty list items. I tried preceding it with an "if @beer.reviews.length>0", but that didn't work(same result). How can I prevent it from running when there aren't any reviews?

```
<h3> Reviews </h3>
<ul>
  <% @beer.reviews.each do |review| %>
  <li><%= review.created_at%></li>
  <li>author: <%= review.author%></li>
  <li>body: <%= review.body%></li>
  <% end%>
</ul>
```

**Comment by amaseda** [comment]
Does using `empty?` work - http://apidock.com/rails/ActiveRecord/Relation/empty%3F

If not can you link me to your repo and I'll take a look.

**Comment by jschultz21** [comment]
tried this, but same result

```
<% if @beer.reviews.empty?%>
  <% puts "no reviews"%>
  <%else%>
  <% @beer.reviews.each do |review| %>
    <li><%= review.created_at%></li>
    <li>author: <%= review.author%></li>
    <li>body: <%= review.body%></li>
  <% end%>
<% end%>
```

repo link: https://github.com/jschultz21/dc-brew-circuit

**Comment by nolds9** [comment]
@jschultz21 do you still have this issue? It works locally for me if I had the necessary assocation between `beer` and `review` in the `Beer` model https://github.com/jschultz21/dc-brew-circuit/blob/master/app/models/beer.rb#L2

**Comment by jschultz21** [comment]
yup it's still doing it 
![2016-07-05 02 14 20 pm](https://cloud.githubusercontent.com/assets/18902022/16594961/dbb6f3c6-42ba-11e6-951d-bd1cf0dd3f15.png)

**Comment by nolds9** [comment]
I was able to display `No Review Yet` with this logic...

``` ruby
<% if @beer.reviews.any? %>
  <% @beer.reviews.each do |review| %>
    <%= review.author %>
  <% end%>
<% else %>
  <p> No Reviews Yet!</p>
<% end %>
```

**Comment by jschultz21** [comment]
I guess it has something to do with the li's. thanks!

**Comment by jshawl** [comment]
`<%= review.created_at%>` is blank here. do you have `t.timestamps` in a migration file? did you `rake db:migrate:reset`?

**Comment by jschultz21** [comment]
yup, the migration file looks like: 

```
class CreateReviews < ActiveRecord::Migration
  def change
    create_table :reviews do |t|

      t.string :body, null: false
      t.string :author, null: false
      t.integer :beer_id
      t.integer :brewery_id

      t.timestamps null: false
    end
  end
end
```

**Comment by jshawl** [comment]
now im getting - ![](https://dl.dropbox.com/s/eo97yrlvmjgnwnf/Screenshot%202016-07-05%2014.56.52.png?dl=0) which page are you looking at?

**Comment by jschultz21** [comment]
I'm working on the modeling-users branch and on the beer show pages. Just
pushed the updated code for the beer show pages to github.

**Comment by jshawl** [comment]
👍 I am able to see the created at now! can close?

**Comment by amaseda** [comment]
Going to close this one but feel free to re-open if the issue persists!
