### ISSUE TITLE
issue with Creating new post

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/project2#584]
I tried do the New and Create portion I expected it so save to happen. redirects properly but the information is not saved in the db. 
My repo link is https://github.com/AT89/Townboard/tree/master/bulletin and my question is about lines create, new in posts_controller.

Other question, do i need to nest the post since it belongs to a particular post?

**Comment by AT89** [comment]
I added another post to the seed.rb and it won't pickup the additional post for board[0] . Can't figure out whats wrong

**Comment by nolds9** [comment]
@AT89 what do you mean by not saved in the DB?

From the looks of your `posts_controller` I would say yes, you need to build the association between a `board` and a `post` in your `new` and `create` actions

**Comment by nolds9** [comment]
To do this, it might be more feasible to nest your resources, so that you have access to any `board` you are trying to create a `post` on...

**Comment by AT89** [comment]
and can i nest a comment inside of post as well?

**Comment by AT89** [comment]
but even so, why isnt my seed data working? it has the destroys working and the 2nd post of board[0] will not pick up. 

I tried the rails c and it broke as well, I did do the nesting so maybe that is what caused it but even before I did the nesting, 2nd post of board[0] wouldn't seed

**Comment by jshawl** [comment]
rails c is working for me - fresh clone. are you getting an errors?

**Comment by AT89** [comment]
Yes hold on, trying to figure out how to fix destroy since I nested :(

**Comment by AT89** [comment]
the error is probably because I nested things

```
NameError: undefined local variable or method `post' for main:Object
    from (irb):1
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/anhtice/wdi/projects/project2_redux/bulletin/bin/rails:9:in `<top (required)>'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
    from /Users/anhtice/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /Users/anhtice/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/anhtice/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

FYI the 2nd post isnt on the current repo's seed.db, did you copy another one in?

**Comment by jshawl** [comment]
no it's ok. you're trying to access local variable - but it is not defined in rails c, only in the seeds file.

Try instead: `Post.find` or `Post.first`...

**Comment by AT89** [comment]
Ah ok that works (i swear i did post.all last night and it worked).

however, it is still missing my 2nd post in board[0] that I seeded with rake db:seed.

**Comment by jshawl** [comment]
`Board.first.posts` <- is it in there?

**Comment by AT89** [comment]
Nope

**Comment by AT89** [comment]
prior to the nesting, it wasnt working but since i nested things, do i have to drop the db and reload it again? I only change the nesting in routes.rb and made some changes to the views to get it slightly working

**Comment by jshawl** [comment]
it is! ![](https://dl.dropbox.com/s/ojija2ie7kfgzn5/Screenshot%202016-07-05%2014.51.39.png?dl=0)

**Comment by AT89** [comment]
waitup, its in there now...

**Comment by AT89** [comment]
yea i dont know what happened but its working properly now :)

now to redo all the nested associations..

thanks

**Comment by jshawl** [comment]
👍
