### ISSUE TITLE
Cannot create form to add text fields to a column that is an array

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project2#585]
I need text fields in my form_for to add values to an ingredients array column when creating or editing a dish. I've tried a few different ways; here are the most recent two:

```
<%= f.label :ingredients %>
<%= f.text_field :ingredients, multiple:true, as: :array %>
<%= f.text_field :ingredients, multiple:true %>
```

**Comment by jshawl** [comment]
oo may need to create custom ones not attached to `f`. Try `<%= text_field_tag %>`
http://apidock.com/rails/ActionView/Helpers/FormTagHelper/text_field_tag

**Comment by wombatdev** [comment]
So now I'm using a couple different setups--one for ingredients and one for categories and tags.
Ingredients:

```
  <%= f.label :ingredients %>
  <% 15.times do |n| %>
    <% if @dish.ingredients[n] %>
        <input name="dish[ingredients][]" type="text" value="<%=@dish.ingredients[n]%>"/>
    <% else %>
        <input name="dish[ingredients][]" type="text"/>
    <% end %>
  <% end %>
```

Categories/Tags:

```
  <%= f.label :tags %>
  <%= f.text_field :tags, multiple:true %>
  <%= f.text_field :tags, multiple:true %>
  <%= f.text_field :tags, multiple:true %>
```

The ingredients method displays the current values appropriately. However, nothing saves from the form. I can see from the Rails server output that I'm storing the parameters correctly:
`"ingredients"=>["mozzarella", "parmesan", "olive oil", "", "", "", "", "", "", "", "", "", "", "", ""], "tags"=>["family", "", ""], "category"=>["Italian", "", ""]`

But there is an additional message: `Unpermitted parameters: ingredients, tags, category`

Those params are included in my dish_params method. Any ideas?

**Comment by jshawl** [comment]
hmm - I would use `binding.pry` and check to see what `params` looks like before and after your `dish_params` method

**Comment by wombatdev** [comment]
Resolved -- I needed to change my dish_params so `:ingredients, :tags` are `{:ingredients => []}, {:tags => []}`.

A follow up: now my form is accepting all of the blank values from the unused text fields. I found something saying I should be using `<% if @dish.ingredients.blank? %>` (or something similar). My question is where do I put that? In the form html.erb? In the controller? Class?

**Comment by jshawl** [comment]
oo I like before_save in the model. You filter out the empty inputs with reject

**Comment by wombatdev** [comment]
Thanks for the feedback. Hopefully last question--I built this out:

```
before_save :remove_blanks_from_arrays

    private
    def remove_blanks_from_arrays
        self.ingredients.each do |n|
            if self.ingredients[n].blank?
                self.ingredients.delete_at(n)
            end
        end
```

I'm getting an error for `no implicit conversion of String into Integer` on the `if self.ingredients[n].blank?` line. I've confirmed in the Rails console that the if-blank and delete_at lines work if i specify a specific dish. Should I not be calling `self` here?

**Comment by jshawl** [comment]
`if n.blank?` right?

**Comment by wombatdev** [comment]
Ahhhh, `DUH`

Settled on this because it was simpler:

```
private
    def remove_blanks_from_arrays
        self.ingredients.delete_if {|ingredient| ingredient == ""}
        self.category.delete_if {|category| category == ""}
        self.tags.delete_if {|tag| tag == ""}
    end
```

**Comment by jshawl** [comment]
could simplify to

``` rb
def remove_blanks_from_arrays
        self.ingredients.delete_if &:empty?
        self.category.delete_if &:empty?
        self.tags.delete_if &:empty?
end
```

**Comment by amaseda** [comment]
Closing but feel free to open if you have more questions about this issue.
