### ISSUE TITLE
issue with pushing changes with git

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/project2#586]
My git push is rejected due to current branch being behind

I tried git pull --rebase and that did no good. I'm slightly scared to lose all my local data. Kind of frustrated because this happened out of no where.

error message below:

```
To git@github.com:AT89/Townboard.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:AT89/Townboard.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```

**Comment by jshawl** [comment]
what is output of `git pull origin master && git push origin master`

**Comment by AT89** [comment]
the above is git push origin master.

git pull origin master works, asking me to merge.
I think this was due to recreating a readme.md on the repo (i repo'd the whole folder so i just copied and created a new readme) and thats why the github version is 'ahead'. If this is the case then I should be ok to merge without a problem

**Comment by jshawl** [comment]
yep! good to go!

**Comment by AT89** [comment]
well it opened up an atom file and i dont know how to 'proceed' with it. my terminal is still on the command, what do i need to do?

**Comment by AT89** [comment]
<img width="840" alt="screen shot 2016-07-05 at 4 03 30 pm" src="https://cloud.githubusercontent.com/assets/19195314/16598058/14e15204-42ca-11e6-9eb1-0cc415501e94.png">

**Comment by jshawl** [comment]
save and close the file in atom

**Comment by AT89** [comment]
ah ok. thanks :)!
