### ISSUE TITLE
Adding current user to array in Project model

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#587]
I'm trying to add the current user to an array that's kept on the Project model (end goal is seeing a list of users on the Project page, i.e. let users join a project). I tried two different ways of approaching this, neither one has worked out:

On project show.html.erb

1.

```
<% unless User.exists?(@project.user_projects) %>
  <p><%= link_to "Join this Project!", @project.user_projects << @user.email %></p>
<% end %>
```

Note on 1. I tried getting rid of the logic, no luck

2.

```
<%= form_for @project do |proj| %>
  <%= proj.label :user_projects,"Join this Project!" %>
  <%= proj.check_box :user_projects, checked_value = @user %>
  <%= proj.submit %>
<% end %>
```

**Comment by jshawl** [comment]
stick with option 2 - any errors?

**Comment by dcordz** [comment]
![screen shot 2016-07-05 at 6 04 36 pm](https://cloud.githubusercontent.com/assets/17937472/16601530/092eb058-42db-11e6-98ea-b1e98eb0e1ba.png)

**Comment by jshawl** [comment]
second argument should be a value and not an expression

**Comment by dcordz** [comment]
Got it thanks Jesse!
