### ISSUE TITLE
Creating comment, nest within a nest

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/project2#588]
<img width="1642" alt="screen shot 2016-07-05 at 8 05 08 pm" src="https://cloud.githubusercontent.com/assets/19195314/16603663/d70be620-42eb-11e6-893b-f7ea5c3ae363.png">

I nested a few things..
board > post > comment

I am following the structure I used with post and added on @post but it's giving me an error, how do i correctly show this if its double nested?

**Comment by amaseda** [comment]
Can you just call `@post.comments.create(comment_params)` on line 19 in your comments controller? It's the `@board.@post` part that's giving you the error.

**Comment by AT89** [comment]
Hey that works, thanks, thought I had to refer @board

but I am getting an error on the comment_params

```
  private
  def comment_params
    params.require(:comment).permit(:author, :comment :image)
  end
```

```
/Users/anhtice/wdi/projects/project2_redux/bulletin/app/controllers/comments_controller.rb:36: syntax error, unexpected ':', expecting ')' params.require(:comment).permit(:author, :comment :image) ^
```

**Comment by amaseda** [comment]
Nope, since the comments belong to the post you don't need to reference the board on that line.

As for your latest error, it's probably because you're missing a comma in `.permit`

**Comment by AT89** [comment]
still erroring..

```

Extracted source (around line #36):
34
35
36
37
38
39

  private
  def comment_params
    params.require(:comment).permit(:author, :comment, :image)
  end

end
```

**Comment by AT89** [comment]
this error:
param is missing or the value is empty: comment

**Comment by AT89** [comment]
I don't get how it's saying my comment is nil, I also go into comments and it also says it is nil as well
this is my controller for post: (still need to add edit)

```
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end
  def show
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
  end
  def new
    @board = Board.find(params[:board_id])
    @post = @board.posts.new
  end
  def create
    @board = Board.find(params[:board_id])
    @post = @board.posts.create(post_params)
    if
      @post.save
      redirect_to board_path(@board)
    else
      render 'new'
    end
  end

  def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to board_path(@post.board)
  end

  private
  def post_params
    params.require(:post).permit(:title, :author, :description, :value, :image)
  end

end

```

**Comment by AT89** [comment]
whoops sorry, this is my controller for Comment

```
class CommentsController < ApplicationController

  def show
    @comments = Comment.all
  end
  def new
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end
  def show
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end
  def new
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if
      @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
  @comment = Post.find(params[:id])
  @comment.destroy
  redirect_to post_path(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :comment, :image)
  end

end

```

**Comment by amaseda** [comment]
Is your Comment model supposed to have an attribute called comment? Can't tell if it's the `:comment` in `.require` or `.permit` that's causing the error.

Also make sure you're using the proper attributes in your comment form.

**Comment by AT89** [comment]
Actually, maybe I need to nest the comments in post solely because right now its nested in boards as well, making it overly complicated

**Comment by AT89** [comment]
Maybe I could try in routes.rb:

currently it's

```
Rails.application.routes.draw do
  root to: "boards#index"
  resources :boards do
    resources :posts do
      resources :comments
    end
  end
end
```

```
Rails.application.routes.draw do
  root to: "boards#index"
  resources :boards do
    resources :posts
      end
      resources :posts do
      resources :comments
    end
end
```

I could make resource:board independent and then link them together..

**Comment by AT89** [comment]
resources:boards**

**Comment by AT89** [comment]
hmm it could be breaking because im putting comment in as the 'description' and its trying to call comment?

**Comment by amaseda** [comment]
I'm not sure if your nested routes are causing the issue. Can you push up your code and link me to your repo?

Would double check to make sure that your form account for the nesting.

Not sure if `strong_params` freaks out when the `.require` argument is the same as a `.permit` argument but might be worth exploring what happens if you rename the comment attribute to something like `body`.

**Comment by AT89** [comment]
https://github.com/AT89/Townboard

I will do the renaming tomorrow, im coded out lol

Thanks for looking into it

**Comment by AT89** [comment]
omg that was it. i changed the comment text to description instead of comment, need to be careful with semantics or rails will be confused

**Comment by amaseda** [comment]
Ha, good to know! Going to close this one now, but feel free to re-open if the same thing starts happening. Sounds like you got it though.

**Comment by AT89** [comment]
still an issue :(

param is missing or the value is empty: comment

```
Extracted source (around line #36):
34
35
36
37
38
39

  private
  def comment_params
    params.require(:comment).permit(:author, :description, :image)
  end

end
```

**Comment by AT89** [comment]
I get this error when I try to "add a comment"

**Comment by AT89** [comment]
still an issue :(

param is missing or the value is empty: comment

```
Extracted source (around line #36):
34
35
36
37
38
39

  private
  def comment_params
    params.require(:comment).permit(:author, :description, :image)
  end

end
```

**Comment by amaseda** [comment]
Can you push your code to your repo and I'll take a look?

**Comment by amaseda** [comment]
Might have to do with the mentions of `:comment`, `@comment.comment` and/or `comment[comment]` in your form. Try replacing this with the new attribute wherever it makes sense.

https://github.com/AT89/Townboard/blob/master/bulletin/app/views/comments/_form.html.erb

**Comment by amaseda** [comment]
To make things more readable in the form, try using the `text_area` form helper too: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-text_area

**Comment by AT89** [comment]
ah yes, i changed the form correctly, no bueno

**Comment by jshawl** [comment]
might be worth putting a `binding.pry` somewhere in your action to see what the value of params is

**Comment by AT89** [comment]
probably, what is the 'action' though?

And I am suspecting its something wrong in the controller

**Comment by jshawl** [comment]
the method handling your request like `index` or `show` or `create`

**Comment by AT89** [comment]
cool I figured it out embarassingly..

boards -> post -> comments are my nesting

now a real issue. I expected this to work given how destroy was setup in the postcontroller. Why is it not working as expected?
Couldn't find Comment with 'id'=2

```
Extracted source (around line #31):
29
30
31
32
33
34


  def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to board_path(@post.board)
  end
```

Post Controller:

```
  def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to board_path(@post.board)
  end
```

**Comment by jshawl** [comment]
what controller is this code in?

```
 def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to board_path(@post.board)
  end
```

**Comment by AT89** [comment]
thats the comment controller

**Comment by jshawl** [comment]
try deleting another comment? also can you take a screenshot so  can see red error message and url? cmd-shift-4

**Comment by AT89** [comment]
I trried deleting another comment before, no bueno.

**Comment by AT89** [comment]
correct SS***
<img width="1672" alt="screen shot 2016-07-06 at 10 33 00 am" src="https://cloud.githubusercontent.com/assets/19195314/16621699/31edbf86-4365-11e6-8ca6-b3c228ec56c3.png">

**Comment by jshawl** [comment]
well that looks right. if you go to rails c do you see any comments?

**Comment by jshawl** [comment]
maybe you need to refresh the page before clicking delete?

**Comment by AT89** [comment]
let me reseed etc

**Comment by AT89** [comment]
same error after reseeding it :(

**Comment by jshawl** [comment]
`<robot-voice>cloning. in. progress.</robot-voice>`

**Comment by jshawl** [comment]
getting many errors; visiting
