### ISSUE TITLE
The Equal Sign in <%=

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#589]
I'm a little confused about what the = sign does in the rails <%=, I thought it only affected visibility of code but it seems to be doing more. For example I have: (the 3rd/middle line has no = sign)

```
<%= form_for @project do |f| %>
  <%= f.label :user_projects, "Join this Project!" %>
  <% f.check_box :user_projects, {checked: true} %>
  <%= f.submit "Join Project" %>
<% end %>
```

I did this because I want a user to join a project without having to click a checkbox first. I thought I could do this by defaulting the checkbox to true and then hiding it but I guess not.

Here are the params from pry without the = sign:

```
[1] pry(#<ProjectsController>)> params
=> {"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>
  "77XctnWXyc2BjFfpYygg+pEPwidC0UI8WHG2XCqzRA3TtASwvoXN0Td9RtFJmuNJG3ntJWH0yyXmdwPY3/VMMQ==",
 **"commit"=>"Join Project",**
 "controller"=>"projects",
 "action"=>"update",
 "id"=>"7"}
```

And here are the params with the = sign:

```
[1] pry(#<ProjectsController>)> params
=> {"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>
  "uYo/fSTFoOVG8mWLh24B+zQ/BjMijadYHzl2TsIAyv2Fi+d779ek+fADdLOt3MJIvkkpMQGoLkGhP8PKN0bCwQ==",
 **"project"=>{"user_projects"=>"1"},**
 "commit"=>"Join Project",
 "controller"=>"projects",
 "action"=>"update",
 "id"=>"6"}
```

And here is the error I get when I remove the = sign:
![screen shot 2016-07-06 at 9 12 34 am](https://cloud.githubusercontent.com/assets/17937472/16618939/e405488a-4359-11e6-9d29-c34ee61d58da.png)

Is doing `<% f.check_box :user_projects, {checked: true} %>` with the {checked: true} not good practice? I checked the "name" and "value" fields in the html, they're the same both ways (with and without the = sign)

**Comment by jshawl** [comment]
`<% f.check_box :user_projects, {checked: true} %>` will not show in the html. you need the equals sign so it submits with the form

**Comment by dcordz** [comment]
So would my best option here be to place the form in a div and then set the div to display: none; with css?

**Comment by jshawl** [comment]
yes! alternatively, only show the checkbox if you are updating, not creating. 

then, in create action, you can hardcode the project sign up logic

**Comment by dcordz** [comment]
Sounds good, thanks - went with the css
