### ISSUE TITLE
Changing project idea

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#59]
It is already Monday afternoon, but I would like to change my subject of the project.
I was little confused with making MVP models with the previous subject, and I think I can make more clear MVP model with this new one.

I made a new repo, added wireframe, ERD and user stories. Please let me know if this is okay.
https://github.com/ktw1222/MyRefri

**Comment by jshawl** [comment]
:+1:  looks good! let's sync up on this tomorrow as well
