### ISSUE TITLE
Author's Name Does Not Show

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project2#590]
When I go to the BOOKS INDEX to view all book titles:
Where the AUTHOR's NAME once was is now an AUTHOR's ID...

I check my models, seed file, routes and associations... : |

Things just keep breaking when I try to fix one issue...

Where do I begin to get the app to recognize the author by id???

**Comment by jshawl** [comment]
start with the view - what erb code do you have at `books/index.html.erb`?

**Comment by amaseda** [comment]
Going to close this for now since we discussed it during office hours this morning. Feel free to re-open if you have any new developments on this front.
