### ISSUE TITLE
Issue with comments

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project2#591]
I got my comments form to show up on the locations page. Whenever I enter data, I know that the data was stored in my database since I checked it in the rails console. It's just not showing up on the locations page which is my issue. 

*I don't think it's my routes because it's redirecting to the correct page. 

https://github.com/kristinmaripasive/travel-tales/tree/profiles/travel_tales

**Comment by jshawl** [comment]
it looks like you're not trying to print out the comments? https://github.com/kristinmaripasive/travel-tales/blob/profiles/travel_tales/app/views/locations/show.html.erb

**Comment by kristinmaripasive** [comment]
I'm not entirely sure how to do that. I don't need a show page for comments right?

**Comment by jshawl** [comment]
```
<% thought.comments.each do |c| %>
 <%= c.inspect %>
<% end %>
```

**Comment by kristinmaripasive** [comment]
ohhhh... thanks Jesse!

**Comment by jshawl** [comment]
👍 np!
