### ISSUE TITLE
Expiring content

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project2#592]
General question -- for those of us using "posts" with expiring content (like food or news), is there a recommended way to handle expiration? I'm imagining that I could set an arbitrary time limit, and then exclude any content from before that limit wherever content is displayed, but that seems pretty arduous and would require a lot of repeating code. Is there a before action I could use to hide things from appearing in views?

**Comment by jshawl** [comment]
Thing to Google is active record scope. You can do something like Post.recent to filter only new things

**Comment by wombatdev** [comment]
Cool thanks, I should be able to figure that out. So if I have a column with the values 0 (active) and 1 (expired), and another column that sets the # of days to expiration, is there a way with ruby back end I can automatically flip the 0s to 1s without manual work?

**Comment by jshawl** [comment]
can you calculate active/expired based on time from created_at?

**Comment by amaseda** [comment]
You good to go here? Feel free to re-open if you need more help on this one.
