### ISSUE TITLE
before_create validation

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project2#593]
I'm trying to prevent users from creating Teams on Projects that already have a Team (1 Team max/project)

In my teams.rb model 

```
class Team < ActiveRecord::Base
  before_create :one_team_per_project

  belongs_to :user
  belongs_to :project


  private
  def one_team_per_project
    if Team.exists?(@project)
      record.errors[:base] << 'Project has a Team'
      binding.pry
      redirect_to @project.teams.first
    end
  end
end
```

When creating a new Team it doesn't go to the pry, I've been reading about validations but they seem more concerned with validating the attributes on a record, not validating the record itself. Any advice on how to add the before_create validation?

**Comment by jshawl** [comment]
must mean this is false: `if Team.exists?(@project)` try moving binding.pry above that

**Comment by dcordz** [comment]
got the pry working but I'm really not getting how before_create works, I realized the problem was I don't have access to @project or params in the method but... why?

```
class Team < ActiveRecord::Base
  before_save :one_team_per_project, :on => :create

  belongs_to :user
  belongs_to :project

  private
  def one_team_per_project
    binding.pry
    if @project.teams.any?
      binding.pry
      record.errors[:base] << 'Project has a Team'
      redirect_to @project.teams.first
    end
  end
end
```

https://github.com/dcordz/did_that

**Comment by jshawl** [comment]
the model shouldn't know about the request (including params).  you should be able to get the project from a team:

``` rb
self.project

```

**Comment by amaseda** [comment]
You good to go here? Going to close but feel free to re-open if you have more questions about this issue.
