### ISSUE TITLE
Destroy comment

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project2#594]
I'm trying to destroy each comment I made. **I'm confused on what I'm missing.** 

My browser is complaining about this line: 

```
<%= link_to "Delete", location_thought_comment_path(@comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "edit" %>

```

It's saying "No route matches {:action=>"destroy", :controller=>"comments", :id=>nil, :location_id=>nil, :thought_id=>nil} missing required keys: [:id, :location_id, :thought_id]"

This is how my destroy method looks in my comments controller:

```
  def destroy
    @location = Location.find(params[:location_id])
    @thought = @location.thoughts.first 
#purposely putting just the first thought in here to test it first instead of thought_id
    @comment = @thought.comment(params[:id])
    @comment.destroy
    redirect_to location_path @location
  end
```

**Comment by kristinmaripasive** [comment]
https://github.com/kristinmaripasive/travel-tales/tree/profiles/travel_tales

**Comment by jshawl** [comment]
`location_thought_comment_path(@comment)` should be `location_thought_comment_path(@comment.thought.location, @comment.thought, @comment)`

**Comment by kristinmaripasive** [comment]
it's saying my method thought is undefined but didn't I already define it in my locations controller?

**Comment by kristinmaripasive** [comment]
i'm checking my console as well and i'm seeing the "thought"

**Comment by jshawl** [comment]
does a comment belong to a thought?

**Comment by kristinmaripasive** [comment]
yes, it's nested in a thought which is nested in a location

**Comment by amaseda** [comment]
Catching up here! Will look through your repo now.

**Comment by amaseda** [comment]
I was able to get it to work when I changed your destroy link to look like the following...

``` html
# locations/show.html.erb

<%= link_to "Delete", location_thought_comment_path(@location, @thought, c), method: :delete, data: { confirm: 'Are you sure?' }, class: "edit" %>
```

And then I had to modify the destroy method in your comments controller to look like this...

``` rb
  def destroy
    @location = Location.find(params[:location_id])
    @thought = @location.thoughts.first
    @comment = Comment.find(params[:id]) # this is the line that needed to be fixed
    @comment.destroy
    redirect_to location_path @location
  end
```

> You weren't using `.find` to retrieve the comment originally.

**Comment by kristinmaripasive** [comment]
oh wow, I tried **Comment.find(params[:id])** before. I think my problem was the actual path in the show for locations. I wasn't passing comments into it. _facepalm_

Thanks a lot, Adrian!

**Comment by amaseda** [comment]
Yay!
