### ISSUE TITLE
sign up is working but login is throwing error when you actually click login 

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project2#598]
it's trying to route to session/new but I don't know how to set where it routes instead

https://github.com/jschultz21/dc-brew-circuit/tree/integrating-devise

**Comment by amaseda** [comment]
Where in your repo should I be looking? (I think Jesse was helping you earlier - he stepped out for a bit).

**Comment by jschultz21** [comment]
The 'sign in' button on the new session view is throwing this error "ActionController::UnknownFormat" when clicked. Not sure if an error with the sessions controller, routes, or something in devise.

**Comment by jschultz21** [comment]
i just pushed the latest version to the integrating devise branch

**Comment by jschultz21** [comment]
i just pushed the latest version to the integrating devise branch

**Comment by jshawl** [comment]
any updates @jschultz21 ? progress?

**Comment by amaseda** [comment]
Gonna close this one since we made some progress on user auth earlier but go ahead and re-open it if you have any more questions!
