### ISSUE TITLE
comment destroy deletes comment and the post

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/project2#599]
hey sorry went off to lunch so i didnt respond to the issue (and cant figure out how to reopen the issue)

still an issue

```
Couldn't find Post with 'id'=2

Extracted source (around line #8):
6
7
8
9
10
11

  def show
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
  end
  def new
    @board = Board.find(params[:board_id])
```

**Comment by AT89** [comment]
the issue is that it deletes the post and the comment, when i go to delete the comment.

**Comment by jshawl** [comment]
i think you want to find the comment and not the post - https://github.com/AT89/Townboard/blob/e92aad0c600f8ca6b25cb5da22c0a2951d0ff2cc/bulletin/app/controllers/comments_controller.rb#L31-L32

**Comment by AT89** [comment]
right but i need the @post and @board to redirect. (i think). the error takes me back to the postcontroller since it cannot find the id (since it got deleted with the comment)

**Comment by AT89** [comment]
hmm i just tried it, replaced it with post_path for the redirect and took out the @board and @post (you dont see @board in the repo) and it worked!

**Comment by AT89** [comment]
it worked at first but then it didnt. on a _new added comment_, it recreates the prior problem of deleting the post with it

**Comment by jshawl** [comment]
You have to Comment.find not Post.find when destroying

**Comment by AT89** [comment]
yea, the error it was giving me was in post becuase it could not find the id (since it was deleted). this is in my comment controller

```
  def destroy

  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to board_post
  end
```

the redirect was working but now its not so i have to change it

**Comment by AT89** [comment]
hmm so i created 3 comments, deleted one and it ended up deleting all of them.

so another issue is new/create comment is not creating it with a unique ID? or my delete is messed up

**Comment by AT89** [comment]
**actually it deleted the comments and the post (it just deleted hte post so the comments went away with it since its dependent destroy). 

It redirected me to the next board (board[2])
using this as my redirect

```
  redirect_to board_post_path
```

**Comment by amaseda** [comment]
Tagging in here! Sounds like you guys covered a number of issues in this chain. Can you please take a screenshot of the error you're getting now?

I'll compare it to the code that's in your repo now so please make sure the most recent version is pushed up. Thx

**Comment by AT89** [comment]
<img width="707" alt="screen shot 2016-07-06 at 2 30 46 pm" src="https://cloud.githubusercontent.com/assets/19195314/16629993/69879acc-4386-11e6-92a2-88e0b5336323.png">

my CRUD on post is working perfectly.

Comments does not work, it gives me this error because it deletes the comment and the post so it cannot redirect or find it.

**Comment by AT89** [comment]
i think the issues is because comments is being double nested..

**Comment by AT89** [comment]
current routes 

```
Rails.application.routes.draw do
  root to: "boards#index"
  resources :boards do
    resources :posts do
      resources :comments
    end
  end
end
```

can i do..

```
Rails.application.routes.draw do
  root to: "boards#index"
  resources :boards do
    resources :posts
end
     resources :posts do
      resources :comments
  end
end
```

?

**Comment by jshawl** [comment]
if you go into rails console and type Post.all what is the output?

**Comment by AT89** [comment]
```
2.3.1 :001 > Post.all
  Post Load (1.0ms)  SELECT "posts".* FROM "posts"
 => #<ActiveRecord::Relation [#<Post id: 1, title: "This is a post looking for stuff", author: "Hannah Wants", description: "i want a steak that looks like the USA", value: 100, image: "http://i.imgur.com/12FlP56.jpg", created_at: "2016-07-06 18:09:57", updated_at: "2016-07-06 18:09:57", board_id: 1>, #<Post id: 4, title: "This is a post to get rid of stuff", author: "Hannah Wants", description: "i give a 24in monitor", value: 0, image: "http://i.imgur.com/12FlP56.jpg", created_at: "2016-07-06 18:09:57", updated_at: "2016-07-06 18:09:57", board_id: 3>]> 
2.3.1 :002 > 
```

**Comment by AT89** [comment]
this was the Post.all after some ID's got deleted

**Comment by amaseda** [comment]
This fixed it for me: remove `:dependent => :destroy` from `comment.rb`. 

It should only be in `post.rb` next to `has_many`.

**Comment by AT89** [comment]
hmm. im not denying that it fixed it but i cant understand why. doesnt comment need to be dependent destroy? because if a post gets destroyed, the comments get destroyed too? 

now that i think of it, since there is no CRUD on the Boards and only the post, only the comments are dependent on the post, so that makes sense

**Comment by amaseda** [comment]
Yeah that's just how it works. If you add dependent destroy to the `belongs_to` it will also delete the post the comment belongs to.

**Comment by AT89** [comment]
let me check something else before this issue is closed. Thanks!

**Comment by AT89** [comment]
Ok I made the changes to the models /comment.rbdid the whole db:drop db:create db:migrate db:seed,

I added a new comment to a post that already had a comment, deleted the comment and it deleted both comments

**Comment by AT89** [comment]
Actually nvm i think the redirect is just wrong, it deleted the only comment.

but another issue is if you look at the seeds.rb, there is another post for board[2] and that is never seeding in the db:seed; do you know why that is? I do not get any errors (all ='s) in the db:seed when I run the command in terminal

**Comment by amaseda** [comment]
It's because your title is too short. That violates the validation you set up in `post.rb`...

```
validates :title, presence: true, length: {maximum: 50, minimum: 5}
```

**Comment by AT89** [comment]
so issues right now 
1. new data is not seeding -CHECK omg youre right..
1. redirect from destroy is not working, looking at rake routes and asking a peer for help (to verify im not crazy), board_post or board_post(post) or with @post, board is not either
   
   is format supposed to be filled in with _path?

**Comment by nolds9** [comment]
@AT89 yes, what does your redirect to look like

**Comment by AT89** [comment]
yesssssss i got it working.

Thanks all!! you may close this issue

**Comment by nolds9** [comment]
👍
