### ISSUE TITLE
my association just quit on me

### ISSUE THREAD

**Issue by gandyland** [ga-wdi-exercises/project2#600]
I'm trying to get one model to associate with two totally separate models. I used the polymorphic association but now the beer won't save with any of the other models. I need an adult.

``` rb
class Beer < ActiveRecord::Base
  belongs_to :brewery, :polymorphic => true
  validates :brewery, presence: true
  validates :name, presence: true
end

```

``` rb
class Brewery < ActiveRecord::Base
  has_many :beers, :as => :booze
  validates :name, presence: true
end
```

``` rb
class Restaurant < ActiveRecord::Base
  has_many :beers, :as => :booze
  validates :name, presence: true
end
```

**Comment by jshawl** [comment]
how are you trying to associate the two models?

**Comment by jshawl** [comment]
can associate beer with brewery. what errors are you getting?

![](https://dl.dropbox.com/s/zoxsi312mzppwkt/Screenshot%202016-07-06%2014.43.27.png?dl=0)

**Comment by gandyland** [comment]
I'm getting "NameError: uninitialized constant Beer"
Not sure what I did. I wasn't getting this before.

**Comment by jshawl** [comment]
where do you get that error?

**Comment by gandyland** [comment]
that was when I tried to run beer.new in pry but now my localhost page throws me a 
"ActiveRecord::RecordNotFound in BeersController#create
Couldn't find Brewery with 'id'="

And points to beer_controller.rb with the code:

``` rb
 def create
    brewery = Brewery.find(params[:brewery_id])
        @beer = @brewery.beers.create(beer_params)
    redirect_to @beer
  end
```

saying that the second line is the problem.

**Comment by nolds9** [comment]
@gandyland the key for the value of the `Brewery`'s `id` in `params` depends on how routes are structured. Can you screenshot the output of `rake routes`?

**Comment by gandyland** [comment]
![screen shot 2016-07-06 at 3 35 39 pm](https://cloud.githubusercontent.com/assets/19474694/16631866/63bf0b44-438f-11e6-88c6-353087e33b8e.png)

**Comment by nolds9** [comment]
@gandyland In the controller I think you're just missing an `@` for `brewery`

**Comment by gandyland** [comment]
I added it and I'm still getting the same error.

**Comment by nolds9** [comment]
so your `create` action looks like:

``` ruby
def create
    @brewery = Brewery.find(params[:brewery_id])
    @beer = @brewery.beers.create(beer_params)
    redirect_to @beer
end
```

When do you get that error? What action triggers it?

**Comment by gandyland** [comment]
When I try to create a new beer.

**Comment by nolds9** [comment]
You mean when you are on the form for a new beer, and hit submit?

**Comment by gandyland** [comment]
Yeah exactly. It works fine for creating breweries and restaurants but not beers.

**Comment by nolds9** [comment]
Interesting, you mind pushing you code to github and ill take a look

**Comment by gandyland** [comment]
Sure thing

**Comment by gandyland** [comment]
Shit, sorry. It looks really crazy right now because I'm messing with the styling.

**Comment by nolds9** [comment]
no worries, Im getting set up now.

**Comment by nolds9** [comment]
@gandyland So figured out one issue, you're referencing a variable `@brewery` in your view thats not defined in the controller! https://github.com/gandyland/Booze_Rails/blob/master/booze_rails/app/views/beers/new.html.erb#L3

**Comment by nolds9** [comment]
The other issue, is your associations. Because you are using a polymorphic relationship, a `Brewery` does not have the method `beers`, instead it would be `boozes` as you have defined it.

That being said, I'm not sure you need the polymorphic relationships, I'm thinking you can just have multiple one to many relationships, i.e. `Beer` belongs_to both `Brewery` and `Restaurant` and each of `Brewery` and `Restaurant` have_many `:beers`

**Comment by gandyland** [comment]
That will make this much easier. Thanks

**Comment by nolds9** [comment]
No problem, feel free to open another issue in the future!
