### ISSUE TITLE
Fail: testing my many-to-many relationship 

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project2#602]
I'm beginning to create my user and location's many-to-many relationship. I have created a join table called "user_locations"... Before anything, I am testing the relationship on the rails console. I created dummy data and tried the following:

```
kristin = User.create({name: "kristin"})
john = User.create({name: "john"})
idaho = Location.create({name: "idaho"})
detroit = Location.create({name: "detroit"})
john_go_to_london = UserLocation.create({user: "john", location: "idaho"})
```

I keep getting an Association Type Mismatch. 

https://github.com/kristinmaripasive/travel-tales/tree/treks/travel_tales

**Comment by amaseda** [comment]
It's because you're passing in strings into `user:` and `location:`. You should pass in the variables (i.e., without quotes).

**Comment by kristinmaripasive** [comment]
I just tried it without the quotes and the error is gone, but it's still showing up empty when I try to call idaho.users

**Comment by amaseda** [comment]
Solved IRL! Let me know if you have any other issues with this.
