### ISSUE TITLE
Question on my issues index

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project2#603]
link to my repo: 
https://github.com/JuliaNajafi/two_faced

When I loop through my issues on my index page, I originally looped through each headline in each issue to output them on the page. However, I decided I only want to output the first headline within each issue. This works for each headline ON THE LEFT (i.e. where the affiliation: 'left'), however i get an error when I implement it the exact same way for the headlines on the right. At first I thought that because there is no headline on the right for the second issue - and that it cant read and parse a null value - however this is not the case since it still works when I do "issue.headlines.where(affiliation: 'right').each do |headline| and loop through all the headlines. So for some reason its not picking up on just the first headlines on the right when i do 'headline = issue.headlines.where(affiliation: 'right').first' ...  Sorry if that is confusing!

**Comment by jshawl** [comment]
what error do you get? screenshot?

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-06 at 2 57 26 pm](https://cloud.githubusercontent.com/assets/19292741/16630843/13fc2aec-438a-11e6-8a9f-f2a27d44a485.png)

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-06 at 2 59 04 pm](https://cloud.githubusercontent.com/assets/19292741/16630881/4030585e-438a-11e6-95c9-88d7d75be6df.png)

**Comment by JuliaNajafi** [comment]
Line 23 works, but line 30 does not

**Comment by nolds9** [comment]
@JuliaNajafi looks like `headline`is not defined. I would double check to make sure there are any headlines that are affiliated to the right....maybe check in your rails console

**Comment by JuliaNajafi** [comment]
thats what i thought the issue was originally - because for my second issue, there isnt a headline for the right, so I went back to what I did before targeting the first, which was replaced line 29 with 'issue.headlines.where(affiliation: 'right').each do |headline|' and looped through all the headlines rather than just the first. and even though I didnt have a headline for the right on the second issue, it still worked and did not throw an error, which means, i think, that it wouldnt matter if there aren't headlines on the right for some issues (which would be ideal) if I were looping through, but it does matter if I target just the first headline ?

**Comment by nolds9** [comment]
Yep so, just add an `if` statement before you grab the first one.

Thinking: 

``` ruby
<% if issue.headlines.where(affiliation: "right").any? %>
 <% headline = ....first %>
   etc
<% end %>
```

**Comment by JuliaNajafi** [comment]
ok thanks !

**Comment by amaseda** [comment]
Going to close this one but feel free to re-open if need be!
