### ISSUE TITLE
Timestamp formating showing date in the future

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/project2#605]
Attempting to reformat my timestamp display, the migration files have the correct timestamps (so it's not my computer) but the format is listing as July 16 for sites index. Any reason that might be? Thanks

https://github.com/alpha2262/DC_development_map/tree/silver2

**Comment by nolds9** [comment]
timestamps are by default in `utc` format...

you mind find it useful to use the native rails helper `time_ago_in_words` http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words

**Comment by amaseda** [comment]
Going to close this one but feel free to re-open if need be!
