### ISSUE TITLE
Using jquery

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project2#606]
https://github.com/adina-pollack/needtacos

I've put a span with an id of "help" around the first word of my title: "Help!", on my application.html.erb  page. I'm trying to create a jquery function that will change the background image of the page when you hover over "Help!". I've also added the jquery link into the application.html.erb page. Could you please point me in the right direction for getting this to work? Thanks :)

**Comment by amaseda** [comment]
Did you test to see if the Javascript was being loaded properly (e.g., have the first line be something like `console.log("running!");`.

If that works, can you wrap your jQuery in a `$(document).ready( )` and see if that causes your event listener to work?

**Comment by adina-pollack** [comment]
Okay, so that works. But now it's saying my image is not found. I have it in app/assets/images.

**Comment by amaseda** [comment]
What happens if you just reference the image using the path `/images/giphy.gif` (so no `../`). If that doesn't work try just `giphy.gif`.

**Comment by adina-pollack** [comment]
Neither works. It looks like i'm getting a routing error
![screen shot 2016-07-06 at 4 22 19 pm](https://cloud.githubusercontent.com/assets/18648382/16633194/0ad16f02-4396-11e6-9216-584dfb9f7f3e.png)

**Comment by amaseda** [comment]
Can you move the image file into Rails' public folder? That made in work locally for me if I just used the `giphy.gif` path.

**Comment by amaseda** [comment]
If we place images in `assets`, that means we're going to access it using Rails (e.g., `image_tag`). When placing an image in assets, it gives it a new name behind the scenes that only Rails knows.

If we place it in `public`, the image is accessible everywhere by everything, including Javascript/jQuery.

**Comment by amaseda** [comment]
@adina-pollack Did this work for you?

**Comment by adina-pollack** [comment]
It worked! But now I can't seem to get it to stop when the mouse goes away. Should mouseout work?

**Comment by amaseda** [comment]
Yeah give that a shot!

**Comment by adina-pollack** [comment]
Also, I haven't touched anything else and i'm getting an error when I try to go to my 'favorites' now.
![screen shot 2016-07-06 at 4 58 54 pm](https://cloud.githubusercontent.com/assets/18648382/16634291/f77fb8c8-439a-11e6-93a0-56f656dcc435.png)

**Comment by adina-pollack** [comment]
Andy helped with that last error. 

But is there a way to make the js work across all views, not just the initial page ready?

**Comment by nolds9** [comment]
Think you are running into an issue with jQuery and Rails' built in turbolinks...try using 
`on("page:change")` instead of `on("ready")`

**Comment by nolds9** [comment]
if that doesnt work, the answer with the checkmark might help http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

**Comment by adina-pollack** [comment]
Thank you!!
