### ISSUE TITLE
pre populated sign in

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project2#607]
So when I go to add a new user my browser is prepopulates the user user and password field with my user information - even though I put <% @user = " "%> before the do. Anyway to prevent that?

**Comment by jshawl** [comment]
is the background of the input yellow?

**Comment by marasanders** [comment]
yes

**Comment by amaseda** [comment]
In that case, sounds like it might just be your browser pre-populating that with info you already used to log in. Nothing to do with your app.

**Comment by marasanders** [comment]
thanks
