### ISSUE TITLE
My app is no longer CRUD...

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project2#608]
My app was working and my associations were wrong I realize I had to do nested resources after I nested the resources with my authors and my books everything stopped working

**Comment by jshawl** [comment]
do you have any errors? any screenshots?

**Comment by ayespi** [comment]
https://www.dropbox.com/s/yuifsjtzrufnoqb/Screenshot%202016-07-06%2017.10.04.png?dl=0

**Comment by ayespi** [comment]
Here are my [Rake Routes]

https://www.dropbox.com/s/ouo5psioyh8l39v/Screenshot%202016-07-06%2017.11.33.png?dl=0

**Comment by jshawl** [comment]
dropbox says images are still uploading - can you drag and drop image into issue?

**Comment by ayespi** [comment]
![image](https://cloud.githubusercontent.com/assets/17255879/16634844/9a45fae8-439d-11e6-8f3a-e2b991574210.png)

**Comment by ayespi** [comment]
Rake Routes
![image](https://cloud.githubusercontent.com/assets/17255879/16634863/adae5c56-439d-11e6-898e-402b20309ae0.png)

**Comment by jshawl** [comment]
`new_author_book_path` needs to know about an author.

Should be `new_author_book_path(@author)`

**Comment by ayespi** [comment]
It didn't work,  but the problem may be in my controller...

**Comment by jshawl** [comment]
Any errors?

**Comment by ayespi** [comment]
I was fiddling around with controller actions... hoping for a miracle...

**Comment by jshawl** [comment]
Don't fiddle! What does the error message say?

**Comment by ayespi** [comment]
The error message says the same thing...

**Comment by ayespi** [comment]
The error message is: ActionController::UrlGenerationError in Books#index

**Comment by jshawl** [comment]
Is your latest code on GitHub?

**Comment by ayespi** [comment]
It is now...

**Comment by jshawl** [comment]
because you have this in your routes:

``` rb
 resources :authors do
    resources :books
  end
```

you can't 

``` rb
root 'books#index'
```

because a book needs to know about an author

**Comment by jshawl** [comment]
try

``` rb
root 'authors#index'
```

instead

**Comment by ayespi** [comment]
Ok, will do...

**Comment by ayespi** [comment]
I am able to see the Author's Index... But, I no longer see the Welcome#Index... Does this mean that in order to have my Welcome Page, I would have to nest that as well???

**Comment by ayespi** [comment]
Nvm... Since the main part is the books, I can use the Author's Index as the Welcome Page... I hope...

**Comment by ayespi** [comment]
![image](https://cloud.githubusercontent.com/assets/17255879/16638360/9774ce90-43b4-11e6-9dd9-0bf6d2cf6765.png)

```
class BooksController < ApplicationController
  def index
    @author = Author.find(params[:author_id])
    @books  = Book.all
  end

```

Please let me know if I am on the right track...

**Comment by jshawl** [comment]
@author is nil because there is no author_id in the params

**Comment by ayespi** [comment]
Okay... Thanks... I am making progress... My laptop may survive the night...
