### ISSUE TITLE
Issues with join table

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/project2#609]
I'm doing an application that will show information about a television show.  I've got three tables:  Actors has actor Information, Episodes has information about the episode, and actorepisodes is the join table with one record per actor per episode pointing to the actor and the episode. 

```
class Actor < ActiveRecord::Base
  has_many :actorepisodes
  has_many :episodes, :through => :actorepisodes
end 

class Episode < ActiveRecord::Base
  has_many :actorepisodes
  has_many :actors, :through => :actorepisodes
end

class Actorepisode < ActiveRecord::Base
  has_many :actors
  has_many :episodes
end
```

I can't get the join to work, when I reference @actor.episode in the html it tells me it can't find the episodes.actorepisode_id column, which doesn't, and shouldn't, exist.  I think I've got either the database structure or the associations set up wrong.

**Comment by nolds9** [comment]
@kwg58  shouldn't an `Actorepisode` belong to an `Actor`, and belong to an `Episode`

**Comment by kwg58** [comment]
Hmmmm.....  Can I just change it and restart the server, or do I need to reload the data?

**Comment by nolds9** [comment]
try just restarting the server, if that doesn't work then reload the data

**Comment by kwg58** [comment]
I'm reseeding.  I got this:  ActiveRecord::AssociationTypeMismatch: Episode(#70265218309260) expected, got String(#70265208217680)

Is this telling me that it's getting a string where it's expecting a number?

**Comment by nolds9** [comment]
Seems like it, can you post your seeds, i'd just double check how you are using your associations...i.e. an episode has many actors, and an actor has many episdoes, so you can't call `actor.episode`

**Comment by kwg58** [comment]
The episode fields in each of these tables are string.  The data are numeric, so I can migrate them fairly easily and try that, if you think that wise.

```


require 'csv'

Actor.delete_all

CSV.foreach('db/mash_cast.csv', headers: true) do |row|
  Actor.create(
    {
      name: row['name'],
      actor_id: row['name_id'],
      first_name: row['first_name'],
      last_name: row['last_name'],
      character: row['character']
    }
  )
end

Episode.delete_all

CSV.foreach('db/mash_episodes.csv', headers: true) do |row|
  Episode.create(
    {
      ep_year: row['ep_year'],
      ep_num: row['ep_num'],
      episode: row['episode'],
      title: row['title'],
      air_date: row['air_date'],
      synopsis: row['synopsis']
    }
  )
end

Actorepisode.delete_all

CSV.foreach('db/MASH_cast_by_episode.csv', headers: true) do |row|
  Actorepisode.create(
  {
    episode: row['EpID'],
    name: row['Actor'],
    actor_id: row['name_id'],
    episode_id: row['EpID']

  }
  )
end
```

**Comment by nolds9** [comment]
Yeah i think thats wise, but Im might rename the columns you have called `episode`  to prevent `Active Record` from trying to force an association. 

In that last block to create all your `Actorepisode`s, make sure that `episode_id` is being passed an integer and not a string....and make that be reflected in your schema

**Comment by kwg58** [comment]
OK, I've changed the tables around and reseeded fine.

Now when I do the query from the HTML page i'm not getting an error message anymore, I appear to be getting null results.  

Any advice???  How do I go about troubleshooting this?  I'm stumped.
