### ISSUE TITLE
Error - Undefined Table

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#61]
My delete link is not working and will send me the following error. I don't understand what the error is asking. I googled it but all that is recommended is to restart your database. I did that and also ran rake db:seed for good measure. I currently only have one model which is posts.

![screen shot 2015-08-03 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/11203264/9044887/a5a6f7f8-39ed-11e5-840e-83d0ec20d674.png)

**Comment by jshawl** [comment]
Do you have a migration that creates the comments table?

**Comment by jshawl** [comment]
or `dependent: destroy` in your `post` model?

**Comment by malissaromero** [comment]
Ok it is working. I decided to not do comments and thought I had deleted all the files related to it but I still had "has many comments" in my post model. It is now working. Thank you.
