### ISSUE TITLE
I'm getting an 'Access-Control-Allow-Origin' error while trying to integrate an API

### ISSUE THREAD

**Issue by rmilford** [ga-wdi-exercises/project2#611]
the error message is: 

```
XMLHttpRequest cannot load http://www.opensecrets.org/api/?method=getLegislators&id=NJ&apikey=... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400.
```

i tried replacing local host with opensecerts.org  (something i read on slackoverflow) but i couldn't get it to work.. help, thank you :)

**Comment by amaseda** [comment]
Can you include some code indicating where/how you're making the API call?

**Comment by rmilford** [comment]
```
$(document).ready(function(){

var url = 'http://www.opensecrets.org/api/?method=getLegislators&id=';
var apiKey = '&apikey=';
$("button").click(function(){

  var search = "NJ"
  $.ajax({
    url: url+search+apiKey,
    type: "GET",
    dataType: "json"
  }).success(function(response){
    console.log(response);


  }).fail(function(response){
    console.log("sucks for you", response);
  });
});
});
```

**Comment by amaseda** [comment]
Hm, could be a number of things at work here.

One thing to try is setting the `dataType` to `jsonp`. More info here: https://www.sitepoint.com/jsonp-examples/

Another thing you could do is try to make the API call from the back-end. HTTParty is a gem that allows you to do that. Take a look at the documentation and give it a spin: https://github.com/jnunemaker/httparty

If you end up going with HTTParty but need to get that information asynchronously, you'll need to do a bit more work. But start with the above and see where that takes you.

**Comment by rmilford** [comment]
One more question, where should I save the API in the rails app so it doesn't get compromised?

**Comment by jshawl** [comment]
Thing to Google is "figaro gem"
