### ISSUE TITLE
https://github.com/ga-dc/project2-gallery/issues/27

### ISSUE THREAD

**Issue by jshawl** [ga-wdi-exercises/project2#612]
![](https://cloud.githubusercontent.com/assets/17255879/16656039/118de2ea-442b-11e6-9954-9b8dcbb32f99.png)

**Comment by jshawl** [comment]
should be `Book.find(params[:id])`

**Comment by jshawl** [comment]
@ayespi

**Comment by ayespi** [comment]
It says MISSING TEMPLATE...
I was under the impression that Update did not have a view because it was placing records directly into the db...

![image](https://cloud.githubusercontent.com/assets/17255879/16656546/1a09b370-442d-11e6-9506-df75bb98a455.png)

**Comment by jshawl** [comment]
need to `redirect_to @book`

**Comment by ayespi** [comment]
Figured out right before your comment!
It feels good to figure something out!!! : )

**Comment by ayespi** [comment]
Thank you Jesse!!! Now to the DELETE...

**Comment by jshawl** [comment]
👍
