### ISSUE TITLE
issue with everything. <top (required)

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/project2#613]
I created a new branch to try to add users but it messed alot of things up for me. I gave up on users for now and edited the seed file to something presentable. 

I get the same error (from trying to do the users) saying something is wrong with my environment.rb. This error occurs on the terminal when I try to do db:drop db:create db:migrate db:seed 

`
Anhs-MBP:bulletin anhtice$ rake db:drop db:create db:migrate db:seed
rake aborted!
NameError: undefined local variable or method `config' for main:Object
/Users/anhtice/wdi/projects/project2_redux/bulletin/config/environment.rb:7:in `<top (required)>'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/Users/anhtice/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/anhtice/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/anhtice/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments => environment
(See full trace by running task with --trace)
`
Repo link: https://github.com/AT89/Townboard/tree/master/bulletin

**Comment by jshawl** [comment]
remove this line https://github.com/AT89/Townboard/blob/master/bulletin/config/environment.rb#L7

**Comment by AT89** [comment]
Thanks :)

**Comment by jshawl** [comment]
👍
