### ISSUE TITLE
Form returning params as string not hash?

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#62]
My edit form loads properly now but creates a AssociationTypeMismatch in PhotosController#update on submit.  Error also states: User(#70250406445440) expected, got String(#70250331047800).  Error is in 
this line:   if @photo.update(photo_params).  Sounds like it is looking for the user object, which was passed to form as @user (as was @photo) so seems like everything got through...

[ I'm assuming photo_params is a hash from the form, but don't see where the form inputs are grouped into it.  (No "photo[date_taken]" for example on form... form helper takes care of this?) ]

photos_controller.rb

```
  def update
    logger.warn "### photos#update"
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
      else
        format.html { render :edit }
      end
...
```

_form.html.erb

```
<%= form_for [@user, @photo] do |f| %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
...
```

**Comment by jshawl** [comment]
what is in your `photo_params` method?

**Comment by jshawl** [comment]
OH. It's because you have a text field to enter a user object. Remove that field from the form. and in your update method:

``` rb
if @photo.update(photo_params.merge(user: session[:user]))
```

You were getting this error because rails is expecting a User object, but letting users type in a name in a field will submit a string instead.

Please reopen if you'd like further assistance.

**Comment by adambray** [comment]
As some further clarification, @jshawl's suggestion is somewhat depending on how you're handling user login. I'm happy to pair with you for a bit this afternoon on that part (since I noticed you had some questions / issues on that with your scribble HW)

**Comment by adambray** [comment]
@tomBeach pinging your GH username to make sure you saw the  above message.

**Comment by tomBeach** [comment]
Got it!  Thanks for working solution (Jesse) and thanks for cautionary note (Adam) re the session[:user] part of Jesse's answer.  I don't have sessions set up yet so I used redirect_to user_photo_path(@user, @photo) for now... am about to tackle user auth and sessions... hopefully moving beyond homework quagmire this time...
