### ISSUE TITLE
Can you have two totally separate models with their own user authentications?

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#621]
Basic app idea - fire stations (which have to log in) can initiate an emergency campaign to any given apartment building, and all pet owners who have signed up and are also users will be notified of the status of the pet rescue.

My current solution is that you have a fire station model (with it's own columns/attributes) and a pet owner model (with his/her own  columns/attributes). The join table is called emergency. It connects a firestation to a pet owner, and has an added column called status.

My hesitation is that in class we learned about creating a USER model with different permissions for an admin for instance, but in this case, the firestation model has totally different attributes than the pet owner table, and in addition, the two tables need to be able to reference each other THROUGH the emergency table.

Am I overthinking this? Can I simply create user authentications separately for firestations and for pet owners? 

Thanks,
Tyler

**Comment by andrewsunglaekim** [comment]
👍
