### ISSUE TITLE
Accessing and Assigning current_user

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#622]
I’m having an issue working on nested routes.

I've been able to find one of the ids associated with my create method, but am struggling at where to assign the "current_user" value to user_id.

I think this is something we did briefly, but I can't find the reference.
Would I be assigning this in the form rendered in the new view, or would I be assigning this directly in the controller action for CREATE?

Thanks so much!

**Comment by andrewsunglaekim** [comment]
are you using any external dependencies like devise?

**Comment by andrewsunglaekim** [comment]
Otherwise checkout https://github.com/ga-wdi-exercises/tunr_rails_users/pull/3/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR5

**Comment by ghost** [comment]
Fixed the current user problem and now I'm having an issue with the parent id of the nested resource. My url looks like this root/tweets/1/emojitweets/new and I'm trying to assign Tweet.find(params[tweet_id]) where in this case tweet_id would be 1.

Error being generated: tweet id is still nill after calling create method when using the above notation:

``` ruby
    def create
        @tweet=Tweet.find(params[:tweet_id])
        @emojitweet = Emojitweet.new(emojitweet_params)
        @emojitweet.user = current_user
        @emojitweet.save
        binding.pry
        redirect_to root_path
    end
private
    def emojitweet_params
        params.require(:emojitweet).permit!
    end
```

**Comment by nolds9** [comment]
@chris-A-phillips what is the output of `rake routes`?

**Comment by andrewsunglaekim** [comment]
do `emojitweets` have a tweet associated with them?

**Comment by ghost** [comment]
Issues closed we fixed it will talk about it in a second!
