### ISSUE TITLE
image_tag syntax help

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/project2#623]
I've looked at the Rails syntax but still need help trouble shooting
My code to put an image in header that links to home

```
<%= link_to <%= link_to image_tag(assets/images/foodme.png), boxes_path(@box) %>
```

I've tried putting the file path in the image_tag parens but to no avail. The image is at /assets/images/foodme.png

```
Syntax examples

image_tag("icon")
# => <img alt="Icon" src="/assets/icon" />
image_tag("icon.png")
# => <img alt="Icon" src="/assets/icon.png" />
image_tag("icon.png", size: "16x10", alt: "Edit Entry")
# => <img src="/assets/icon.png" width="16" height="10" alt="Edit Entry" />
image_tag("/icons/icon.gif", size: "16")
# => <img src="/icons/icon.gif" width="16" height="16" alt="Icon" />
image_tag("/icons/icon.gif", height: '32', width: '32')
# => <img alt="Icon" height="32" src="/icons/icon.gif" width="32" />
image_tag("/icons/icon.gif", class: "menu_icon")
# => <img alt="Icon" class="menu_icon" src="/icons/icon.gif" />

```

**Comment by superbuggy** [comment]
@chaseTfreeman do you have the images in your assets?
http://apidock.com/rails/ActionView/Helpers/AssetTagHelper/image_tag

**Comment by chaseTfreeman** [comment]
Yes. I accidentally submitted my issue before putting that info. it is up to date now

**Comment by chaseTfreeman** [comment]
Also updated syntax because the previous stuff was bogus

**Comment by nolds9** [comment]
if you have a an image called `logo` in `app/assets/images/logo.png`, 

you should be able to link to it with `<%= image_tag("logo") %>`

**Comment by chaseTfreeman** [comment]
Awesome! Thanks. I just needed to take the file type out of the Parens/quotes

**Comment by andrewsunglaekim** [comment]
i'm going to close this issue, please reopen if the need arises
