### ISSUE TITLE
Active record access

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#624]
I'm having an issue where a view file returns nil:NilClass when calling an active record association 
`<h1>HI MOM!</h1>
<% @tweets.each do |tweet| %>
    <p><%=tweet.status%></p>
    <p><%= tweet.emojis.first.face %></p>
<%end%>`

tweet.emojis.first.face returns:

 nil:NilClass

tweet.emojis.first.inspect will render the active record in the view:

'#<Emoji id: 1, face: "😄", description: "smiling face with open mouth and smiling eyes", aliases: "[\"smile\"]", tags: "[\"happy\", \"joy\", \"pleased\"]">'

nilNilClass is returned for all the key values (id, face, description, etc)

Does anyone have an idea why this stops being accessible after the inspect level?

**Comment by nolds9** [comment]
I would check first to see if that `tweet` has any emojis...

pseudo-code:

``` ruby
<% if tweet.emojis.any? %>
  # print the first emoji's face
<% end %>
```

**Comment by ghost** [comment]
Just confirmed their existence calling binding pry in the view after tweet have been defined.

**Comment by nolds9** [comment]
interesting, can you see any data about each individual emoji? Sounds like the model / database are not in sync. want to push your code to github and I can take a look

**Comment by ghost** [comment]
https://github.com/chris-A-phillips/Did-you-see-that here is the repo - View I'm in currently is tweets < index.html.erb

**Comment by ghost** [comment]
Removed depend: :destroy and still am not able to access past inspect
tweet.emojis.first.inspect renders this by the way(typo before): 

<Emoji id: 1, face: "😄", description: "smiling face with open mouth and smiling eyes", aliases: "[\"smile\"]", tags: "[\"happy\", \"joy\", \"pleased\"]">

**Comment by ghost** [comment]
`#<Emoji id: 1, face: "😄", description: "smiling face with open mouth and smiling eyes", aliases: "[\"smile\"]", tags: "[\"happy\", \"joy\", \"pleased\"]">`

**Comment by ghost** [comment]
Question! Are active record memory stores supposed to change on refresh?

Have this - 
`#Emoji:0x007fb164787018

#Emoji:0x007fb164786cf8

#Emoji:0x007fb1647869d8`
Refresh Page get this - 

`#Emoji:0x007fb16bc6bc58

#Emoji:0x007fb16bc6bb18

#Emoji:0x007fb16bc6b9d8`

**Comment by nolds9** [comment]
no, dont think they change on refresh thanks to Rails caching - at least until the cache busts

**Comment by andrewsunglaekim** [comment]
going to close issue, reopen if problem is still persisting
