### ISSUE TITLE
Need help creating a new instance in a join table

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#625]
**\* The error I keep getting is:

undefined method `address' for #Emergency:0x007f8c51511000

```
<%= form_for @emergency, url: emergencies_path, method: :post do |f| %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.submit "LOG IN" %>

<% end %>
```

I'd like to submit a post request on the f.submit button when a user submits this form. This form is in the EMERGENCIES views, called new.html.erb. The Emergencies table is the join table between my two self referential User id's.

  emergencies POST   /emergencies(.:format)     emergencies#create

^^ that is my rake routes for posting an emergency.

I think the problem has to do with the f.label and f.text field.

In order to even access this form, the user has to be signed in. All I want the user to have to do is to enter the address of the building where the new emergency is taking place, so in other words, only one form field, and then a submit button. I want it to be able to already know the user object that is signed in. I have access to @current_user already. How can I create this form utilizing @current_user?

I would like the firestation to be able to pass through an address, and then I want the program to iterate through that address finding all the pet_owners at that address.

Thanks

**Comment by andrewsunglaekim** [comment]
sounds like you'll have to do just a regular form_tag instead of a form builder. Because your post request not only creates the emergency for the user creating it, but also seems like you'd be creating an emergency for each pet owner. It kind of seems like there needs to be a join between pet_owners and emrgencies

**Comment by andrewsunglaekim** [comment]
so it wont fall under the normal crud functionalities that we went over
