### ISSUE TITLE
Form builder issue within an enumeration? 

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#626]
This is the users SHOW page (show.html.erb). 

```
    <% @current_user.emergencies.each do |emergency| %>

      <div class="emergency">

        <div class="firestation_status"
          <h1>FIRESTATION STATUS:</h1>
        </div>

        <div class="user_status"
          <h1>MY STATUS:</h1>
          <%= form_for emergency, url: emergency_path(emergency.id) do |f| %>
            <%= f.button  :submit, name: "user_status", value: "Safe" %>
          <% end %>
        </div>

      </div>

<% end %>
```

Here is the user show action in the user controller:

```
def show
    @user = User.find(params[:id])
end
```

I am not declaring @emergency here because, being on the user's show page, the route only has the id param available for user meaning I wouldn't be able to explicitly use a @emergency = Emergency.find(params[:id]) type of thing. However, I do have access to each emergency because in the above code I am enumerating through each instance using @current_user.emergencies.

In the "user status" div, notice I am attempting to have a button available that, when clicked, will send a put request to THAT INDIVIDUAL emergency instance, and update the value in it's column called user_status. However, when I click SUBMIT, nothing happens (which indicates no error), but the problem is when I look in my rails console and look at Emergency.all, neither of the two emergencies have their user_status column changed. Both values are still nil (as they are nil by default upon an instance's creation). I expected one of them to change to the value "Safe".

I'm guessing (and hoping) that this is simply an issue with form builder not being able to be nested inside an enumeration. Either that or I'm just not setting up the form parameters correctly. 

This is the main functionality behind my app. Once I get this working, the backend of my app will be pretty much complete and everything else will fall into place.

Any help?

Thanks

**Comment by andrewsunglaekim** [comment]
whats the action when you inspect the form in chrome?

**Comment by superbuggy** [comment]
I might try `f.submit` also if it seems like the form keeps returning an empty hash

**Comment by andrewsunglaekim** [comment]
reopen if you have an isse with this still
