### ISSUE TITLE
Saving HTML5 Canvas as an Image and Uploading it to the Server with Rails

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/project2#627]
Here's my project repo: https://github.com/megancoyle/map_sketch

I've set up CarrierWave and AWS so that I'm able to upload files to the server with a file upload field. I'd like to somehow use this functionality for the HTML5 canvas drawing element that I have on the form. Right now the user can save the canvas as an image locally via canvas2image JS. I'm struggling to figure out the approach to move forward with making it so the user can save the image to the server.

I've found these articles, but I'm not sure which direction I should go in:
http://stackoverflow.com/questions/18365189/save-canvas-to-image-on-server-upon-form-submit-with-rails
http://stackoverflow.com/questions/13198131/how-to-save-a-html5-canvas-as-image-on-a-server

**Comment by andrewsunglaekim** [comment]
that first one seems the most promising.

**Comment by andrewsunglaekim** [comment]
have you tried taht solution yet?

**Comment by megancoyle** [comment]
Not yet -- I've been googling like crazy at the moment. I'll reopen this issue if I'm unable to get any of these possible solutions to work.
