### ISSUE TITLE
Running tests, receiving error 

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/project2#628]
I'm trying to be able to add users and I am trying to run tests as I go, but I am receiving an error and a warning. I started with $rails test, but the console returns (below) that I don't have permission, so I tried $sudo rails test, but that didn't work. Below is the results from running $rails test: 

Run options: --seed 29097
# Running:

WARNING: Rails was not able to disable referential integrity.

This is most likely caused due to missing permissions.
Rails needs superuser privileges to disable referential integrity.

```
cause: PG::InsufficientPrivilege: ERROR:  permission denied: "RI_ConstraintTrigger_a_18504" is a system trigger
```

: ALTER TABLE "genres" DISABLE TRIGGER ALL;ALTER TABLE "movies" DISABLE TRIGGER ALL;ALTER TABLE "schema_migrations" DISABLE TRIGGER ALL;ALTER TABLE "ar_internal_metadata" DISABLE TRIGGER ALL

E

Error:
UsersControllerTest#test_should_get_new:
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "genres" violates foreign key constraint "fk_rails_0a6710c65a" on table "movies"
DETAIL:  Key (id)=(980190962) is still referenced from table "movies".
: DELETE FROM "genres"

bin/rails test test/controllers/users_controller_test.rb:4

Finished in 0.200303s, 4.9924 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

**Comment by andrewsunglaekim** [comment]
i think the test ran fine. THe referential integrity thing just seems to be a warning. I think what's causing your test to fail is a foreign key constrait on one of your models.

**Comment by andrewsunglaekim** [comment]
I think it's great to do testing, but I would forego testing while your still learning rails and get the CRUD functionality working first.

**Comment by danielanoir** [comment]
OK, sounds good. Thanks!

**Comment by andrewsunglaekim** [comment]
just reopen if you come back to this later!
