### ISSUE TITLE
late user story and erd submission

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/project2#63]
sorry I thought I had posted this before I left friday!  added erd !

**Comment by RobertAKARobin** [comment]
Can you link to it?

**Comment by mattscilipoti** [comment]
Please read: https://github.com/ga-dc/pbj-project2/blob/master/schedule.md

**Comment by edwardpark** [comment]
WOW. sorry about that,  here's the link https://github.com/edwardpark/ReMed4Me/blob/master/README.rdoc

**Comment by edwardpark** [comment]
link for full repo : https://github.com/edwardpark/ReMed4Me

**Comment by mattscilipoti** [comment]
It's about time.  10 points from Ravenclaw.  :)

**Comment by mattscilipoti** [comment]
Looking good. As discussed, it is appropriate for this project.

Please give a brief overview of your project.
Check your markdown formatting (you can preview in Atom).
