### ISSUE TITLE
Problem authenticating new user

### ISSUE THREAD

**Issue by johnestes4** [ga-wdi-exercises/project2#630]
I tried working in some authentication for user creation to check email formatting and encrypt passwords, but now I'm getting a "password can't be blank" validation error.

Here's my user.rb:

```
class User < ActiveRecord::Base
  attr_accessor :username, :email, :password, :password_confirmation
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, :presence => true, :uniqueness => {case_sensitive: false}, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => {with: EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }
  validates :password_confirmation, presence: true


  has_many :messages, through: :inboxes
  has_many :messages, through: :outboxes
end
```

The relevant code in users_controller:

```
def create
    @user = User.create!(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
      redirect_to '/'
    end
  end
```

And the form used:

```
<%= form_for @user do |f| %>
  <p> Username:</br> <%= f.text_field :username%> </p>

  <p> Email:</br> <%= f.text_field :email%> </p>

  <p> Password:</br> <%= f.password_field :password%></p>

  <p> Confirm Password:</br> <%= f.password_field :password_confirmation%> </p>

  <%= f.submit "Sign Up" %>

<% end %>
```

**Comment by andrewsunglaekim** [comment]
put a binding.pry at the top of your create action to see what the values of params is to see what you're getting in the create action. Seems like your passwords not getting through. Also, which flash notice are you getting?

**Comment by johnestes4** [comment]
I checked in pry and the correct values are there in the user_params. I'm getting the form is invalid notice.

**Comment by andrewsunglaekim** [comment]
what is the value of @user after the `create!`? Does it have stuff in it for a password.

**Comment by superbuggy** [comment]
make sure your strong params private method block includes permitting the password field

**Comment by johnestes4** [comment]
Every value is nil.

```
 id: nil,
 username: nil,
 email: nil,
 password_digest: nil,
 created_at: nil,
 updated_at: nil>
```

Am I using the has_secure_password function incorrectly? My understanding was that it would be able to take those input password values and encrypt them into password_digest, but maybe it's not doing that and it's just reading these as the wrong values.

**Comment by johnestes4** [comment]
The attr_accessors were the problem, once I removed that whole line it worked.
