### ISSUE TITLE
Setting fullscreen background video?

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#633]
I'm trying to avoid a jquery plugin and figure out how to do this purely with html and css. I finally got the video to show up, full width as expected, by using an embedded video_tag. But it wasn't playing at all - just a still image. Then I realized it's working just fine in firefox (autoplay, looping, and correct formatting), it just won't work in chrome.  So I figured I'd hardcode it to play with jquery, but that's not working out. Any troubleshooting tips would be much appreciated.

Here is my index.html.erb code in the welcome view, where you can see I added a script tag to try and "force" autoplay in chrome:

```
<%= video_tag "dark_storm_clouds_CLIPCHAMP_480p.mp4", controls: false, autoplay: true, loop: true, id: 'fullvid' %>
<script type="text/jquery">
$(document).ready(function() {
  $("#fullvid").play();
});
</script>
<div class="welcome">
  <h1>Dreamscape</h1>
  <button><a href="#">Sign up / Login</a></button>
  <button><a href="/dreams">See a Demo</a></button>
</div>
```

And here's the css that targets it, for reference:

```
#fullvid {
  position: fixed;
  top: 50%;
  left: 50%;
  min-width: 100%;
  min-height: 100%;
  width: auto;
  height: auto;
  z-index: -100;
  transform: translateX(-50%) translateY(-50%);
}
```

If it helps, I can see the element in the chrome browser's console and it displays the element like so, no errors thrown:

```
<video autoplay="autoplay" loop="loop" id="fullvid" src="/videos/dark_storm_clouds_CLIPCHAMP_480p.mp4"></video>
```

**Comment by superbuggy** [comment]
try this: 

``` html
<video autoplay="autoplay" loop="loop">
    <source src="/videos/dark_storm_clouds_CLIPCHAMP_480p.mp4" >
</video>
```

**Comment by aubreynortham** [comment]
It's.... so beautiful. So functional. Thank you!
