### ISSUE TITLE
Updating attributes in one click (incrementing by 1)

### ISSUE THREAD

**Issue by EvanSanderson** [ga-wdi-exercises/project2#634]
Heyoo there friends,

In my app, there are Players, Decks for those Players, and Matchups for those decks. Two of the properties of both decks and matchups are "wins" and "losses".

I'm currently trying to implement a feature that allows the user to click a button("Add A Win") and add +1 to the wins attribute (and do the same thing for the losses). Currently, users can update their deck via an edit page and add a win in a text field (say, if there were 3 wins and they want to add an additional, they'd just write 4, which is kind of lame).

I'd love for them to be able to increment wins and losses in an easier manner through a click. I've tried creating a method in the Deck controller that looks like: 

```
def increment_wins
@deck.wins.increment!
end
```

but I'm not sure where to call it, or how to create like a partial form that would let me modify the wins attribute.

**Comment by andrewsunglaekim** [comment]
seems like you should be able to just make a form that will update, instead of calling normal action call the increment_wins. Maybe something like this in your `config/routes.rb`:

```
put '/decks/:id/increment_win' => 'decks#increment_win'
```

**Comment by andrewsunglaekim** [comment]
check this branch of the [reminderly repo](https://github.com/ga-wdi-exercises/reminderly/blob/mark_complete/config/routes.rb). In this application theres a feature to mark a todo complete. Follow the put request from `routes.rb` to the controller. What you're trying to do is going to be really similar.

**Comment by EvanSanderson** [comment]
So I followed your advice, and this is my code:

in decks controller: 

```
  def increment_wins
      @deck = Deck.find(params[:id])
      @deck.wins += 1

      redirect_to player_deck_path(@deck), notice: "Added a win!"
    end
```

in routes:

```
  resources :decks do
        resources :cards
        resources :matchups
        put "increment_wins", on: :member
    end
```

in deck show view:

```
<p> <%= link_to 'Add a Win', increment_wins_player_deck_path(@deck.player, @deck), method: :put %> </p>
```

When I click the Add a Win link nothing happens at all. The page reloads, but no wins are tallied.

**Comment by superbuggy** [comment]
are deck `wins` an ActiveRecord prop? if so, call `.save` on `@deck` after you increment

**Comment by EvanSanderson** [comment]
YOU'RE A GENIUS! YOU'RE ALL GENIUSES! PIES FOR EVERYONE!
