### ISSUE TITLE
Creating 2 of the same params with one form problem

### ISSUE THREAD

**Issue by VansPhan** [ga-wdi-exercises/project2#635]
I am creating a new pokemon and assigning it moves on creation (moves is a table by itself in the database so I am just assigning a relationship with the newly created pokemon). 

```
<%= f.label :moves %>
<%= f.select :moves, options_for_select(Move.all.map{ |i| i.name }) %>
```

This will return me a key value of..

```
 "moves"=>"Scratch"
```

as params.

So how can I have 2 select boxes like so 

```
<%= f.label :moves %>
<%= f.select :moves, options_for_select(Move.all.map{ |i| i.name }) %>

<%= f.label :moves %>
<%= f.select :moves, options_for_select(Move.all.map{ |i| i.name }) %>
```

and return both as an array in the key value pair of the returned params
Like so..

```
 "moves"=>["Scratch", "Flamethrower"]
```

So far if I were to do this I would get only the last select option value as the only key value pair.

I am not the best at formulating questions so please let me know where to clarify. Thank you.

**Comment by andrewsunglaekim** [comment]
basically you want to pass in two moves as a parameter. how are you using the parameters afterward?

**Comment by VansPhan** [comment]
This is my controller for it

```

    def create
        @pokemon = Pokemon.new(pokemon_params)
    end

private

    def pokemon_params
        params.require(:pokemon).permit(:name, :cp, :description, :poke_type, :moves)
    end
```

Except I need an array of two moves to be pass in for the moves param, so far I just have the one string

**Comment by andrewsunglaekim** [comment]
but you said moves is another model. It can't be a property of pokemon. That where you use the`has_many` association

**Comment by andrewsunglaekim** [comment]
seems like there a many_to_many relationship between moves and pokemon. If you want to build instances of your join model when you create a pokemon. thats a different thing all together.

**Comment by superbuggy** [comment]
I think the many-to-many approach makes the most sense here. a join between Moves and Pokemon might be a LearnedMove

**Comment by VansPhan** [comment]
Everything is super duper awesome now. Thank you 💯
