### ISSUE TITLE
Foreign Keys..

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/project2#638]
Hi, I could use some help and an extra set of eyes to clear up the issue I'm having with my foreign keys for my many to many models. I've gotten far enough to get the association to work in the console but now it looks like I have an issue with my foreign keys. I am close to getting this stuff working but I need a final bit of help with the finer details

**Comment by andrewsunglaekim** [comment]
what errors are you getting? what have you tried, what's not working

**Comment by chaseTfreeman** [comment]
PG::UndefinedColumn: ERROR:  column "recipe_id" referenced in foreign key constraint does not exist
: ALTER TABLE "boxes" ADD CONSTRAINT "fk_rails_2bf5d6b41b"
FOREIGN KEY ("recipe_id")
  REFERENCES "recipes" ("id")
 ON DELETE CASCADE

**Comment by chaseTfreeman** [comment]
That is in reference to trying to edit my schema by removing a column

**Comment by chaseTfreeman** [comment]
Hi Andy, 

I've successfully recreated my models, schema and re-seeded my database. However now I can't access the actual data i.e. <%= recipe.title %> is no longer returning the title as it did before

**Comment by chaseTfreeman** [comment]
It still holds true in my console aswell.. still not putting data where it is supposed to be. After I create the objects with given titles, etc.. its returns them as "nil"

```
2.3.1 :006 > cake
 => #<Recipe id: 12, title: nil, ingredients: nil, directions: nil, image: nil, created_at: "2016-08-09 16:02:03", updated_at: "2016-08-09 16:02:03"> 
2.3.1 :007 > cakebox
 => #<Box id: 10, theme: nil, title: nil, image: nil, created_at: "2016-08-09 16:03:02", updated_at: "2016-08-09 16:03:02"> 
2.3.1 :008 > cake_in_box
 => #<Collection id: 1, box_id: 10, recipe_id: 12, created_at: "2016-08-09 16:05:52", updated_at: "2016-08-09 16:05:52"> 
```

**Comment by chaseTfreeman** [comment]
I have gone in and used the PSQL cli to look at my tables. The tables were populated with my seed data but the "titles", etc are not populated. The timestamps are accurate though which I believe is a give-away that the there is something going wrong with my migrations or schema when I re-created and re-seeded my app's tables.
