### ISSUE TITLE
issue with seeding my database

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#64]
I tried ___rake db:seed with a seeds.rb file shown below__. I expected **My database to seed with the data in the seeds.rb file_** to happen.___I received an error that there is an undefined method 'destroy_all' when called on my Prompt class. I also receive an undefined method when I use create or any other ruby method.  __ happened instead.

https://github.com/cameronfry11/prompt.git

Here's a link to my repo and the error is in my seeds.rb file. The error listed below:

Frys-MacBook-Pro:prompt cameronfry11$ rake db:seed
rake aborted!
NoMethodError: undefined method `destroy_all' for Prompt:Module
/Users/cameronfry11/wdi/projects/prompt/db/seeds.rb:21:in`<top (required)>'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in`block in load'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in`load'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in`load_seed'
/Users/cameronfry11/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by jshawl** [comment]
Active record models cannot be named the same as your rails application.

Either rename the app or the model. Or check out this answer: http://stackoverflow.com/a/4947517/850825
