### ISSUE TITLE
Have modal transition to another view?

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#640]
I've got this awesome page transition working for my app, but it works through opening and closing a modal on the same view page. I want to adapt it so that it can transition either to an individual "show" view page, or so that the modal can pull in the correct "show" view content without actually loading a new view. The transition is mostly powered by css, with a bit of js in the background. I'm not very familiar with modals, so I'm having trouble wrapping my head around what needs to change. Abandoning this transition is not an option, it's the highlight of my life right now. Can I accomplish this purely within the html? Any tips on where to start would be awesome :)

Here is the code from my dreams index page, where all the dream titles are displayed as divs and each div serves as a modal transition trigger. The modal-content section is what's pulling in generic but I ultimately need to customize (or redirect).

```
<div class="center">
    <% @dreams.each do |dream| %>
    <div class="dreambox"><a href="<%=dream_path(dream)%>" class="cd-btn cd-modal-trigger"><%= dream.title %></a></div>
    <% end %>
  </div>

<div class="cd-modal">
  <div class="modal-content">
    <h1>Dream Title</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad modi repellendus, optio eveniet eligendi molestiae? Fugiat, temporibus! 
    </p>
  </div>
  <a href="<%=dreams_path%>" class="modal-close">Close</a>
</div>
```

**Comment by andrewsunglaekim** [comment]
so you want to be able to click something on the modal to render a show view?

**Comment by aubreynortham** [comment]
Yep, I want to be able to click on a div and have my fancy transition render the dream's "show" content, whether that actually requires a different view or pulls the correct content into the modal, I'm not so sure.

**Comment by andrewsunglaekim** [comment]
well i imagine it'll depend largely on the confines of the dependency your using, do you have a gem or plugin you're using or just handrolling it?

**Comment by andrewsunglaekim** [comment]
come over to our table when you get a chance so i can see the code working in the browser.
