### ISSUE TITLE
How to access .emergencies on both petowners AND firestations

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#641]
When I try to do firestation.emergencies or petowner.emergencies it says undefined method -_-
Am I setting up the model wrong? Maybe the migration is set up wrong? Pretty confused on what foreign_key does and where to put it etc. Thanks!

```
class Firestation < ApplicationRecord
  has_many :emergencies
  has_many :petowners, through: :emergencies
end

```

```
class Emergency < ApplicationRecord
  belongs_to :firestation
  belongs_to :petowner
end
```

```
class Petowner < ApplicationRecord
  has_many :emergencies
  has_many :firestations, through: :emergencies
end
```

**Comment by TyRyanR** [comment]
Also having problems overall with my program. Could definitely use some in person help. Thanks

**Comment by andrewsunglaekim** [comment]
that all looks correct, whats the entire error message say
