### ISSUE TITLE
Base64 to encode/decode images when submitting them through forms

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/project2#642]
I have the pieces for what I need to do, but I'm having trouble putting them together the right way.

On my app, users can draw on an html canvas with JS. On submit of the form where they're creating a new drawing, I want the JS drawing to get converted to an image and store it in the database. So far I've converted the drawing to an image so the user could actually right click the drawing and save it as a PNG. I managed to achieve that with this:

`var img = new Image;
    img.onload = function(){
     ctx.drawImage(img,0,0);
    };
    img.src = window.mapImgUrl;`

I've also managed to add the piece to convert the image to a data URL:

`var dataUrl = canvas.toDataURL();`

Although I'm struggling with figuring out how to add the on submit within rails where I can send this data to the database. Is this something I can just add to my JS and retrieve the result in the rails views?

**Comment by megancoyle** [comment]
hmm, apparently toDataURL throws a security error in JavaScript since I'm pulling the background image form the Google API: http://stackoverflow.com/questions/36609668/todataurl-throw-an-security-error

I'm trying to wrap my mind around any other solutions...

**Comment by megancoyle** [comment]
I feel like the solution might have something to do with this, but still struggling to figure it out:

https://gist.github.com/ifightcrime/9291167a0a4367bb55a2

**Comment by andrewsunglaekim** [comment]
yeah, thats a tricky one. this is kind of a work around. Have your file upload to like an image hosting site. then just pass the url into the form as a string?

**Comment by andrewsunglaekim** [comment]
also that code looks like it could work for you.. potentially. Although its unclear where the rubber meets the road

**Comment by megancoyle** [comment]
since the image is something static on the page, I'm really struggling to figure out how to submit/alter something that isn't in a field. Do I need to target it with javascript or something?

**Comment by megancoyle** [comment]
@jshawl I took a break from this to work on other parts of the app, but with console.log() I got this:
![screen shot 2016-08-09 at 9 00 33 pm](https://cloud.githubusercontent.com/assets/13081618/17538544/7819635a-5e74-11e6-9c18-ca059ea0ec6e.png)

for the following:

```
var dataImage = btoa(img);
var imageFromData = atob(dataImage);

console.log(dataImage)
console.log(imageFromData)
```

where the img refers to the canvas element. I'm stuck on the form submission part - does it make sense to fiddle around with AJAX and add an event listener for this form to submit the data at the same time it's submitting the form via the usual rails form submission? http://stackoverflow.com/questions/21662836/send-form-data-using-ajax

**Comment by jshawl** [comment]
What if you added a hidden input, set the value to the base64 encoded string, and then submitted the form?

**Comment by megancoyle** [comment]
Good idea, although now I'm realizing just using atob and btoa methods don't seem to properly encode/decode. There's something more to it...think I'll just have to give up on this one soon.

**Comment by superbuggy** [comment]
I know you probably have hacking-fatigue with this but might this be a solution?
https://html2canvas.hertzen.com/examples.html

**Comment by megancoyle** [comment]
@superbuggy so much hacking-fatigue. Apparently even with screenshot scripts, you get a "tainted canvas may not be exported" because of the Google API. I'll keep looking for a solution to this, although 'fraid it won't be in time for tomorrow.

**Comment by superbuggy** [comment]
your hacking-endurance is admirable!

**Comment by megancoyle** [comment]
Woohoo, this resolved the weird tainted canvas error: http://stackoverflow.com/questions/20027839/todataurl-throw-uncaught-security-exception

**Comment by megancoyle** [comment]
it's working, it's working!

```
document.getElementById('create-drawing').addEventListener('mouseover', function(){
            var dataUrl = canvas.toDataURL("image/jpeg");
            var dataImg = document.createElement('img')
            dataImg.src = dataUrl
            document.body.appendChild(dataImg)
  });
```

Just by adding this where the canvas is defined: 
`img.setAttribute('crossOrigin', 'anonymous');`

Now I just need to figure out sending the string to the database...

**Comment by megancoyle** [comment]
@jshawl I tried to add the string value to the form by appending a new field, although that didn't seem to work:

```
document.getElementById('create-drawing').addEventListener('mouseover', function(){
            var dataUrl = canvas.toDataURL("image/jpeg");
            var dataImg = document.createElement('img');
            dataImg.src = dataUrl;
            var drawingField = document.createElement('div');
            drawingField.innerHTML = "<input type='hidden' name='drawing[drawing_image]' id='drawing_image' value='" + dataImg.src + "'>"
            document.getElementById('map-drawing').appendChild(drawingField);
    });
```

I'll keep trying a couple of different ways to add this, but is there a better way to incorporate this data in the form so it gets submitted to the database?

**Comment by megancoyle** [comment]
Also tried adding a hidden input field on the rails form and then changing the value via javascript in the separate script file. Still no luck with that. So close...

**Comment by andrewsunglaekim** [comment]
what is the data type that `toDataURL()` returns?. I don't really see a way you can pass that info without the use of `$.ajax()` if what you did didn't work. what are the parameters in that fieldin the first attempt?

**Comment by andrewsunglaekim** [comment]
!!!!
