### ISSUE TITLE
Many to many controller help

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/project2#643]
I'm not sure if it's my controller or my code in views that is not letting me access my code. 

Please help

**Comment by nayana487** [comment]
are you getting an error? what do you mean you can't access your code?

**Comment by chaseTfreeman** [comment]
undefined method `collections' for #Box::ActiveRecord_Relation:0x007f9811d729a8
Did you mean?  collect
               collect_concat
               connection
Extracted source (around line #33)

```
                <h3><%= box.theme %></h3>
                <h4><%= box.title %></h4>
                <% @boxes.collections.each do |collection| %>
                <h2><%= box.recipe_id %>
                  <% end %>
```

**Comment by chaseTfreeman** [comment]
by can't access the code I mean that I cannot access and use the attributes I want from the join model (i.e. box_id, and recipe_id)

**Comment by nayana487** [comment]
Do you have the relationships set up in your models?

**Comment by chaseTfreeman** [comment]
```
class Box < ApplicationRecord
has_many :collections, dependent: :destroy
has_many :recipes, through: :collections

end


class Collection < ApplicationRecord
  belongs_to :box
  belongs_to :recipe
end

class Recipe < ApplicationRecord

  has_many :collections, dependent: :destroy
  has_many :boxes, through: :collections

  mount_uploader :image, ImageUploader


end
```

**Comment by chaseTfreeman** [comment]
I think it may have to do with my routes. I don't have anything different in my routes since I created my Join Model
