### ISSUE TITLE
Do I need to nest my routes

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/project2#644]
I'm trying to follow along with the lesson plan but it is based off of nested routes which I do not have. Is it a pre-requisite for the type of association I am trying to do (add many recipes to any/many boxes)

**Comment by andrewsunglaekim** [comment]
it totally depends on your domain model, if you want to emulate what we did in class then yes.

**Comment by chaseTfreeman** [comment]
Could you help walk me through making a new form for adding recipes to boxes. The controller stuff is confusing me

**Comment by andrewsunglaekim** [comment]
what have you tried, whats breaking?/not working the way you intended

**Comment by chaseTfreeman** [comment]
the code isn't really breaking, I just can't wrap my head around making a new form to create a recipe for a specific Box. The rails guide just side-steps the actual process in figuring this out

```
In short, you can just pass the model instance and have Rails figure out model name and the rest..
```

**Comment by andrewsunglaekim** [comment]
this seems like a good reference https://hackhands.com/building-has_many-model-relationship-form-cocoon/

I don't want to just walk you through it. I think this will be much more valuable for you to struggle with this. That said, implement some things on this blog post and if its still not working, give us another buzz. This is just one example, you don't have to follow this to a tee, but more to use as a reference.
