### ISSUE TITLE
Weird reloading issue

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#645]
My main model doesn't have a show view because it uses a modal that acts like a show view instead. So I've eliminated that "show" route and/or link everywhere I can think of, including listing it as an exception in the resources of routes.rb. Usually the modal behavior works normally (seems like any time the page is hard refreshed, or if the user has routed there from a controller "redirect" action) BUT there are weird cases, like when the user gets to the index through the nav bar, when the modal trigger doesn't work unless there is a hard refresh. Page loads as normal, but functions aren't the same. Any idea how I can fix it without manual hard refresh?

**Comment by andrewsunglaekim** [comment]
so the modal doesn't work when you go to the index from the nav bar?

**Comment by jshawl** [comment]
remove turbolinks, check out http://blog.steveklabnik.com/posts/2013-06-25-removing-turbolinks-from-rails-4

**Comment by andrewsunglaekim** [comment]
sounds like a [turbo links issue](http://stackoverflow.com/questions/18555020/js-in-rails-app-only-loads-the-first-time)

**Comment by aubreynortham** [comment]
I removed all the turbolinks references following that 4-step article above, but I guess that removed the connection for all my css to pull in? Looks like I made it angry.

**Comment by andrewsunglaekim** [comment]
you don't want to take any css links out of there only the things that say turbolinks for js

**Comment by andrewsunglaekim** [comment]
or just the parts taht says turbo links in the css link

**Comment by aubreynortham** [comment]
Oops, that makes a lot more sense. Seems like it took care of the issue! Thanks team!

**Comment by andrewsunglaekim** [comment]
great!
