### ISSUE TITLE
Rendering and Dynamically adding values issue 

### ISSUE THREAD

**Issue by ahmedelk91** [ga-wdi-exercises/project2#646]
Hello, 

I am attempting to dynamically add the variable of "calories" in a "meal" form to the variable "total_calories" in the "day" model. I would like for the value of "total_calories to render in both the index and "day" show page. 

I am using the following code on both the index and show pages:

```
<%= @day.total_calories += @meals.calories %>
```

When I visit the index, I get the following error: 

```
undefined method `total_calories' for nil:NilClass
```

If I comment out that line in the index, the index will render. However, once I create a new "meal" I get the following error in the show page: 

```
undefined method `calories' for nil:NilClass
```

I am not sure how to proceed. Please provide any guidance possible. Thank you!

**Comment by andrewsunglaekim** [comment]
seems like neither `@day` or  `@meals` is defined in the view
