### ISSUE TITLE
 rescue_from ActiveRecord

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#647]
I'm having an issue using this helper in the Application controller:

``` ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record
  before_action :authenticate_user!

  private
  def couldnt_find_record
      redirect_to root_url, notice: "That record does not exist!"
  end
end
```

When I try to navigate to a page such as root/tweets/8675309 it's still rendering a show page but with no content. This is unexpected since I would like it would throw me back to my home with the described error?

Am I crazy?

**Comment by andrewsunglaekim** [comment]
can you show the `show` action in your controller

**Comment by andrewsunglaekim** [comment]
and also your view that handles that action

**Comment by ghost** [comment]
We're good to go! I just checked all of them before posting and found the error. Thanks!
