### ISSUE TITLE
issue with messaging

### ISSUE THREAD

**Issue by mfournier91** [ga-wdi-exercises/project2#648]
I tried to implement a messaging feature. I expected to be able to post messages to a convo. I got an attribute error.
My [repo link](https://github.com/mfournier91/BarApp-Project2WDI/tree/messaging) and my question is about file `app/controllers/messges_controller.rb lines 31 && [37..40]`.

**Comment by andrewsunglaekim** [comment]
which attribute was erroring out?

**Comment by andrewsunglaekim** [comment]
sorry for lateness, didn't see til this am!

**Comment by andrewsunglaekim** [comment]
also could you link your `schema.rb`

**Comment by mfournier91** [comment]
https://github.com/mfournier91/BarApp-Project2WDI/blob/messaging/db/schema.rb It's alright. I had a different problem when I approached you in person but then I started to debug so I had to wait until I hit another wall to make an issue.  My error message is 
unknown attribute 'user_id' for Message  in MessagesController#create  (around line #31)

**Comment by superbuggy** [comment]
does @conversation have scope in the MessagesController?

**Comment by mfournier91** [comment]
class MessagesController < ApplicationController
before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

rake routes ...
                             POST   /conversations/:conversation_id/messages(.:format)                   messages#create
...
