### ISSUE TITLE
Server already running when 'rails s'

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#650]
Having trouble getting to localhost:3000

```
Tylers-MacBook:Petsafe Tyler$ rails s
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /Users/Tyler/wdi/projects/Petsafe/tmp/pids/server.pid.
Exiting
Tylers-MacBook:Petsafe Tyler$ 
```

**Comment by andrewsunglaekim** [comment]
kill your terminal and restart it. 

If that doesn't work try restarting computer.

**Comment by superbuggy** [comment]
in the same directory, try `spring stop` also, if that doesn't work. `spring status` will show if a server is running in a particular directory

**Comment by superbuggy** [comment]
did either of these approaches work?

**Comment by TyRyanR** [comment]
Yep thanks guys. Closing issue.
