### ISSUE TITLE
Form to create nested resource not working

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#651]
I have a many to many relationship between a dreams model and a classifications model (join model = tags), and classifications are nested in dreams. I want the "edit" view for dreams to contain a form allowing users to create classifications for their dreams. I cannot get this form right, I've been failing miserably for 2 days. The error says this: First argument in form cannot contain nil or be empty. Here is the chunk of code causing problems (error always points to first line):

```
  <%= form_for ([@dream, @classification]) do |f| %>
    <%= text_field_tag :name %>
    <%= f.submit "Create Tag" %>
  <% end %>
```

**Comment by superbuggy** [comment]
are both @dream and @classification defined in your controller? is @tag nested in @dream?

**Comment by superbuggy** [comment]
this reference may be useful: http://stackoverflow.com/questions/2034700/form-for-with-nested-resources

**Comment by superbuggy** [comment]
More supplementary information: http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormOptionsHelper/collection_check_boxes

2 articles from SO:
http://stackoverflow.com/questions/17435937/checkbox-for-many-to-many-relationship
http://stackoverflow.com/questions/15452488/checkbox-form-in-ruby-on-rails-based-on-many-to-many-relationship

**Comment by aubreynortham** [comment]
I'm actually really confused about how I need to be defining @classification in my controller also. When I define the dream controller (for edit, update, and create) with this info:
  def edit
    @dream = Dream.find(params[:id])
    @classification = @dream.classifications
... I no longer get the "First argument in form cannot contain nil or be empty" error, but instead I get this error: "undefined method `to_key' for #<ActiveRecord::Associations::CollectionProxy []>
Did you mean?  to_query / to_set / to_ary"
