### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/project2#654]
I just added an image attribute to my nested resource (movies). The image is showing up as a tiny box on the screen and not as the actual image. Below is my code: 

`<p>
  <strong>Image:</strong>
  <img src= "<%= movie.photo_url %>" width="200px"></img>
</p>`

Below is a link to my repo: 

https://github.com/danielanoir/project2/commits/master

**Comment by superbuggy** [comment]
can you screenshot or link the specific file in question?

**Comment by danielanoir** [comment]
[image: Inline image 1]
