### ISSUE TITLE
devise gem

### ISSUE THREAD

**Issue by jacahn** [ga-wdi-exercises/project2#655]
Hi guys, I am having trouble after having installed Devise. I used to have "reviewers", but changed the word to "users" in my project.

**Comment by jacahn** [comment]
This is the error I'm getting:

```
NoMethodError in ReviewsController#create
undefined method `user_id' for nil:NilClass

Extracted source (around line #10):
8
9
10
11
12
13

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    @review.user_id = current_user.user_id

    @review.save
    # redirect_to review_path(@review)
```

**Comment by superbuggy** [comment]
you will have to rename your controllers and anything that is named reviewers-- try CMD+Shift F to search your entire codebase

**Comment by superbuggy** [comment]
try create instead of new
  @review = @restaurant.reviews.create(review_params)
  @review.user_id = current_user.user_id

**Comment by jacahn** [comment]
Yes, I renamed all the reviewers to "user".

**Comment by jacahn** [comment]
It's having trouble with this line of code

```
    @review.user_id = current_user.user_id
```

Where it's extracted from:

```
NoMethodError in ReviewsController#create
undefined method `user_id' for nil:NilClass

Extracted source (around line #10):
8
9
10
11
12
13

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)
    @review.user_id = current_user.user_id

    @review.save
    # redirect_to review_path(@review)
```

**Comment by jacahn** [comment]
This error happens when I try to add a review w/o logging in on the Restaurant show page.

Before Devise I was able to add reviews w/o being logged in, which is what I intended.

**Comment by superbuggy** [comment]
I suspect current_user is undefined here because there is no user logged in--does that seem to fit?
