### ISSUE TITLE
Could use a quick one on one for a few things - listed below - Thanks!

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project2#658]
1) How to blacklist non-signed in people from typing in a random route in the URL bar and accessing that page

2) Where to use jQuery in the rails app

3) Issue with my form submit buttons not displaying the correct value

Thanks,
Tyler

**Comment by andrewsunglaekim** [comment]
Example of using auth

``` ruby
def index
  @current_user = User.find(session[:user_id])
  if @current_user
    # do something that only a user can do
  else
    redirect_to root_url, notice: "not logged in!"
end
```

In `app/assets/javascripts/application.js`. Don't remove any of the commented code, just start writing jquery.

What issue are you having with your submit button?

**Comment by TyRyanR** [comment]
It's not allowing me to change the string value of the button because I am already passing in the value as a string to the database column

**Comment by andrewsunglaekim** [comment]
can you be more specific? can you point to parts of your code?

**Comment by TyRyanR** [comment]
Sure.
Below is an example. Based on the functionality of the app, I need to be able to press a button and have a string value be passed to a certain column in any given emergency instance. Below I am accessing the specific emergency, accessing the column "user_status" in the emergency instance, and entering the string value automatically of either "Safe with owner" or "Home alone-permission to enter". For some weird reason I can no longer change the text that the button displays as.

```
  <%= form_for @emergency, url: emergency_path(@emergency.id) do |f| %>
              <%= f.button :submit, name: "user_status", value: "Safe With Owner" %>
            <% end %>

            <%= form_for @emergency, url: emergency_path(@emergency.id) do |f| %>
              <%= f.button :submit, name: "user_status", value: "Home Alone - Permission To Rescue" %>
            <% end %>

```

**Comment by nayana487** [comment]
Try this: <%= f.submit "My Submit Text" %>

http://stackoverflow.com/questions/4769483/rails-3-form-how-to-change-the-text-on-the-submit-button

**Comment by andrewsunglaekim** [comment]
what she said

**Comment by TyRyanR** [comment]
Awesome! For some reason it works with f.submit but not with the f.button format. I'll close the issue.
