### ISSUE TITLE
git troubles with Mac

### ISSUE THREAD

**Issue by pamelaolney** [ga-wdi-exercises/project2#659]
My laptop's charger died.  Perfect timing...

So I am using a Mac from GA and having troubles with merging my changes.  How do I gain permission to push my changes up to my repo?  I keep getting this error every time I try.

`
Generals-MacBook-Air-3:uppercut generalassembly$ git push origin master
remote: Permission to pamelaolney/uppercut.git denied to rebeku.
fatal: unable to access 'https://github.com/pamelaolney/uppercut.git/': The requested URL returned error: 403
`

I initialized the directory that I placed this project in with git init.
I git pulled the project.
It allows me to add and commit.  Just not push.

Read this article https://wincent.com/wiki/Git_repository_access_control but not sure how to apply the information.  Please help.

**Comment by andrewsunglaekim** [comment]
think you need to set up ssh on github, sec lemme find link

**Comment by andrewsunglaekim** [comment]
https://github.com/ga-wdi-lessons/git-ssh

**Comment by andrewsunglaekim** [comment]
also, since it isn't your computer, i might recommend doing http instead of ssh, and just putting in your username and password each time.

**Comment by pamelaolney** [comment]
I cloned using http.  But it still wouldnt let me push

**Comment by andrewsunglaekim** [comment]
did it ask you for username/password?

**Comment by pamelaolney** [comment]
it never asked.  this laptop also does not have rails.  I am not sure if that is affecting anything.

when I typed sudo gem install rails it seems like it is telling me that the version of ruby is too old to install rails. 

When i try to install ruby to update it by typing ruby-install it says that install is not a command.  not sure how to move forward
