### ISSUE TITLE
Can I use users in my nested routes?

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#66]
I decided to use users and posts for my app and took out comments. I have been converting my users and posts files. I needed reminders of syntax and looked back at scribble, but we never converted our files to reflect users as being above posts. I would like to change my paths to users_posts_path but am not sure if that is necessary. 

If it is true, do I have to include comments to fulfill the 2 model requirement. I am not sure if that made any sense.

**Comment by RobertAKARobin** [comment]
That's fine! But it may be tricky if you're using Devise. And yes, Users count as a model!

**Comment by mattscilipoti** [comment]
Agreed.  Also, if you are listing posts for the current user, you don't need the user in the url - you already know the current_user.

**Comment by malissaromero** [comment]
I decided to not us Devise because I am still shaky on user authentication so I am using this as a crash course. Thank you for the help!

**Comment by malissaromero** [comment]
I am having issues with users as the parent of post. I am getting errors stating that in my paths a user_id is needed as a parameter. I am not understanding why post erbs needs a user id. My reaction would be to remove user id from the private method in post controller and from the column in my migrations but then I might have issues later. 

![screen shot 2015-08-03 at 4 09 19 pm](https://cloud.githubusercontent.com/assets/11203264/9046649/1875d7e8-39fa-11e5-9b7b-29399256585c.png)

**Comment by andrewsunglaekim** [comment]
you need to pass in a user as an argument for `user_posts_path`

**Comment by malissaromero** [comment]
Can you explain why that would be? I want any anyone to be able to see the post index page. I even included "skip_before_action :authenticate, only: [:index]" in my posts controller for that reason.

**Comment by mattscilipoti** [comment]
You used the `user_posts_path` helper in your link_to.  That named routes helper requires a `user`.  You can see this as a named parameter `:user_id` in `rake routes`.

If you want to list all the posts, you need a route that supports that.

**Comment by malissaromero** [comment]
I ended up going with the following code and it is working great so far. 

```
resources :users do
    resources :posts, only: [:index]
  end

  resources :posts do
  end

```
