### ISSUE TITLE
Nested form issues

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#660]
I don't understand how to make sure this form for tags is only pulling in for the dream I'm showing, not the tags for all dreams created. And I also can't figure out why this code is displaying twice on the same page, like a loop. 

```
    <!-- list the tags, if there are any -->
    <% @dreams.each do |dream| %>
    <% if dream.tags.length > 0 %>
    <h4>Tags:</h4>
    <%= render dream.tags %>
    <% end %>
    <% end %>

    <!-- option to create tags -->
    <h4>Create a tag:</h4>
    <% @dreams.each do |dream| %>
    <%= form_for [dream, dream.tags.build] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
    <% end %>
```

**Comment by andrewsunglaekim** [comment]
seems like for each dream your doing this thing with tags(making an h4 for tags and rendering all the dreams tags)

then for each dream you're creating a form to build a tag for each dream. This seems like functionality that should go in a dream show page.

**Comment by aubreynortham** [comment]
Seems like I should just GIVE UP ON ALL MY DREAMS THEN.

**Comment by andrewsunglaekim** [comment]
...!

**Comment by andrewsunglaekim** [comment]
I gota head to this AMA, but will follow up after its done. In the meantime, what errors and schtuff are you getting

**Comment by aubreynortham** [comment]
James just helped me achieve some of my dreams. Sorry for the uncontrollable dream puns. The issue has been resolved!

**Comment by andrewsunglaekim** [comment]
ok!
