### ISSUE TITLE
user authentication doing something unexpected

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project2#663]
I am using devise and I have this line in my application controller so that the user can access certain places without being logged in. The most important being the welcome page, which I've defined as the root. 

```
before_filter :authenticate_user!, :except => [:welcome, :show, :get_explore, :get_collective]
```

However, I'm realizing you actually can't access the welcome page at all unless you have already signed in. Shouldn't the "except :welcome" part of line above be preventing that?

**Comment by andrewsunglaekim** [comment]
i dont think this neccessarily has any problems, but `before_filter` is deprecated and `before_action` should be used instead.

**Comment by andrewsunglaekim** [comment]
are you able to enter the url manually for the welcome page and get to it without signing in?

**Comment by aubreynortham** [comment]
I tried replacing before_filter with before_action, but in both cases I'm unable to manually type in the url to access the page. It sends me straight to the /user/login instead. The only time I can access the root url is when a user is signed in, which is ironically the only time I don't want a user to access the root url.

**Comment by andrewsunglaekim** [comment]
interesting, let me finish up here and i'll take a look

**Comment by superbuggy** [comment]
can you post your `routes.rb`?
