### ISSUE TITLE
citizen's hopper displaying bills from database

### ISSUE THREAD

**Issue by mrnelley** [ga-wdi-exercises/project2#664]
Trying to post bill information to the get_bill view
 tried creating the loop for displaying info for each bill error says unexpected keyword end? 
should i be approaching this a different way?

**Comment by mrnelley** [comment]
Aside from that rake is not recognizing the resources from usercreatedbills or authorships tables

**Comment by mrnelley** [comment]
fixed usercreatedbills and authorship routes; however im getting a "missing application template" error for the home page now... there doesnt seem to be anything wrong with the application controller or the users controller at the root sign in page.

**Comment by andrewsunglaekim** [comment]
can you post the code thats causing the error. 

1.What is the name of of the file the template is looking for 
2. What path is it looking in?
3. Which controller action is doing that?
