### ISSUE TITLE
Problem with reviews not showing up

### ISSUE THREAD

**Issue by jacahn** [ga-wdi-exercises/project2#665]
After using Devise, the reviews do not show up on the screen. On reviews_controller.rb:

```
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    if current_user
      @review.user_id = current_user.id
    else
      flash[:alert] = "You must login to create new review"
    end

    @review.save
    # redirect_to review_path(@review)
    # @review = Review.create!(review_params.merge(user: current_user))
    redirect_to restaurant_path(@restaurant)
  end
```

**Comment by jacahn** [comment]
To be clearer: the reviews of current_users do show up, but if someone's not logged in, their reviews do not show up on the page.

**Comment by jacahn** [comment]
I suppose I could just not allow reviews if they are not logged in...

**Comment by andrewsunglaekim** [comment]
It totally depends on what you want to have happen. Are they not being created and therefore not showing? or is it an authentication issue? If its the latter than I would look into those actions that are causing that not create.

**Comment by nayana487** [comment]
We're ok on these now @andrewsunglaekim
