### ISSUE TITLE
Not sure how to implement join feature for an event

### ISSUE THREAD

**Issue by kscoulter** [ga-wdi-exercises/project2#68]
I made an associations table with user_id and event_id. Now I'm not sure how to render form_for correctly in order to pass the required params. I'd appreciate some in-person guidance.

**Comment by jshawl** [comment]
what did you try?

**Comment by kscoulter** [comment]
I'm lost conceptually, I'm not even sure what to try.

**Comment by jshawl** [comment]
ok ill come say hey!

**Comment by kscoulter** [comment]
I'm by classroom 2
