### ISSUE TITLE
Link doesn't work.

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project2#684]
I'm really interested in this photo upload feature.  I'd like to look at your mini lessons in addition to my own research, however, your link doesn't work...

![image](https://cloud.githubusercontent.com/assets/20567326/19389424/fdb174ca-91f1-11e6-8b6d-ea456c1757ac.png)

**Comment by nolds9** [comment]
The Gems to look into are either [Carrier Wave](https://github.com/carrierwaveuploader/carrierwave) or [Paperclip](https://github.com/thoughtbot/paperclip)

The link to mini-lesson is [here](https://github.com/ga-dc/wdi6-formerly-curriculum/tree/3071663bc9aaac00fe5eee4b11c171af60f826b5/mini-lessons/file-uploads-with-carrier-wave-and-aws)

**Comment by nolds9** [comment]
Going to go ahead and close this, but feel free to reopen with any other questions!
