### ISSUE TITLE
issue with creation/post routes for partially nested resources

### ISSUE THREAD

**Issue by jeffjones89** [ga-wdi-exercises/project2#69]
I currently have two models, companies and users. Companies is nested under users, but part of the functionality of the app is an index of all companies, and their associated user on an index page.

When trying to create a new company, I'm attempting to pull and merge the user ID into the params of the company. I've been able to create companies without the user ID passing in, but that A) isn't a good solution and B) breaks functionality when trying to list all companies, as certain companies will pull with a nil company.user and break the companies index page. 

I've been trying to cross reference the final Tunr app, when we associated artists with users to create a favorites tab but can't diagnose where I'm going wrong. I also asked Matt F to take a look and we couldn't make any headway there, either.

**Comment by andrewsunglaekim** [comment]
One thing you can do for the index page is do an if/else conditional that only lists the `company.user` if `company.user` exists. 

My next question is, how is the ID currently being added into the creation of a company? Is it through the form? Or is it through session?

**Comment by RobertAKARobin** [comment]
If you're using Devise, you can `current_user.companies.create!(company_params)`, and if not, you can `@user.companies.create!(company_params)`.
