### ISSUE TITLE
ERD Questions

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#690]
I am designing an app so that users can post items to sell, can browse, posted items for sell, add items to a cart, and checkout the cart to place an order (which will consist of multiple items they want to purchase). Below is my current ERD:

![image](https://cloud.githubusercontent.com/assets/21045394/19394445/3bf840a0-9207-11e6-80af-9cdd31913cac.png)

Questions: 
1. If I want to only allow users to post a single item for sale at a time, can I get rid of the "Listing" table and simple draw a one-to-many relationship from users to products (and if so, do I need to split "Products" up into multiple tables)
2. If I want a user to have a view for their "Account" through which they can view all their listed items and their placed orders, should I create a separate "Account" model that the user "has", or can that functionality be achieved by adding attributes to the "User" model that contain this data.

Thank you!

**Comment by AndyWhitley** [comment]
Update to ERD model:
Added 'cart' attribute to user that will contain an array of 'selected' items that upon 'checkout' will be converted into an 'order'
![image](https://cloud.githubusercontent.com/assets/21045394/19394882/0227f774-9209-11e6-9439-219a90ca4ad8.png)

**Comment by nolds9** [comment]
1. Just thinking out loud, you should be able to have the one to many with users to products, and the benefit being any newly created product will automatically be able to be "ordered". No need to split of product I don't think.
2. If your associations are set up right, looks like you can just use active record helper methods to find all of a user's associated orders + products. No need for the separate `Account` model I would say.

**Comment by nolds9** [comment]
@AWhitleyGA did that answer you questions, or should I leave this issue open?

**Comment by nolds9** [comment]
closing since we discussed IRL
