### ISSUE TITLE
Seeding Many 2 Many table

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#692]
I need some education here.  I have 3 tables projects, users and portfolios.  Here is the ERD 
![image](https://cloud.githubusercontent.com/assets/19254862/19399297/d893605e-921e-11e6-8f0c-adcba59d2e17.png)

My seed file works up until I get the part where I am [seeding the portfolios records](https://github.com/merubin/portfolio_management_system/blob/master/db/seeds.rb). Starting around line 86

I could use a sample or explanation on how to create records in this table.  It is still not clear to me how this table would not be normalized with repeating data for the title and description.  Please help me understand this.  Thanks,  Mike

**Comment by amaseda** [comment]
What error are you getting? That'll help guide the troubleshooting.

**Comment by merubin** [comment]
$ rails db:seed
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: User must exist, Project must exist
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:78:in `raise_validation_error'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:50:in`save!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in`block in save!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`block in transaction'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`transaction'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in`with_transaction_returning_status'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in`save!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:51:in `create!'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/db/seeds.rb:86:in`<top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in`block in load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in`load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:549:in `load_seed'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:268:in`load_seed'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in`block in run_rake_task'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in`run_command!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/bin/rails:9:in`require'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/bin/rails:9:in `<top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in`load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/command.rb:7:in`call'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/bin/spring:49:in`<top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in`<top (required)>'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/bin/spring:14:in `require'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/bin/spring:14:in`<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in`<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by merubin** [comment]
Did not mean to close it

**Comment by amaseda** [comment]
So you need to associate your Portfolio with a Project and User when you create it. Try setting those values inside of your `Portfolio.create( ... )` methods.

**Comment by merubin** [comment]
But how do I create multiple records for all the projects that I want associated with portfolio 1 and 2?
and not have repeating titles and descriptions?

**Comment by amaseda** [comment]
Talked about it IRL! Feel free to re-open if you have any more questions.
