### ISSUE TITLE
rails stuck

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#693]
Every time I try to run rails g migration, my command line freezes up. Tried spring stop to no avail. I even destroyed the whole folder and started from scratch twice but still freezing on rails g migration

![image](https://cloud.githubusercontent.com/assets/21045394/19401227/1e796312-9228-11e6-8294-8e8a769ee602.png)

**Comment by nolds9** [comment]
interesting, do you have a `rails server` running anywhere? What if you try running it a new tab?

**Comment by jshawl** [comment]
`ctrl-c` then `spring stop` - does that help?

**Comment by nolds9** [comment]
then `spring start`

**Comment by AndyWhitley** [comment]
I restarted my computer and it's working again. Initially it wasn't responding to ctrl-c / spring stop tho

**Comment by AndyWhitley** [comment]
All good now though. Thanks!

**Comment by jshawl** [comment]
ok great!
