### ISSUE TITLE
Setting Up User Model with Many to Many Relationship that Points to Self (Through another Model)

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project2#694]
[I did my best putting this into words. Let me know how I can clarify!]

I'm trying to write my User model, and I'm not quite sure the best way to establish ActiveRecord associations given my ERD (below). As you can see, a User has many expenses and many UserOwedExpenses. Should I also say that a User has many expenses through UserOwedExpenses?:

``` ruby
class User < ApplicationRecord
  has_many :expenses
  has_many :user_owed_expenses
  has_many :expenses, through: :user_owed_expenses
end
```

`has_many :expenses` and `has_many :expenses, through: :user_owed_expenses` seem like they should _both_ be there because those represent two different associations.

The third relationship would account for Expenses that a user is associated with by way of someone else's payment, e.g. "Matt bought TP for $30 (`user` --> `expense`). Jack (`user`) will be associated with that `expense` through the `user_owed_expenses` join table (because I need to know that Jack owes money to Matt based on Matt's expense). 

![image](https://cloud.githubusercontent.com/assets/2591447/19402064/f38a9ffe-922c-11e6-8097-fe7272975b5d.png)

**Comment by nolds9** [comment]
Yes, that looks right to me, you need to have all 3 lines in the model to account for both types of relationships. Try it out in the console and see if you get the right records back

**Comment by timfoley** [comment]
Thanks again for this Nick! 

And I think I'll be able to correctly associate things using [Self Joins](http://guides.rubyonrails.org/association_basics.html#self-joins)

**Comment by amaseda** [comment]
Closing this one but let us know if you have any more questions about this!
