### ISSUE TITLE
Sending CheckBox information to Backend for processing

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#697]
I have a page that now is showing a list of user projects.  Next to each project name is a check box. Here is the picture:
![image](https://cloud.githubusercontent.com/assets/19254862/19421064/31d62be4-93c6-11e6-8cff-5bc5f18ab832.png)

The code creates unique id's for each checkbox along putting in a string value with the project id, with the intent to see which projects for that user were checked so I can create a new portfolio out of those projects.  How do I send the list of checked projects to the backend when they will press the Create New Portfolio button?

Is there a way to add this list as Params to the route? Can I put in some javascript to create a list as they check the boxes?  I'm new to buttons and the functionality.  Is there some "On Click" that I can do here?

Here is the code for creating the projects:

```
<ul>
  <% i=0 %>
  <% @projects.each do |project| %>
  <label><input type="checkbox" id=<%="cbox" + i.to_s %> value=<%="id:"+project.id.to_s%>> <%=project.name %>></label><br>


  <p> <%=project.description %> </p>
  <% i=i+1 %>
  <% end %>
  <br>
  <p> <%=i%> Total Projects for User <%=@current_user.name %>
</ul>

```

**Comment by amaseda** [comment]
We talked IRL but let me know how this goes. For reference, here is the documentation on `check_box`: http://apidock.com/rails/ActionView/Helpers/FormHelper/check_box

**Comment by amaseda** [comment]
Going to close this one but let us know if you have any other questions about this!
