### ISSUE TITLE
Accidentally created a new repository inside my project repository

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#70]
I need help straightening out what I did with Git. I'm worried I'm losing work. I know it's not a real specific issue but I really need help to move forward. If Andy could come help me out that would be much appreciated!

**Comment by andrewsunglaekim** [comment]
whats your issue with git? Did you do a git init in your current repo?

**Comment by ghost** [comment]
I renamed my repository which was stupid and then I accidentally created a new repository inside my repository initially.

**Comment by ghost** [comment]
Then I cloned down my work from the github to try to start anew and I'm running into errors when trying to change the word prompt within my app

**Comment by RobertAKARobin** [comment]
As long as you didn't delete your `.git` folder, and have been committing somewhat frequently, you're fine. But Andy's on his way!
