### ISSUE TITLE
Loading in vendor javascripts 

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#700]
I am trying to load a the jquery library in locally. I may switch it a cdn later but want to figure out how to bring it in to the vendor/assets/javascripts folder first. 

<img width="1440" alt="screen shot 2016-10-17 at 9 49 54 am" src="https://cloud.githubusercontent.com/assets/21045394/19440450/fa79b2e4-944f-11e6-8fa4-2eba028a777d.png">

Also, in javascripts/application.js, // = require jquery is already there by default. However, it does not seem to be loading in when I open the console in the browser. 

<img width="1440" alt="screen shot 2016-10-17 at 9 50 25 am" src="https://cloud.githubusercontent.com/assets/21045394/19440531/387bf566-9450-11e6-9996-1471aa063a56.png">

**Comment by jshawl** [comment]
👍 jquery is already included with rails - how do you know it's not being included? what error message do you see? what does application.html.erb look like?

**Comment by AndyWhitley** [comment]
Nevermind, it was being loaded in. I was making syntax mistakes when testing it. Thanks!

**Comment by jshawl** [comment]
:+1: excellent!
