### ISSUE TITLE
Getting overwhelmed...

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#701]
Hey instructors,
I tried to plan my app the best way I knew how. Here are the views. I was wondering if someone could help me as I am getting overwhelmed by what I will need to build.

View - Show All Projects (only Managers can add Projects)
![view - all projects](https://cloud.githubusercontent.com/assets/8737117/19441494/e3eae90e-9453-11e6-838e-844f2fc122df.png)
subsequent View - Add Project
![view - add project](https://cloud.githubusercontent.com/assets/8737117/19441538/079ff916-9454-11e6-8294-4b3a55562bbd.png)

View (Worker) - Show All Hours
![view - all hours](https://cloud.githubusercontent.com/assets/8737117/19441572/1fd31342-9454-11e6-88a6-d1f9c9398bf1.png)

View (Worker) - Add Hours ( days are instantiated on the day, can't add future time )
![view - add hours](https://cloud.githubusercontent.com/assets/8737117/19441604/3cb2c2b4-9454-11e6-8158-0b31e359b803.png)

View (Worker) - Edit Hours
![view - edit hours](https://cloud.githubusercontent.com/assets/8737117/19441622/476c8276-9454-11e6-93fc-d8d7e4fdb65f.png)

This is my MVP I think...

Please help!

**Comment by nolds9** [comment]
Hey @mikeflores happy to chat about big picture questions, but as far as how to build the project, Im afraid thats up to you...I'd start by just getting `Project` 's full CRUD working, then move on from there.

**Comment by jshawl** [comment]
A good place to start would be seeds for `Project` - what attribute does a project have?

**Comment by ghost** [comment]
I see `Projects` as having a `name` and `total hours worked`. But those the hours come from a Worker logging in those hours. Also, I'm going to have multiple workers clocking in hours.

**Comment by jshawl** [comment]
ok great! have you created a migration for Projects with those columns?

**Comment by mikeflores** [comment]
I haven't run `db:migrate` yet but does this look alright?

model
![image](https://cloud.githubusercontent.com/assets/8737117/19445843/fda01bca-9463-11e6-9699-4d638c9078b1.png)

seeds.rb
![image](https://cloud.githubusercontent.com/assets/8737117/19445864/156c6812-9464-11e6-8612-7de2e5886dde.png)
