### ISSUE TITLE
checkout to new branch

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project2#702]
Hiii!!

I'm planning on checking out to a new branch to work on devise. How do it add it to my master branch when I'm done with the new branch?

**Comment by jshawl** [comment]
`git checkout master && git merge branch-you-created`

**Comment by pohckuan** [comment]
what do I enter after git checkout master if I don't want to merge the stuffs from the new branch?

**Comment by pohckuan** [comment]
I checked out to master, but the contents are still the same as the branch's

**Comment by nolds9** [comment]
@pohckuan what is the output of `git status`?

**Comment by pohckuan** [comment]
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   Gemfile
modified:   Gemfile.lock
modified:   app/models/ring.rb
modified:   app/views/layouts/application.html.erb
modified:   app/views/welcome/index.html.erb
modified:   config/routes.rb
modified:   db/schema.rb
```

Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
app/assets/javascripts/users.coffee
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
db/migrate/20161017150253_devise_create_users.rb
db/migrate/20161017154413_add_users_to_rings.rb
test/controllers/users_controller_test.rb
test/fixtures/users.yml
test/models/user_test.rb
```

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by nolds9** [comment]
so you want to get rid of all these changes?

``` bash
$ git add .
$ git stash
```

**Comment by pohckuan** [comment]
yes. I added new stuffs on my new branch and they messed up the page.

**Comment by pohckuan** [comment]
So I do 
$ git add .
$ git stash

at the master branch?

**Comment by pohckuan** [comment]
it did get rid of the changes on atom, however, the page still looks the same when I run rails s again

**Comment by nolds9** [comment]
@pohckuan what is the output of `git status`?

**Comment by pohckuan** [comment]
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

**Comment by pohckuan** [comment]
i did git push
my page still looks the same.

**Comment by pohckuan** [comment]
FIXED IT!!!
I just had to seed it again
