### ISSUE TITLE
Adding information to a form from different models

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project2#705]
When creating a new student I need to get information from two different models. I've tried different forms and variations of iterating through @languages and keep coming up with a no method error.

![image](https://cloud.githubusercontent.com/assets/15305847/19445802/d3320542-9463-11e6-9fac-367fe500091f.png)

my erd (Language only takes a language)
![image](https://cloud.githubusercontent.com/assets/15305847/19445894/40ea0e04-9464-11e6-99e9-3fe32183cba2.png)

**Comment by amaseda** [comment]
What error are you getting?

`check_box` is expecting the first argument to match up to an attribute that belongs to the object in question (in this case `@student`). I can't see the error, but I imagine it doesn't know what to do with just `language`.

Make sure the arguments to `check_box` match up to the way they are ordered in the documentation: http://apidock.com/rails/ActionView/Helpers/FormHelper/check_box

If you want to submit values through a form using checkboxes that do not necessarily match up to model attributes (in this case, attributes of a `Student`), `check_box_tag` might be the way to go: http://apidock.com/rails/ActionView/Helpers/FormTagHelper/check_box_tag

---

Also came across this. Might be a bit too much for now but wanted to put it on your radar: https://www.sitepoint.com/save-multiple-checkbox-values-database-rails/

**Comment by marks828** [comment]
Accidentally closed the issue. 

I'm looking for something like this:

![image](https://cloud.githubusercontent.com/assets/15305847/19449489/c3585aee-9473-11e6-9570-3ef6e6361272.png)

But the code doesn't work for many reasons:
![image](https://cloud.githubusercontent.com/assets/15305847/19449516/db6d9662-9473-11e6-997b-bdcfc7aef57d.png)

**Comment by nolds9** [comment]
Hey, this is a bit of a complex situation. In essence, you want the fields for each language to show up in params, but not trigger a separate request entirely.

In that case, I suggest using [check_box_tag](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/check_box_tag) as Adrian suggested earlier, or looking into [Active Record nested attributes](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) to help pull values from other models...

Another useful resource might be the [cocoon gem](https://github.com/nathanvda/cocoon) though comes with its own learning curve.

**Comment by amaseda** [comment]
Checking in on this one. Any luck?

**Comment by marks828** [comment]
Got my check boxes, now trying to figure out how to assign value for them and create a separate instance for each

**Comment by marks828** [comment]
This is returning the same name for every student.

![image](https://cloud.githubusercontent.com/assets/15305847/19454861/c142916a-9488-11e6-9472-54b49727d2c6.png)

**Comment by nolds9** [comment]
`.find_by` needs a key-value pair...missing the key

**Comment by amaseda** [comment]
Closing this one for now since we discussed IRL, but please re-open if you have more questions.

**Comment by marks828** [comment]
Hey still no luck creating any proficiencies
