### ISSUE TITLE
loading image assets as background images in views

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#706]
I am trying to use an image I have saved in app/assets/images as a background for a div on one of my views. I keep getting a 404 in the console saying that the server cannot find the image. I have tried a couple different path variations but this is the one I have currently.

<img width="1211" alt="screen shot 2016-10-17 at 12 32 07 pm" src="https://cloud.githubusercontent.com/assets/21045394/19446276/0da92cd0-9466-11e6-9112-44dc3f8429d1.png">

Do I need to put the image in the public folder instead or write the path differently?

**Comment by nolds9** [comment]
If you are setting it inline, I believe you can just pass the name of the file directly, as long as the image itself is in `app/assets/images`.

http://stackoverflow.com/questions/30992446/how-to-add-background-image-in-ruby-on-rails

**Comment by nolds9** [comment]
What does `@category.img_url` represent? The name of a file that you have already uploaded, or the url for an image hosted by some third party? If the latter, then you probably want something like:
`url(<%= @category.img_url %>)`

**Comment by AndyWhitley** [comment]
@category.img_url is simple the name of the image. So for my first category, it would translate into 'electronics.png'

**Comment by AndyWhitley** [comment]
it is the name of the file I added to the assets/images

**Comment by nolds9** [comment]
Great, then you should be able to use the same syntax: `url(<%= @category.img_url %>)`

**Comment by AndyWhitley** [comment]
Thanks!
