### ISSUE TITLE
make `total_hours` default to 0

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#708]
Hey fellas,

When a user creates a new project, I would like the `total_hours` to always start at 0. Is this the way to do this?

![image](https://cloud.githubusercontent.com/assets/8737117/19450142/3e39bbac-9476-11e6-90cf-6a18910504bf.png)

I don't want the user to edit or add that at all.

**Comment by amaseda** [comment]
You could either do something like `Project.create(total_hours: 0)` or you could update your migration/schema so that this happens automatically whenever you create a new project...

```
create_table :projects do |t|
  t.integer :total_hours, default: 0
end
```

**Comment by ghost** [comment]
Thanks!
