### ISSUE TITLE
Where to write new methods? 

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project2#709]
Hi there! 

I've been creating some useful methods within my user.rb model:

``` ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses
  has_many :debts, foreign_key: "debtor_id"

  def owed
      # returns an array of objects (debts) that are owned by the user in question
  end

  def balance(user)
      # returns a `user_id` and a positive or negative decimal value for `amount`. 
      # if I try `tim.balance(matt)` I could find out that Matt owes Tim $200, for example
      # I left it out of here for brevity, but can include it if that would be helpful.
  end
end
```

**My question:** Should I do this in the model files, or in the controller? It's a bit annoying doing it in the model because I have to re-seed the database to test. If I put these methods in the controller, 1: can I? 2: would I still call them with dot-notation as above?

**Comment by jshawl** [comment]
definetly looks like a good place for a model method - why do you have to reseed to test? can you use `rails c` instead?

**Comment by timfoley** [comment]
Ah! You're right. I thought I had to re-seed, but in fact I just needed to restart the rails console. Thanks!

**Comment by jshawl** [comment]
you can also do `reload!` while in `rails c` to avoid quitting and restarting
