### ISSUE TITLE
CRUD works for one Model

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#711]
Hello again fellas,

The CRUD for my Projects works. Now onto the other model, which I think might be `Worker`? A `Worker` has hours that add up to the `:total_hours` of a Project. I want to say that a `Worker` has many `Projects` and a `Project` has many `Workers`. Part of me feels like I am working with the wrong entity... any thoughts?

**Comment by jshawl** [comment]
This sounds good! have you drawn an ERD?

**Comment by ghost** [comment]
I have not...I will draw it now and share shortly.

**Comment by jshawl** [comment]
👍

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8737117/19452541/6a1fad5e-947f-11e6-8ebc-bf3a84a8fe91.png)

I realized some thing. `Projects` for a `User: Worker` is going to be different than  a `Project` for a `User: Manager`. I think this is where all my confusion is coming from. I keep questioning how many Entities I really have.

**Comment by amaseda** [comment]
This ERD looks good. I would not worry about workers vs. managers for now. Get it working with whichever of the two models you think is most integral to your app - I'm guessing that's Worker.

If the many-to-many proves difficult to implement at first, consider starting out with just a one-to-many relationship between Projects and Workers and take it from there.

Happy to answer any other questions that'll clarify this a bit more.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8737117/19453072/ac7db84c-9481-11e6-8e05-f8e5fffa891e.png)

Do you think I should keep the models 1:1? This way, I can focus on building out the App for just the Worker?

**Comment by amaseda** [comment]
I think beginning with a one-to-many relationship between Projects and Workers is the way to go. That way it will match up with much of the work we've been doing in class.

**Comment by ghost** [comment]
Okay. I'll try to keep the 1:Many thing going but I think I may only be able to build out the app from the Worker's User POV for now.
