### ISSUE TITLE
Devise Login: Can I update redirect after logging in?

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/project2#712]
When I log in from my welcome/index (http://localhost:3000/welcome/index) page, it goes straight to
http://localhost:3000/

I'd like it to go to this instead:
http://localhost:3000/posts

Can I customize this?

views/layouts/application.html.erb
`<% if !current_user %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
  <% else %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <%= current_user.email %>
  <% end %>
`

**Comment by jshawl** [comment]
yes! in whatever action corresponds to `/`:

``` rb
if current_user
  redirect_to posts_path
end
```

**Comment by LWatsonlm** [comment]
ah! in the layout?

**Comment by jshawl** [comment]
no in the controller action

**Comment by LWatsonlm** [comment]
of course, got it! thanx!!
