### ISSUE TITLE
uninitialized constant SessionController

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#714]
![image](https://cloud.githubusercontent.com/assets/19254862/19452305/9a987192-947e-11e6-876d-a2009b0d18e0.png)

Just added session variables to get current_user sessions variable.

Now i cannot start up my system.  The root route was changed to be 
  root 'session#new'

This does exist in the controller:

```
class SessionController < ApplicationController
  def new
    @user = User.new
  end


```

my new erb page has the following code:

```

<!-- app/views/sessions/new.html.erb -->

<h2>Sign In</h2>
<%= form_for @user, url: session_path, method: :post do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Submit" %>
<% end %>


```

Any ideas?

**Comment by nolds9** [comment]
what does your  root route look like in`routes.rb` look like? Also, can you double check the name of your controller file

**Comment by nolds9** [comment]
shouldn't it be `Sessions` controller?

**Comment by merubin** [comment]
resource :session   # Add this after the resources already in the file.
  root 'session#new'

**Comment by nolds9** [comment]
what happens when you try `root to: "sessions#new"`?

**Comment by merubin** [comment]
Same thing.  It is sessions controler
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

**Comment by nolds9** [comment]
and you are sure you have a file `sessions_controller.rb`?

**Comment by merubin** [comment]
![image](https://cloud.githubusercontent.com/assets/19254862/19453045/8a11fc1e-9481-11e6-9b2f-ad9e92aa2c74.png)

**Comment by nolds9** [comment]
closing since we tackled this IRL
