### ISSUE TITLE
Dropping just one table

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project2#715]
I am trying to drop a table that was automatically pluralized. It is using postparta but I would like to use postpartum

![image](https://cloud.githubusercontent.com/assets/20979785/19453183/282acb24-9482-11e6-829f-2c26a0692d4b.png)

![image](https://cloud.githubusercontent.com/assets/20979785/19453201/3ebdf80c-9482-11e6-82c4-1a10b562af21.png)

**Comment by nolds9** [comment]
Must admit I'm a little confused by the plurality, but if you want to drop a table you can just create a new migration. 

http://guides.rubyonrails.org/active_record_migrations.html

The `drop_table` method is what you want

**Comment by griffind2009** [comment]
do you know the syntax for that and where I would run it?

**Comment by griffind2009** [comment]
oh i found it thanks!
