### ISSUE TITLE
Undefined Table

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project2#716]
I am now getting this error after I dropped the table.  Does this mean i have to create a table using the pluralization postparta?

![image](https://cloud.githubusercontent.com/assets/20979785/19454039/a78a9090-9485-11e6-9e6f-26bcf2f38ef6.png)

**Comment by amaseda** [comment]
Run `$ rails routes` and make sure you're using the correct path helper. I'm guessing you're using the wrong one since Rails is suggesting other options.

**Comment by amaseda** [comment]
Can you paste the contents of `routes.rb` and the output of `$ rails routes`?

**Comment by griffind2009** [comment]
```
resources :clients
resources :charts
resources :basics
resources :prenatals
resources :births
resources :postpartums

end
```

rails routes

```
         Prefix Verb   URI Pattern                     Controller#Action
        clients GET    /clients(.:format)              clients#index
                POST   /clients(.:format)              clients#create
     new_client GET    /clients/new(.:format)          clients#new
    edit_client GET    /clients/:id/edit(.:format)     clients#edit
         client GET    /clients/:id(.:format)          clients#show
                PATCH  /clients/:id(.:format)          clients#update
                PUT    /clients/:id(.:format)          clients#update
                DELETE /clients/:id(.:format)          clients#destroy
         charts GET    /charts(.:format)               charts#index
                POST   /charts(.:format)               charts#create
      new_chart GET    /charts/new(.:format)           charts#new
     edit_chart GET    /charts/:id/edit(.:format)      charts#edit
          chart GET    /charts/:id(.:format)           charts#show
                PATCH  /charts/:id(.:format)           charts#update
                PUT    /charts/:id(.:format)           charts#update
                DELETE /charts/:id(.:format)           charts#destroy
         basics GET    /basics(.:format)               basics#index
                POST   /basics(.:format)               basics#create
      new_basic GET    /basics/new(.:format)           basics#new
     edit_basic GET    /basics/:id/edit(.:format)      basics#edit
          basic GET    /basics/:id(.:format)           basics#show
                PATCH  /basics/:id(.:format)           basics#update
                PUT    /basics/:id(.:format)           basics#update
                DELETE /basics/:id(.:format)           basics#destroy
      prenatals GET    /prenatals(.:format)            prenatals#index
                POST   /prenatals(.:format)            prenatals#create
   new_prenatal GET    /prenatals/new(.:format)        prenatals#new
  edit_prenatal GET    /prenatals/:id/edit(.:format)   prenatals#edit
       prenatal GET    /prenatals/:id(.:format)        prenatals#show
                PATCH  /prenatals/:id(.:format)        prenatals#update
                PUT    /prenatals/:id(.:format)        prenatals#update
                DELETE /prenatals/:id(.:format)        prenatals#destroy
         births GET    /births(.:format)               births#index
                POST   /births(.:format)               births#create
      new_birth GET    /births/new(.:format)           births#new
     edit_birth GET    /births/:id/edit(.:format)      births#edit
          birth GET    /births/:id(.:format)           births#show
                PATCH  /births/:id(.:format)           births#update
                PUT    /births/:id(.:format)           births#update
                DELETE /births/:id(.:format)           births#destroy
    postpartums GET    /postpartums(.:format)          postpartums#index
                POST   /postpartums(.:format)          postpartums#create
 new_postpartum GET    /postpartums/new(.:format)      postpartums#new
edit_postpartum GET    /postpartums/:id/edit(.:format) postpartums#edit
     postpartum GET    /postpartums/:id(.:format)      postpartums#show
                PATCH  /postpartums/:id(.:format)      postpartums#update
                PUT    /postpartums/:id(.:format)      postpartums#update
                DELETE /postpartums/:id(.:format)      postpartums#dest
```

**Comment by amaseda** [comment]
What are you setting `@postpartum` to in your controller's `new' action?

Also can you push your code and send a link to your repo?

**Comment by griffind2009** [comment]
https://github.com/griffind2009/The_Practical_Doula

**Comment by griffind2009** [comment]
def new
    @postpartum = Postpartum.new
  end

**Comment by amaseda** [comment]
Can you try running `rails db:migrate:reset` (FYI this will clear data from you tables)? I got a few errors when trying to set up your application so I'm wondering if you need to re-run your migrations.

**Comment by griffind2009** [comment]
So it clears all the tables in the schema?

**Comment by griffind2009** [comment]
It looks like it started but then did not finish because of a data type

$ rails db:migrate:reset
Dropped database 'the_practical_doula_development'
Dropped database 'the_practical_doula_test'
Created database 'the_practical_doula_development'
Created database 'the_practical_doula_test'
== 20161014143548 CreateClients: migrating ====================================
-- create_table(:clients)
   -> 0.0200s
== 20161014143548 CreateClients: migrated (0.0205s) ===========================

== 20161014151748 CreateCharts: migrating =====================================
-- create_table(:charts)
   -> 0.0235s
== 20161014151748 CreateCharts: migrated (0.0241s) ============================

== 20161014195525 AddColumnToClients: migrating ===============================
-- add_column(:clients, :chart_type, :string)
   -> 0.0023s
== 20161014195525 AddColumnToClients: migrated (0.0024s) ======================

== 20161017144839 AddColumnToCharts: migrating ================================
-- add_column(:charts, :name, :text)
   -> 0.0012s
-- add_column(:charts, :address, :text)
   -> 0.0010s
-- add_column(:charts, :age, :text)
   -> 0.0010s
-- add_column(:charts, :EDD, :text)
   -> 0.0010s
-- add_column(:charts, :phsician, :text)
   -> 0.0012s
-- add_column(:charts, :nutrition, :text)
   -> 0.0010s
-- add_column(:charts, :bp, :text)
   -> 0.0010s
-- add_column(:charts, :medications, :text)
   -> 0.0022s
-- add_column(:charts, :intervention, :text)
   -> 0.0012s
-- add_column(:charts, :contraction, :text)
   -> 0.0013s
-- add_column(:charts, :effacement, :text)
   -> 0.0010s
-- add_column(:charts, :dilation, :text)
   -> 0.0010s
-- add_column(:charts, :support, :text)
   -> 0.0009s
-- add_column(:charts, :questions, :text)
   -> 0.0011s
-- add_column(:charts, :comments, :text)
   -> 0.0013s
== 20161017144839 AddColumnToCharts: migrated (0.0186s) =======================

== 20161017145820 ChangeColumnToCharts: migrating =============================
-- change_column(:charts, :EDD, :integer)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "EDD" cannot be cast automatically to type integer
HINT:  You might need to specify "USING "EDD"::integer".
: ALTER TABLE "charts" ALTER COLUMN "EDD" TYPE integer
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in`block in execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in`instrument'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in`execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:490:in `change_column'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:845:in`block in method_missing'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `block in say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in`say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:834:in `method_missing'
/Users/Nikki/wdi/projects/the_practical_doula/db/migrate/20161017145820_change_column_to_charts.rb:3:in`change'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:788:in `exec_migration'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:772:in`block (2 levels) in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:771:in `block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in`with_connection'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:770:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:950:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in`block in ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in`within_new_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in`transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1210:in`execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in`each'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in`block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `up'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:983:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in`block (2 levels) in <top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in`run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in`<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in `require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in`<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in`call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client.rb:30:in`run'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in`load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in`require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in `<top (required)>'
bin/rails:3:in`load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  column "EDD" cannot be cast automatically to type integer
HINT:  You might need to specify "USING "EDD"::integer".
: ALTER TABLE "charts" ALTER COLUMN "EDD" TYPE integer
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in`async_exec'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in`block in log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in`log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:490:in`change_column'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:845:in `block in method_missing'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in`block in say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:834:in`method_missing'
/Users/Nikki/wdi/projects/the_practical_doula/db/migrate/20161017145820_change_column_to_charts.rb:3:in `change'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:788:in`exec_migration'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:771:in`block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:770:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:950:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1211:in`block in execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`block in transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in`ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1183:in`block in migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `each'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in`migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1298:in`with_advisory_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in`up'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:983:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in`block in run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in`run_command!'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in`require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in `<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in`load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/command.rb:7:in`call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/bin/spring:49:in`<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in`<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in `require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in`<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in`<main>'
PG::DatatypeMismatch: ERROR:  column "EDD" cannot be cast automatically to type integer
HINT:  You might need to specify "USING "EDD"::integer".
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in`block in execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in`instrument'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in`execute'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:490:in `change_column'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:845:in`block in method_missing'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `block in say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in`say_with_time'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:834:in `method_missing'
/Users/Nikki/wdi/projects/the_practical_doula/db/migrate/20161017145820_change_column_to_charts.rb:3:in`change'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:788:in `exec_migration'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:772:in`block (2 levels) in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:771:in `block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in`with_connection'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:770:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:950:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in`block in ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in`within_new_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in`transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1210:in`execute_migration_in_transaction'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in`each'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in`block in migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `up'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:983:in`migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in`block (2 levels) in <top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in`run_rake_task'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/Nikki/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in`<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in `require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/rails:9:in`<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in`call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client.rb:30:in`run'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in`load'
/Users/Nikki/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in`require'
/Users/Nikki/wdi/projects/the_practical_doula/bin/spring:14:in `<top (required)>'
bin/rails:3:in`load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate:reset => db:migrate
(See full trace by running task with --trace)

**Comment by griffind2009** [comment]
I tried dropping the table "charts" and migrating again but that did not work. I get the same error

**Comment by griffind2009** [comment]
I fixed the migration, thanks!

**Comment by griffind2009** [comment]
This is the error I am getting now. I deleted the migrations from when I changed the table to Postpartums, however it is not updated in the schema.
![screen shot 2016-10-17 at 4 20 20 pm](https://cloud.githubusercontent.com/assets/20979785/19498464/01c5c6e0-955f-11e6-95d7-0d3faf85fd29.png)

**Comment by nolds9** [comment]
@griffind2009 did you run `rails db:migrate:reset`?

**Comment by griffind2009** [comment]
I did yesterday morning. Should I try again today?

**Comment by nolds9** [comment]
if you still have that error, then I would....

**Comment by amaseda** [comment]
Still working on this one @griffind2009 or can it be closed?

**Comment by griffind2009** [comment]
All fixed. Thanks!
