### ISSUE TITLE
Triggering the creation of one model (debt#create) from the controller of another (expense#create)

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project2#718]
When a user creates an Expense, I need to automatically create Debt associated that expense:
- Tim logs an `expense` of "Paper Towels" for $30
- my backend then creates $10 `debt` (on the debts table) for Matt and Jack that is associated with the purchase

It looks like I could do everything within the `Expense` controller, even creating some strong params for passing into `@expense.debt.create(debt_params)`, but that feels a bit fishy. Is there another way I can trigger the create method from one controller to another? 

Here's my ERD for context, and a link to [my current repo](https://github.com/timfoley/expensiv). 

![image](https://cloud.githubusercontent.com/assets/2591447/19458768/1ac38222-949c-11e6-9f74-80708d5647bf.png)

**Comment by amaseda** [comment]
Nothing wrong with what you're suggesting here. Alternatively you could redirect to a path that then triggers a controller action which creates the debt, but that sounds like more steps/code to do the same thing.

**Comment by timfoley** [comment]
Cool, thanks Adrian! Going to start on that now.
