### ISSUE TITLE
How to handle Delete of Many to Many records

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#719]
I have a many2many index ProjectPortfolio table  How would you handle a destroy request for records in the Project table or Portfolio table.  I believe I should destroy the Project Portfolio records first  and since there could be more than one record I probably need to do a find then a  destroy all.  Is this understanding correct?
![image](https://cloud.githubusercontent.com/assets/19254862/19458993/ff71cc3e-949d-11e6-8ff8-69bea82478ed.png)

**Comment by amaseda** [comment]
Add `dependent: :destroy` next to the `ProjectPortfolio` association in your `Portfolio` and/or `Project` model files. Then try deleting a project or portfolio. Does that work?

**Comment by merubin** [comment]
I did not  put a dependent clause in my model

Are you saying to add it like this?

class Project < ApplicationRecord
  belongs_to :user
  has_many :project_portfolios **:destroy**
  has_many :portfolios, through: :project_portfolios
end

The Doc's show this:
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_portfolios **dependent: :destroy**
  has_many :portfolios, through: :project_portfolios
end

**Comment by amaseda** [comment]
Yes, although you forgot `dependent:` for `Project`.

Did this end up working?

**Comment by nolds9** [comment]
@merubin going to go ahead and close this since its been awhile. Feel free to reopen or post a new one if problem persists

**Comment by merubin** [comment]
Just did this and it worked PERFECT!

Selected Project id 4 to delete:
Before:
ortfolio_management_system_development=# select \* from project_portfolios;
 id | project_id | portfolio_id |         created_at         |         updated_at
----+------------+--------------+----------------------------+----------------------------
  1 |          1 |            1 | 2016-10-18 00:00:57.71519  | 2016-10-18 00:00:57.71519
  2 |          2 |            1 | 2016-10-18 00:00:57.717932 | 2016-10-18 00:00:57.717932
  4 |          4 |            1 | 2016-10-18 00:00:57.722382 | 2016-10-18 00:00:57.722382
  5 |          5 |            2 | 2016-10-18 00:00:57.724749 | 2016-10-18 00:00:57.724749
  7 |          1 |            3 | 2016-10-18 00:26:20.452973 | 2016-10-18 00:26:20.452973
  8 |          4 |            3 | 2016-10-18 00:26:20.457723 | 2016-10-18 00:26:20.457723
 10 |          5 |            3 | 2016-10-18 00:26:20.465051 | 2016-10-18 00:26:20.465051
(7 rows)

After:

portfolio_management_system_development=# select name,id from projects;
               name                | id
-----------------------------------+----
 Mario's Match Game                |  1
 My Business                       |  2
 My Blog                           |  3
 Traffic Light Javascript exercise |  5
(4 rows)

portfolio_management_system_development=# select \* from project_portfolios;
 id | project_id | portfolio_id |         created_at         |         updated_at
----+------------+--------------+----------------------------+----------------------------
  1 |          1 |            1 | 2016-10-18 00:00:57.71519  | 2016-10-18 00:00:57.71519
  2 |          2 |            1 | 2016-10-18 00:00:57.717932 | 2016-10-18 00:00:57.717932
  5 |          5 |            2 | 2016-10-18 00:00:57.724749 | 2016-10-18 00:00:57.724749
  7 |          1 |            3 | 2016-10-18 00:26:20.452973 | 2016-10-18 00:26:20.452973
 10 |          5 |            3 | 2016-10-18 00:26:20.465051 | 2016-10-18 00:26:20.465051
(5 rows)
