### ISSUE TITLE
Not being able to record scores

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project2#720]
I used to be able to record my scores, however now it doesn't seem to be recording at all. I've submitted my new form multiple times and checked the console and none of my submission was saved.

Schema.rb
![image](https://cloud.githubusercontent.com/assets/20713810/19458969/def797cc-949d-11e6-9f12-efc785eb201b.png)

routes.rb
![image](https://cloud.githubusercontent.com/assets/20713810/19458980/ed5ee5cc-949d-11e6-959c-347cdfb9bc27.png)

scores controller
![image](https://cloud.githubusercontent.com/assets/20713810/19459039/568d3134-949e-11e6-935d-ede6be0f9b75.png)

show page for workout
![image](https://cloud.githubusercontent.com/assets/20713810/19459014/20a056e6-949e-11e6-9c37-3056d1b74352.png)

**Comment by MichaelZLai** [comment]
Heres the link to [my repo](https://github.com/MichaelZLai/Project2)

**Comment by amaseda** [comment]
Hm, it's working for me. I created a couple of scores and then was able to seem them in the Rails console after entering `Workout.last.scores`.

Also, while in `scores_controller.rb`, noticed that your `Score` strong params is missing some attributes.

**Comment by MichaelZLai** [comment]
ah, you're right! I didn't update my score strong params to reflect my recent migration changes.

**Comment by amaseda** [comment]
Nice! Closing this one but feel free to re-open if the error returns.
