### ISSUE TITLE
Seeds

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project2#722]
![image](https://cloud.githubusercontent.com/assets/21348450/19478688/878a3eee-9511-11e6-8730-cb7a10521b08.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19478711/9afc5ab6-9511-11e6-9550-9ad3101b4006.png)

having trouble with my seeds and viewing it when i run the server, did i write them out correctly?

**Comment by brophy2321** [comment]
after the img_url in " " it ends in }) to close the seed

**Comment by jshawl** [comment]
do you get any error messages with `rails db:seed`?  if so, what is the message?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19479573/68828be2-9515-11e6-882f-56bff6b310ec.png)

**Comment by brophy2321** [comment]
do i not need spaces?

**Comment by jshawl** [comment]
ah ok instead of colon and  `=>`, choose one, so either:

``` rb
User.create!(:name => 'Ryan')

# or

User.create!(name: 'Ryan')
```

**Comment by brophy2321** [comment]
fixed that and another syntax error and ran db:seed and got this in response
![image](https://cloud.githubusercontent.com/assets/21348450/19479729/21fde18e-9516-11e6-8f2b-86c69e14ecdb.png)

**Comment by jshawl** [comment]
did you change your seeds? I don't see `Raging Bitch` anywhere in the above screenshot

**Comment by brophy2321** [comment]
its the first Beer.create next to type.

**Comment by brophy2321** [comment]
I think im going to start from scratch with Models IPA Styles and IPA Beers. theres ten styles and then the Beers part would be all IPA in which i can create or add them. I started with models Users and Beers but that was kind of not the way I wanted to create it.

**Comment by jshawl** [comment]
ok I think you have a lot of great progress already - but let me know if there's something I can help with

**Comment by brophy2321** [comment]
ok thank you, gonna think bout it during outcomes. Ill let you know.
