### ISSUE TITLE
Rails Server is not working!

### ISSUE THREAD

**Issue by a-espinoza** [ga-wdi-exercises/project2#723]
And I am postive I am inside the directory I should be to able to run it!

![image](https://cloud.githubusercontent.com/assets/19412086/19479514/1ab0ff0c-9515-11e6-8937-99fd742dd47a.png)

**Comment by jshawl** [comment]
what is the output of ls?

**Comment by a-espinoza** [comment]
![screen shot 2016-10-18 at 9 30 34 am](https://cloud.githubusercontent.com/assets/19412086/19479605/9a64dda4-9515-11e6-8e5f-ccbfde329743.png)

**Comment by jshawl** [comment]
what if you do `bin/rails s`? does that give any errors?

**Comment by a-espinoza** [comment]
Tue Oct 18 09:32:07 ~/Documents/wdi/projects/project02/project2/dronestagram/dronestagram (master _)
$ bin/rails s
*_-bash: bin/rails: No such file or directory**

(Did I maybe delete "bin" by mistake? Can I regenerate it without compromisin my progress? Or just go back to an earlier commit?)

**Comment by jshawl** [comment]
yes what is the output of git status

**Comment by a-espinoza** [comment]
Ok, that seems to be the problem! I will go back! Thank you señor!

![image](https://cloud.githubusercontent.com/assets/19412086/19479826/8e8199b8-9516-11e6-8ab8-4cfe088e765c.png)

**Comment by jshawl** [comment]
wait! you can remove the deletion with `git checkout -- bin`

**Comment by a-espinoza** [comment]
SWEEEEEETTTTT!! That made the trick!!! Thank you!
![image](https://cloud.githubusercontent.com/assets/19412086/19479953/0787a33e-9517-11e6-9b21-3cd730ff569f.png)
