### ISSUE TITLE
Worker model

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#724]
I'm a hung up on the attributes for my Worker. Here is what I am wrastlin' with.

``` ruby
    create_table :workers do |t|
      t.timestamps
      :name, :string
      :hours_per_day, :decimal
      :total_hours_per_week, :decimal
      :total_hours_per_project, :decimal
    end
```

versus

``` ruby
    create_table :workers do |t|
      t.timestamps
      :name, :string
      :monday, :decimal
      :tuesday, :decimal
      :wednesday, :decimal
      :thursday, :decimal
      :friday, :decimal
      :saturday, :decimal
      :sunday, :decimal
      :total_hours_per_week, :decimal
      :total_hours_per_project, :decimal
    end
```

**Comment by amaseda** [comment]
What do you mean by "hung up"? Happy to help but want to get an idea of what exactly you're struggling with.

From a syntax perspective, make sure your migration follows this setup...

``` rb

class CreateProducts < ActiveRecord::Migration[5.0]
  def change
    create_table :products do |t|
      t.string :name
      t.text :description

      t.timestamps
    end
  end
end
```

> Each entry follows this structure: `t.data_type :attribute_name`

**Comment by ghost** [comment]
Okay sorry. By "hung up" I mean, I am fearing how time plays a factor in my application. My approach is to have Ruby:
1. create the day (whatever that day is at that day) and perform calculations for that day.
2. perform calculations determined by user input
3. store a decimal value for the hours of that day
4. sum up the hours per week
5. sum up the hours per `Project`

Is it better to create the variables for each day?

I see that there are other methods to use on `t` like `.time`, `.timestamp`, and `.decimal`. Not sure which to use or how to use.

**Comment by ghost** [comment]
I'm just gonna go for it! 😅
