### ISSUE TITLE
unknown attribute error

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project2#726]
I have update my models to have the correct relationships however I am still getting an error saying client_id is unknown

![screen shot 2016-10-18 at 3 01 37 pm](https://cloud.githubusercontent.com/assets/20979785/19492317/2b4025ee-9544-11e6-9ea1-8452108798e1.png)

**Comment by nolds9** [comment]
@griffind2009 what does `birth_params` look like?

Also, can you double check that your `births` table has a column for `client_id`

**Comment by griffind2009** [comment]
Hello,

This is what the birth_params looks like in births_controller 
private
    def birth_params
      params.require(:birth).permit(:medication, :intervention, :dilation, :effacement)
    end
  end

This is the births table in my schema
create_table "births", force: :cascade do |t|
    t.text    "medication"
    t.text    "intervention"
    t.integer "dilation"
    t.integer "effacement"
    t.integer "clients_id"
    t.index ["clients_id"], name: "index_births_on_clients_id", using: :btree
  end

**Comment by nolds9** [comment]
@griffind2009 ahh, I think you need to make another migration that changes `clients_id` to `client_id`. I think this was caused by an extra `s` when you added the references line.

**Comment by nolds9** [comment]
It might be helpful to use this method http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/remove_reference when changing the table...i.e could remove the old references then add the correct references in the same step

**Comment by griffind2009** [comment]
is there a way to do that for all 4 tables?

**Comment by nolds9** [comment]
Yeah i think you can have as many of those add / remove references methods as you like

**Comment by griffind2009** [comment]
i did the migration but it added a plural to 'clients_id' again.
