### ISSUE TITLE
Back link

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project2#728]
![image](https://cloud.githubusercontent.com/assets/21348450/19497405/21a69688-955a-11e6-8e46-c347b0f5022b.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19497423/31a86c8c-955a-11e6-8ff9-97ed8b9857d5.png)
having trouble getting this back link to work. i switched the position of it a few times with no luck.

**Comment by jshawl** [comment]
I think you need one more end - there is a form within another form, and that second form doesn't look like it has an end

**Comment by brophy2321** [comment]
got it to work thank you
