### ISSUE TITLE
Resources for Securing API keys, etc? 

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project2#730]
Hey team! 

I found this [guide](http://gregeng.github.io/blog/2013/11/21/hide-your-keys/) with a quick google. 
Got any good go-to resources on this?

**Comment by timfoley** [comment]
Oooh, I just found this one and it looks excellent: https://launchschool.com/blog/managing-environment-configuration-variables-in-rails

**Comment by jshawl** [comment]
+1 for figaro

**Comment by amaseda** [comment]
Going to close this one since Figaro is the best move here. Re-open if you have any questions about it though!

**Comment by timfoley** [comment]
Sounds good, thanks!
