### ISSUE TITLE
User must exist error when trying to seed database

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project2#731]
Good morning.  Last night I implemented devise and it worked just fine, but today, I'm getting this error message when I try to re-seed my database.

![image](https://cloud.githubusercontent.com/assets/20567326/19519014/eda54928-95d7-11e6-8b60-feac0cb2d3ba.png)

**Comment by jshawl** [comment]
can we see your seeds

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19519352/994fd9f4-95d9-11e6-824a-b3244af76530.png)

**Comment by jshawl** [comment]
``` rb
Tip.create([
  { user: lo}
]) # Tips need a user
```

**Comment by brown2206** [comment]
Hey Jesse, I tried to give Tip a user and I inserted it before I defined "lo" and it's now giving me this error.  I'm trying to pinpoint what I may be typing wrong in the seed file?

![image](https://cloud.githubusercontent.com/assets/20567326/19519776/5304456e-95db-11e6-9497-d447667e1d50.png)

**Comment by brown2206** [comment]
attaching my seed

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19519833/8e898cac-95db-11e6-9098-e214a8912781.png)

**Comment by amaseda** [comment]
`lo` needs to be defined before you use it in `User.create`

**Comment by nolds9** [comment]
@brown2206  looks like you have validations set up on `Tip` so that you need to pass a user each time you create a new tip...including on the last line there

**Comment by brown2206** [comment]
Thanks gentleman.  You can close this issue now.
