### ISSUE TITLE
JavaScript - Using .every to test jquery array of elements 

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#732]
I am having trouble using the .every() method to test each input element in a given form to see if it has been filled out before advancing. The console is telling me that I can't use .every is not a method of the jquery array. Here is my code:

<img width="1155" alt="screen shot 2016-10-19 at 9 21 17 am" src="https://cloud.githubusercontent.com/assets/21045394/19520285/b4bd1888-95dd-11e6-96be-dd59788efb8c.png">
<img width="259" alt="screen shot 2016-10-19 at 9 22 44 am" src="https://cloud.githubusercontent.com/assets/21045394/19520289/b8c19ae4-95dd-11e6-9bd6-e228a1b1fac0.png">

Am I syntactically missing something or can I not use .every on JQuery arrays?

**Comment by jshawl** [comment]
.every is a method only available to arrays, try: can you use jquery's each to solve the problem?

also thing to google is `jquery .get()` not the ajax one though

**Comment by jshawl** [comment]
https://api.jquery.com/get/

**Comment by AndyWhitley** [comment]
The .get() method works! Thank you. Although, I don't get why .every didn't work without it considering the output of the jquery's .find is an array.
<img width="452" alt="screen shot 2016-10-19 at 9 54 24 am" src="https://cloud.githubusercontent.com/assets/21045394/19521576/21f179ea-95e2-11e6-9c31-1242a358aa00.png">

**Comment by jshawl** [comment]
it only looks like an array... ![](https://dl.dropbox.com/s/cuxepvrb160a98j/Screenshot%202016-10-19%2010.01.10.png?dl=0)

**Comment by AndyWhitley** [comment]
Oh I see. Thanks!
