### ISSUE TITLE
Had to create a new model, controller issues

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project2#733]
![image](https://cloud.githubusercontent.com/assets/20734065/19520583/b98502b2-95de-11e6-9516-9e87f431a279.png)

![image](https://cloud.githubusercontent.com/assets/20734065/19520596/c4b058bc-95de-11e6-9bab-f203a41e2970.png)

**Comment by jshawl** [comment]
can i see config/routes.rb

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19521259/f5a2ee92-95e0-11e6-95b9-b244a355eb20.png)

**Comment by jshawl** [comment]
``` rb
@continent = Continent.find... if params[:continent_id]
```

you have to check whether the continent is present in params. This is because you have one controller serving multiple routes (multiple URLS)

**Comment by khoitle** [comment]
Sorry, I'm not sure if thats the code I'm supposed to use?

**Comment by jshawl** [comment]
not quite. add a conditional to your controller such that you're only looking for a continent if contentinent_id is in params

**Comment by khoitle** [comment]
got it, thankss
