### ISSUE TITLE
Assets Images path issues ( Where in the world are my pictures?)

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#734]
I am having a heck of a time trying to reference my images that are located in the Assets folders into .erb pages.

I followed the docs where they say to use the helper.
![image](https://cloud.githubusercontent.com/assets/19254862/19520397/19cab78a-95de-11e6-8ebe-e6b394d1e42b.png)

Here is my matching code.
`<%= image_tag "/nav/social/twitter.png" %>`

When Executing and looking at Google Toolkit the tooltip is showing the path as:

![image](https://cloud.githubusercontent.com/assets/19254862/19520571/af39f54c-95de-11e6-9d76-3e726c98ce71.png)

Here is where everything is located:

![image](https://cloud.githubusercontent.com/assets/19254862/19520604/cc748406-95de-11e6-9884-4d8f6bcc047a.png)

What am I missing here?

**Comment by merubin** [comment]
UGG I just re-read the docs.  PUBLIC/ASSESTS....

**Comment by merubin** [comment]
Well it still does not work. I moved them to the public/assets/images location

**Comment by jshawl** [comment]
how do you know it doesn't work?

**Comment by jshawl** [comment]
if you visit that url, what do you see? what is the generated html

**Comment by merubin** [comment]
![image](https://cloud.githubusercontent.com/assets/19254862/19521252/f352bdc0-95e0-11e6-8ea2-1b0b5a5f239e.png)

**Comment by merubin** [comment]
The page is rendered like this with boxes around the areas where I believe my images should go
![image](https://cloud.githubusercontent.com/assets/19254862/19521306/1f14347a-95e1-11e6-9c14-1e27de41eecf.png)

I was expecting something more like 
![image](https://cloud.githubusercontent.com/assets/19254862/19521369/5838f1a0-95e1-11e6-8a76-928ce8034f2f.png)

**Comment by jshawl** [comment]
if you view source of the rendered html (cmd-option-u) where do the links point to?

**Comment by merubin** [comment]
```
    <div id="footer">
      <div id="social">
        <img src="/nav/social/twitter.png" alt="Twitter" />
        <a href="#" target="_blank"><img src="app/assets/images/nav/social/email.png" alt="email id"></a>
        <a href="#" target="_blank"><img src="app/assets/images/nav/social/instagram.png" alt="instagram id"></a>

      </div>
      <div>
```

it goes to an invalid page:

![image](https://cloud.githubusercontent.com/assets/19254862/19521575/1efa6698-95e2-11e6-8786-1181197402f1.png)

**Comment by jshawl** [comment]
can you get any asset to load? e.g. put an image inside `assets/images` and use `image_tag` without the nav folder - reading mroe here http://stackoverflow.com/questions/15827763/why-images-are-not-showing-in-my-rails-basic-app

**Comment by merubin** [comment]
In the public/assets or the app/assets?  The article does not specify.

**Comment by jshawl** [comment]
`app/assets` - all though putting it in the public folder will be the easy way to make it work, the assets folder is the right way

**Comment by merubin** [comment]
I just tried in the public/assets/images and it did not work.

I then created a app/assets/images and put it in there and IT DID SHOW UP. 

I then created a folder nav moved it inside the nav folder changed the helper to:
    <%= image_tag "nav/twitter.png" %>  That worked too.  With this in hand I can move on.

That worked to:  it did not work if I had "/nav/twitter.png"
