### ISSUE TITLE
formatting product form checkboxes to create links to multiple categories

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#737]
<img width="428" alt="screen shot 2016-10-19 at 11 51 26 am" src="https://cloud.githubusercontent.com/assets/21045394/19526513/a7103a3e-95f2-11e6-8911-e03b095b7ad1.png">

<img width="440" alt="screen shot 2016-10-19 at 11 53 58 am" src="https://cloud.githubusercontent.com/assets/21045394/19526558/bfb0c43c-95f2-11e6-8e91-981538a1604b.png">

Hey Adrian, I'm trying to create a field of checkboxes on the products#new view where a user can select one (or many) categories to list their new product in. I've been looking up the documentation but cannot seem to find how to format the f.check_box so that it's rendered 'name' attribute would perform this association for me. Thanks!

**Comment by AndyWhitley** [comment]
PS Ignore the fact that all the labels say Electronics at the moment

**Comment by amaseda** [comment]
Closing since we talked about it IRL. Feel free to re-open if you encounter any problems with that implementation we discussed.
