### ISSUE TITLE
Customizing seed file

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project2#738]
So my athletes has a one to one relationship with user. I'm trying to set up my seed data so I can directly an athlete with a user

seed data (view 1)
![image](https://cloud.githubusercontent.com/assets/20713810/19527062/a503cab0-95f4-11e6-830a-53722d9d0d49.png)
seed data (view 2)
![image](https://cloud.githubusercontent.com/assets/20713810/19527076/b18ca55e-95f4-11e6-8dc7-ebb2d3c34442.png)

schema
![image](https://cloud.githubusercontent.com/assets/20713810/19527102/c98e620a-95f4-11e6-8a70-7fa433d148ee.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19527111/d1d9b9be-95f4-11e6-8316-4edf9d1d3377.png)

model
![image](https://cloud.githubusercontent.com/assets/20713810/19527126/dd5e48fe-95f4-11e6-8179-8b4e3aaa4eff.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19527135/e4f99ee2-95f4-11e6-9ff7-ea8ef09648f2.png)

**Comment by MichaelZLai** [comment]
*directly associate an athlete with a user variable. Kinda similar to the one in hogwarts. However running the db:seed, my athlete is not recording the user_id

**Comment by jshawl** [comment]
Don't you need to add a `user:` attribute each time you create an athlete

**Comment by MichaelZLai** [comment]
I think I have that in the seed data (view2)

**Comment by jshawl** [comment]
any errors if you add an exclamation point to each create? are you sure the user is being created?

**Comment by MichaelZLai** [comment]
I have a temporary workaround for this. I'll get back to it once I finish this last model. Thanks for the response!
