### ISSUE TITLE
Issue with create action

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project2#739]
![image](https://cloud.githubusercontent.com/assets/20734065/19527801/6f88e232-95f7-11e6-9da9-06c01f36a94c.png)

![image](https://cloud.githubusercontent.com/assets/20734065/19527805/7535bdae-95f7-11e6-98a0-ef060624ff85.png)

**Comment by khoitle** [comment]
I keep getting this error and forgetting how to fix it, is it something with the URL?

**Comment by jshawl** [comment]
https://github.com/ga-wdi-exercises/project2/issues/733#issuecomment-254821799

**Comment by khoitle** [comment]
Sorry Jesse, I had to get help in person to fix the previous "733" issue. Could you explain it? I didn't have to use a conditional to fix it

**Comment by nolds9** [comment]
@KhoiLe89 what does you form look like to create a new destination?

**Comment by khoitle** [comment]
<img width="465" alt="screen shot 2016-10-19 at 1 33 08 pm" src="https://cloud.githubusercontent.com/assets/20734065/19530151/a57669ec-9600-11e6-85dd-ad87d3d994f6.png">

**Comment by nolds9** [comment]
if I remember correctly, isn't a `destination` nested under a `continent`, so your `form for` needs two objects...i.e. missing the `continent` that you are trying to add a new destination for

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19530384/a5ef334e-9601-11e6-85c3-7ddb8bfd1da2.png)

How about this? I'm still getting the same error

**Comment by khoitle** [comment]
actually, i had to refresh the server. theres a different error. I'll try to work with that! Thanksss

**Comment by nolds9** [comment]
cool! going to go ahead and close this but feel free to reopen or post a new one
