### ISSUE TITLE
destroy proficiency

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project2#740]
I'm trying to set up my destroy function and i keep getting a no method error. I've tried passing in different ways of writing the path and methods.

![image](https://cloud.githubusercontent.com/assets/15305847/19528127/d71d03a0-95f8-11e6-91a7-0c52b272a4d9.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19528073/a38171b6-95f8-11e6-8b61-797e2b449e02.png)

`<%= link_to "Delete", delete_student_proficiency_path(@student, proficiency), method: :delete %>`

**Comment by andrewsunglaekim** [comment]
check your `rails routes` i'm guessing it routes to the same `student_proficiency_path` as the get but is a `delete` request instead but more importantly i don't think there will be a `delete_student_proficiency_path`

**Comment by marks828** [comment]
fixed that last part but now I'm having trouble accessing the instance of a proficiency to delete. This is deleting every proficiency assigned to the student id

![image](https://cloud.githubusercontent.com/assets/15305847/19529669/f05d5bfc-95fe-11e6-905c-ea2a197a32db.png)

before:
![image](https://cloud.githubusercontent.com/assets/15305847/19529718/1c63977a-95ff-11e6-8580-4e6589fcc4cf.png)

after:
![image](https://cloud.githubusercontent.com/assets/15305847/19529735/2a716932-95ff-11e6-9e68-a91b240af8e6.png)

**Comment by nolds9** [comment]
@SNESChalmers34 weird, I would put a `binding.pry` in the destroy method, or try those methods out in the rails console.

FWIW, if you have access to the individual proficiency's id, should just be able to find a proficiency by that id, then delete that proficiency

**Comment by marks828** [comment]
Figured it out. I create the same prof. id for two different values so when i want to delete one i delete both. thanks!
