### ISSUE TITLE
Updating name from a different model

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project2#741]
I'm currently adding a form for editing my athlete model. It has most of the attributes that need to be updated, however the name is nested in my user model (1-1 relationship). How do I edit my form, so it will edit the name from my user model.

error
![image](https://cloud.githubusercontent.com/assets/20713810/19530680/dbb300d6-9602-11e6-926d-7bb917981856.png)

schema
![image](https://cloud.githubusercontent.com/assets/20713810/19530630/a3de3c84-9602-11e6-83fb-5fa93ce138bd.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19530637/ad452a58-9602-11e6-9776-4df033fb17b5.png)

edit view
![image](https://cloud.githubusercontent.com/assets/20713810/19530668/cc79813a-9602-11e6-9de2-1be6a7796951.png)

athletes controller
![image](https://cloud.githubusercontent.com/assets/20713810/19530703/f1a94530-9602-11e6-91be-237fd0c6bf3b.png)

**Comment by nolds9** [comment]
@MichaelZLai this is a little complicated because what you are trying to do is update two different records in one form, which `form_for` does not know how to do.

That being said, maybe you could do something along the lines of this SO http://stackoverflow.com/questions/10003806/how-to-update-child-object-in-a-nested-form-in-rails

**Comment by MichaelZLai** [comment]
That worked! Thanks #Holla

**Comment by MichaelZLai** [comment]
@nolds9 So it's showing the name now, however when updating, it's not saving the value

before
![image](https://cloud.githubusercontent.com/assets/20713810/19532092/3bf94a04-9608-11e6-9ec3-af72bead7009.png)
after
![image](https://cloud.githubusercontent.com/assets/20713810/19532107/46e990c2-9608-11e6-89b4-04636e5a980f.png)

form
![image](https://cloud.githubusercontent.com/assets/20713810/19532120/527d276e-9608-11e6-9272-42cecd81efc4.png)

**Comment by nolds9** [comment]
interesting, I think you might need to add a line like `accepts_nested_attributes_for  :user, :name` on your `Athlete` model http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

**Comment by jshawl** [comment]
do you need to modify strong params to account for new incoming attribute?
