### ISSUE TITLE
Showing added content

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project2#742]
![image](https://cloud.githubusercontent.com/assets/21348450/19530720/0164206c-9603-11e6-975f-693fd0e375d2.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19530749/1ad17bbc-9603-11e6-8246-2f9b59320b5b.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19530766/2b1b2a04-9603-11e6-982b-e477256087f8.png)
was trying to show the beers added according to which style i added it to. It just keeps printing beer. Do I need to add an index view for my beers controller or how do I get them to show exactly what i add when i hit create?

**Comment by nolds9** [comment]
@brophy2321 I think you want `beer.name` not `@style.beers.name`

**Comment by brophy2321** [comment]
I changed that and now it just says Name: but no other content. The amount of Names does correlate with the amount of create beers ive submitted

**Comment by amaseda** [comment]
You only need to change `@style.beers.name` to `beer.name` on Line 11, not 6. Is that what you did? If not let me know and we can keep troubleshooting.

**Comment by brophy2321** [comment]
yes, i only changed line 11

**Comment by amaseda** [comment]
Is this your style's show view? If so, can you paste what you have in your `show` action in `styles_controller.rb`?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19531249/f8c7cf56-9604-11e6-9e82-924507f94605.png)

**Comment by nolds9** [comment]
weird, can you double check in rails console that the records are there? i.e. can you go in and find a style, and see all associated beers to that style, and verify that the data is what you think it is

**Comment by nolds9** [comment]
also if you don't mind sharing your most recent `styles/ show` view

**Comment by brophy2321** [comment]
i ran Style.all and they all showed

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19531521/01ab849a-9606-11e6-8068-3cf5c3d048a2.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19531531/090e4754-9606-11e6-9be7-4d3ec121e3b8.png)

**Comment by nolds9** [comment]
@brophy2321 what happens when you run `Beer.all`? Do each beer have a name?

Also something that maybe helpful is to do `Style.first.beers` to see if that returns all the beers, associated to the first style..

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19531689/8eaf309e-9606-11e6-8808-11b9f3b40876.png)

**Comment by brophy2321** [comment]
its still not recording the name

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19531722/b3349404-9606-11e6-859c-729de3ca838b.png)

**Comment by nolds9** [comment]
looks like you might have some problems with your data. I see a lot of beers whose `name` and `style` is `nil`...What does your seeds look like?

**Comment by brophy2321** [comment]
Yeah I'm guessing thats the problem. I actually dont have anything in my seeds

**Comment by brophy2321** [comment]
would i add the styles in the seeds for each one like we did in game of thrones?
![image](https://cloud.githubusercontent.com/assets/21348450/19531900/5d7285ac-9607-11e6-87fa-4b8fe61fe365.png)

**Comment by nolds9** [comment]
@brophy2321 yes that would be a good start. I would create a bunch of `Style`s, then create a bunch of beers making sure to associate a style to each beer.

**Comment by brophy2321** [comment]
ok entered seeds and ran the db:seed, got it all working. thank you
