### ISSUE TITLE
quicktime not working

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#743]
I'm trying to record a test session.  If I start QuickTime.  it immediately goes to a finder menu does not give me the app.

![image](https://cloud.githubusercontent.com/assets/19254862/19531730/bc213586-9606-11e6-9ba7-a4d0cc3fb69e.png)

Clicking open brings up finder
![image](https://cloud.githubusercontent.com/assets/19254862/19531781/f754381a-9606-11e6-9047-7f87c3102af4.png)

Am I missing something here?

**Comment by nolds9** [comment]
quicktime player should be available as an icon in your menu bar

**Comment by merubin** [comment]
OK, user error getting started.  But All I am getting is the screen recording no audio.  I am using my iphone headset.  Should the microphone on the headset work?

**Comment by jshawl** [comment]
it should - do you see a little arrow by the record button?

**Comment by merubin** [comment]
Thanks!  Got it now!
