### ISSUE TITLE
web

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project2#744]
I'm trying to debug thru web browser console, but it's not working. Can't figure the issue.
![Uploading image.png…]()

**Comment by amaseda** [comment]
What are you trying to debug? How do you know it's not working / what error(s) are you getting?

**Comment by jshawl** [comment]
it also says uploading image.... can you reupload?

**Comment by marlungu** [comment]
i tried, the console does not respond

**Comment by jshawl** [comment]
can you close - command - w and open a new terminal window?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19534222/f6f06f92-9610-11e6-901e-a8b79fa0816b.png)

**Comment by jshawl** [comment]
sorry I still don't know what the issue is - what are you trying to debug?
