### ISSUE TITLE
Not showing created comment under topic in show page

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project2#745]
<img width="1056" alt="screen shot 2016-10-19 at 2 44 49 pm" src="https://cloud.githubusercontent.com/assets/19317100/19532804/4c2d526e-960b-11e6-8964-fa2202efef93.png">
<img width="726" alt="screen shot 2016-10-19 at 2 45 32 pm" src="https://cloud.githubusercontent.com/assets/19317100/19532803/4c2ba7c0-960b-11e6-8712-b372d40fba3a.png">

**Comment by jshawl** [comment]
try `@topic.comments`

**Comment by alman92** [comment]
I had tried that already and it didn't work

**Comment by alman92** [comment]
Also ive since added 

  def show
    @comment = Comment.find params[:id]
  end

to the comment controller

**Comment by jshawl** [comment]
please try:

```
<%= @topic.comments %>
```

in show.html.erb

**Comment by alman92** [comment]
Still nothing :/

**Comment by jshawl** [comment]
please paste output

**Comment by jshawl** [comment]
give me something to work with!

**Comment by alman92** [comment]
Wait ok I fixed something in the controller, the local variable was wrong. Now im getting this

![image](https://cloud.githubusercontent.com/assets/19317100/19533062/3b0c437c-960c-11e6-8652-723391621519.png)

**Comment by jshawl** [comment]
ok excellent what about `<%= @topic.comments.inspect %>`

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19533121/7c9607ec-960c-11e6-9748-2c24c22ed496.png)

**Comment by alman92** [comment]
It just put the number string in an array i think

**Comment by jshawl** [comment]
it looks like the comment is not being created - can you add an exclamation point to `create`

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19533290/2007170e-960d-11e6-8ce3-795ae970128c.png)

Still not showing

**Comment by alman92** [comment]
Could it have anything to do with my show page?

**Comment by jshawl** [comment]
and no errors when you try to create a topic now? I think the show page looks correct

**Comment by alman92** [comment]
No errors, Im not creating a topic, im making a new comment under a topic.

**Comment by jshawl** [comment]
sorry I meant "and no errors when you try to create a comment now? I think the show page looks correct"

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19533588/70303a66-960e-11e6-9fdb-55f837326d79.png)

Yes! An error now

**Comment by jshawl** [comment]
aw hell yeah

**Comment by alman92** [comment]
I feel like it might have to do with comment_params (?)

**Comment by jshawl** [comment]
when creating the comment, can you merge in the current_user?

``` rb
@topic.comments.create(comment_params.merge(user: current_user))
```

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19533798/42482e0a-960f-11e6-9ed9-f66da866f59f.png)

Progress!!

**Comment by alman92** [comment]
Now I'm pretty sure I have to use the show page to display it correctly right?

**Comment by jshawl** [comment]
yeah! an each for each of the comments, maybe?

**Comment by alman92** [comment]
Yea definitely, last question, would I use the comments show page or the topics show page?

**Comment by jshawl** [comment]
what

**Comment by jshawl** [comment]
how do you mean

**Comment by alman92** [comment]
Nvm i got it haha

**Comment by amaseda** [comment]
Word!
