### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by bkeating55** [ga-wdi-exercises/project2#746]
Whenever I click new activity I keep getting this error

<img width="1280" alt="screen shot 2016-10-19 at 2 58 31 pm" src="https://cloud.githubusercontent.com/assets/20100536/19533132/88ec3d0e-960c-11e6-81bd-2d681b9923c4.png">

<img width="1280" alt="screen shot 2016-10-19 at 2 54 25 pm" src="https://cloud.githubusercontent.com/assets/20100536/19533045/2e5263d2-960c-11e6-91ce-85394ef12143.png">

<img width="1280" alt="screen shot 2016-10-19 at 2 54 47 pm" src="https://cloud.githubusercontent.com/assets/20100536/19533056/3888041a-960c-11e6-8eac-8587b0e80325.png">

<img width="1280" alt="screen shot 2016-10-19 at 2 55 07 pm" src="https://cloud.githubusercontent.com/assets/20100536/19533064/3e40a308-960c-11e6-8073-61b44a5d0e08.png">

**Comment by jshawl** [comment]
shouldn't it be `form_for [@user, @activites]`?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-10-19 at 3 20 05 pm" src="https://cloud.githubusercontent.com/assets/20100536/19533891/9ac8915a-960f-11e6-878b-08def35464ed.png">

**Comment by jshawl** [comment]
ok progress! do you have a `@user` in your controller? for activities new

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-10-19 at 3 29 04 pm" src="https://cloud.githubusercontent.com/assets/20100536/19534197/de16b058-9610-11e6-910e-ef050b54429c.png">

i just added it and got this error

<img width="1280" alt="screen shot 2016-10-19 at 3 30 30 pm" src="https://cloud.githubusercontent.com/assets/20100536/19534243/062d0dd0-9611-11e6-98d4-1c78399b81b3.png">

**Comment by jshawl** [comment]
shouldn't `@user` be `User.find(params[:user_id])`

**Comment by bkeating55** [comment]
thanks
