### ISSUE TITLE
i STILL cant figure it out

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project2#747]
![image](https://cloud.githubusercontent.com/assets/20734065/19533334/486b1f7e-960d-11e6-8111-2ec6ab7ad613.png)

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19533339/536e7402-960d-11e6-9310-e8b54198023d.png)

**Comment by khoitle** [comment]
i know my code in the show action is completely wrong also..

**Comment by khoitle** [comment]
another error on top of the previous one 
![image](https://cloud.githubusercontent.com/assets/20734065/19533399/9d798762-960d-11e6-94a3-77ed5f3c2134.png)

im sure they're related

**Comment by amaseda** [comment]
How are you getting to this page? A particular link? If so, can you paste that code here?

You probably don't have a Continent with an id of 15 -- you can confirm that in the Rails console -- so perhaps 15 is an id for something else...

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19533633/9c226ae0-960e-11e6-8ac5-54afe3becfed.png)

**Comment by khoitle** [comment]
its creating and saving, perhaps its the redirect thats the issue?

**Comment by khoitle** [comment]
<img width="570" alt="screen shot 2016-10-19 at 3 14 56 pm" src="https://cloud.githubusercontent.com/assets/20734065/19533699/d65e2a00-960e-11e6-8470-12dd17db5a3a.png">

**Comment by amaseda** [comment]
Yeah, I think it's the redirect. You're passing in a destination when you should be passing in a continent (i.e., the first model mentioned in the path helper).

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19533948/ded5f158-960f-11e6-9e83-aee74bdcd61b.png)

but i thought i am passing in a continent

**Comment by amaseda** [comment]
I'm talking about the redirect in your DestinationController's `create` method. It currently says `continent_destinations_path(@destinations)`, when you should instead be passing in a continent.

This solves the [second error](https://github.com/ga-wdi-exercises/project2/issues/747#issuecomment-254910531) you sent over, but I wouldn't be surprised if something similar was happening for the first one.

**Comment by khoitle** [comment]
working on it!

**Comment by khoitle** [comment]
I fixed the second issue, but then got lost with another issue. Perhaps i could get some help on this new one and if/when i stumble on the old problem ill make a new issue? 

![image](https://cloud.githubusercontent.com/assets/20734065/19534959/e1216cea-9613-11e6-8d48-cee6eff37e8f.png)

![image](https://cloud.githubusercontent.com/assets/20734065/19534964/e806e2b0-9613-11e6-8691-a49e588d222a.png)

**Comment by jshawl** [comment]
you need to pass in a continent if youre using `contient_destination_path`

**Comment by khoitle** [comment]
im trying to delete a destination, not the continent so heres my code, which i think is closer to what i want

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19535406/85388948-9615-11e6-995c-47ad46f2085a.png)

and heres my delete route for destinations 

![image](https://cloud.githubusercontent.com/assets/20734065/19535418/925d8f74-9615-11e6-89a2-850e5b9ec081.png)

**Comment by amaseda** [comment]
Whenever you do `continent_destination_path` (**note**: that destination is singular), it needs a continent **and** destination, so this...

``` rb
continent_destination_path(@destination)
```

...turns into this...

``` rb
continent_destination_path(@continent, @destination)
```

**Comment by khoitle** [comment]
sweet. 

my path doesn't include a contintent id:
`http://localhost:3000/destinations/19/activities`

But it would work if the url were:
`http://localhost:3000/destinations/19/activities?continent_id=7`

How do I set _that_ up?

**Comment by khoitle** [comment]
I think all my issues are actually revolved around that. Its the same error thats killing me. Im sorry for asking the same questions over and over :( 

![image](https://cloud.githubusercontent.com/assets/20734065/19535865/6e70b2ba-9617-11e6-8143-a5e862a02b39.png)

**Comment by jshawl** [comment]
there is no contintent_id in the url - should there be?

what link takes you to that page?

**Comment by khoitle** [comment]
i believe there should be, just so it can take in the params.  I hate to be rude, im just frustrated but could you explain the conditional in the controller for me? I still havent gotten a clear answer on that. 

Since ALL my errors have come from implementing a new model last night, i believe its what you said how one controller is referencing multiple tables

**Comment by jshawl** [comment]
I don't think there needs to be a conditional in the controller if the `continent_id` should be in the url

**Comment by jshawl** [comment]
what link is taking you to that url?

**Comment by khoitle** [comment]
I cant get to that link anymore. When i put a link method to delete, i get this error.
![image](https://cloud.githubusercontent.com/assets/20734065/19537263/4ee44c4e-961d-11e6-8c53-ca50797e5cf6.png)

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19537289/6527529e-961d-11e6-8e2b-232187ce67d1.png)

**Comment by khoitle** [comment]
Line 4 of the previous screen shot is the link i click when i get this error.

**Comment by jshawl** [comment]
shouldn't it be `link_to continent_destination_activity_path`

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19537487/17e922d6-961e-11e6-9082-8a92ec922672.png)

**Comment by khoitle** [comment]
i have no such route.

**Comment by khoitle** [comment]
<img width="1016" alt="screen shot 2016-10-19 at 5 05 00 pm" src="https://cloud.githubusercontent.com/assets/20734065/19537650/cc508656-961e-11e6-97d9-2d9c4d13c8d8.png">
<img width="970" alt="screen shot 2016-10-19 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/20734065/19537659/d31f9c10-961e-11e6-9f49-94c2cb347e61.png">

**Comment by amaseda** [comment]
Referencing [this error](https://github.com/ga-wdi-exercises/project2/issues/747#issuecomment-254939037)...

Ok looks like `@continent` is nil. If you can't access the continent using `params[:id]`, what about if you instead did `@continent = @destination.continent`? This assumes that the destination already belongs to a continent.

**Comment by khoitle** [comment]
@amaseda ALRIGHT IT WORKED! To catch  you up, I had a foreign key error, so i added a dependent destroy. When i deleted the destination, it deletes everything but it comes with the MAIN error I have. Here it is

![image](https://cloud.githubusercontent.com/assets/20734065/19560374/408856d8-96a2-11e6-8e88-c835fbd1b9bf.png)

**Comment by jshawl** [comment]
aw hell yea! are you redirecting to the right place after the destroy?

**Comment by khoitle** [comment]
that worked! but now im getting an error with update a destination 

![image](https://cloud.githubusercontent.com/assets/20734065/19561076/281a4054-96a5-11e6-9962-ddac050eceee.png)

**Comment by jshawl** [comment]
isn't it just `:id` and not `:destination_id` in the controller?

**Comment by khoitle** [comment]
No errors! But when I click this link ~ <%= link_to "Edit this Destination", edit_continent_destination_path(@continent, @destination) %> ~

It brings me to a show page, rather than the edit page

**Comment by jshawl** [comment]
what is the url when you click

**Comment by khoitle** [comment]
i got it to go to the right edit page. but now when i update the the destination it prints out 
![image](https://cloud.githubusercontent.com/assets/20734065/19561496/f0cd830c-96a6-11e6-9b92-c70f20fda15c.png)

here is my route page 
![image](https://cloud.githubusercontent.com/assets/20734065/19561515/fd2d2f9e-96a6-11e6-9750-0418f13467fa.png)

**Comment by jshawl** [comment]
It looks like destinations belong to a continent - is the form_for `[@continent,@destination]`

**Comment by khoitle** [comment]
Yeah thats in there 
![image](https://cloud.githubusercontent.com/assets/20734065/19561630/7e0d7cd6-96a7-11e6-9f03-d990ac8cc3db.png)

**Comment by nolds9** [comment]
@KhoiLe89 what does your `edit` and `update` controller actions look like?

**Comment by khoitle** [comment]
@nolds9  ![image](https://cloud.githubusercontent.com/assets/20734065/19561849/35726314-96a8-11e6-8d9d-f6b1a86b1ea6.png)

**Comment by nolds9** [comment]
@KhoiLe89 `@continent` needs to be defined in your `edit` and `update` actions!

**Comment by nolds9** [comment]
Also, make sure to remember to pass the correct objects to your path helper, when you redirect on the update

**Comment by khoitle** [comment]
oh.. my apologies, i didnt define continent. I do have two more major errors. And full disclosure,  It might be something we've already gone over..  

When i try to update activities i get this omnipresent error 
![image](https://cloud.githubusercontent.com/assets/20734065/19562212/7ca7220a-96a9-11e6-932b-596e6153c2e5.png)

**Comment by khoitle** [comment]
The activity itself takes in the update and changes, but that error comes up. Could you explain why?

**Comment by khoitle** [comment]
I do know that if I change line three of the activities controller, I will no longer be able to delete destinations

**Comment by jshawl** [comment]
after updating the activities, what url do you want the user to go to?

**Comment by nolds9** [comment]
Can you post you activities controller?

**Comment by khoitle** [comment]
@nolds9 activities controller 
![image](https://cloud.githubusercontent.com/assets/20734065/19562764/8a52fada-96ab-11e6-86b8-9777d0479495.png)

**Comment by khoitle** [comment]
@jshawl After updating an activity, i want to to redirect to the Activites Index page

**Comment by nolds9** [comment]
@KhoiLe89 ok, so pull up `rails routes` and check if you have a path for that...my guess is that you are redirecting to the wrong path, and probably want some context of a destination

**Comment by khoitle** [comment]
![image](https://cloud.githubusercontent.com/assets/20734065/19562951/5149f56c-96ac-11e6-8a54-ec7ad7264205.png)

**Comment by khoitle** [comment]
i actually changed the redirect to destination_activities_path(@destination) but then i get this error 

![image](https://cloud.githubusercontent.com/assets/20734065/19563085/baf14588-96ac-11e6-885d-566b845e0879.png)

**Comment by khoitle** [comment]
here is my new controller, but the same error still comes, 
![image](https://cloud.githubusercontent.com/assets/20734065/19563152/03301216-96ad-11e6-9fba-1cd954a85c0e.png)
