### ISSUE TITLE
pushing objects into other objects

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#748]
<img width="594" alt="screen shot 2016-10-19 at 3 11 23 pm" src="https://cloud.githubusercontent.com/assets/21045394/19533594/74b05936-960e-11e6-9bce-fa325e01032f.png">

To create a cart functionality, I have a 'cart' attribute on the user model that is initialized as an empty array. When a user clicks 'add to cart', it redirects to this controller. The controller finds the relevant product (which it is doing successfully) and shovels it into the user's 'cart' array. However, I'm finding that it is shoveling 'nil' into the array each time I try it (despite the fact that @product is defined correctly). Is this a strong params thing or am I missing something syntactically?

**Comment by jshawl** [comment]
> However, I'm finding that it is shoveling 'nil'

is @product nill in the binding.pry?

**Comment by AndyWhitley** [comment]
no, it is showing up correctly

**Comment by jshawl** [comment]
but `current_user.cart` is nil after the save?

**Comment by AndyWhitley** [comment]
So if I do it three times, cart looks like this:

[nil, nil, nil]

**Comment by jshawl** [comment]
what is the data type for `user.cart` ?

**Comment by jshawl** [comment]
can i see schema.rb

**Comment by AndyWhitley** [comment]
In doing so, I am changing an attribute of the current user (cart). While I'm not feeding params directly into it, they are involved. Could rails be preventing me from directly pushing it in (without going through some strong_params) or simply unable to read/store the object?

Here is the schema (cart is about half-way down):

<img width="1063" alt="screen shot 2016-10-19 at 3 25 42 pm" src="https://cloud.githubusercontent.com/assets/21045394/19534076/5dc20290-9610-11e6-8cd5-a5e5106abda5.png">

**Comment by jshawl** [comment]
do you need to map each of `params[:add_to_cart]` to integers? http://blog.plataformatec.com.br/2014/07/rails-4-and-postgresql-arrays/

**Comment by AndyWhitley** [comment]
I convert params[:add_to_cart] to integers coming in to find the related object. But I see, let me change the array data type to text and see if that will allow me to store objects.

**Comment by AndyWhitley** [comment]
That worked in allowing the full object in as a string but now I can't access it (because it's a string): 
<img width="1161" alt="screen shot 2016-10-19 at 3 44 11 pm" src="https://cloud.githubusercontent.com/assets/21045394/19534731/00d03892-9613-11e6-8b9a-137dee0cbe1b.png">

Is there any way to convert it back into a recognizable object whose properties I can access? I've tried using eval and to_i so far but they just convert it to nil and 0, respectively.

**Comment by jshawl** [comment]
yes! `user.cart.map{|id| Product.find(id)}`
