### ISSUE TITLE
unnamed variable

### ISSUE THREAD

**Issue by chrisjaff** [ga-wdi-exercises/project2#749]
I'm making my crate method and I get this error when submitting the form.

<img width="1436" alt="screen shot 2016-10-19 at 3 41 11 pm" src="https://cloud.githubusercontent.com/assets/18494879/19534705/d9ffee1a-9612-11e6-9a8f-876f1e5e9d6b.png">
<img width="736" alt="screen shot 2016-10-19 at 3 44 27 pm" src="https://cloud.githubusercontent.com/assets/18494879/19534727/f8c26ba2-9612-11e6-97e6-dc4525c62923.png">

**Comment by jshawl** [comment]
what if you remove the space after new on line 16?

**Comment by chrisjaff** [comment]
I get the same error message.

**Comment by jshawl** [comment]
hmm this looks right - can you try restarting your rails server?

**Comment by chrisjaff** [comment]
The message is the same but here is what the server log says about the creation.
<img width="548" alt="screen shot 2016-10-19 at 3 57 05 pm" src="https://cloud.githubusercontent.com/assets/18494879/19535229/d9b10848-9614-11e6-8ca9-40877b29465b.png">

**Comment by jshawl** [comment]
and the error message is the same?

**Comment by chrisjaff** [comment]
yes

**Comment by jshawl** [comment]
have you pushed your latest code to github? I will clone down n check it out

**Comment by amaseda** [comment]
`private` doesn't need an `end`. I think if you get rid of the second-to-last `end` you'll be good.

**Comment by jshawl** [comment]
OMG your create method was missing an end

**Comment by amaseda** [comment]
:point_up: Both of these! :point_up:

**Comment by chrisjaff** [comment]
You guys are correct. After making the changesI was redirected back to the home page. Thank you.
