### ISSUE TITLE
Decrementing an integer in the database

### ISSUE THREAD

**Issue by kscoulter** [ga-wdi-exercises/project2#75]
I want to decrement the number of players needed by one when a player submits a form. I tried: 

<%= form_for [@event, @attendance] do |f| %>
  <%= f.submit "Join" %>
  <% @event.num_players -= 1 %>
<% end %>

That didn't work. Not sure where I hate to put that ruby code.

**Comment by kscoulter** [comment]
Also tried: 

<%= form_for [@event, @attendance] do |f| %>
  <%= f.hidden_field :num_players, @event.num_players - 1%>
  <%= f.submit "Join" %>
<% end %>

got this error: undefined method `merge' for -1:Fixnum

**Comment by RobertAKARobin** [comment]
Instead of doing this in your view, I would do it in the controller.

```
@people_needed = @event.num_players - 1
```

In view:

```
<% if @people_needed > 0 %>
  <%= f.submit "Join" %>
<% end %>
```

**Comment by kscoulter** [comment]
That didn't work. People_needed doesn't change when I submit the form.
