### ISSUE TITLE
Changing Devise Sign Up / Sign IN

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project2#750]
Hello.  I'm Googling like crazy...trying to turn the devise Sign Up / Sign In from an email to a PIN.  There are about 10 different ways to do this but I was wondering if you guys could steer me in the right direction.  It's not that important.  If I get it, I get it...if I don't, it doesn't really take away from my project.

**Comment by jshawl** [comment]
so you want to remove the email, and instead have people have a unique pin that they log in with?

**Comment by jshawl** [comment]
https://github.com/ga-wdi-exercises/project2/issues/751#issue-184059242

**Comment by jshawl** [comment]
hmm honestly I've never done this... have you seen https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address ?

**Comment by amaseda** [comment]
Going to close this one but please keep us posted. Would be great to know how to do it for future reference!
