### ISSUE TITLE
Editing Devise New User Registration controller

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project2#752]
I'm following this [tutorial for setting up user invites](https://coderwall.com/p/rqjjca/creating-a-scoped-invitation-system-for-rails), and got to the section about editing the new user registration controller: 
![image](https://cloud.githubusercontent.com/assets/2591447/19535448/b4d3f35e-9615-11e6-83ad-ef3c90b5365b.png)

Where do I find this stuff to edit? I'm not sure how to translate her code examples into my own devise configuration right now. 

Thanks!

**Comment by nolds9** [comment]
https://github.com/plataformatec/devise#configuring-controllers

Looks like you need to generate the controllers, since they are hidden by default

**Comment by timfoley** [comment]
Sweet!
