### ISSUE TITLE
Trying to prevent other tipsters from deleting suspects from Tips that aren't theres.

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project2#753]
Hello gentlemen.  I found a bug in my code.  I'm trying to prevent Tipsters from being able to delete suspects from Tips that they didn't provide.  Attached are my code snippets from Tips.  I was able to successfully block users from deleting other people's Tips, but I can't seem to block users from Deleting Suspects. 

![image](https://cloud.githubusercontent.com/assets/20567326/19536436/f27555c8-9619-11e6-8d1a-6623f27cbe8b.png)

This is the code snippet for Suspects.  This is where I'm having the issue.

![image](https://cloud.githubusercontent.com/assets/20567326/19536469/0f810fb8-961a-11e6-85f5-2b7d0452bbf0.png)

**Comment by jshawl** [comment]
can you put the same conditional in the update?

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19536801/8398cb24-961b-11e6-929b-49c06081e6dc.png)

**Comment by jshawl** [comment]
does that solve the issue?

**Comment by brown2206** [comment]
No, unfortunately it doesn't.

**Comment by jshawl** [comment]
does the flash notice appear?

**Comment by brown2206** [comment]
No

**Comment by jshawl** [comment]
do you have the flash code in your view? can you put a puts in there to see if the conditional is evaluating to true or false?

**Comment by amaseda** [comment]
Any update on this one @brown2206? Did you check to make sure the necessary view code is in there?

**Comment by brown2206** [comment]
I accomplished the goal.  It works.  Please close this.

**Comment by jshawl** [comment]
👍
