### ISSUE TITLE
New Activity

### ISSUE THREAD

**Issue by bkeating55** [ga-wdi-exercises/project2#754]
Having an issue with what to put here....before I was getting an error that it must be a hash now I'm getting this...

<img width="1280" alt="screen shot 2016-10-19 at 4 46 47 pm" src="https://cloud.githubusercontent.com/assets/20100536/19536834/b333b20e-961b-11e6-8c4d-5be6dfd76e67.png">

<img width="1280" alt="screen shot 2016-10-19 at 4 44 55 pm" src="https://cloud.githubusercontent.com/assets/20100536/19536843/bdd0f50a-961b-11e6-8f7e-e1c8b1059394.png">

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-10-19 at 4 55 18 pm" src="https://cloud.githubusercontent.com/assets/20100536/19537121/db864194-961c-11e6-82fb-f18d6991c440.png">

**Comment by jshawl** [comment]
`user_params` looked good... do you have a method named `user_params` in your controller?

**Comment by bkeating55** [comment]
Do you mean add it to the activity controller with the "activity_params"

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-10-19 at 4 59 57 pm" src="https://cloud.githubusercontent.com/assets/20100536/19537321/818f4784-961d-11e6-87f1-538c28303410.png">
<img width="1280" alt="screen shot 2016-10-19 at 5 00 27 pm" src="https://cloud.githubusercontent.com/assets/20100536/19537340/8f923652-961d-11e6-86e6-445cf81914b3.png">

**Comment by nolds9** [comment]
@bkeating55 what is your end goal? Looks like you were working on creating a new `activity`. 
Inside `activities#create`, make sure you first **find** the `user`, then create a new `activity` associated to that `user.
