### ISSUE TITLE
Edit Issue

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project2#755]
<img width="1131" alt="screen shot 2016-10-19 at 4 51 13 pm" src="https://cloud.githubusercontent.com/assets/19317100/19537022/6bec1e62-961c-11e6-80f1-030d8e3134e9.png">
<img width="1066" alt="screen shot 2016-10-19 at 4 51 22 pm" src="https://cloud.githubusercontent.com/assets/19317100/19537023/6bed6fa6-961c-11e6-9e4d-f3fa03af226b.png">

Editing function isnt working

**Comment by nolds9** [comment]
@alman92 What do you mean by not working? When you click on the link to edit a topic, it gives you that routing error?

**Comment by alman92** [comment]
Yea exactly that, I'm confused as to why its giving me the delete route

**Comment by jshawl** [comment]
did you click the delete comment link?

**Comment by alman92** [comment]
No i clicked edit

**Comment by jshawl** [comment]
can you refresh the page and try again? delete requests can only be initiated from a link with `method: :delete`

**Comment by nolds9** [comment]
looks like `@comment` is not what you think it is

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19537205/20aa23f8-961d-11e6-99fe-c321fc771378.png)

Stupid mistake on my part

Getting this one now

**Comment by alman92** [comment]
Looks much more managable

**Comment by nolds9** [comment]
👍

**Comment by amaseda** [comment]
Gonna close this one but feel free to re-open if the issue persists!
