### ISSUE TITLE
Ordering by column with boolean value

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project2#757]
I'm trying to order my students by an admin column with a boolean datatype.

I've tried:
![image](https://cloud.githubusercontent.com/assets/15305847/19538231/1d722b3c-9621-11e6-93ad-223cd9247346.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19538255/37b56cca-9621-11e6-87d3-a8f6e1dd79b5.png)

and other variations of these

**Comment by amaseda** [comment]
What about `@students = Student.order("admin DESC")`? Throws some SQL into the mix. Borrowing that idea from [this post](http://stackoverflow.com/questions/12524311/how-to-order-results-by-an-existing-boolean-attribute-first).

**Comment by jshawl** [comment]
@SNESChalmers34 let me know!
