### ISSUE TITLE
extra field with no content

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project2#758]
![image](https://cloud.githubusercontent.com/assets/21348450/19538416/eff70514-9621-11e6-87c9-43295cb9f522.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19538426/faa8626e-9621-11e6-878d-bff8111dfd6c.png)

on all my show pages it has an empty content below the actual beers displayed. I can delete the ones with content but not the empty one

**Comment by amaseda** [comment]
Can you paste the code for the following...
- This view
- The corresponding controller
- `routes.rb`

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19558460/a4bfa2a0-9698-11e6-9818-4fc5f7859299.png)

**Comment by jshawl** [comment]
it seems you're sending a delete request to `styles/14/beers`, but instead should specify an id for which beer to delete. can i see the code for the link to delete?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19560948/9ce59060-96a4-11e6-8044-c4a4ebceb0e8.png)

**Comment by jshawl** [comment]
it should be a `link_to` in your view

**Comment by brophy2321** [comment]
i have it in my first model for styles
![image](https://cloud.githubusercontent.com/assets/21348450/19561013/eb3921b4-96a4-11e6-8f86-0dc01c2c0779.png)

**Comment by brophy2321** [comment]
i actually dont have any views for my beer model, would that be why?

**Comment by jshawl** [comment]
what page has the link where you clicked delete?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19562227/83a6b778-96a9-11e6-950a-45cabb88e430.png)
if i start here and i click the show button on any of the styles, they all have that initial content field with nothing in it like so
![image](https://cloud.githubusercontent.com/assets/21348450/19562269/af19add4-96a9-11e6-8f9b-fdb767cb94e9.png)
