### ISSUE TITLE
Javascript click events sometimes don't work on page load but do when page refreshed

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project2#759]
This happens randomly and it is very confusing.

**Comment by bcope** [comment]
Here is my javascript: https://github.com/bcope/dm/blob/master/app/assets/javascripts/application.js

Here is my view: https://github.com/bcope/dm/blob/master/app/views/creatures/show.html.erb
On the view the .toggle-buttons div are the links that sometimes don't work. This is particularly confusing because all it takes to get them working is a page reload.

**Comment by jshawl** [comment]
thing to google is "remove turbolinks rails"

**Comment by bcope** [comment]
Thanks! I think that did it.
