### ISSUE TITLE
deployment issues

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project2#760]
So after much trouble, I was able to get heroku to successfully deploy (or at least build) my web app. However, when I go to open it, I get the following message. 
<img width="1440" alt="screen shot 2016-10-20 at 8 49 33 am" src="https://cloud.githubusercontent.com/assets/21045394/19560420/6c20e51c-96a2-11e6-8074-0bfe16921f93.png">
I can't figure out how to proceed since the last thing the logs show is the successful deployment of my app.

**Comment by jshawl** [comment]
did you `heroku run rake db:migrate`

**Comment by jshawl** [comment]
also `heroku logs`

**Comment by AndyWhitley** [comment]
I deployed through their github linking service, not the heroku cli

**Comment by AndyWhitley** [comment]
it was able to successfully precompile everything though and build as well

**Comment by AndyWhitley** [comment]
So should I download their cli and redeploy?

**Comment by jshawl** [comment]
if you visit herokuapp.com you can see the logs there - can you tell me what the log says?

**Comment by AndyWhitley** [comment]
<img width="1302" alt="screen shot 2016-10-20 at 9 13 41 am" src="https://cloud.githubusercontent.com/assets/21045394/19561187/92e390de-96a5-11e6-8de8-28c10b90bbbf.png">

**Comment by AndyWhitley** [comment]
Last night, to fix my precompiling deployment issues, I moved the script tag in layout.html.erb to the bottom of the html (my event listeners weren't being loaded in on the first page load of my login page). Would that be causing this?

**Comment by jshawl** [comment]
the logs are promising! but there is not enough info in them to diagnose - can you see anything else maybe right above what you took a screenshot of?

**Comment by AndyWhitley** [comment]
nope, that is all the info the logs gave me (no scroll up available)

**Comment by jshawl** [comment]
refresh the page - the app should crash again and give you more output

**Comment by AndyWhitley** [comment]
<img width="1191" alt="screen shot 2016-10-20 at 9 25 34 am" src="https://cloud.githubusercontent.com/assets/21045394/19561571/36791a24-96a7-11e6-942a-986b170d18a7.png">

logs just keep showing the same errors

**Comment by AndyWhitley** [comment]
I'm going to try moving the js tag back to the head and redeploy

**Comment by AndyWhitley** [comment]
I moved the js tag back to the head and redeployed. It deployed successfully but still getting the 'something went wrong' screen and the same servers logs
<img width="1234" alt="screen shot 2016-10-20 at 9 28 19 am" src="https://cloud.githubusercontent.com/assets/21045394/19561673/ab29461e-96a7-11e6-97d3-91faafd5829d.png">

**Comment by jshawl** [comment]
can you scroll up or down at all? there is not enough info in what you posted to debug

**Comment by AndyWhitley** [comment]
nope, still can't scroll. I think that's all there is.

**Comment by AndyWhitley** [comment]
actually they just loaded in. I think the relevant error is near the bottom (the categories table not existing)
<img width="1255" alt="screen shot 2016-10-20 at 9 32 50 am" src="https://cloud.githubusercontent.com/assets/21045394/19561854/3b104d9a-96a8-11e6-958f-cdfa109eaedf.png">

**Comment by AndyWhitley** [comment]
i.e. it can't find my database on the server

**Comment by nolds9** [comment]
ahh, we need to figure out how to do the equivalent of `heroku run rails db:migrate`

**Comment by AndyWhitley** [comment]
I just downloaded the heroku cli app, do I run that command before I deploy through the app?

**Comment by nolds9** [comment]
After you deploy the app, https://devcenter.heroku.com/articles/getting-started-with-rails5#migrate-your-database

**Comment by AndyWhitley** [comment]
ran heroku run rails db:migrate and seed and it fixed it. Thank you!
