### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project2#761]
I connected github to heroku, should I select automatic deploy ?
![image](https://cloud.githubusercontent.com/assets/15622467/19560874/2ec4fe0e-96a4-11e6-9a19-cccba4d8934a.png)

**Comment by jshawl** [comment]
yeah give it a go!

**Comment by pohckuan** [comment]
the deployment was successful, but it breaks as soon as I click a link in my app
![image](https://cloud.githubusercontent.com/assets/15622467/19561200/a0e1be36-96a5-11e6-8cd9-8009b5bb0d6d.png)

**Comment by jshawl** [comment]
ok great! if you visit heroku - you should be able to see logs - is there any info in the logs?

**Comment by nolds9** [comment]
@pohckuan I would recommend deploying through the Heroku CLI instead of via the gitub integration....you can download the CLI here https://devcenter.heroku.com/articles/heroku-command-line

And follow the steps in https://devcenter.heroku.com/articles/getting-started-with-rails5

**Comment by pohckuan** [comment]
I used the CLI and it's not working yet. i checked the build log and saw this 
![image](https://cloud.githubusercontent.com/assets/15622467/19562010/bda72256-96a8-11e6-92a7-a9b9a16f2191.png)

**Comment by jshawl** [comment]
no this is all good information! anything after that

**Comment by nolds9** [comment]
Those warnings are fine, did you run `heroku run rails db:migrate`?

**Comment by pohckuan** [comment]
nothing 'worse' than that in the log. 
I will run the command now

**Comment by pohckuan** [comment]
i have all these info after running heroku run rails db:migrate. Should I do heroku create again?
![image](https://cloud.githubusercontent.com/assets/15622467/19562258/a3ec8d50-96a9-11e6-9a38-feaaf3feaf7e.png)

**Comment by jshawl** [comment]
this looks great! is your app working now?

**Comment by nolds9** [comment]
no need to run `heroku create`, should be able to run `heroku open` to view your app

**Comment by pohckuan** [comment]
it is showing the html and css but not the data

**Comment by jshawl** [comment]
did you `heroku run rails db:seed`?

**Comment by pohckuan** [comment]
NOW IT WORKS! 
Do I submit a new issue with the the app's link and the video's youtube link?

**Comment by nolds9** [comment]
Nice! https://github.com/ga-wdi-exercises/project2#deliverables

**Comment by pohckuan** [comment]
in the same place we create issue for questions?
