### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project2#762]
I put a background image on my application.css which I'm aware is throughout the whole application.  But I don't know how to just apply it to the front page.

Also separately having trouble styling with devise.

**Comment by jshawl** [comment]
can you share the html / class you're using to style

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19562116/1edf5ad4-96a9-11e6-83b7-028d53d90924.png)
![image](https://cloud.githubusercontent.com/assets/19317100/19562131/2ee19f14-96a9-11e6-96f3-e915624c867e.png)

**Comment by nolds9** [comment]
@alman92 If you are trying to style devise, you might want to generate the views.

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19562154/48401f3a-96a9-11e6-9f3c-84161d60309f.png)

![image](https://cloud.githubusercontent.com/assets/19317100/19562169/595d6a3e-96a9-11e6-8795-546e0906dc2b.png)

**Comment by nolds9** [comment]
What if instead of selecting the body, you were to add a container element to your splash page, and then select that instead

**Comment by alman92** [comment]
Sorry haha, which is the splash page?  The application.html.erb?

**Comment by nolds9** [comment]
@alman92 whichever view you want the fire

**Comment by alman92** [comment]
Its the index.html.erb under the topics view, but I have a topics.scss page and it doesn't seem to manipulate anything

**Comment by nolds9** [comment]
@alman92 remember all that stuff that looked like comments in `application.css`? That was how rails actually pulled in other stylesheets. You might want to add that back

**Comment by alman92** [comment]
How can I add that back?

**Comment by nolds9** [comment]
I'll help ya out:

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require_tree .
 *= require_self
 */
```
