### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#767]
Having an issue when attempting to update a post. Rather than updating it, it creates a brand new post with the new parameters. 

I'm using a partial for the form and have a feeling its doing this because its missing the 'method: :patch' command. How can I add the patch functionality to a partial? 

Can I do anything like <%= render 'form', method: :patch %>? That didn't work but something along those lines.

**Comment by superbuggy** [comment]
I don't think you necessarily need the method: :patch in the form submission. Are you rendering the form from `edit.html.erb`?

Can you create a repo, push, and share your code you have so far?

**Comment by ghost** [comment]
https://github.com/RobRomaniw/patch

Rendering the form in both /edit and /new.

**Comment by superbuggy** [comment]
can you try adding in a `puts "* In create" * 10` in your def create method? check the terminal for  `create` being triggered and let me know if it is actually triggering create

**Comment by superbuggy** [comment]
you could also try removing `url: posts_path` and seeing if that alters form submission behavior

``` rb

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
```

**Comment by superbuggy** [comment]
is this issue still an issue?

**Comment by superbuggy** [comment]
if not, please close issue

**Comment by ghost** [comment]
I'll close for now. I will just write out forms long ways if I cannot figure it out.
