### ISSUE TITLE
Having trouble utilizing a gem

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project2#768]
I'm trying to use a gem called ruby-poker which will help evaluate poker hands for me.  ive added the gem to my gem file and run bundle install.  The gem should enable me to run a method (.rank) on an array of cards ("5H", "KH", "7S", "7D", "6S").  When I try to run the ".rake" method as part of an action in my controller i receive the following error:

undefined method `rank' for ["3D", "TD", "JS", "2D", "8H"]:Array

The documentation for the gem mentions including require 'rubygems' and require 'ruby-poker' somewhere in my file, however when I include it either at the top of my controller or at the top of my method I receive a different error:

cannot load such file -- ruby-poker

This is the first time I've used an external gem like this - so I am not totally clear on the setup and implementation......

Help plzzzz

**Comment by superbuggy** [comment]
Did you add it to your `Gemfile` and run `bundle install`?
