### ISSUE TITLE
need db help

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#77]
So I've futzed with my db and now the actions in the browser aren't talking to it. I've tried a few different things and the db is recognizing commands issued through the console. I THINK it's talking to a different database, though. Is there a way to fix this and avoid rebuilding the whole rails app again?

**Comment by RobertAKARobin** [comment]
It's hard to say without seeing specific errors or code samples. But as long as you aren't writing SQL statements directly into the database, or modifying `schema.rb`, the database itself shouldn't be affected. The models may have been affected, but you can change those without needing to restart your server, let alone recreate the database.

**Comment by jkoul** [comment]
Thanks Robin! i THINK I got it ironed out with a rake db:reset. I'll close the issue and open a new one if further complications come up.

**Comment by RobertAKARobin** [comment]
Sounds good!
