### ISSUE TITLE
I broke everything :(

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project2#770]
Looks like my entire Card class/model is now somehow corrupted... trying to reseed my db and gettting:

NoMethodError: undefined method `destroy_all' for Card:Class

**Comment by superbuggy** [comment]
You probably just broke the chain of inheritance from `ActiveRecord::Base`

**Comment by jgrune** [comment]
application record still looks good:

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

**Comment by superbuggy** [comment]
is Card inheriting from ApplicationRecord?

**Comment by jgrune** [comment]
yep it is

**Comment by jgrune** [comment]
*ApplicationController

**Comment by superbuggy** [comment]
card.rb should inherit from ApplicationRecord

**Comment by jgrune** [comment]
it does :( should I come over?
