### ISSUE TITLE
Rails c

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project2#771]
This worked about an hour ago and now its not for some reason.

When I enter the repl in rails c and I copy and paste some sample seed such as

`sky = Course.create(img_url:"none", name:"pebble", location:"123 white", num_holes:18, par:72, yardage:6820, rating:74)`

its doesnt create a ID for the course 

` => #<Course id: nil, img_url: "none", name: "pebble", location: "123 white", num_holes: 18, par: 72, yardage: 6820, rating: 74, created_at: nil, updated_at: nil> `

 yet if I do this for hole,user,group, or bet it will.

**Comment by amaseda** [comment]
What happens if you use `.create!` (with an exclamation mark) instead of `.create`? Does that cause new error(s) to appear?

**Comment by bradleycravens** [comment]
I fixed it somehow I have no idea how but thank you lol

**Comment by amaseda** [comment]
:+1:
