### ISSUE TITLE
Creating a post form on a non traditional rails route

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project2#772]
Goal: Create a sign in page that routes to the user's show page (profile)

I will try to post a picture of the error. I think the top of my form looks correct after reviewing previous examples. It looks like the form is getting tripped up on my "@user" not having an ID because it hasn't been made yet. Any thoughts?

**Error**
`No route matches {:action=>"show", :controller=>"users"} missing required keys: [:id]
`

**Code**
```
<%= form_for @user, url: user_path(@user), method: :post do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Submit" %>
<% end %>

```

**Comment by robertzehnder** [comment]
<img width="801" alt="screen shot 2016-11-11 at 1 33 12 pm" src="https://cloud.githubusercontent.com/assets/16313830/20225900/b96ce51e-a813-11e6-85fc-24b713d57c81.png">

**Comment by robertzehnder** [comment]
For the record, there is a show action in the users controller

```
class UsersController < ApplicationController
  def welcome
  end

  def show
    @user = User.find(params[:id])
    @session = session[:name]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:name] = @user.email
    redirect_to user_path(@user)
  end

  def sign_in
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :image_url)
  end
end

```

**Comment by robertzehnder** [comment]
I kinda see what it is saying that there isn't an ID yet, but how do I make it wait for the input to be submitted before evaluating the ID in the show action of the users controller

**Comment by superbuggy** [comment]
it's looking for a route that matches `post '/users/:id'`, you could create a custom route for that. creating a new User would seem to be  a sign-up, rather than a sign-in also. does that make sense?

**Comment by superbuggy** [comment]
the show action corresponds to get a `get '/users/:id'`

**Comment by superbuggy** [comment]
I would probably handle with a redirect after the form submission. Would that suffice?

**Comment by robertzehnder** [comment]
Ok I think I got it, so custom post route where you redirect? I was trying to redirect in the same action that was calling my form, but that wasn't working for obvious reasons. I will give it a shot. You can close this for now.

**Comment by superbuggy** [comment]
will do; just reopen if you have any more questions!
