### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project2#773]
When I try to login it doesn't throw an error it just doesn't create the user. This used to work but I changed the user model to include a group_id and I think thats messing it up. 

`class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to users_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :group_id)
  end

end`

Even if i take out `:group_id` from user_params it doesn't work

**Comment by bradleycravens** [comment]
https://github.com/bcravens/Project2/tree/master/golf

**Comment by superbuggy** [comment]
Not immediately seeing it-- what error comes up if you `!` `create`?

**Comment by bradleycravens** [comment]
Group must exist

**Comment by bradleycravens** [comment]
Is there somewhere I can say group is not required even if its a relationship between models?

**Comment by superbuggy** [comment]
Yeah you have to have an existing group to reference. you can pass in `belongs_to :group, optional: true`

http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html
