### ISSUE TITLE
Where to go next

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/project2#775]
So I've got two models (User, Account) and I "think" I want to nest them but I'm not getting the result I want when I do. Here's the code I'm inputing that's generating the error:

sorry about posting code, I just don't know what to do
-----------------------------
users/show.html.erb
-----------------------------
<h2>Add an account:</h2>
<%= form_for([@user, @user.accounts.build]) do |f| %>
  <p>
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :assoc_email %><br>
    <%= f.text_area :assoc_email %>
  </p>
  <p>
    <%= f.label :assoc_password %><br>
    <%= f.text_area :assoc_password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

--------------------------------------------------
accounts_controller.rb
--------------------------------------------------
  def create
    @user = User.find(params[:user_id])
    @account = @user.accounts.create(account_params)
    redirect_to user_path(@user)
  end
end

 
  private
    def account_params
      params.require(:account).permit(:website, :assoc_email, :assoc_password)
    end

**Comment by ejsorrento** [comment]
Is this where I'd use a many-many?

https://github.com/ejsorrento/Project-2-Password-Log

**Comment by superbuggy** [comment]
what error are you getting?

**Comment by superbuggy** [comment]
I also think that nesting makes sense here. I don't think you'd want a many to many. Can you screenshot or include your error?

**Comment by ejsorrento** [comment]
I figured it out 

rake db:rollback
add - t.integer :user_id - into db/migrate/<timestamp>_create_accounts.rb
**_add addition for app/views/users/show.html.erb**_
rake db:migrate

**Comment by ejsorrento** [comment]
the issue was the lack of "t.integer :user_id"

**Comment by superbuggy** [comment]
awesome! i didn't know what error you were getting-- make sure to include that next time. posting code is more than fine!

**Comment by superbuggy** [comment]
awesome. gonnna close the issue 👍
