### ISSUE TITLE
DB:SEED ISSUE

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/project2#776]
Problem: I've been adding onto my project in pieces. I've created mentors (model), mentees (model) and mentorships (join model) as the relationship that brings the two together. Once, I had that working, I wanted to add user accounts and that's what I'm currently having problems with. I've added the user model and everything that goes with it. I've added a user account into my seed but, I'm getting the following error:

ActiveRecord::RecordInvalid: Validation failed: User must exist

I feel like I'm missing something small with how I have my seeds.rb setup. How do I fix this?

Repo: https://github.com/avalant/wdi13-project2

**Comment by andrewsunglaekim** [comment]
sounds like when you're creating a mentor/mentee, there needs to be a user associated with it.

**Comment by superbuggy** [comment]
try adding `optional: true` after your `belongs_to` statement

you may need `dependent: :nullify` for delete as well

**Comment by superbuggy** [comment]
http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

**Comment by avalant** [comment]
I missed adding the user_id from the user account into the creation of my mentee and mentor records. This solved the issue.

After reading the provided link, I definitely want to have user accounts associated with the mentee/mentor records. As I want to the user accounts to be responsible for being able to manipulate data.
