### ISSUE TITLE
Newly created items not populating within the model that it belongs to

### ISSUE THREAD

**Issue by nguyendthinh** [ga-wdi-exercises/project2#777]
Hello.

I created an option under each show view for the Brands model so that an admin (user at this time) can add a new sneaker in the model. The new function work as I was able to go to the new view page for the Sneakers model confirming that it was successfully created. However, the newly created sneakers aren't populating on the show page of the Brands model that it was created from.

I suspect it's probably something to do with it not having an id assign but I would think that the id would automatically be assigned by creating it within the Brands model.

Github: https://github.com/nguyendthinh/projectTwoShoes

**Comment by superbuggy** [comment]
I suspect that this is because of `belongs_to: brand, optional: true` in `sneaker.rb`; a new sneaker is not necessarily being linked to a specific instance of a brand.

**Comment by nguyendthinh** [comment]
I did that because every time when I try to create a sneaker, it kept telling me that the validation has failed and that Brand must exist and I'm not sure what means because I never told the Sneaker model that it needed that validation.

**Comment by superbuggy** [comment]
it's something that `belongs_to:` does in Rails 5 

http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

**Comment by nguyendthinh** [comment]
I see. What should I look into to solve this validation error?

**Comment by superbuggy** [comment]
Well I think you have to write code that specifically associates your sneaker with a certain brand **_when creating a new sneaker**_, if you want the sneaker to show up when you filter on brands. The other thought I have is that you may not need a brand model, and you could just have a brand attribute of your sneaker model.

**Comment by nguyendthinh** [comment]
In the sneakers controller:

``` ruby
def create
    @brand = Brand.find_by_id(params[:brand_id])
    @sneaker = @brand.sneakers.create!(sneaker_params)
    redirect_to @sneaker
  end

class Sneaker < ApplicationRecord
  belongs_to :brand
  validates_presence_of :brand_id
end
```

These are the following changes that I've made into the code. Now it is saying that `undefined method 'sneakers' for nil:NilClass`. Am I somehow referencing something that doesn't even exist -_-

**Comment by superbuggy** [comment]
`@brand` isn't an instance of a join model, so you can't use that type of helper method

edit: apologies-- the above was wrong-- you can do this with has_many

**Comment by superbuggy** [comment]
I think you are on the right track with grabbing the brand_id, you just need to associate it with the instance of the brand

**Comment by superbuggy** [comment]
@sneaker hasn't been defined

**Comment by superbuggy** [comment]
just checking in -- did you resolve your issue?

**Comment by nguyendthinh** [comment]
I'm getting close to solving it. I decided to try nesting the resources~

**Comment by superbuggy** [comment]
That makes sense-- if you find you don't need a `brand` model, you could also just add a brand column to your sneakers table, and filter on that `brand` column for `sneakers`
