### ISSUE TITLE
Instance variable question

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project2#778]
I am trying to access the value a user adds to an input text box across multiple views.... The value is originally gathered from the "new hand" page, and stored in an instance variable (@bet). I can access the value in the create action, but I want to continue accessing it after I redirect to other actions/views.  

At the end of the create action, I redirect to the edit action/route, and at that point, I am unable to access the original instance variable.  Any idea what I'm doing wrong?

def create
    @bet = params[:bet]
    # render plain: @bet.inspect
    hand = Hand.create!
    @card_array = Card.order("RANDOM()").first(5)
    @card_array.each do |card|
      card.hand_id = hand[:id]
      card.img = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bordered_#{card.suit[0]}_#{card.value}.svg/88px-Bordered_#{card.suit[0]}_#{card.value}.svg.png"
      card.dealt = true
      card.save
    end
    @lasthand = Hand.last

    redirect_to edit_hand_path(@lasthand)
  end

  def edit
    @hand = Hand.find(params[:id])
  end

**Comment by superbuggy** [comment]
I think sessions is your best **_bet**_

**Comment by jgrune** [comment]
eyyyyyyyy :)

**Comment by jgrune** [comment]
still having trouble displaying session values directly in my view.  I stored my bet in the create action as session[:bet] = @bet, but when I try to display session[:bet] directly in my veiw, nothing is showing up... do I need to first store the value of session[:bet] into an instance variable in the controller, and then include that variable in my view?

**Comment by superbuggy** [comment]
You can just directly assign session[:bet] to params[:bet]

**Comment by jgrune** [comment]
That did it! Thank you sir!

**Comment by bet** [comment]
Please stop Cc-ing me on this thread.

**Comment by superbuggy** [comment]
btw make sure you're enclosing your ruby instance variables in backticks i.e. `@instance`

**Comment by superbuggy** [comment]
otherwise you're tagging github users 😆
