### ISSUE TITLE
Monday checkup

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/project2#779]
Buenos dias, muchachos,

I was hoping I could get some time with someone just to go over what I've done so far in my work and get some feedback. I feel like I'm going in the correct directions, but there's still a bit a of doubt. I think there may possibly be some conflict when I move into my sessions, as there was when I attempted devise yesterday. Currently I'm mapping out what I want to get accomplished for today.

Let me know when works for one of you!
Gracias

**Comment by ejsorrento** [comment]
Please answer my question, I have no friends

**Comment by andrewsunglaekim** [comment]
I'll have open office hours at 11. But we haven't even learned devise yet! It's an optional mini lesson for this afternoon. Users, however, is something we've learned how to do. Check out https://github.com/ga-wdi-lessons/rails-users-sessions-flash-cookies

**Comment by andrewsunglaekim** [comment]
going to close this for now, please reopen if you have any further questions.
