### ISSUE TITLE
question about multiple models nested in forms

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/project2#78]
I am trying to manage multiple models with a single form and most of the literature points to the accepts_nested_attributes_for method.  

However all the tutorials i've found addressing how to and it's validity are more than a couple years old  so just want to see if this is still valid or if there was a newer method I should be looking into.

**Comment by RobertAKARobin** [comment]
You can, it's just a bit tricky. You can't rely on `form_for` and other helpers. You'd need something like:

```
<%= form_tag("/some_path", method: "post") do %>
  <%= text_field_tag("owner_name") %>
  <%= text_field_tag("pet_name") %>
<% end %>
```

```
def create_owner_and_pet
  owner = Owner.create(params[:owner_name])
  pet = Pet.create(params[:pet_name], owner_id: owner.id)
end
```

**Comment by edwardpark** [comment]
excellent i'll give that a shot thanks!
