### ISSUE TITLE
Embed links in Seed File

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project2#780]
Goal: I want to figure out how to make a link in a seed file, so that I can show functional links when a page loads.

Down below I tried to 

**Try #1, using string interpolation and a html tag**
```
roadmap4 = Roadmap.create(
smallGroup: 'NO SMALL GROUPS THIS WEEK',
resources: "#{<a href="https://drive.google.com/open?id=0B0cuNYi34jyuV1NmRjgzSDJ4d3M">}; Cover Letters & Emails; Social Media; Writing"
)
```

**Try #2, Using the link_to method (Tried with and without string interpolation**
```
roadmap4 = Roadmap.create(
smallGroup: 'NO SMALL GROUPS THIS WEEK',
resources: "#{link_to 'Resume', "https://drive.google.com/open?id=0B0cuNYi34jyuV1NmRjgzSDJ4d3M"}; Cover Letters & Emails; Social Media; Writing"
)
```

This is a tough thing to google, because I'm just presented link_to documentation for rails, as opposed to embedding links in Active Record.

**Comment by andrewsunglaekim** [comment]
I think you just need to make the link a property of the model.. Then when you generate it, it will look something like this:

``` html
<%= link_to "string that link will appear as in view", model.url_property %>
```

**Comment by robertzehnder** [comment]
ugh ok thanks, was hoping to avoid that

**Comment by andrewsunglaekim** [comment]
link_to helpers only work in views. and saving the entire link as an anchor feels like an anti pattern to me. Why would you want to avoid it? If eventually your data model is needed on the front end its not tightly coupled to your rails back end. It's just a link

**Comment by andrewsunglaekim** [comment]
gonna close this for now, reopen if you have any further issues.
