### ISSUE TITLE
Grouping data and printing it out 

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project2#781]
At a high level, I'm trying to take some data and group it in a certain way then print it out each instance of that group but I'm having trouble figuring out how to group it correctly and then print it out in an each statement. 

My models are course, hole, bet, group, membership, and user.

I'm trying to print it out all the bets on the index page. 
I basically want 

BETS 
---
Group1
At Course1
Betting on 18 holes 

Group1
At Course3
Betting on 9 holes 

Group2
At Course1
Betting on 18 holes 

-----

In rails c I know how to group them by:
`group1.bets.where(course_id:1)`
`group1.bets.where(course_id:2)`

I've trying to do something like:

```ruby
<% @groups.each do |group| %>
  <%= group.name %>
  <% group.bets.courses.each do |course| %>
      <%= course.name %>
      <%= course.holes.count %>
  <% end %>

<% end %>
```

I'm having trouble at `  <% group.bets.courses.each do |course| %>`

**Comment by andrewsunglaekim** [comment]
are you trying to order them in a certain way? or just query for them? If you're trying to order try `http://apidock.com/rails/ActiveRecord/QueryMethods/order`. If you want to order by two or more crtieria check out `http://stackoverflow.com/questions/3587776/ruby-on-rails-how-do-i-sort-with-two-columns-using-activerecord`

**Comment by bradleycravens** [comment]
I don't care about the order at this point.

**Comment by superbuggy** [comment]
What error are you getting?

**Comment by bradleycravens** [comment]
```
undefined method `courses' for #<Bet::ActiveRecord_Associations_CollectionProxy:0x007fe03b54c270>
```

because I cant do bets.courses

**Comment by superbuggy** [comment]
Ah, because you're trying to do this on `bets`-- you'd have to have another .each for `bets`
