### ISSUE TITLE
Form Field Validation

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project2#782]
On my "new hand" page, I have a text field that accepts user input and represents a user's bet amount (accessible via params).  I would like to perform multiple validations on that bet amount, and am trying to perform that validation right when my create action fires off.  I am attempting to utilize flash messages with the following code: 

```
def create

    # validates bet amount
    if params[:bet].is_a? String
      flash[:alert] = "You must enter a valid bet amount"
      redirect_to new_hand_path
      return
    elsif params[:bet] > @current_user.dollars
      flash[:alert] = "You don't have enough money to bet that amount!"
      redirect_to new_hand_path
      return
    elsif params[:bet] < 0
      flash[:alert] = "You must enter a bet greater than zero"
      redirect_to new_hand_path
      return
    end
```

I am receiving an error stating that I can't have multiple redirects in an action.  Is there a better way to validate this input that I'm missing?

**Comment by andrewsunglaekim** [comment]
seems like your redirecting to the new_hand_path no matter what, so just move that to the bottom and get rid of it in the conditionals. get rid of all those `return` keywords too.

**Comment by jgrune** [comment]
thanks - this can be closed!
