### ISSUE TITLE
Attempting to get back to an old commit

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/project2#784]
Good morning guys, 

I'm trying to get back to an old commit I had called "Nested pre-devise", I made it before I tried devise which was smart because I'm going back to it.

My errors are I'm deleting files and not reseting them

Here's the commands I'm running

-----------------------------------------------------
Bonus Exercise 3: Reset your work

What if you staged some work and realize you don't want that saved? Or, what if you've gone even further and committed something, but want to revert back to the last commit?

make a few changes to your resume.txt file
stage those files, but do NOT commit
check your git status
try reverting that file back to before it was staged, what happens when you run git status again?
git reset head
make a new change to your resume.txt file, and this time add and commit it
can you still revert with the same command?
try git reset head^
note, be VERY careful when reseting! you cannot undo if you go back a commit
this will return the changes you made to be untracked
to completely undo the changes, run git checkout -- resume.txt after git reset head^
-------------------------------------------------------------

I'm not sure what I need to do

**Comment by superbuggy** [comment]
How many commits back is the commit you would like to revert to? You can check this with git log.  If you have multiple branches, you will have to account for that also.

**Comment by ejsorrento** [comment]
Right,

The commit I was looking for was the most recent. After the commands I've put in, not only do I not have that commit in git log, but also the one before it

**Comment by andrewsunglaekim** [comment]
http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit

**Comment by ejsorrento** [comment]
http://stackoverflow.com/questions/15745045/how-do-i-resolve-git-saying-commit-your-changes-or-stash-them-before-you-can-me

**Comment by ejsorrento** [comment]
git clean -dfx
