### ISSUE TITLE
Nesting issue?

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/project2#787]
So my models are users and accounts, no problem going from users > user/:id/ > user/:id/accounts, as long as this line is not in the code: *Error message as well*

#Error:
<img width="857" alt="screen shot 2016-11-15 at 12 01 37 pm" src="https://cloud.githubusercontent.com/assets/22303391/20315414/ce9458da-ab2b-11e6-9e46-391e87b4ab34.png">

#Rake routes:
<img width="516" alt="screen shot 2016-11-15 at 12 08 53 pm" src="https://cloud.githubusercontent.com/assets/22303391/20315588/7db12b5e-ab2c-11e6-9ef9-204950638d50.png">

#Routes:
<img width="326" alt="screen shot 2016-11-15 at 12 09 19 pm" src="https://cloud.githubusercontent.com/assets/22303391/20315597/8a305742-ab2c-11e6-9770-4bae3979db99.png">

I've tried:

-Leaving the error line blank link so this, which brought up the page.
<td><%= link_to 'Show'  %></td> 
-Leaving it blank completely which got rid of the show link
-Inputing different paths pertaining to rake routes

I understand it's a routing issue, but rake routes tells it's available
-so maybe it isn't

**Comment by ejsorrento** [comment]
The error changed!

**Comment by ejsorrento** [comment]
<img width="607" alt="screen shot 2016-11-15 at 12 31 27 pm" src="https://cloud.githubusercontent.com/assets/22303391/20316348/728344a8-ab2f-11e6-9284-cb3d018982b9.png">

**Comment by andrewsunglaekim** [comment]
for the `user_account_path` you need to make sure you pass in a `user_id` as well as an `id` (for the account)

**Comment by superbuggy** [comment]
how are you doing with this issue at the moment? just checkin in

**Comment by ejsorrento** [comment]
Here's what I've done:

-Remove everything from accounts/index.html.erb <- whoops, estupido

-Rerouted my users/show.html.erb to accept the accounts/show.html.erb
**<h1><%= link_to 'Accounts', user_account_path(users_path) %></h1>**

The issue was the accounts index

I'm curious about this though:

http://localhost:3000/users/%2Fusers/accounts/2
-The users id has that weird thing^^

**Comment by ejsorrento** [comment]
Is that a problem or is that a bi-product of nesting?

**Comment by ejsorrento** [comment]
Nvm yes it is

**Comment by superbuggy** [comment]
%2F is the url encoding of `/` -- rather than have users twice in the url,  where `%2Fusers/` is, you want a number (a user_id)

**Comment by ejsorrento** [comment]
I'm assuming that is also causing this

ActiveRecord::RecordNotFound (Couldn't find Account with 'id'=accounts):

but you know what they say about assuming...

**Comment by ejsorrento** [comment]
Update:

I got the first one, now it looks like this

http://localhost:3000/users/1/accounts/%2Fusers%2F1

**Comment by superbuggy** [comment]
I think the problem lies in your show (or maybe index) view for users-- specifically when you link the show view for an account account
