### ISSUE TITLE
halp :/

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/project2#788]
I am trying to have a 'playlist' function for my application, which gives you the ability to add live music videos to your playlist (or "showlist") if logged in as a user. I created the "showlist" model and controller and it is connected to my "users" and "shows" (aka videos) models via the following relationships:

In show.rb
```
class Show < ApplicationRecord
  belongs_to :album
  has_many :showlists
  has_many :users, through: :showlists
end
```

In showlist.rb
```
class Showlist < ApplicationRecord
  belongs_to :user
  belongs_to :show
end
```

In user.rb
```
class User < ApplicationRecord
  has_many :showlists
  has_many :shows, through: :showlists

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
```

What I am trying to do (to start) is have a link to create a new showlist - this will essentially just create the showlist (and allow you to name it) and then as you browse through the application, you can select individual shows to add to this showlist that you have created. [I'm just starting with one showlist per user session to get the functionality down]. The problem I'm having is coding the new and create actions in the showlist controller. For showlist#new and showlist#create, I currently have:
```
def new
    @user = current_user
    @showlist = @user.showlists.build
  end

def create
    @user = current_user
    @showlist = @user.showlists.create!(showlist_params)
    ???>>> @showlist.show_id = nil <<<???
    redirect_to @showlists
  end
```
How can I re-factor the showlist controller's create action (or possibly the showlist/show relationship?) to create an empty showlist (with no show_id's) and be able to access that showlist in other controller actions (i.e. adding and removing songs). With what I have now I am getting the following rails red page (I'm pretty sure the @showlist.show_id line is wrong, but that's kind of the idea of what I'm trying to do):

![screen shot 2016-11-15 at 12 21 30 pm](https://cloud.githubusercontent.com/assets/22160743/20315994/25ae6e06-ab2e-11e6-80e0-94983b11ba1a.png)

Let me know if this doesn't make sense or if I can provide additional info.

**Comment by andrewsunglaekim** [comment]
you're getting this error because you have a validation on your showlist model that makes it need to have a show. In `showlist.rb`: `belongs_to :show`

**Comment by donovanallen** [comment]
When I take that out though, how can I still access the shows of a specific showlist (i.e. doing .each to list the shows in that showlist). Without that association in showlist, I can no longer do something like: 

```
  def show
    @showlist = current_user.showlists.find(params[:id])
    @shows = @showlist.shows
  end
```

**Comment by superbuggy** [comment]
try `belongs_to :show, optional: true`

**Comment by superbuggy** [comment]
`optional: true` disables the built-in Rails 5 validation that requires the presence of a foreign key in order to be instantiated.

**Comment by donovanallen** [comment]
Got it. Do I have to re-migrate after I change model relationships/validations?

**Comment by donovanallen** [comment]
![screen shot 2016-11-15 at 2 18 49 pm](https://cloud.githubusercontent.com/assets/22160743/20320066/866da1ac-ab3e-11e6-9b4a-e438161f4c4a.png)

I'm still not getting my expected behavior of being able to access a showlist's shows. When opened in the rails console, each showlist has a show_id field, but I want each show to belong to a showlist (i.e. have a showlist_id). Can I switch this relationship around -- for example: change `belongs_to :show, optional: true` to `has_many :shows, optional: true` and make Show `belongs_to :showlist, optional: true`?  Will that affect the Users model as the showlist model is the join table between users and shows?

**Comment by superbuggy** [comment]
You shouldn't have to re-migrate, it's just changes model validations essentially

**Comment by donovanallen** [comment]
Ok, I think this is my last questions that shold help me get to the bottom of this. 

In my schema, showlists table has a show_id field. I think what I want instead is for each show to have an (optional) showlist_id (of user playlists that video has been assigned to) so then I can access each show within a user's showlist. If I change 

```
class Showlist < ApplicationRecord
  belongs_to :user
  belongs_to :show, optional: true
end
```

to 

```
class Showlist < ApplicationRecord
  belongs_to :user
  has_many :shows, optional: true
end
```

, i get an error that :optional is not a valid argument. What do I need to do to update the schema accordingly, make the relationship work this way, and access each showlist's shows?

**Comment by superbuggy** [comment]
closing for now! reopen if necessary
