### ISSUE TITLE
Difficulty with splitting date, time

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/project2#789]
I had a working join table "performances" that would associate "artists" with "shows" that is no longer working now that I've updated one of the "shows" attributes from "datetime" to "starts_at_date" and "starts_at_time"

from my seeds: 

```
fourthshow = Show.create(flyer_img: "http://i4.mirror.co.uk/incoming/article7220601.ece/ALTERNATES/s615/PAY-Donald-Trump-Duck.jpg",
starts_at_date: "2016-11-21",
starts_at_hour: "9:00:00")

firstperf = Performance.create(artist_id: 1, show_id:1)
```

no performances are created when seeding, and when I try to do create one in the repl it's showing as nil

```
  Show Load (0.3ms)  SELECT  "shows".* FROM "shows" WHERE "shows"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
   (0.1ms)  ROLLBACK
 => #<Performance id: nil, artist_id: 1, show_id: 2, created_at: nil, updated_at: nil> 
2.3.0 :007 > 
```

I'm not sure what I've done differently other than changing the columns in "shows"

**Comment by andrewsunglaekim** [comment]
did you re run migrations?

**Comment by drewswinburne** [comment]
Yup! Dropped the db, recreated it, migrated and seeded.

**Comment by drewswinburne** [comment]
Oh nevermind, I think the problem was with this time_splitter gem I was trying to use. Deleted it and it seems to work
