### ISSUE TITLE
issue with updating a comment

### ISSUE THREAD

**Issue by walter-0** [ga-wdi-exercises/project2#79]
I tried updating a comment with this code.

```
def edit
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:photo_id])
  end

def update
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to photo_path(@photo)
  end
```

 I expected the comment to update, but the comment did not change and also the edit form was prepopulated with the updated comment text. Can I get some help with my update controller?

**Comment by RobertAKARobin** [comment]
Are you sure the comment didn't change? Did you check your database?

**Comment by jshawl** [comment]
I recommend adding a `binding.pry` just after the `.update` method. This will allow you to inspect the values of the different variables: `params`, `comment_params`, etc..

**Comment by walter-0** [comment]
I checked out pry and the comment.content data is correct, but it's just not showing up as an updated comment. Do I need the .save method?

**Comment by jshawl** [comment]
try `binding.pry` after `.update`. `.update = .find + .save`

**Comment by walter-0** [comment]
I tried binding.pry after .update and the database has the right data. The updated comments aren't showing up on the page.

**Comment by walter-0** [comment]
Edit: the comments shown on the page aren't being updated

**Comment by RobertAKARobin** [comment]
If the database has the right data, that's good news! Can you share the code for the view page?

**Comment by walter-0** [comment]
```
<p>
  My Photos -- All Photos
</p>

<p>
  <%= @photo.title %>
</p>
  <div class="photo">
  <%= image_tag @photo.photo_url %>
  </div>
<p>
  upvotes - score - downvotes
</p>

<p>
  <%= link_to "Add Tag", new_tag_path %>
</p>

<p>
<%= form_for @photo, method: :delete do |f| %>
  <%= f.submit "Remove Photo", class: "delete" %>
  <% end %>
</p>

<% @comments.each do |comment| %>
  <ul>
    <%= link_to comment.id, photo_comment_path(@photo, comment) %>
    <%= comment.content %>
  </ul>

<% end %>

<%= render partial: "comments/comment_form" %>
```

A lot is placeholder/throwaway.

**Comment by walter-0** [comment]
Solved: The issue was resolved by changing the
@comment = Comment.find(params[:photo_id])

in both the edit and update actions in the comment controllers to
@comment = Comment.find(params[:id])
