### ISSUE TITLE
Datetime troubles

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project2#790]
I can't figure out how to display my datetime data in a more readable format.
I can do
`<%= event.time %>`
Stackoverflow gives me answers like 
`Time.now.strftime("%Y-%m-%d %H:%M:%S")`
`strftime("%B %-d, %Y")`
I get the error `undefined method strftime' for nil:NilClass` 
I just want something like 01/11/16 5:00pm

**Comment by andrewsunglaekim** [comment]
whats the output of `event.time.class`?

**Comment by bradleycravens** [comment]
`NilClass`

**Comment by bradleycravens** [comment]
But if I do `<%= event.time %>` I get `2016-11-15 18:43:28 UTC` in my html

**Comment by andrewsunglaekim** [comment]
hmm
