### ISSUE TITLE
Another DB Seed Issue

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/project2#791]
I removed everything pertaining to "expertise" from mentor migration, etc. so that I could create a skill table. I created the following models:

`user_skill.rb `(join table) , `skill.rb` ,and updated the `mentor.rb` and `mentee.rb` to reflect the has_many relationship between the models.

`user_skill.rb`:
```ruby
class UserSkill < ApplicationRecord
  belongs_to :mentor, :mentee, :skill
end
```

`skill.rb`:
```ruby
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :mentors, :mentees, through: :user_skills
end
```

`mentee.rb`:
```ruby
class Mentee < ApplicationRecord
  belongs_to :user

  has_many :mentorships
  has_many :mentors, through: :mentorships

  has_many :user_skills
  has_many :skills, through: :user_skills

  validates :name, :photo_url, :location, :phone, :email, :profgoals, presence: true
end
```

`mentor.rb`:
```ruby
class Mentor < ApplicationRecord
  belongs_to :user

  has_many :mentorships
  has_many :mentees, through: :mentorships

  has_many :user_skills
  has_many :skills, through: :user_skills

  validates :name, :photo_url, :location, :phone, :email, :about, presence: true
end
```

In my `db/schema.rb` I have the following:
```ruby
create_table "skills", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "user_skills", force: :cascade do |t|
    t.integer  "mentor_id"
    t.integer  "mentee_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["mentee_id"], name: "index_user_skills_on_mentee_id", using: :btree
    t.index ["mentor_id"], name: "index_user_skills_on_mentor_id", using: :btree
  end
```

then i created skills in my `seeds.rb`:

```ruby
skills1 = Skill.create!([{skill: 'Self-Care'}, {skill: 'Web Development'}, {skill: 'Social Justice'}])
```

and sample into my mentee

```ruby
mentee1 = Mentee.create!({
  name: 'Sue Mentee',
  photo_url: 'http://clahrc.azurewebsites.net/wp-content/uploads/2014/04/placeholder-02-wide-01.png',
  location: 'Washington DC',
  phone: '123-456-7890',
  email: 'sue@fakeemail.com',
  profgoals: 'Lorem ipsum dolor sit amet, at mea illum minim, te iudico denique omnesque mea, cu sea velit quando voluptatibus. Mei ex omnis iusto, ex quod facilisi his. Nisl sententiae cum te. Sea error philosophia ad, ut sed atqui possim reprimique. Nam id sale errem bonorum, ei melius utamur nominavi nec, mea ad porro dolores. Cu mundi nominati complectitur quo, quo et dicunt atomorum appellantur.',
  skill: skills1.first,
  user_id: 1
})
```

I need do db create, migrate, and when I go to see my file I received the following:

`rake aborted!
NoMethodError: undefined method 'arity' for :mentees:Symbol`

What I'm reading about arity confuses me. I did however check my files to see if I set something up wrong with my mentees and everything looks correct to me. But, the error message doesn't lie. I just don't understand.

**Comment by andrewsunglaekim** [comment]
can you do a find on your project folder for `arity` which files has that word?

**Comment by andrewsunglaekim** [comment]
which line of code is erroring in your seed file, and can you paste those lines in this issue?

**Comment by avalant** [comment]
The error isn't giving a specific line of code.

This is the full error when trying to seed the database.

`$ rake db:seed
rake aborted!
NoMethodError: undefined method`arity' for :mentees:Symbol
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/associations/builder/association.rb:54:in `build_scope'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/associations/builder/association.rb:46:in`create_reflection'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/associations/builder/association.rb:29:in `build'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/associations.rb:1360:in`has_many'
/Users/avalant/wdi/projects/wdi13-project2/mentoring_app/app/models/skill.rb:3:in `<class:Skill>'
/Users/avalant/wdi/projects/wdi13-project2/mentoring_app/app/models/skill.rb:1:in`<top (required)>'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:477:in `load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:477:in`block in load_file'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:476:in`load_file'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in`block in load_interlock'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in`exclusive'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in`load_interlock'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:511:in`load_missing_constant'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
/Users/avalant/wdi/projects/wdi13-project2/mentoring_app/db/seeds.rb:11:in`<top (required)>'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in`block in load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in`load'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:549:in `load_seed'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:268:in`load_seed'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/avalant/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in`<top (required)>'
/Users/avalant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/avalant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
`

**Comment by superbuggy** [comment]
/Users/avalant/wdi/projects/wdi13-project2/mentoring_app/**_db/seeds.rb:11:in**_

check out line 11

**Comment by superbuggy** [comment]
sometimes with a stack trace, i'll cmd+f for whatever file i'm working on that is generating the error

**Comment by avalant** [comment]
It's my Skill.destroy_all
I still don't quite understand what's wrong with my db

**Comment by andrewsunglaekim** [comment]
you want to make sure any dependent models get destroyed last. IE

If i have `posts` and `comments`. And `comments` have a `post_id`. I need to make sure all `comments` are destroyed before `posts`

**Comment by superbuggy** [comment]
are you still facing this issue?
