### ISSUE TITLE
Writing Custom Put routes

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project2#792]
Can you confirm that this is the correct way to write a custom put route on the second line?

```ruby
get "homework/:user_id/brand/:id" => 'homeworks#brand'
put "homework/:user_id/brand/:id" => "homeworks#brandUpdate"
```

**Comment by andrewsunglaekim** [comment]
Yep. Seems off that you're putting in a user id under a homework, but yep.

**Comment by andrewsunglaekim** [comment]
If you have your user stored in a session through devise or through a handrolled solution for user auth, don't you have access to the user id that way?

**Comment by robertzehnder** [comment]
Theoretically yes, but I passed on sessions temporarily to finish what I wanted to accomplish

**Comment by robertzehnder** [comment]
thanks!
