### ISSUE TITLE
Trying to bang something in the seed file

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project2#794]
In my seed file, I'm trying to create blank instances of homework and set the user's homework id equal to the id of the homework that was just created. I was trying to use bang but it isn't working. The homework instances are being created, but I'm getting an error when trying to make the ids equal each other.

**Code from the seed file**
```
users.each do |user|
homeworkX = Homework.create(
  brand_strengths: "",
  brand_values: "",
  brand_interests: "",
  brand_personality: "",
  brand_achievement: "",
  brand_mentor: ""
  )

  user.homework_id = homeworkX.id!

end
```

**Error**
```
SyntaxError: /Users/robertzehnder/wdi/exercises/outcomes/db/seeds.rb:102: syntax error, unexpected '!', expecting keyword_end
```

**Comment by andrewsunglaekim** [comment]
can you post your model associations. homeworks has_many users?

**Comment by robertzehnder** [comment]
```
class Homework < ApplicationRecord
  has_many :users
end
```

```
class User < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :cohorts, through: :memberships
  belongs_to :homework
end

```

**Comment by superbuggy** [comment]
did you mean `create!`?

**Comment by robertzehnder** [comment]
@superbuggy, no that part works. A homework instance exists at this point and so does the user. I want to take this newly created instance of homework and set to the current (the one selected for the particular iteration through the each statement) user id. This is the line giving me trouble:

`user.homework_id = homeworkX.id!`

**Comment by andrewsunglaekim** [comment]
why do you have an `!`?

**Comment by robertzehnder** [comment]
@andrewsunglaekim because I want to change the user's (someone who had been created previously) homework id to this id of the newly generated homework instance.

**Comment by robertzehnder** [comment]
I ran through it once without the bang and the user's homework ids weren't updating

**Comment by robertzehnder** [comment]
This is what comes back without the bang

```
outcomes_development=# select email,homework_id from users;
    email     | homework_id 
--------------+-------------
 Man in Black |            
 Dolores      |            
 Teddy        |            
 Maeve        |            
 Bernard      |            

```

**Comment by robertzehnder** [comment]
Do you want me to come over and just talk through it? Would be open to alternative implementations of what I'm trying to do.

**Comment by andrewsunglaekim** [comment]
so instead do this:

``` ruby
user.homework_id = homeworkX.id
user.save
```

the `!` method works differently in active record then it does with many things in the ruby language. Usually only to determine how it should fail or error out( ie silently or loudly)

**Comment by robertzehnder** [comment]
@andrewsunglaekim @superbuggy user.save worked, thanks!
