### ISSUE TITLE
One-to-One Devise to Profile Association Issue

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project2#795]
Attempted to connect the creation of profile with a user log-in and sign-up.  I am unable to test/trouble shoot due to these errors:
1. If NOT logged in I receive the error: undefined method `build_profile' for nil:NilClass
2. If logged in, I receive the error: Failed to remove the existing associated profile. The record failed to save after its foreign key was set to nil.
3. If I try to create a new log-in, I receive the error: NoMethodError in Devise::RegistrationsController#create undefined method `save' for nil:NilClass

It seems that there are problems within each of these files below:

Here is my User Model:
```
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_one :profile
after_create {
    :build_profile unless profile
    profile.save
  }
accepts_nested_attributes_for :profile
end
```

Here is my Profile Model:
```
class Profile < ApplicationRecord
  has_many :signups
  has_many :trips, through: :signups

  belongs_to :user, autosave: true
end
```

Here is my Profile Controller:

```
class ProfilesController < ApplicationController

def new
    @profile = current_user.build_profile
end

def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(profile)
    else
      render action: :new
    end
end

private
  def profile_params
    params.require(:profile).permit(:name, :gender, :dob, :address, :city, :state, :zip, :passport, :telephone_num, :email, :notes)
  end

end
```

**Comment by andrewsunglaekim** [comment]
``` ruby
after_create {
    :build_profile unless profile
    profile.save
  }
```

where is `build_profile` defined? Work through that error first. Where is profile defined? Sounds like it's calling save on something that is nil.

**Comment by superbuggy** [comment]
do you define `profile`? what do you want to happen with regards to profile and users?

**Comment by andrewsunglaekim** [comment]
try https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-up-(registration) out for redirection. Instead of the `after_create` callback you have currently.
