### ISSUE TITLE
ActionController::UrlGenerationError in Profiles#new

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project2#799]
I have a one-to-one model relationship between devise User model and Profile model.

I expected that upon creating a new user session, there will be an automatic redirect to new profile view through the devise Registrations controller:
  
```
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/profiles/new'
  end
end
```

This had previously worked perfectly, but after a new db:drop, db: create, db: migrate, rails is hitting errors:
```
ActionController::UrlGenerationError in Profiles#new
Showing /Users/julietberman/wdi/projects/travel_app/app/views/layouts/application.html.erb where line #14 raised:

No route matches {:action=>"show", :controller=>"profiles", :id=>nil} missing required keys: [:id]
```

**Comment by jshawl** [comment]
application.html.erb where line #14

can i see that file at that line number

**Comment by julietberman** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApps</title>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="login">
    <% if current_user%>
    <span><%=link_to "Welcome, #{current_user.profile.name}!", profile_path(current_user.profile) %></span>
      <span><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></span>
    <% else %>
      <span><%= link_to "Sign Up", new_user_registration_path %></span>
      <span><%= link_to "Sign In", new_user_session_path %></span>
    <% end %>
  </div>

  <a href="/"><%=image_tag("logo.png", class:"logo")%></a>

  <nav>
    <a href="/">Home</a>
    <a href="#">FAQs</a>
    <a href="/trips">Trip Options</a>
    <% if current_user%>
    <%=link_to "Register", new_profile_signup_path(current_user.profile)%>

    <% else %>
    <%=link_to "Log In", new_user_session_path%>

    <% end %>

  </nav>

    <%= yield %>

  </body>
</html>
```

**Comment by jshawl** [comment]
just line 14 though?

**Comment by julietberman** [comment]
Terminal is also listing this error:

```
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"profiles", :id=>nil} missing required keys: [:id])
```

**Comment by jshawl** [comment]
That's ok let's keep on the first error

**Comment by jshawl** [comment]
line 14 is 

```
    <span><%=link_to "Welcome, #{current_user.profile.name}!", profile_path(current_user.profile) %></span>

```

**Comment by julietberman** [comment]
This is the code:

```
<% if current_user%>
    <span><%=link_to "Welcome, #{current_user.profile.name}!", profile_path(current_user.profile) %></span>
      <span><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></span>
    <% else %>
      <span><%= link_to "Sign Up", new_user_registration_path %></span>
      <span><%= link_to "Sign In", new_user_session_path %></span>
    <% end %>
```

**Comment by jshawl** [comment]
`profile_path(current_user.profile)` is causing the URL generation error, and I know that because it's the only code on line 14 that generates a URL.

Try removing that line (temporarily) does it fix the error?

**Comment by julietberman** [comment]
I tried that, it just continues to hit errors anytime a current_user is listed

**Comment by jshawl** [comment]
what error message. Also - I asked you to remove line 14. does only removing that line remove the red rails error?

**Comment by jshawl** [comment]
if not, please post a screen shot or give more info cmd-shift-4

**Comment by julietberman** [comment]
Yes, that is what i did. Here is the next error message that occurred.
<img width="1114" alt="screen shot 2016-11-16 at 1 24 31 pm" src="https://cloud.githubusercontent.com/assets/17633399/20359988/17241db8-ac00-11e6-9024-2d7f64291497.png">

**Comment by jshawl** [comment]
ok execellent - this is the same line of code. remove that one, too

**Comment by jshawl** [comment]
but also, here is the issue:

no route matches show, because the profile id is missing.

try this code:

```
<%= current_user.profile %>
```

what's the output of that?

**Comment by jshawl** [comment]
keep removing the profile_path until you don't get an issue

**Comment by julietberman** [comment]
Okay I have removed all current_user.profile from my code on all the documents. Now the homepage renders. I double checked rake routes and profile_path is listed as the helper method, but this was incorrect?

**Comment by jshawl** [comment]
ok excellent.

what is the output of `<%= current_user.profile %>` on the home page

**Comment by julietberman** [comment]
Nothing seems to appear...

**Comment by jshawl** [comment]
ok great - that means it's nil.

**Comment by jshawl** [comment]
You were getting an error because `profile_path(nil)` doesn't know how to generate a show route

**Comment by jshawl** [comment]
maybe you destroyed the current user's profile when you reset your DB? and that's why the current user doesn't have a profile?

**Comment by julietberman** [comment]
I tested that out previously, and had created new users, but the original errors were what occurred. I just put back in all the code that I had removed one part at a time, and it worked when there is a user. When I try again to create a new user, I run into the same issues.

**Comment by jshawl** [comment]
> When I try again to create a new user, I run into the same issues.

Another way to say this is... I get the same error when the current user doesn't have a profile

**Comment by jshawl** [comment]
solution - only display a link to show the profile if `current_user.profile`

**Comment by jshawl** [comment]
right?

**Comment by julietberman** [comment]
Cool, seems to fix the original issue. However, now wherever there is a link to "http://localhost:3000/users/sign_in" or "http://localhost:3000/users/sign_up" it automatically redirects to the homepage.

**Comment by julietberman** [comment]
the URL doesn't seem to render, but my other URLS render fine

**Comment by andrewsunglaekim** [comment]
I think that's because you already signed in as a user, try clearing your cookies

**Comment by andrewsunglaekim** [comment]
Also, I would remove those link, if there already is a current user something like this : 

``` html
<% if !current_user %>
  <%= #link to sign up %>
  <%= #link to sign in %>
<% end %>
```

**Comment by julietberman** [comment]
Running into an issues with my elsif statement:
<%elsif current_user && current_user.profile%>

I expected this would block code from running unless both a user was logged in AND a profile existed for that used, but the code seems to run and then hit an error.

**Comment by jshawl** [comment]
let's see the error

**Comment by julietberman** [comment]
Same error was before, so I believe my elsif statement isnt sufficiently stopping the code from rendering under the conditions I list

<img width="1053" alt="screen shot 2016-11-16 at 2 22 46 pm" src="https://cloud.githubusercontent.com/assets/17633399/20362090/3c90f76c-ac08-11e6-89e3-8f624ed4deed.png">

**Comment by jshawl** [comment]
what is the output of `<%= current_user.profile %>`

**Comment by julietberman** [comment]
I theory it would be nil, as I have created a user but not yet a profile, it is stopping the "/profiles/new" route from rendering. I am trying to have my elsif statement prevent this error and stop the code until the profile has been created in the /profiles/new form.

**Comment by jshawl** [comment]
what is the output of `<%= current_user.profile %>`

**Comment by julietberman** [comment]
It is nil, doesn't appear on page

**Comment by julietberman** [comment]
Is my theory correct that my  elsif statement isn't truly prevent the code from rendering. I am trying to write code that wouldn't show the specific links until after the user profile is created in the /profiles/new form.
