### ISSUE TITLE
Project2 stories, wireframe, etc.

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project2#8]
<b>_Project2-Photostream link</b>
link to repo: https://github.com/tomBeach/_Project2-Photostream

<b>User Stories</b>
• As a general user I want to be able to select, sort and categorize photos so I can use them for different purposes in the future
• ... view all of my photos as a collection so I can consider my editing options
• ... view my photos by category, group, subject and date taken so I can select them according to my current needs/interests
• ... identify photos with a category
• ... add categories to the category list so I can track new photo types as they come along
• ... organize photos into a collection (group) that I can name myself so I can keep relevent photos together
• ... add groups to the group list so I can preserve photos according to new events/experiences/subjects as time goes on
• ... select individual photos to view so I can decide what to do with them
• ... edit info about each photo (title, description, photographer, location, date taken, etc.) so I have a record of what each one is about
• ... assign a rating to each photo so I can choose the best ones at a later date
• ... display a selection of photos in a slideshow so I can entertain my friends for hours

<b>Models and Database</b>
User -- user_id, username, password, firstname, lastname, email
Photo -- photo_id, user_id, photo_source, photo_WH, title, description, date_taken, loc_taken, rating
Category -- category_id, photo_id, category_title
Group -- group_id, photo_id, group_title

<b>sample wireframes</b>
![photostream](https://cloud.githubusercontent.com/assets/10157094/9028325/77428242-3943-11e5-8f87-859fb843b8e4.png)

**Comment by adambray** [comment]
Hey Tom!

This looks like a great idea! Really like the wireframes!

-Adam
