### ISSUE TITLE
issue with no route matching missing required key

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project2#80]
I tried changing current_user to @user. I expected the missing key to be found. The same error happened instead.

**Comment by jshawl** [comment]
can you please add the error message here and any relevant code that will help us solve this issue?

**Comment by adrianshep** [comment]
I'm trying to get my index page to load. The problem isn't in the user_id as I stated above; it's in a stores id that's missing.  The error message points to a link on the index page that connects to a show page, but that can't be what's preventing index from loading properly.

ActionController::UrlGenerationError in Stores#index

No route matches {:action=>"show", :controller=>"stores", :id=>nil, :user_id=>"1"} missing required keys: [:id]

class StoresController < ApplicationController
  # before any post action happens, it will authenticate the user
    before_action :authenticate_user!

```
# another devise helper method that retrieves the user object that has been authenticated
def index
  @stores = current_user.stores
end
```

**Comment by andrewsunglaekim** [comment]
check your resources/rake routes in `config/routes.rb` if you're getting a no routes matches error

**Comment by adrianshep** [comment]
the error was being caused by link code meant to send index visitor to a show page. commenting it out allowed index to load. on to solving the link code error.

**Comment by RobertAKARobin** [comment]
Thanks for updating, Adrian. Are you still having trouble? If so, could you re-clarify what the trouble is?
