### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/project2#800]
I have a "Shows" show view that plays a video of a selected id:
```
<div class="embed-container">
  <div class="show-nav-arrow" id="previous-button"><%= link_to "<", "/albums/#{:album_id}/shows/#{:id}/previous_show", class: "link" %></div>
  <iframe width="640" height="360" src="<%= @show.video_url %>" frameborder="0" allowfullscreen></iframe>
  <div class="show-nav-arrow" id="next-button"> <%= link_to ">", "/albums/#{:album_id}/shows/#{:id}/next_show", class: "link" %></div>

</div>
```

I am trying to implement next and previous buttons that will route to the next video in the list, but I am getting a weird "wrong number of arguments error" 

![screen shot 2016-11-16 at 1 30 45 pm](https://cloud.githubusercontent.com/assets/22160743/20360306/36402e52-ac01-11e6-9174-f9c0eadc92c9.png)

this is the method in my Shows controller
```
  def next_show
    @nextshow = Show.where(["id > ?", params([:id])]).order(:id).first
  end

  def previous_show
    @previousshow = Show.where(["id < ?", params([:id])]).order(:id).last
  end
```

Is this because of the syntax of the method or link? I've tried changing to a few different versions of "id", but none of them work. Any ideas?

**Comment by andrewsunglaekim** [comment]
I don't think you want the argument of where to be an array.

**Comment by andrewsunglaekim** [comment]
please reopen if you're having issues
