### ISSUE TITLE
Simple pagination

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/project2#802]
I am trying to some simple pagination without using a paginate gem. My calendar week isn't a model, so I can't set the pages to 7 days per page, which is what the gem wants. I figured it would be easy enough to just render weeks but maybe I'm barking up the wrong tree. From my shows controller: 

```ruby
class ShowsController < ApplicationController
 before_action :set_week, except: [:new, :create]

  def index
    @shows = Show.all
    @performances = Performance.all
    end

def set_week
  @today = Date.today 
  @days_from_this_week = (@today.at_beginning_of_week..@today.at_end_of_week).map
  @days_from_last_week = ((@today.at_beginning_of_week - 7.days)..(@today.at_end_of_week - 7.days)).map
end

def week_behind
  @days_from_this_week = @days_from_last_week
  render :index
end
```

and then on my application.html nav bar I'm trying to call `week_behind` but it's giving me "undefined local method". I feel like there should be a way to do this, just not like this

```ruby
        <li><%= link_to "Last Week", week_behind %></li>
```

here's how I'm generating the calendar on the index page: 

```ruby
<% @days_from_this_week.each do |day| %>

<div class="day">

      <%= day.strftime('%A, %m/%d') %><br>

<% @shows.each do |show| %>
<%#= show.date.strftime("%Y-%m-%d") %>
<% if day.strftime("%Y-%m-%d") == show.starts_at_date.strftime("%Y-%m-%d") %>
<span class="show"> #etc
```

**Comment by andrewsunglaekim** [comment]
I don't think you can call the `.map` method with any arguments

**Comment by andrewsunglaekim** [comment]
in your `set_week` method

**Comment by drewswinburne** [comment]
Oh that part works actually, I can get the current week no problem. I guess what I'm having trouble doing is changing the current week instance variable with a path

**Comment by andrewsunglaekim** [comment]
you can use parameters in the same way we use it with ids, but for your pagination?

**Comment by andrewsunglaekim** [comment]
and instead of `week_behind` as your argument for `link_to` use a custom path you create in `routes.rb`

**Comment by drewswinburne** [comment]
This makes a lot of sense and I think I'm close to understanding it but I might not get it in by noon. Will push functioning app now.
