### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/project2#803]
I'm trying to redirect back to a mentor page -- on that mentor page are associated mentorships. When I create a mentorship relationship I want to redirect back to the mentor page that the user was previously on.

I have the following code:
```ruby  
def create
    redirect_to root_path unless @current_user
    @mentor = Mentor.find(params[:mentor_id])
    @mentorship = @mentor.mentorships.create!(mentorship_params)
    redirect_to mentor_mentorship_path(@mentor_id), notice: "Mentorship was created."
end
```

The URL path is the following: 
`/mentors/:mentor_id/mentorships(.:format)`

I'm unsure of how to pass the mentor id into the redirect.

**Comment by andrewsunglaekim** [comment]
why not

``` ruby
redirect_to mentor_mentorship_path(@mentor.id), notice: "Mentorship was created."
```

**Comment by andrewsunglaekim** [comment]
although i think it might be `mentor_mentorships_path`

**Comment by avalant** [comment]
Ah! I tried that too and thought it wasn't a solution/working properly because the page isn't actively redirecting back to the mentor page.

**Comment by andrewsunglaekim** [comment]
are you getting an error?

**Comment by avalant** [comment]
No error, the URL is reflecting the correct information. But, showing the full listing of all mentorships within database as a mentorship#index.

**Comment by avalant** [comment]
I went ahead and changed it to:

`redirect_to mentor_path(@mentor.id)`

Just thought it should work the other way?
