### ISSUE TITLE
Trying to get back to an old commit

### ISSUE THREAD

**Issue by ejsorrento** [ga-wdi-exercises/project2#805]
Attempting to get back to a previous commit, trying to be careful.

Here's the commands I've run:

git reset --hard <commit> *which seemed to merge all this with the previous
*and move to <commit>

git reset <commit> 
*which did nothing

Not sure where to go

followed this link
http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit

**Comment by jshawl** [comment]
what is the output of git status?

**Comment by ejsorrento** [comment]
<img width="479" alt="screen shot 2016-11-16 at 6 52 28 pm" src="https://cloud.githubusercontent.com/assets/22303391/20370663/e100b7d6-ac2d-11e6-9d12-9b941c084178.png">

at one time I did something like git clean -dtx, but I feel the context is different here

**Comment by ejsorrento** [comment]
I'm thinking "git add ." at this point

**Comment by jshawl** [comment]
yeah!

**Comment by jshawl** [comment]
go ahead and make a commit and push to github - then we'll revert

**Comment by ejsorrento** [comment]
ok so here's where I'm at:

git add .
git commit -m "devise mistake"
git push origin master

**Comment by jshawl** [comment]
excellent!

what's the output of `git log --all --oneline --graph`

**Comment by ejsorrento** [comment]
<img width="472" alt="screen shot 2016-11-16 at 7 04 24 pm" src="https://cloud.githubusercontent.com/assets/22303391/20370955/84fef5b8-ac2f-11e6-85f3-22d860acc105.png">

**Comment by jshawl** [comment]
sorry i meant `git log --all --oneline --graph --decorate`

**Comment by ejsorrento** [comment]
<img width="536" alt="screen shot 2016-11-16 at 7 05 49 pm" src="https://cloud.githubusercontent.com/assets/22303391/20370993/bc971082-ac2f-11e6-9652-f6a4649d7f3d.png">

**Comment by jshawl** [comment]
ok excellent so that's down at the bottom - can you identify the commit that you want to go to?

**Comment by ejsorrento** [comment]
<img width="521" alt="screen shot 2016-11-16 at 7 08 10 pm" src="https://cloud.githubusercontent.com/assets/22303391/20371033/0aa919d2-ac30-11e6-92fb-da564b51aefb.png">

I sent you the wrong screen shot

**Comment by ejsorrento** [comment]
I want to go to "MVP, moving to sessions"

**Comment by jshawl** [comment]
`git reset --hard 0c5405f`

**Comment by ejsorrento** [comment]
awesome, thanks man. 

so just to reiterate to go back to a previous commit:

-git add .
-git commit -m "blah"
-git push origin master
-git reset --hard "somecommit"

**Comment by jshawl** [comment]
technically you only need the last command. 

the first two commands (git add and git commit) were because your working directory wasn't clean.

The git push was a "just incase we mess _everything_ up"

**Comment by jshawl** [comment]
note: you'll need to force push to gthub once you're happy with what you've done:

```
git push -f
```

**Comment by ejsorrento** [comment]
awesome, took some screen shots of this. 

Thanks for the help, Jesse
