### ISSUE TITLE
Sessions/user issue 

### ISSUE THREAD

**Issue by herrerake** [ga-wdi-exercises/project2#806]
I coded my sessions and user log in/out feature to my code. Things were operating smoothly except that I the main page was not displaying "welcome current user" where it was supposed to be. 

The last thing that happened before I could no longer view any pages was log in as a user. I hit a sign in button and taken to a new user page, then when I attempted to navigate away from that page the follow error showed:

``
ActiveRecord::RecordNotFound in EventsController#index
``

``
Couldn't find User with 'id'=
``

```rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_new_user
  before_action :set_current_user # Here we're saying "run the method set_current_user before every controller action"

  def create_new_user
    @user = User.new
  end


  def set_current_user
    if User.exists?(session[:user_id]) #if there is a user_id currently stored in the session hash...
      @current_user = User.find(session[:id]) #... find and save that in @current_user
    else
      @current_user = nil # ...overwise, set @current_user to nil
    end
  end
end
```

Around line 12 the error says.

(Please mention the areas I can improve my issue"

**Comment by jshawl** [comment]
ah ok try opening up this window incognito - cmd-shift-n in chrome - do you still get the same error?

**Comment by herrerake** [comment]
OH WOW, no I do not

**Comment by jshawl** [comment]
radical - i think you need to log out when not incognito

**Comment by herrerake** [comment]
but, I can never get to the log out link once im logged in. the main page still doesn't display the "welcome user display", or "log out"

here is my code where that is supposed to make that happen.

``` rb
    <nav class= "navi">
      <% if @current_user %>
      <%= link_to "Welcome #{@current_user.username}!", user_path(@current_user) %>
      <%= link_to "Sign Out", session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign Up", new_user_path %> |
      <%= link_to "Sign In", new_session_path %>
      <% end %>
```

**Comment by jshawl** [comment]
ahhhhh so `@current_user` is always nil - where are you setting the value of `@current_user`?

**Comment by herrerake** [comment]
in my application_controller

``` rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_new_user
  before_action :set_current_user # Here we're saying "run the method set_current_user before every controller action"

  def create_new_user
    @user = User.new
  end

  def set_current_user
    if User.exists?(session[:user_id]) #if there is a user_id currently stored in the session hash...
      @current_user = User.find(session[:id]) #... find and save that in @current_user
    else
      @current_user = nil # ...overwise, set @current_user to nil
    end
  end
end
```

**Comment by jshawl** [comment]
is it `session[:id]` or `session[:user_id]` ?

**Comment by jshawl** [comment]
you use both in the above code

**Comment by herrerake** [comment]
OOOH okay. I need to change that `session[:id]` to `session[:user_id]`

This issues thing is kinda cool...

**Comment by jshawl** [comment]
you know it!
