### ISSUE TITLE
sessions/user problem

### ISSUE THREAD

**Issue by herrerake** [ga-wdi-exercises/project2#807]
I am signed in as a user and I am attempting to leave a comment. Now, only users can leave a comment, however, even though I am signed in as a user I am getting an error.

Validation failed: User must exist
Around line 16
  ``` @comment = @event.comments.create!(comment_params)```

```rb
 def create
class CommentsController < ApplicationController
  def index
  end

  def show

  end

  def new
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new
  end

  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create!(comment_params)
    redirect_to event_path(@event)
  end

  def edit
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end
  end
```

**Comment by andrewsunglaekim** [comment]
This is failing because a comment can't be created without a user being associated with it. You'll have to do something like this:

``` ruby
@comment = @event.comments.new(comment_params)
@comment.user_id = current_user.id
@comment.save
```

**Comment by herrerake** [comment]
okay lemme think about this further...

**Comment by superbuggy** [comment]
In your `new` method, you might have to add an instance variable for the logged in user's user_id, so that you can use it in `new.html.erb`

**Comment by herrerake** [comment]
I am getting a new error that my comment is an undefined method. I've tried multiple things, now I am stuck. 

``` rb
  def create
    @event = Event.find(params[:event_id])
    @comment = @current_user.events.comment.create!(comment_params)
    redirect_to event_path(@event)
  end
```

line three in this excerpt is the problem.
please help

**Comment by jshawl** [comment]
shouldn't it be `@current_user.events.comments` not the singular

**Comment by herrerake** [comment]
that's what I initially thought and tried, however, I get the same problem.
Except that instead of 'comment' the error will say 'comments'.

**Comment by jshawl** [comment]
let's see it do you mind taking a screenshot

**Comment by herrerake** [comment]
sure thing!

![screen shot 2016-11-17 at 10 23 22 am](https://cloud.githubusercontent.com/assets/22248931/20395136/e68661ce-acaf-11e6-9168-d38c1eaea027.png)

**Comment by jshawl** [comment]
a screenshot of the error

**Comment by herrerake** [comment]
Lol...

![screen shot 2016-11-17 at 10 24 27 am](https://cloud.githubusercontent.com/assets/22248931/20395178/08ff8afa-acb0-11e6-95fa-019e21727661.png)

**Comment by jshawl** [comment]
oh i see. You can only create comments on one event. You're getting this error because you're trying to create comments on all the users' events. use `@event` instead of `@current_user.events`

**Comment by herrerake** [comment]
![screen shot 2016-11-17 at 10 27 10 am](https://cloud.githubusercontent.com/assets/22248931/20395306/6d00fce6-acb0-11e6-9404-4471cb23302b.png)

**Comment by jshawl** [comment]
use `@event` instead of `@events`

**Comment by herrerake** [comment]
sorry, yeah, I made that fix immediately afterwards. Now my error says i need a valid user

**Comment by jshawl** [comment]
can i see screenshot of error message

**Comment by herrerake** [comment]
![screen shot 2016-11-17 at 10 32 08 am](https://cloud.githubusercontent.com/assets/22248931/20395498/28225556-acb1-11e6-8302-99db5ff21b90.png)

**Comment by jshawl** [comment]
try adding the current user to the params hash:

```
@event.comments.create(comment_params.merge(user: @current_user))
```

**Comment by herrerake** [comment]
Success, thanks man. Your patience is of high admiration.
