### ISSUE TITLE
Redirect not working 

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project2#808]
For all my CRUD functions I have 
`redirect_to root_path unless @current_user`
which works in every instance but one and I have no idea why

```ruby
class MembershipsController < ApplicationController

  def index
    @memberships = @current_user.memberships.all
  end

  def new
    puts "****************************"
    puts @current_user.inspect
    redirect_to root_path unless @current_user
    @group = Group.find(params[:group_id])
    if Membership.exists?(user_id: @current_user.id, group_id: @group.id)
      flash[:alert] = "You are already in this group!"
    else
      @membership = Membership.create(user_id: @current_user.id, group_id: @group.id)
      flash[:notice] = "You have joined this group"
    end
    redirect_to @group
  end

  private
  def membership_params
    params.require(:membership).permit(:user_id, :group_id)
  end

end
```

When I puts @current_user it equals nil. It skips over the redirect and errors out at 
` if Membership.exists?(user_id: @current_user.id, group_id: @group.id)`

**Comment by andrewsunglaekim** [comment]
hmmm. i would drop a `binding.pry` in the new to mess with the variables when the action executes. Are you building a user in a form anywhere in the view for that action?

**Comment by bradleycravens** [comment]
No the memberships#new view is empty since its just a join model between a user and a group.

**Comment by bcravens** [comment]
Okay so now the entire site isn't working and errors out because my if statements for @current_user aren't working

**Comment by andrewsunglaekim** [comment]
then why is it an accessible path?

**Comment by andrewsunglaekim** [comment]
if it's empty it's not being used right?
