### ISSUE TITLE
Unable to iterate over DOM Array using Javascript

### ISSUE THREAD

**Issue by jdreiser1** [ga-wdi-exercises/project2#809]
I am trying to iterate through an array of html elements in order to add an event listener, which in turn adjusts the display styling for each element, like so.

```
var arr = document.getElementsByClassName('program')
arr.forEach(function(x){
  x.addEventListener('click', function(){
  document.getElementsByClassName('hotkey-details').style.display = 'block';
})})
```

however I am getting an error stating  `arr.forEach is not a function(…)` . I am not sure why for Each is not working on the array.  It appears forEach does not work on an HTMLCollection, which is what the array is.

**Comment by andrewsunglaekim** [comment]
whats printed when you do:

``` js
console.log(arr)
```

**Comment by jshawl** [comment]
try a for loop:

```
for(var i = 0; i < arr.length; i++){
  var element = arr[i]
}
```

**Comment by jdreiser1** [comment]
Okay. So I added for loops to both of my HTML collections, which fixed the errors, but now I am freezing the application every time I run it.

```
var arr = document.getElementsByClassName('program')
for(var i = 0; i < arr.length; i++){
  arr[i].addEventListener('click', function(){
  var arr2 = document.getElementsByClassName('hotkey-details')
  for (var j = 0; j < arr2.length; i++){
    arr2[j].style.display = 'block';
  }
})}
```

**Comment by jshawl** [comment]
it's because your incrementing i in the second loop and not j

**Comment by jdreiser1** [comment]
Now I am getting the error message: `Uncaught Error: jquery-ujs has already been loaded!`

**Comment by jshawl** [comment]
let me see the top 25 lines of `app/assets/javascripts/application.js`

**Comment by jdreiser1** [comment]
```
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file. JavaScript code in this file should be added after the last require_* statement.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```

**Comment by jshawl** [comment]
what if you remove `//= require jquery_ujs` still same error?

**Comment by jdreiser1** [comment]
No longer receiving an error. However the feature is not working.

**Comment by jshawl** [comment]
ok perfect! a new issue! can you phrase it in the form of I do _____ i expect ____ to happen _____ happened instead?

**Comment by jdreiser1** [comment]
When I click on any of the HTML elements with the classname 'program', I expect the html elements with the classname 'html-details''s display styling to change from hidden to block, therefore appearing. However no such change in occurs.

```
var arr = document.getElementsByClassName('program')
for(var i = 0; i < arr.length; i++){
  arr[i].addEventListener('click', function(){
  var arr2 = document.getElementsByClassName('hotkey-details')
  for (var j = 0; j < arr2.length; j++){
    arr2[j].style.display = 'block';
  }
})}
```

**Comment by jshawl** [comment]
can you `console.log("a click happened")` when you click on `.program` elements?

**Comment by jdreiser1** [comment]
It successfully logs "a click happened" to the console

**Comment by jshawl** [comment]
console.log( i, "a click happened") when you click on .program elements? do the numbers change depending on what you click on?

**Comment by jshawl** [comment]
also maybe jquery is the answer here? `$(".hotkey-details").show()`

**Comment by jdreiser1** [comment]
The numbers do not change depending on what I click on. It stays at three.

Also tried implementing jquery, but it is giving a syntax error for the period.  `Uncaught SyntaxError: Unexpected token .`

**Comment by superbuggy** [comment]
is there a styling rule that is overriding the display property of elements with `program` class?

**Comment by superbuggy** [comment]
try adding quotes
