### ISSUE TITLE
Routes path error

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-wdi-exercises/project2#81]
My path is going to: /user_id/ instead of the actual number in the :user_id.

**Comment by jshawl** [comment]
what code is generating that link?

**Comment by omarimayerswalker** [comment]
I have a private action:

  def find_user
    @user = User.find(params[:user_id])
  end

**Comment by andrewsunglaekim** [comment]
re : above. That action doesn't generate the link. You should check your `link_to` helper that directs you to `/user_id` instead of `/:user_id`

**Comment by jshawl** [comment]
^^ :+1:

**Comment by jshawl** [comment]
in your index action, use the `current_user` helper provided by devise.

``` rb
@user = current_user
```
