### ISSUE TITLE
Returning an array of values from an API

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project2#810]
I am using two APIs to return event information. The first returns all the event info and a location id. I take the id from the first and run it through the second one to return the names of all the venues. I can return all the venue names, but I'm having difficulty isolating the value I want from the second aPI for some reason. 

Where it says print line below, I am trying to puts the single address value, but it just returns blank. When I take out["address_1"], it puts the whole object. I've included an example of what should be returned underneath the code.

**To summarize**: I just want to return one object value, instead of the whole object

**Code**
```
venue = []
    for x in response
      venueID = response["events"][1]["venue_id"]
      venueURL = "https://www.eventbriteapi.com/v3/venues/#{venueID}/?token=XOPE6JNWCBHK7PUPYY5W"
      z = HTTParty.get(venueURL)
  >>>>>Print line:    puts z.inspect["address"]["address_1"]
      venue.push(z["address"]["localized_multi_line_address_display"])
    end
```

So here, I just want address_1

```
{
    "address": {
        "address_1": "1133 15th Street NW, 12th floor", 
        "address_2": "8th Floor Office #8", 
        "city": "Washington", 
        "region": "DC", 
        "postal_code": "2005", 
        "country": "US", 
        "latitude": "38.90486360000001", 
        "longitude": "-77.03399630000001", 
        "localized_address_display": "1133 15th Street NW, 12th floor 8th Floor Office #8, Washington, DC 2005", 
        "localized_area_display": "Washington, DC", 
        "localized_multi_line_address_display": [
            "1133 15th Street NW, 12th floor", 
            "8th Floor Office #8", 
            "Washington, DC 2005"
        ]
    }, 
    "resource_uri": "https://www.eventbriteapi.com/v3/venues/17084442/", 
    "id": "17084442", 
    "name": "DC Blockchain Center at 1776", 
    "latitude": "38.90486360000001", 
    "longitude": "-77.03399630000001"
}
```

**Comment by jshawl** [comment]
what is the ouput of `puts z.inspect`

**Comment by robertzehnder** [comment]
@jshawl The entire API response I displayed at the bottom of the first post over and over again

**Comment by robertzehnder** [comment]
So it works, but I'm just having trouble narrowing down to address_1 or any other particular value

**Comment by jshawl** [comment]
what is the output of `puts z["address"]`

**Comment by robertzehnder** [comment]
oh wait that was bombing out. `puts z` worked though for returning the whole object

**Comment by jshawl** [comment]
what do you mean by bombing out

**Comment by robertzehnder** [comment]
not working. I think I just realized that .inspect was screwing everything up

**Comment by jshawl** [comment]
what do you mean by not working? Is there an error message?

**Comment by robertzehnder** [comment]
Yea sorry, not really industry jargon. I got it to work though. Thanks!

**Comment by jshawl** [comment]
what was the fix? I am genuinely curious!

**Comment by robertzehnder** [comment]
Instead of `puts z.inspect["address"]["address_1"]`, get rid of .inspect

**Comment by jshawl** [comment]
ahhhhhh ok great!

**Comment by robertzehnder** [comment]
derp lol, just forgot to take it out from trying to see if it would return anything at all. Rushing to get this done
