### ISSUE TITLE
Nesting resources in Devise users?

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#813]
I am making a todo list app with the following ERD: User -> List -> Item. I think it makes sense to nest items inside lists and lists inside users, but I would like a second opinion on the latter. In short, does it make sense to nest resources inside of users, and will Devise make my life a living hell if I try to do so?

(By the way, Wes has the same question.)

Thanks,
Nat

**Comment by amaseda** [comment]
You can do that. Don't think Devise would complain. What's the reasoning behind wanting to do this?

I would instead recommend that you get all user information for a particular list or item programmatically (e.g., referencing `current_user` or `@list.user` in the controller code).

On a related note, once I start nesting more than two resources in the URL I start to wonder whether I really need to make it that long.

**Comment by ghost** [comment]
Sounds good to me. For that matter, why should I nest items inside of lists? I plan to do dependent: :destroy on lists, so that each item _has_ to belong to a list, but that does not require me to nest the resources, right? I suppose I am still unclear on the purpose/consequences of nesting. Does it only affect the URLs and the names of the helper methods? What do you gain by nesting? What do you lose?

**Comment by amaseda** [comment]
Nested resources do not have to reflect associations in your ERD. You only need to nest things if, for whatever reason, you want to be able to access both (in this case) an item and the list it belongs to in the URL. But there might be other ways for you to access the information you need.

I would start with a minimal approach (maybe just lists in the URL!) and from there expand if you need to.

@ngcarter

**Comment by ghost** [comment]
Great, thanks!

**Comment by amaseda** [comment]
Rad! Closing this for now but feel free to re-open if you have more questions about this.

**Comment by justwes2** [comment]
Hey it looks like it makes more sense to add this here rather than create a new issue. Since I have a few models that depend on user, but not on each other, (as in a((b)(c)), not a(b(c)), should the resources stack in the routes look like this:
```  resources :users do
    resources :assessments
    resources :memories
  end```
or
```  resources :users do
    resources :assessments
  end
  resources :users do
    resources :memories
  end``` 
What is the difference, or is there one?

**Comment by amaseda** [comment]
They'll do the same thing. Try both out!
