### ISSUE TITLE
Seeds issue

### ISSUE THREAD

**Issue by ericcgreen** [ga-wdi-exercises/project2#815]
I tried db:seed in my console.
I expected my seed to upload to happen.
I got this message:
"rails aborted!
ActiveRecord::RecordInvalid: Validation failed: User must exist"
happened instead.

Please help

**Comment by amaseda** [comment]
Sounds like you might have a model that must have a user attached to it, and you're not giving it a user in the seed file. Do you have `null: false` next to `user_id` in your schema/migrations?

**Comment by ericcgreen** [comment]
Thank you, no I do not. How would I go about adding "null: false" to user_id in the schema?

**Comment by AndyWhitley** [comment]
Hey Eric, copy and paste your seed file as a code snippet here real quick. If you are using user_id's for associations, you have to drop the database to reset the id's (indexes).

**Comment by ericcgreen** [comment]
`City.destroy_all
Rating.destroy_all


tokyo = City.create!(name: "Tokyo", country: "Japan", photo: "http://www.telegraph.co.uk/content/dam/Travel/Destinations/Asia/Japan/Tokyo/Tokyo---CB-guide---Skyline-large.jpg")

mark = User.create!(email: "me@gmail.com", encrypted_password: "abc123")

tokyo_ratings = Rating.create!(overall_rating: "#", safety_rating: "#", comment: "#", recommendations: "#", user_photo: "#", city: tokyo, user: mark)
`

**Comment by ericcgreen** [comment]
So I added user "mark" and I got a new error in the console:

"rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Password can't be blank"

**Comment by AndyWhitley** [comment]
Use a field `password` on the User seed instead of `encrypted_password` (devise will do the encryption for you and change the field's name before recording it in the database. Let me know if that fixes it.

**Comment by ericcgreen** [comment]
It worked! Thank you!
