### ISSUE TITLE
Timestamps on user interface

### ISSUE THREAD

**Issue by cabralsylvester** [ga-wdi-exercises/project2#816]
Hello.  So the overarching objective of my app is for users to have a vehicle to log of their biometrics (as part of a larger Electronic Health Records system). You can think of this log as an online bank statement for your health. Said log would appear on the user interface.  In order to accomplish my objective, will I need to create t.timestamps table in my model? I have included a copy of the image for reference.  thanks!
![metricslog](https://cloud.githubusercontent.com/assets/25065204/23366174/c4e73538-fcd3-11e6-815b-af99ed79854c.PNG)

**Comment by amaseda** [comment]
Sounds like including timestamps could be useful, especially if the date/time on the right corresponds to when an entry is created or updated.

**Comment by amaseda** [comment]
Going to close this but feel free to re-open if you have any issue interacting with the timestamps!
