### ISSUE TITLE
User dependent data forms

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project2#817]
I'm getting an error that my data table 'assessments' is undefined in the form (NoMethodError in Welcome#index). I have my form structured as a dependency on current user,  like so:
```<%= form_for([current_user, @user.assessments.build]) do |f| %>``` I have also tried structuring assessments as an independent data type:
```<%= form_for :assessment, url: welcome_index do |f| %>```
Do I need to define the data type in the welcome controller, or should I redirect to the assessment.new as the root to make this my homepage, or am I completely misunderstanding this error?

**Comment by amaseda** [comment]
Hm, would you mind pushing up your code, linking me to your repo and pointing out the files in question? Will take a look.

**Comment by justwes2** [comment]
https://github.com/justwes2/wellnyss
The relevant error is in app/views/welcome/index.html.erb. Thanks.

**Comment by amaseda** [comment]
Just met IRL but let me know if you have any questions about this one. Otherwise, close it once you've fixed!

**Comment by justwes2** [comment]
Alright, looks like adding the instance variable definition to the welcome controller did the trick. Thanks again.
