### ISSUE TITLE
edit and create not working

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/project2#818]
I am not getting any errors but my form is not populating my database and I can't edit a donation as well, I could delete one.

This is the cli log 
Started POST "/projects/4/donations" for ::1 at 2017-02-27 14:12:15 -0700
Processing by DonationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Q+2Ao6ElkK06g9SR0xTrvJ9qJlFIOACTqKwsKPYJvShAr2ZqaErbPJvCqlPqMPuYPrGYCWOcsPGLhCXETZs9sw==", "donation"=>{"title"=>"sdfg", "description"=>"wdh", "donation_amt"=>"1234567890"}, "commit"=>"Create Donation", "project_id"=>"4"}

**Comment by amaseda** [comment]
Hm, can you show me the corresponding controller code?

**Comment by HabRonan** [comment]
```
#create
       def create
           @project = Project.find(params[:project_id])
           @donation = @project.donations.create(donation_params)

           redirect_to "/projects/#{@project.id}"
        end
# update

         def update
             @project = Project.find(params[:project_id])
             @donation = Donation.find(params[:id])
             @donation.update(donation_params)

            redirect_to "/projects/#{@project.id}"
         end

 #delete

          def destroy
              @project = Project.find(params[:project_id])
              @donation = Donation.find(params[:id])

              if   @project.user == current_user
                        @donation.destroy
             else
                   flash[:alert] = "Only the person who added the donation can delete it"
             end

              redirect_to project_path(@project)

          end
```
Delete works though

**Comment by amaseda** [comment]
Can you also show your `donation_params`?

**Comment by HabRonan** [comment]
private
         def donation_params
           params.require(:donation).permit(:title, :description, :donation_amt)
         end

**Comment by amaseda** [comment]
Interesting. Would you mind pushing up your code, sending me the repo link and indicating which files I should look at? Thx

**Comment by HabRonan** [comment]
https://github.com/HabRonan/project2/tree/devise
/app/controllers/donations_controller.rb
/app/views/donationa/new.html.erb and edit.html.erb
/app/views/layouts/application.html.erb

**Comment by amaseda** [comment]
When I use `create!` instead of `create`, after submitting a new donation I get the error `Validation failed: User must exist`. That means you somehow have to indicate that the donation that is being created also belongs to a user.

[Look back at the devise lesson](https://github.com/ga-wdi-lessons/devise#we-do-update-the-controller-10-minutes--130) and see the two different ways we used to associate a new instance with the `current_user`. At least one of those will work.

**Comment by HabRonan** [comment]
I am about to look at that. the current user needs to only be associated to a project rather than a donation. B.c.  project has a one to many with donation. a user should be able to add and edit a donation to anywhere but can edit a project if only the user is the one who created it

**Comment by HabRonan** [comment]
I do have .merge method to the project, should I add that to the donation as well?

**Comment by amaseda** [comment]
Right now donation needs a user, whether that's the `current_user` or somebody else. Either way, you can use `.merge(user: ???)` in `create` and `update` and it will solve this issue.

**Comment by HabRonan** [comment]
That worked, but with the .merge(user: current_user) only. Thanks

**Comment by HabRonan** [comment]
.merge(user: ???) didn't work for me.

**Comment by amaseda** [comment]
Yes, ??? just needs to be replaced with an actual instance of a user. `current_user` does the trick. I just used ??? in case you wanted to put a user other than `current_user` in there.

**Comment by amaseda** [comment]
@HabRonan Are you good to more forward with `.merge(user: current_user)`. If so, feel free to close this issue / re-open if you have any problems with it down the line. Thx!
