### ISSUE TITLE
"Edit" route issue

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project2#819]
Hello, 

I am trying to enable edit functionality for my child-model and I am getting the following error message: 

NoMethodError in Exercises#edit
Showing /Users/natashaclark/wdi/project/project2/fit2/app/views/exercises/edit.html.erb where line #3 raised:

undefined method `exercise_path' for #<#<Class:0x007fe625be11b8>:0x007fe624a98550>
Extracted source (around line #3):
             
<h2>Edit Exercise</h2>

**<%= form_for [@program, @exercise] do |f| %>**
  <%= f.label :name %>
  <%= f.text_field :name %>

-------------------------------------

I thought I had my edit method set up correctly: 

def edit
      @exercise = Exercise.find(params[:id])
  end

**Comment by nayana487** [comment]
What do you mean by child model? Do you have resources for exercise nested in resources for programs?

**Comment by nrc0004** [comment]
yes, sorry, its my dependent model I guess? 

And yes, I do have them nested.

**Comment by nayana487** [comment]
Can you show me what your routes look like?

**Comment by nrc0004** [comment]
refix Verb   URI Pattern                                        Controller#Action
                 root GET    /                                                  program#index
    program_exercises GET    /programs/:program_id/exercises(.:format)          exercises#index
                      POST   /programs/:program_id/exercises(.:format)          exercises#create
 new_program_exercise GET    /programs/:program_id/exercises/new(.:format)      exercises#new
edit_program_exercise GET    /programs/:program_id/exercises/:id/edit(.:format) exercises#edit
     program_exercise GET    /programs/:program_id/exercises/:id(.:format)      exercises#show
                      PATCH  /programs/:program_id/exercises/:id(.:format)      exercises#update
                      PUT    /programs/:program_id/exercises/:id(.:format)      exercises#update
                      DELETE /programs/:program_id/exercises/:id(.:format)      exercises#destroy
             programs GET    /programs(.:format)                                programs#index
                      POST   /programs(.:format)                                programs#create
          new_program GET    /programs/new(.:format)                            programs#new
         edit_program GET    /programs/:id/edit(.:format)                       programs#edit
              program GET    /programs/:id(.:format)                            programs#show
                      PATCH  /programs/:id(.:format)                            programs#update
                      PUT    /programs/:id(.:format)                            programs#update
                      DELETE /programs/:id(.:format)                            programs#destroy

**Comment by nayana487** [comment]
think you need something like

```rb
  def edit
    @program = Program.find(params[:program_id])
    @exercise = Exercise.find(params[:id])
  end
```

**Comment by nrc0004** [comment]
That did the trick!! Thank you!

**Comment by nayana487** [comment]
👍
