### ISSUE TITLE
unable to drop db after adding devise

### ISSUE THREAD

**Issue by kristingreenslit** [ga-wdi-exercises/project2#82]
I just added devise to my project, and now I'm trying to drop the db and and recreate it in order to generate a new migration (I had a resource commented out in routes.rb until I finished the user auth portion of the project). The error message after running rake:db drop in terminal is "Couldn't drop tech-assess_development" although I've signed out of the session and cleared the cookies. I've googled the error message but articles are suggesting I reroute the default registration path which doesn't seem like a logical solution to resolve the error.

**Comment by RobertAKARobin** [comment]
Can you paste more of the error message? Do you have PSQL running somewhere?

**Comment by jshawl** [comment]
Try stopping rails server, rails console, and or psql. then `rake db:drop:all`

**Comment by kristingreenslit** [comment]
<img width="478" alt="screen shot 2015-08-04 at 11 54 32 am" src="https://cloud.githubusercontent.com/assets/5890436/9065686/3dbe7e4a-3aa1-11e5-9f26-429239fc22df.png">

**Comment by kristingreenslit** [comment]
Robin: I think that worked but I still would like to talk through devise a bit more. Andy I chatted about it briefly but that was before I took a closer look at the file structure after implementing devise.

**Comment by jshawl** [comment]
@kristingreenslit Tomorrow we will have a mini-lesson on devise! I recommend waiting unitl then before going further with devise, but feel free to reopen this issue or comment more if you have more questions!

**Comment by kristingreenslit** [comment]
Jesse: I think I'm at a stopping point with my project until I can figure this out.
