### ISSUE TITLE
CSS doesn't recognize one of the tags inside of another

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project2#820]
my post tag wraps around the entire contents of the .each loop but flexbox doesn't recognize time tag. Other submissions end up piling on top of the timestamps.

<img width="1439" alt="screen shot 2017-02-27 at 3 13 01 pm" src="https://cloud.githubusercontent.com/assets/21371639/23377920/a397d316-fcff-11e6-853d-1df8d77dc78c.png">

index.html.erb
```
<main>
  <submission>
    <% @submissions.each do |submission| %>
      <post>
        <h2><%= link_to submission.title, submission_path(submission) %></h2>
        <img class="all-img" src="<%= submission.url %>">
        <time>Updated by <%= submission.user.email %> at <%= submission.updated_at %></time>
      </post>
    <% end %>
  </submission>
</main>

```
css
```
post {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 400px;
  height: 400px;
}
```

**Comment by nayana487** [comment]
That's how flexbox works. It only impacts the immediate children of a parent container.

**Comment by fanelenan7** [comment]
Yes... but those are all (h2, img and time) immediate children of the post? Why doesn't post even include time tag into itself?

**Comment by nayana487** [comment]
Yea, I just noticed that, sry, for some reason I thought it was was nested. I'll look into that now.

**Comment by nayana487** [comment]
I think it has to do with setting too small a height for your post container. Some good suggestions here on how to work around this: http://stackoverflow.com/questions/34884988/child-elements-outside-parent-div

**Comment by fanelenan7** [comment]
Oh... that did it. I was trying to get them align in the same-size boxes, and it was just 50px too small. Thanks!

**Comment by nayana487** [comment]
sweet!
