### ISSUE TITLE
Fewer pages okay?

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#822]
Right now I have a todo list app with lists and todos. Each has full CRUD. I am thinking of refactoring so the lists are in a nav bar on the left and the currently selected list has its todos displayed on the right. But this would make lists#index obsolete. So my question is: Is it okay to incrementally move toward a single-page app, even if this means using fewer views and controller actions? Or does that somehow violate the letter or the spirit of this assignment?

Thanks,
Nat

**Comment by AndyWhitley** [comment]
Nope, that is completely fine to consolidate functionality into fewer routes / controller actions. So long as you still have (functionally) full CRUD for *at least* one model, you are good to go.

**Comment by ghost** [comment]
Great, thanks!

**Comment by AndyWhitley** [comment]
You may have to look into some custom routes in `config/routes.rb` to accomplish this (as opposed to using the standardized routes that `resources` provides).
