### ISSUE TITLE
.each issue

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-wdi-exercises/project2#823]
I am getting a 'undefined method `each` for nil:NilClass error in my views/assets/index.html.erb file for one of my models. My code snippet is below. I am trying to have the editor iterate through all the assets of a user hence the .each do method. Any idea or advice on where to look? 

<h2>Assets <%= link_to "(+)", new_asset_path %></h2>
<ul> 
<% @asset.each do |asset| %>
<li>
<% link_to asset.category, assets_path(asset) %>
</li>

Thanks for all your help! 
-Mitchell

**Comment by nayana487** [comment]
Can you show me the index controller action in your assets controller?

**Comment by superbuggy** [comment]
is your `index` method instance variable `@assets`?

**Comment by mitchellcarroll** [comment]
my index controller action in my assets controller is 

def index
@assets = Asset.all
end

so James, yes.

**Comment by nayana487** [comment]
you have `@asset` here not `@assets`

`<% @asset.each do |asset| %>`

**Comment by mitchellcarroll** [comment]
that worked. thank you!
