### ISSUE TITLE
ActiveRecord::InvalidForeignKey in ProgramsController#destroy

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project2#824]
I just set up devise and have been trying to implement authentication stuffs. When I tried to require a user be logged in to delete one of my models (programs) I got the following message: 

PG::ForeignKeyViolation: ERROR: update or delete on table "programs" violates foreign key constraint "fk_rails_6ac79f2c13" on table "exercises" DETAIL: Key (id)=(5) is still referenced from table "exercises". : DELETE FROM "programs" WHERE "programs"."id" = $1

Extracted source (around line #35):
              
    @program = Program.find(params[:id])
    if @program.user == current_user
      **@program.destroy**
    else
      flash[:alert] = "Only the author of the post can delete"
    end

----------------------------------------

The destroy function worked before using devise, so I'm not sure what the validation issue is

**Comment by superbuggy** [comment]
What is the relationship between User and Program?

**Comment by nrc0004** [comment]
Users will have many programs

**Comment by superbuggy** [comment]
this is `delete` in `ProgramsController`?

**Comment by nrc0004** [comment]
yes

**Comment by superbuggy** [comment]
do you have `null: false` on `program_id` in for `exercises`?

**Comment by nrc0004** [comment]
In which file? Exercise migration?

**Comment by superbuggy** [comment]
yeah

**Comment by superbuggy** [comment]
something like `t.references :program, null: false`

remove `null: false` if you don't truly need it.

**Comment by nrc0004** [comment]
No. The only file that has that is in the users file devise generated.

**Comment by superbuggy** [comment]
can you add, commit, and push your code, then link your repo?

**Comment by nayana487** [comment]
Closing for now, please feel free to re-open if you're still having issues
