### ISSUE TITLE
Combining two data columns/types into one

### ISSUE THREAD

**Issue by atflick** [ga-wdi-exercises/project2#825]
I haven't been able to find a good answer or if this is even possible.  But right now I am using this calendar gem that uses a 'datetime' data type to display the events on the calendar, labeled 'start_time' in the snippet of my model below.  For controlling incoming data types and better UX I have split out the time and date columns.  Basically I am trying to figure out if it's possible to populate the 'start_time' field with a combination of the two.  I have a method for this but just not quite sure how to correctly implement it or if it's even possible?

```
create_table "reservations", force: :cascade do |t|
    t.date     "res_date"
    t.time     "res_time"
    t.datetime "start_time"
end
```

Thanks!
-Andy

**Comment by superbuggy** [comment]
Yeah, `start_time` will just be 'expecting' a `DateTime` object. You can create a [`DateTime` object](http://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/DateTime.html) passing whatever parameters you need. This is kind of an adapter-based solution.

**Comment by superbuggy** [comment]
You might be able to pass a [`Date` object](https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html) and a [`Time` object](https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Time.html) as arguments to `DateTime.new`, also.

**Comment by atflick** [comment]
Andy helped me, I created a method in my model that combines the date and time and puts it in the column I need and just needed to update my controller as follows

```
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.combine_datetime
    @reservation.save
    redirect_to reservations_path
  end
```
