### ISSUE TITLE
No Error, Can't get default value to show in Form Field

### ISSUE THREAD

**Issue by Justin-Shin** [ga-wdi-exercises/project2#826]
Hello, I'm attempting to get some help here on an issue regarding a default value field under my "edit" erb.  The way I have it set up is a `Recipe` table and a `Food` table that are joined by an `Ingredient` table in a m2m relationship.

This form here is within my `edit.html.erb` file for `Recipes`.  As it stands, it lets me edit everything I want it to do, which are the fields in the `Recipes` table as well as the fields within `Ingredients`.

The logic is that with submit, I'm also submitting another hash/set of parameters called food_amount as well as one called food_unit.  I use these to update, within my controller, the fields in ingredient.  I also use this method at the end of the form to potentially add any new ingredients to the join table.  I did it this way to allow the creation of associations with foods within the initial recipe creation form (instead of adding piecemeal later).

All of this functionality works, but I want there to be a default value in the text boxes for the ingredients, so if there are no changes there, they do not have to keep filling them in.  It makes it difficult because if they leave it blank, it will automatically overwrite the previous values (I can avoid this with an if, but I'd rather there be a default value).

here is my form code:

```rb
<%= form_for @recipe do |f| %>
<br>
<% @recipe.ingredients.each do |ingredient|%>
<p><%=text_field "food_amount[#{ingredient.food.name}]", value: 1 %>
  <%=text_field "food_unit[#{ingredient.food.name}]", value: 1 %><%= ingredient.food.name %></p>
<%end%>
<br>
<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :instructions %>
<br>
<%= f.text_field :instructions %>
<br>
<br>
<%= f.label :servings %>
<br>
<%= f.text_field :servings %>
<br>
<br>

<% Food.all.each do |g| %>
  <% if !@recipe.foods.include? g%>
    <%= label_tag g.name  %>
    <%= check_box_tag "foods[#{g.name}]", g.name  %>
    <br>
  <% end %>
<% end %>
```

here is the code in my controller for "update"

```rb
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.ingredients.each do |ingredient|
      ingredient.update(amount: params[:food_amount][ingredient.food.name.to_sym].first.last,unit_of_measure:params[:food_unit][ingredient.food.name.to_sym].first.last)
    end

    Recipe.update(recipe_params)
    if params[:foods]
      params[:foods].each do |food|
        @recipe.foods << Food.find_by_name(food)
      end
    end

    redirect_to recipe_path @recipe
  end
```

**Comment by superbuggy** [comment]
Hrm, what about making a drop menu with 
```rb
   <%= f.select :ingredient, options_for_select(@ingredient_names) %>
```

`@ingredient_names` would be defined in the controller method as: 
```rb
def edit
  @ingredient_names = @recipe.ingredients.map{ |ingredient| ingredient.name }
end
```
I'd also use `number_field` for numerical values instead of `text_field`.

**Comment by superbuggy** [comment]
actually wait, maybe the drop down doesnt make sense for what you're trying to do, sorry

**Comment by amaseda** [comment]
You would use `value:` to assign default values, like so: http://stackoverflow.com/a/18608271. Although it seems you have already used it in your code (e.g., `value: 1`). 

Does it not work if you do something like `value: ingredient.name`?

**Comment by Justin-Shin** [comment]
Ah, originally I had used `value: ingredient.name` as well as `value: ingredient.unit_of_measure`, and they ended up blank.  I did a `puts` for those right before that part of the code, and it gave me the correct information.  Very strange.

I'm wondering if it has anything to do with the fact that those specific fields are not part of the recipe model/paradigm, whatever, and as a result it's doing funky things.  I'll try it with number field though.  It won't fix it for the unit of measure, however.

**Comment by Justin-Shin** [comment]
I think I have something that might help troubleshoot:

Looking at the DOM, I copied what is written for those fields:

```html
<input type="text" name="food_unit[Baking Soda][{:value=>1}]" id="food_unit_Baking_Soda_{:value=>1}">
```

looks like it might be placing the value in the wrong place, which is strange to me.  Not sure why it would do that.

**Comment by superbuggy** [comment]
Are you using `food_unit` as a namespace under params (`params[:food_unit]`)?

Is the quantity a property on your join model? Would that simplify the problem?

**Comment by Justin-Shin** [comment]
I use the property in the join model to try to set the value, but I use `food_unit` as a namespace under `params[:food_unit]` because the form isn't for the join model but for the recipe.

**Comment by amaseda** [comment]
Can you push up your code, link to your repo and indicate which files we should be looking at? Thx

**Comment by nayana487** [comment]
Think you got this so I'm gonna close, but feel free to re-open if there's more to add.

**Comment by Justin-Shin** [comment]
Hi, sorry I wasn't monitoring this, was working on different parts of my code (pushed up now).

Anyway, I was helping Kevin out with his drop-down/select field in one of his forms, and it just clicked how the parameters work.  I think I know how to solve my problem.  I will reopen if I am unsuccessful!
