### ISSUE TITLE
Helper Methods?

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#827]
I wrote a helper method in application_helper.rb > ApplicationHelper. How to I invoke it in a view? In a controller? Google failed me epically on this one.

**Comment by nayana487** [comment]
Did you see this? http://stackoverflow.com/questions/1266623/how-do-i-call-a-method-in-application-helper-from-a-view

**Comment by superbuggy** [comment]
What kind of helper method(s) did you write?
