### ISSUE TITLE
Create Form is assigning the wrong foreign key from a drop down selection

### ISSUE THREAD

**Issue by cjwightman** [ga-wdi-exercises/project2#828]
I have plants that belong to seasons. When creating a new plant, the user gets to select the season from a drop down menu that the plant will be assigned to. Unfortunately, the form appears to be assigning an apparently random season_id / season. Example. User selects Spring. Upon creation the new plant is assigned to Winter.

Code for new Plant form:
<h2>New Plant</h2>

<%= form_for @plant do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :height%>
  <%= f.text_field :height %>

  <%= f.label :width %>
  <%= f.text_field :width %>

  <%#= f.select(:season_id, options_for_select(@season_name)) %>

  <%= collection_select(
    :plant,
    :season,

    Season.all,
    :id,
    :name,
    )%>

  <%= f.label :hardiness %>
  <%= f.text_field :hardiness %>

  <%= f.label :depth %>
  <%= f.text_field :depth %>

  <%= f.label :separation %>
  <%= f.text_field :separation %>

  <%= f.label :watering %>
  <%= f.text_field :watering %>

  <%= f.label :fertilizing %>
  <%= f.text_field :fertilizing %>

  <%= f.label :maturity %>
  <%= f.text_field :maturity %>

  <%= f.label :production %>
  <%= f.text_field :production %>

  <%= f.label :harvest %>
  <%= f.text_field :harvest %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit "Add to Catalogue" %>
<% end %>

Code for Plants Controller:
  def new
    @plant = Plant.new
    @season_name = Season.all.map { |season| season.name }
  end

  def create
    # @season = Season.find(params[:season_id])
    @plant = Plant.new(plant_params)
    @plant.season = Season.all.sample
    @plant.save
    redirect_to plants_path
  end

I created five new plants assigned to seasons that should have been 1 - 5. Rails did this:

CACHE (0.0ms)  SELECT  "seasons".* FROM "seasons" WHERE "seasons"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "seasons".* FROM "seasons" WHERE "seasons"."id" = $1 LIMIT $2  [["id", 11], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "seasons".* FROM "seasons" WHERE "seasons"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Season Load (0.3ms)  SELECT  "seasons".* FROM "seasons" WHERE "seasons"."id" = $1 LIMIT $2  [["id", 10], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "seasons".* FROM "seasons" WHERE "seasons"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]

**Comment by nayana487** [comment]
Think you need to pass in the season in your form like:

`<%= form_for([@season, @plant]) do |f| %>`

**Comment by nayana487** [comment]
And this in the new method for the plant controller:

```rb
def new
    @season = Season.find(params[:season_id])
    @plant = Plant.new
end
```

**Comment by cjwightman** [comment]
Thanks Nayana. I'll try that. I need to un-screw my html / css since I broke all the things. I'll let you know how it goes.

**Comment by nayana487** [comment]
sounds good @cjwightman. I'm going to close this for now, but feel free to re-open or file a new issue if you encounter anymore hiccups.

**Comment by cjwightman** [comment]
So since I'm not adding a plant from within a season, rather adding a plant from within the plant list, there isn't a season id to pull in and I get "Couldn't find Season with 'id'=" from " @season = Season.find(params[:season_id])"
