### ISSUE TITLE
Adding new class, having troubles getting anything to show up on index page now

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project2#829]
Added Album class that has many Submissions, added album_id to the Submissions, re-seeded the database with new stuff and now my page is empty. View seems to be fine? @albums.each puts down [].
This is all that's showing up on my page (removed the navbar so I can see it)
<img width="543" alt="screen shot 2017-02-28 at 12 13 37 pm" src="https://cloud.githubusercontent.com/assets/21371639/23416093/7013ceae-fdaf-11e6-8692-27bf26168423.png">

**Comment by nayana487** [comment]
Hey Lena, the screenshot link isn't displaying. Can you add again?

**Comment by fanelenan7** [comment]
Just fixed it with Andy's help. Thanks!
