### ISSUE TITLE
Iterating through database

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/project2#83]
I want to be able to check my database to see if multiple values are there. If the values are there, I want to display them in one area on my webpage.

The issue I am having is I can only do this process for one value. Right now I have a form the user can submit values they think are in the database, and if it is there it will display that value. But when they check for a new value, the older value they checked for is no longer displayed and the process repeats itself.

I have tried multiple text boxes in my form, and saving the inputs into an array but when I did that I was unable to check the values against the values in my database. I also tried getting the values from multiple text boxes individually but was only able to check the values in the database for one of the inputs. I also tried using local variables to save the inputs but everything resets once the webpage is refreshed.

What can I do to check the database for multiple values in one instance?

**Comment by RobertAKARobin** [comment]
I'm not sure I'm visualizing this properly, but would an accurate example be that you want to find a Person with the last name of Curtis and an age of 83? If so, you could do:

```
Person.where(name: "Curtis").where(age: 83)
```

**Comment by Curtismn87** [comment]
More like find multiple people.  Say you had a database:
Name   Age
Curtis    23
Robin    24
Adam    25
Mike     26

and you know Curtis, and Robin are in the database, but not Adam and Mike. So you input Curtis and Robin and it will display "Curtis and Robin are in the database" and "Adam and Mike are also in the database"... does that make more sense?

**Comment by RobertAKARobin** [comment]
`Person.where("name  = ? or name = ?", "Curtis", "Robin")`

**Comment by RobertAKARobin** [comment]
Better yet:

```
Person.where(name: ["Curtis", "Robin"])
```
