### ISSUE TITLE
Making image links clickable

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project2#831]
I'm getting this message

undefined method `symbolize_keys' for #<Category::ActiveRecord_Relation:0x007ffb9eae5780>
Extracted source (around line #8):
 
```     
<% @categories.each do |category| %>
  <a href="/categories/<%= category.id%>">
  <%= image_tag category.img_url, @categories %>

  <% end %>
```

**Comment by nayana487** [comment]
Are you calling the `symbolize_keys` method anywhere in your code?

**Comment by nayana487** [comment]
So it looks like this error happens when you're passing some other kinda value where rails is expeting a hash. 

http://stackoverflow.com/questions/14806407/undefined-method-symbolize-keys-for-2fixnum

**Comment by Nykke** [comment]
I not, I'm not sure how to use it.

**Comment by nayana487** [comment]
can you screenshot the whole error you're getting? what's happening is that ruby/rails is expecting a hash somewhere and you're passing in some other value

**Comment by Nykke** [comment]
I got it fixed, I had my path incorrect and was referencing the class variable

**Comment by nayana487** [comment]
👍
