### ISSUE TITLE
User.email Issue

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/project2#834]
I'm getting an error where it's saying that email of user does not exist despite the fact that I check in the console and it most certainly does. 

<% @order.posts.reverse.each do |post| %>
      <p><%= post.user.email %></p>
      <p><%= post.content %></p>
<% end %>

undefined method `email' for nil:NilClass

I've been working on it for a while and I'm confused :-/

**Comment by hawkins-will** [comment]
If I take out "email", I'm able to get the User, but then it says eMail of user does not exist

**Comment by amaseda** [comment]
What's the output of `user.inspect` when you include that in your view?

**Comment by amaseda** [comment]
Oops, sorry, I see Andy is working with you on this. Disregard.
