### ISSUE TITLE
My Email Still Hates Me

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/project2#836]
Help Me!

I'm still having trouble with my code sometimes saying that the eMail attribute of my User doesn't exist. It makes me unhappy. I was working with Andy on this a moment ago.

**Comment by amaseda** [comment]
Same issue as before? Any errors? What do you mean by "sometimes" -- do the users this happens to have anything in common?

Also if you haven't already try outputting the content of `post.user` to the view so we can see what exactly is in there.

**Comment by hawkins-will** [comment]
All is good, kind of. 

I ended up doing something VERY different, but got the result I wanted, so I'm good!

Ah the joys of getting frustrated enough to just change it entirely. :P

Thanks though!

**Comment by hawkins-will** [comment]
Oh, I can close this. I'm gonna go ahead and do that.
