### ISSUE TITLE
Displaying values

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-wdi-exercises/project2#837]
Hey-

I currently have both of my models displaying on a single page. Each model has the same two keys: "category" and "value". At the moment I have the "category" being displayed under the model name. Is there a way to also display the "value" next to the "category"?

**Comment by AndyWhitley** [comment]
Could you add a code snippet of the related .html.erb file?

**Comment by mitchellcarroll** [comment]
<ul>
  <% @assets.each do |asset| %>
    <li>
      <%= link_to asset.category, asset %>
    </li>
  <% end %>
</ul>

**Comment by AndyWhitley** [comment]
Try this and let me know what you see:

<% @assets.each do |asset| %>
<%= link_to "#{asset.category} - #{asset.value}, asset_path(asset) %>
<% end %>

**Comment by mitchellcarroll** [comment]
thank you! that worked.
