### ISSUE TITLE
Invert order of instances in html

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project2#838]
I am trying to get my table of instances to load with the most recent at the top. I have tried adding .order("created_at DESC"), and I'm unsure why that isn't working.

**Comment by amaseda** [comment]
How are you using it?

You could also try it in the model, like with this post model...

```
class Post < ActiveRecord::Base
  default_scope { order('updated_at DESC') } # sorts by updated at in reverse orderr
  has_many :comments
  belongs_to :user
end
```

**Comment by superbuggy** [comment]
Make sure there are timestamps on this model in your `schema.rb`. Then try `order(created_at: :asc)`

**Comment by justwes2** [comment]
Hmm. I think tweaking the model would have worked, but there's a comparison of .last to the current date in the main hub page, so I can't change it that deep in. Superbuggy, that's what I tried first, and its not affecting anything.

**Comment by justwes2** [comment]
Okay, I put the order code in the view, instead of the controller and that did it. Thanks!
