### ISSUE TITLE
pushing project

### ISSUE THREAD

**Issue by malrese1** [ga-wdi-exercises/project2#839]
i'm not able to push my project to git hub

**Comment by AndyWhitley** [comment]
What command are you running?

**Comment by malrese1** [comment]
when i put in git push it replies everything is up to date

**Comment by AndyWhitley** [comment]
That should mean that you have already pushed any changes. What branch are you on?

**Comment by malrese1** [comment]
the master branch. i have a git file in the food journal file and fj is that the problem ?
