### ISSUE TITLE
ActiveRecord unable to recognize database id numbers

### ISSUE THREAD

**Issue by petergcutler** [ga-wdi-exercises/project2#84]
See below screenshot -- ActiveRecord is unable to identify certain ids within the database.

![screen shot 2015-08-04 at 11 42 51 am](https://cloud.githubusercontent.com/assets/11398019/9065180/272d51b8-3a9e-11e5-9f01-49fc3d158584.png)

**Comment by RobertAKARobin** [comment]
What happens if you `puts Trope.all`? Do you see it in there?

**Comment by RobertAKARobin** [comment]
Alternatively, you can `binding.pry` in that `show` action and use that instead of puts

**Comment by petergcutler** [comment]
Hey, are you around to talk through this suggestion?
