### ISSUE TITLE
issue getting new and edit to read

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project2#840]
when I click on edit recipe in my app, I get this message

```
param is missing or the value is empty: recipe
              
private
def recipe_params
  params.require(:recipe).permit(:title, :ingredients, :img_url, :directions)
end
```

when I go to add a new recipe, I get this message

```
Validation failed: Category must exist
              
  def create
    @recipe = Recipe.create!(recipe_params)
    redirect_to recipes_path
  end
```

my shows:

```
<h3><%= link_to "All Recipes", recipes_path %> </h3>
<% @categories.each do |category| %>
  <a href="/categories/<%= category.id %>"><img src="<%= category.img_url %>"></a>

  <% end %>
```

````
<h2><%= @category.name %></h2>

<!-- <a href="/recipes/new/<%# @category.id %>"><%#"add new recipe"%></a> -->
<h3><%#link_to "Add Recipe", new_recipe_path(@category.id) %></h3>

<% @category.recipes.each do |recipe| %>
<div class="recipe">
  <h2><a href="/recipes/<%= recipe.id %>"><%= recipe.title %></a></h2>
  <%= image_tag recipe.img_url %>


<%end %>
```

I tried adding in a @category line in the create and it tells it doesn't exist so I'm not sure what to do, I can't see to fix for the past eight hours

**Comment by amaseda** [comment]
For the `Validation failed: Category must exist`, you need to make sure that, when creating a recipe, you attach it to a category. So doing something like `@category.recipes.create( ... )`, which assumes that you have already defined `@category`. How did you go about attempting to define `@category`?

-----------

As for your first `param is missing or the value is empty: recipe` error, can you show me what your recipe edit form looks like?

**Comment by Nykke** [comment]
Adrian,

so I got my add work by updating my routes and fixing those paths but I'm getting the edit recipe error, here is my edit from 

```
<%= form_for [@recipe, @comment] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%=f.submit %>
<% end %>

  <%= form_for [@recipe,@comment], method: :delete do |f| %>
     <%= f.submit "Delete!", class: "delete" %>
  <% end %>
```

**Comment by amaseda** [comment]
This looks like an edit form for a comment (that belongs to a recipe). Is this what you're trying to use to create a recipe or do you have a different one?

Also what do your routes look like?

**Comment by Nykke** [comment]
I'm using it to edit and create a new form, right now it only works for comments 

here are my routes 

```rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"

  resources :categories, only: [:index, :show]

  resources :recipes do
    resources :comments, except: :index
  end

  resources :categories do
    resources :recipes
  end
end
```

**Comment by Nykke** [comment]
oh I'm sorry here's my recipe edit form

```
<h3>Edit Recipe</h3>

<%= form_for @recipe do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :ingredients %>
  <%= f.text_field :ingredients %>

  <%= f.label :directions %>
  <%= f.text_field :directions %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

<%= f.submit %>
<% end %>

<%= form_for @recipe, method: :delete do |f| %>
  <%= f.submit "Delete", class: "delete" %>
  <% end %>
```

**Comment by amaseda** [comment]
Would you mind pushing up your most recent code and sending the link to your repo? Will dive in and take a look.

**Comment by Nykke** [comment]
link: https://github.com/Nykke/Project_02_Recipe_Ting

everything is pushed up to my repo

**Comment by amaseda** [comment]
The issue is that in your recipe `edit` controller action, you had this...

```rb
def edit
    @recipe = Recipe.find(params[recipe_params])
end
```

You should be pulling the id from the URL instead...

```rb
def edit
    @recipe = Recipe.find(params[:id])
end
```

You'll make use of `recipe_params` in your `update` action.

**Comment by Nykke** [comment]
oh wow, thank-you! everything seems to work the way I want them to.

**Comment by amaseda** [comment]
:+1:
