### ISSUE TITLE
Create Not Working

### ISSUE THREAD

**Issue by laurkgol** [ga-wdi-exercises/project2#846]
```rb
def create
    @club = Club.find(params[:club_id])
    @club.meetings.create(meeting_params.merge(user: current_user))
    redirect_to club_path(@club)
  end
```

In the terminal the output of the create method is:  

```
(0.2ms)  begin transaction
(0.1ms)  commit transaction
```

so it's not creating anything but Club has_many :meetings. Any ideas?

**Comment by amaseda** [comment]
What do you mean it's not working? Is it erroring out? Is it going through the whole process but not creating anything?

Also try changing `.create` to `.create!` and see if that causes an error to show up.

**Comment by laurkgol** [comment]
when I change it to create! I get this error:

ActiveRecord::RecordInvalid in MeetingsController#create
Validation failed: Member must exist

Extracted source (around line #13):
11
12
13
14
15
16
              
  def create
    @club = Club.find(params[:club_id])
    @club.meetings.create!(meeting_params.merge(user: current_user))
    redirect_to club_path(@club)
  end

**Comment by superbuggy** [comment]
in `models/club.rb`:
add `optional: true` to your `belongs_to :member` statement

```rb
class Club < ApplicationRecord
  belongs_to :member, optional: true
end
```

**Comment by amaseda** [comment]
If it's complaining that a Member must exist when creating a Meeting, then you need to make sure that you are associated that new Meeting with an existing member in your controller code. So something like...

```rb
def create
  @member.meetings.create(meeting_params)
end

# OR
def create
  Meeting.create(meeting_params.merge(member: @member)
end
```
> The above code probably isn't exactly what you will use. Just outlining some techniques here.

If you don't want every single meeting to be associated with a member, then you can use the `optional: true` method James mentioned.

**Comment by amaseda** [comment]
Did this work?

**Comment by amaseda** [comment]
Going to close for now but please feel free to re-open if you have more questions/comments on this issue.
