### ISSUE TITLE
Modifying Devise Users Controller?

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#847]
For my todo list app, I would like new users to be initialized with an "Inbox" list. This fixes some bugs I have, but it also makes UI/UX sense. So far I did `rails g devise:controllers users`, and registrations_controller.rb looks like the one to change, but I am wondering whether this is going to be a rabbit hole. I thought I'd reach out to see if I'm on the right track / if anyone has any tips for making this relatively painless.

Thanks,
Nat

**Comment by amaseda** [comment]
Is "inbox" an attribute on the user model?

Not sure if you have the same question as this issue, but take a look: https://github.com/ga-wdi-exercises/project2/issues/814#issuecomment-282742600

**Comment by superbuggy** [comment]
What data in your program is associated with this feature?

**Comment by ghost** [comment]
The associated Model is List. The idea is to have current_user.lists never be empty by (1) initializing each user with an Inbox list, and (2) making the Inbox list un-deletable. I'm pretty sure I know how to do (2), but I'm not sure I know how to do (1).

**Comment by ghost** [comment]
Never mind: I already had a before_action method in my ListsController, and it made sense to add logic to that that accomplishes what I want. Now, when a user has 0 lists (either because they just signed up, or because they just deleted their last list), an Inbox list is automatically generated and made active. Thanks anyway!
