### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by bgalladian** [ga-wdi-exercises/project2#849]
I keep running into the same Heroku error, which I've copy and pasted below. Tried manually clearing and setting the buildpack multiple times, to no avail.

$ git push heroku master
Counting objects: 397, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (369/369), done.
Writing objects: 100% (397/397), 319.87 KiB | 0 bytes/s, done.
Total 397 (delta 182), reused 3 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Failed to detect set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to wasitworthit.
remote:
To https://git.heroku.com/wasitworthit.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/wasitworthit.git'

**Comment by amaseda** [comment]
To confirm what we talked about in #techsupport, are you pushing to heroku from inside your Rails app (i.e., at the same level as the `app` `db` `config` folders and all that jazz)?

**Comment by bgalladian** [comment]
Yes I am.

**Comment by AndyWhitley** [comment]
Check out the article noted in the logs:
https://devcenter.heroku.com/articles/buildpacks#using-an-official-buildpack

To set a buildpack, run:  
`heroku buildpacks:set heroku/ruby`

And then try deploying again

**Comment by AndyWhitley** [comment]
@bgalladian let me know if that works for you

**Comment by bgalladian** [comment]
I got it to push, James helped me.  Thanks guys!

**Comment by amaseda** [comment]
:+1:
