### ISSUE TITLE
if-else loop to display certain element 

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project2#85]
The user story I am working on is adding and deleting articles from a saved reading list. I have a join table that lets users add and remove associations to link users to articles. If there is no association, it says "Add to Reading List"; if there is an association, it says "Saved to Reading List". However, if a user has previously added an association, then removed it, my if-else loop to display the form to add the association doesn't work at all.

Basically, sometimes it works, sometimes it doesn't. Is anything wrong with the following if-else loop?

![screen shot 2015-08-04 at 11 54 35 am](https://cloud.githubusercontent.com/assets/7719096/9065495/bbdf4c16-3a9f-11e5-83cc-7867c2807782.png)

If no association ever has been made, it displays as:
![screen shot 2015-08-04 at 11 39 48 am](https://cloud.githubusercontent.com/assets/7719096/9065151/02897f8a-3a9e-11e5-9690-8fda069bb5b1.png)

If the association exists, it displays as: 
![screen shot 2015-08-04 at 11 39 40 am](https://cloud.githubusercontent.com/assets/7719096/9065181/275d0b74-3a9e-11e5-9cc8-dd02dd36a191.png)

But if the association has been created and subsequently removed, returning to the page displays no button. Based on the if-else loop in my code above, I expect like.user_id not to match the @user.id, and to display the form. Instead it displays nothing:
![screen shot 2015-08-04 at 11 39 56 am](https://cloud.githubusercontent.com/assets/7719096/9065158/086f154a-3a9e-11e5-891a-b782e4b6cd98.png)

**Comment by RobertAKARobin** [comment]
Try removing the `<% break %>` statements

**Comment by jshawl** [comment]
There is a lot going on here. Can you move the logic from your view to a controller or model method?

example ideal logic in the view: 

```
<% if @user.likes?(@article) %>
  <a href='#'>Saved!</a>
<% else %>
  <a href='#'>Save for later</a>
<% end>
```

Instead of looping through every like in the db.

**Comment by msteffan** [comment]
Update: I tried re-setting the database to start over, which made it worse; now nothing displays in that area at all to begin with and I can't make anything show up. 

Robin: Removing <% break %> didn't work; I already tried that.

Jesse: I don't know how to set the logic into a controller/model method, and I can't find a good resource online for it. If you can recommend something to look for, I'm happy to do that. Otherwise, it's not helpful to me to have an example of the ideal and no idea how to get there.

**Comment by jshawl** [comment]
Example of how to get there:

``` rb
class User < ActiveRecord::Base
  def likes? article
    # logic to decide if a user likes an article
  end
end
```

**Comment by RobertAKARobin** [comment]
I'm closing this for now, but please re-open if issues are persisting!
