### ISSUE TITLE
problem moving elements to the middle of screen

### ISSUE THREAD

**Issue by malrese1** [ga-wdi-exercises/project2#852]
when trying to move any text background video stops working and can not find a way to make background video transparent.

**Comment by amaseda** [comment]
Can you elaborate on this problem? Some things to cover...
- What do you mean by "move any text"?
- What do you mean by making the background video transparent?
- What errors are you getting?

Please reference this link for tips on what information to include in an issue: https://github.com/ga-wdi-exercises/project2#asking-for-help

**Comment by malrese1** [comment]
when i try to center the text the video breaks, i have a video for the background and when i edit anything  the video stops working

**Comment by AndyWhitley** [comment]
Post a code snippet of the code you are using to center the text

**Comment by AndyWhitley** [comment]
and a code snippet of the code in your .erb file for the view with the text and video

**Comment by malrese1** [comment]
i just put 

h2{
  font-family: cursive;
  color: red;
  text-align: center;
}

**Comment by AndyWhitley** [comment]
and are you getting a rails error message or just the page doesn't look right?

**Comment by malrese1** [comment]
just the page is not right

**Comment by AndyWhitley** [comment]
could you paste all of your .html.erb file here that the video and text is on

**Comment by malrese1** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <title>GOOD MEAL</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= video_tag "awesome Sony ultra hd food 4K Demo video 2016", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
  <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- <%= image_tag('scribble.png') %>
    <%= link_to "Sign Up", new_user_registration_path %> -->

    <% if !current_user %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Sign In", new_user_session_path %>
    <% end %>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

```

**Comment by AndyWhitley** [comment]
Not sure if this is the problem, but you cannot comment out code using  in .erb files. You have to put a # on each line you want commented out. (I would recommend not commenting out code in your .erb files). Try removing that commented out line and see if that fixes it. 

Also, I don't see the text you are trying to center here in your .erb file (as in the h2 element you reference in your .css file).

**Comment by superbuggy** [comment]
for example `<%# erb comment %>`
