### ISSUE TITLE
Datetime to Time

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/project2#853]
Is there a simple way to convert Datetime to show as a more standard time?

 2000-01-01 13:00:00 -0500     instead show as     1:00

I'm googling things, but I'm pretty confused.

**Comment by amaseda** [comment]
`.strftime` might be helpful. Let me know if this is what you're looking for: https://hackhands.com/format-datetime-ruby/

**Comment by hawkins-will** [comment]
This is everything I could have wanted and more. Thanks!

**Comment by hawkins-will** [comment]
I can get it to work when the data type is time, but not when it's Datetime. Any idea why?

**Comment by amaseda** [comment]
Hm, how exactly are you using it?

**Comment by amaseda** [comment]
Also try this: http://apidock.com/ruby/DateTime/strptime/class

**Comment by hawkins-will** [comment]
I got some of it to work but then pushed to Heroku and it appears Heroku hates strftime. So I undid it and decided to put that on the backburner for a little.

**Comment by amaseda** [comment]
Gotcha. Well hopefully when you revisit this the solution comes quickly. Closing this for now but feel free to re-open if it persists - happy to help!
