### ISSUE TITLE
Deployed app images broke

### ISSUE THREAD

**Issue by dlin2102** [ga-wdi-exercises/project2#854]
My star rating system image isn't showing up.
![screen shot 2017-03-01 at 5 16 13 pm](https://cloud.githubusercontent.com/assets/24783239/23483940/e5afe26c-fea2-11e6-8ba9-2896a91bc383.png)
![screen shot 2017-03-01 at 5 15 58 pm](https://cloud.githubusercontent.com/assets/24783239/23483941/e6d076e8-fea2-11e6-8300-e3c03d8735bf.png)

I don't know it's doing this.

**Comment by amaseda** [comment]
If you run `$ heroku run rails assets:precompile` does that fix it? If not, will send over some other ideas.

**Comment by dlin2102** [comment]
It didn't work. The star images are in my images file in my app. Does that make a difference?

**Comment by dlin2102** [comment]
nvm Hannah fixed it. Thank you!

**Comment by amaseda** [comment]
Sorry, just saw this, but glad you fixed it! What was the solution?
