### ISSUE TITLE
might be too late, but..

### ISSUE THREAD

**Issue by pootsmagoots** [ga-wdi-exercises/project2#855]
I'm adding one quick feature.. I have nested Events with my Months model. When i run my app i receive this error ""ActiveRecord::RecordNotFound in EventsController#destroy, Couldn't find Event with 'id'=1"" My code looks like this   
```rb 
def destroy
    @event = Event.find(params[:month_id])
    if @event.user == current_user
      @event.destroy
    else
      flash[:alert] = " You can not delete that!! STOP!"
    end
    redirect_to months_path
    end
  end
```

**Comment by amaseda** [comment]
What does the URL look like? Does `month_id` exist in there? Or should it be `event_id`?

**Comment by pootsmagoots** [comment]
So i restarted the app, the URL is http://localhost:3000/months/1/events/1/edit. With the error now at  
"undefined local variable or method `event' for #<EventsController:0x007f9f4099d450>"

```rb 
def edit
    **@event = event.find(params[:month_id])**
    if @event.user == current_user
      @event.destroy
    else
```

**Comment by amaseda** [comment]
It should be `Event.find` instead of `event.find` -- make sure it's capitalized.

**Comment by pootsmagoots** [comment]
that's embarrassing.. Can't believe i missed that. thanks Adrian.

**Comment by amaseda** [comment]
No prob :+1:
