### ISSUE TITLE
Gremlins, I tell ya

### ISSUE THREAD

**Issue by cjwightman** [ga-wdi-exercises/project2#856]
For whatever reason, my edit and update function is now applying the data from the instance that I am editing to all other instances. For example, I go into Cucumber to edit it. Once I click edit *POOF*  All of my plants suddenly turn into Cucumbers with all of the same data. Here is my form and controllers.

<h2>Edit this plant</h2>

<%= form_for @plant do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :height%>
  <%= f.text_field :height %>

  <%= f.label :width %>
  <%= f.text_field :width %>

  <%#= f.label :season %>
  <%#= f.text_field :season %>

  <%= f.label :hardiness %>
  <%= f.text_field :hardiness %>

  <%= f.label :depth %>
  <%= f.text_field :depth %>

  <%= f.label :separation %>
  <%= f.text_field :separation %>

  <%= f.label :watering %>
  <%= f.text_field :watering %>

  <%= f.label :fertilizing %>
  <%= f.text_field :fertilizing %>

  <%= f.label :maturity %>
  <%= f.text_field :maturity %>

  <%= f.label :production %>
  <%= f.text_field :production %>

  <%= f.label :harvest %>
  <%= f.text_field :harvest %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit "Save changes"%>

<% end %>

<%= form_for [@season, @plant], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>

<% end %>

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  def edit
      @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant = Plant.update(plant_params)
    redirect_to plant_path(@plant)
  end

**Comment by amaseda** [comment]
I think it's because you're calling `.update` on the `Plant` class -- not the `@plant` instance.

**Comment by cjwightman** [comment]
@plant.update(plant_params)

This is what you meant. Magics.

**Comment by amaseda** [comment]
:+1:
