### ISSUE TITLE
Heroku input error

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project2#857]
Heroku won't let my input into my form convert from a string nor would it let me enter information and have it return as single bullet points

**Comment by amaseda** [comment]
What do you mean?

Can you provide example input and output and how they work in your local app?

Also please...
- Include the relevant view and controller code
- Double check it is working properly on your local app

**Comment by Nykke** [comment]
I ended up using white-space, pre-line and that fixed the entry issue on both local and heroku. I think the mess up happened when I switch my fields from text field to text area.
