### ISSUE TITLE
Delete is now broken and not sure why

### ISSUE THREAD

**Issue by sdkclements** [ga-wdi-exercises/project2#858]
PG::ForeignKeyViolation: ERROR: update or delete on table "shows" violates foreign key constraint "fk_rails_477f73852f" on table "seasons" DETAIL: Key (id)=(1) is still referenced from table "seasons". : DELETE FROM "shows" WHERE "shows"."id" = $1

I have dependent destroy on the models.. deletes used to work.

**Comment by amaseda** [comment]
How exactly are you using `dependent: destroy`? Can you show the model files in question?

**Comment by sdkclements** [comment]
```rb
class Show < ApplicationRecord
	has_many :seasons, dependent: :destroy
	has_many :episodes, dependent: :destroy
end

class Season < ApplicationRecord
	has_many :episodes, dependent: :destroy
  	belongs_to :show
end

class Episode < ApplicationRecord
  belongs_to :season
end
```

-----------------------
PG::ForeignKeyViolation: ERROR: update or delete on table "shows" violates foreign key constraint "fk_rails_477f73852f" on table "seasons" DETAIL: Key (id)=(1) is still referenced from table "seasons". : DELETE FROM "shows" WHERE "shows"."id" = $1

Extracted source (around line #34):

              
  def destroy
    @show = Show.find(params[:id]) 
    @show.destroy         line where the error is
    redirect_to :root
  end

**Comment by sdkclements** [comment]
fixed this

**Comment by amaseda** [comment]
Sorry for the delay here. Glad you fixed it. What was the problem?

@sdkclements

**Comment by superbuggy** [comment]
```rb
class Season < ApplicationRecord
	has_many :episodes, dependent: :destroy
  	belongs_to :show, optional: true #try adding this, or did you add this and it worked? was it something else?
end
```

**Comment by sdkclements** [comment]
I think a show does not have episodes directly only through seasons.
so `class Show < ApplicationRecord
has_many :seasons, dependent: :destroy
end` is how i have it now

**Comment by sdkclements** [comment]
@superbuggy think i should still add that bit u recommended?

**Comment by superbuggy** [comment]
only if you are still running into this error

**Comment by superbuggy** [comment]
closing for now~!
