### ISSUE TITLE
deploying problem

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#86]
I have tried to deploy my apps to heroku as my first MVC function works. 
I cannot figure out what this error is. 

<img width="1142" alt="screen shot 2015-08-04 at 12 01 40 pm" src="https://cloud.githubusercontent.com/assets/11373012/9065884/66e77d48-3aa2-11e5-835c-62575d7004bc.png">

**Comment by RobertAKARobin** [comment]
Would you please run `rake assets:precompile` and let us know what happens?

**Comment by ghost** [comment]
I run rake assets:precompile and it says,

<img width="1040" alt="screen shot 2015-08-04 at 12 28 58 pm" src="https://cloud.githubusercontent.com/assets/11373012/9066252/814f8d36-3aa4-11e5-8253-25fdedc57bb7.png">

should I remove all these files? 
I don't see any these kinds of files on public/asset folder of Scribblr hw that deploying worked.

**Comment by jshawl** [comment]
to fix: commit and push again!
