### ISSUE TITLE
Git wont push

### ISSUE THREAD

**Issue by andrews94** [ga-wdi-exercises/project2#860]
git push origin master
To github.com:andrews94/project2.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:andrews94/project2.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Tried switching to a new branch named "league" but still gave me the same error.

**Comment by amaseda** [comment]
What happens when you try to create a new branch? `git checkout -b league`

**Comment by superbuggy** [comment]
you will have to `git pull` and resolve any merge conflicts.
