### ISSUE TITLE
Problem on show.html

### ISSUE THREAD

**Issue by AmlakBarkon** [ga-wdi-exercises/project2#865]
this is my code and having problem for while
<h1><%= @team.team_name %>
  <%= link_to "Delete Team" ,team_path(@team), method: :delete %></h1>
<% @team.players.each do |player| %>
<h5><%= link_to (image_tag player.img_url), team_player_path(@team, player)%></h5>

<% end %>

Routing Error
uninitialized constant PlayersController

Rails.root: /Users/amlakgirma/Desktop/AMLAKPROJECT/blog

**Comment by juancgarcia** [comment]
Please provide a link to your repo.

**Comment by AmlakBarkon** [comment]
https://github.com/amlakgirma/TeamApp

**Comment by juancgarcia** [comment]
The error `uninitialized constant PlayersController` is telling us that ruby/rails can't find the `PlayersController` class. Rails looks for the controllers inside of `app/controllers/` and these controller classes need to be named very precisely, or they won't be loaded.

Your filename is [`players.controller.rb`](https://github.com/amlakgirma/TeamApp/blob/master/app/controllers/players.controller.rb). For rails to find your file, `players` and `controller` need to be joined with a underscore `_` and not a period `.`

Changing the filename will solve this error

**Comment by AmlakBarkon** [comment]
Thank you Juan
