### ISSUE TITLE
redirect_to error in save action

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-wdi-exercises/project2#87]
My redirect_to after saving an image is causing an error.  I've confirmed the POST is being saved to the db. 

```
undefined method `image_url' for #<ImagesController:0x007f6abd1352c0>

if @image.save
      redirect_to @image, notice: "Image created"
      else redirect "new"
    end
  end
```

**Comment by jshawl** [comment]
Doesn't an image belong to a user? what is the output of `rake routes`?

**Comment by omarimayerswalker** [comment]
The output of rake routes shows images belong to users eg:

/users/:user_id/images/:id images#show

**Comment by jshawl** [comment]
ah yes so `redirect_to user_image_path(@user, @image)`

Closing for now but please reopen if this doesn't solve!

**Comment by omarimayerswalker** [comment]
I'm now getting this error:

No route matches {:action=>"show", :controller=>"images", :id=>"1", :user_id=>nil} missing required keys: [:user_id]

I logged into the console and the user_id: 1. I'm unsure why this isn't being passed in.
