### ISSUE TITLE
Devise

### ISSUE THREAD

**Issue by zonekid** [ga-wdi-exercises/project2#872]
Whats going on guys.  Just having a hard time setting up my devise.  For some reason its not creating a users table.  Would love to meet during office hours if possible

**Comment by AndyWhitley** [comment]
Sure thing, John would be glad to work with you at 10. What steps are you taking currently to set up Devise?

**Comment by zonekid** [comment]
Great, So far I feel like I set it up according to the directions.  I have full crud working for two models.  So I created a users migration.  Set up my models accordingly.  It just when I go to migrate the error reads that a users table doesn't exist

**Comment by AndyWhitley** [comment]
@zonekid Did you get help from John yet regarding this issue?

**Comment by zonekid** [comment]
Yes.  Im probably going to make a new issue soon to work on users uploading files such as photos etc.

**Comment by AndyWhitley** [comment]
@zonekid Oh ok, if this issue is solved, please go ahead and close it
