### ISSUE TITLE
10 doc_ids, but only 3 Docs

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project2#873]
When I create a new Project post within the context of one of my Docs, that post is assigned to a Doc with an id of +1 from whatever the last post/Doc was assigned.  Which means that while I only have 3 Docs, new posts are being assigned to ids other than 1, 2, or 3.  Subsequently, rails cannot find those doc ids when I want to edit or delete those posts.  I'm sure it's something simple that I'm just missing.
<img width="1035" alt="screen shot 2017-05-01 at 9 27 35 am" src="https://cloud.githubusercontent.com/assets/16961196/25580752/68489dd0-2e51-11e7-8f9f-b35710ec7126.png">

https://github.com/edawson1980/story-doc/blob/master/app/controllers/projects_controller.rb#L23-L26

https://github.com/edawson1980/story-doc/blob/master/app/views/projects/edit.html.erb#L3

https://github.com/edawson1980/story-doc/blob/master/app/views/projects/edit.html.erb#L3

**Comment by edawson1980** [comment]
do i need to create a column in my Docs table for id, and then set that id to PRIMARY KEY?  and if so, will that create redundancy issues, as rails automatically creates an id without me asking?

**Comment by AndyWhitley** [comment]
No, you shouldn't need to create a primary key manually. Not sure why it's not linking up. I'm about to clone it down and test it out myself.

**Comment by AndyWhitley** [comment]
It's because you need to link projects to docs in your controller method for `create`:
```rb
  def create
    @doc = Doc.find(params[:doc_id])
    @project = Project.create!(project_params)
    redirect_to doc_project_path(@doc, @project)
  end
```
should be:
```rb
  def create
    @doc = Doc.find(params[:doc_id])
    @project = @doc.projects.create!(project_params)
    redirect_to doc_project_path(@doc, @project)
  end
```

**Comment by AndyWhitley** [comment]
Please let me know if this fixes it for you.

**Comment by edawson1980** [comment]
it didn't, so i re-seeded my data to get rid of the extra posts and start over...which I'm thinking I probably shouldn't have done because that made everything worse and now I've got ids all over the place that don't match up to anything.

**Comment by AndyWhitley** [comment]
Try dropping the database, recreating, and reseeding.

**Comment by AndyWhitley** [comment]
Also, in `app/views/projects/show.html.erb`, you need to give the path helper two inputs, not one:
```erb
<%= link_to "Edit?", edit_doc_project_path(@project) %>
```
should be:
```erb
<%= link_to "Edit?", edit_doc_project_path(@doc, @project) %>
```

**Comment by edawson1980** [comment]
perfect, that all worked.  thank you!
