### ISSUE TITLE
Editing for player 

### ISSUE THREAD

**Issue by AmlakBarkon** [ga-wdi-exercises/project2#875]
having truble editing a player. when you click on a player show, for some reason the url number changes. this is the lick
https://github.com/amlakgirma/Premier-league

**Comment by AndyWhitley** [comment]
In `app/views/players/show.html.erb`, change the order of the inputs to `edit_team_player_path`:
```erb
<%= link_to "Edit", edit_team_player_path(@team, @player) %>
```

**Comment by AndyWhitley** [comment]
Let me know if this fixes it for you

**Comment by AmlakBarkon** [comment]
thank you
