### ISSUE TITLE
creating comments

### ISSUE THREAD

**Issue by zonekid** [ga-wdi-exercises/project2#876]
def create
        @content = Content.find(params[:content_id])
        @comment = @content.comments.create(comment_params)
        redirect_to content_path(@content)
    end

So when I try to create a comment, it takes me back to the show page but a comment doesn't create. Does it have something to do with my controller method?

Now that I think about it, if there is something wrong with the controller for create then I guess you should take a look at update delete and destroy as well just in case. Again my content crud is functional with devise but not comments.

def edit
        @content = Content.find(params[:content_id])
        @comment = Comment.find(params[:id])
    end

    def update
        @content = Content.find(params[:content_id])
        @comment = Comment.find(params[:id])
        if @comment.user !=current_user
            flash[:alert] = "Only the author of comment can delete"
        else
            @comment.update(comment_params)
        end
        redirect_to content_path(@content)
    end

    def destroy
        @content = Content.find(params[:content_id])
        @comment = Comment.find(params[:id])
        if @comment.user == current_user
            @comment.destroy
        else
            flash[:alert] = "Only the author of the comment can delete"
        end
        redirect_to contents_path
    end

**Comment by AndyWhitley** [comment]
On the `create` method, try adding the `!` operator on `.create`, then check the terminal for error messages when you test it again:
```rb
def create
@content = Content.find(params[:content_id])
@comment = @content.comments.create!(comment_params)
redirect_to content_path(@content)
end
```

**Comment by zonekid** [comment]
So with this, it now says user must exist.  So in that case where would I need to add current_user in the controller? I feel like I played around with it but it didn't give me anything

**Comment by zonekid** [comment]
Ok so this is the error I get.
ActiveRecord::RecordInvalid (Validation failed: User must exist)

In that case does this mean i need to add current_user in my controller? And if so where would I add it because I feel that I played around with it and it didn't do anything for me

**Comment by juancgarcia** [comment]
That error means that means the object you're trying to create has a `belongs_to` relationship with `User` so you'll need to provide a user instance to the `.create` method.

You're on the right track with needing `current_user`. In the case of your comment, you'll need to use `.merge` to add that user object just like how we did in the [Devise lesson](https://github.com/ga-wdi-lessons/devise#we-do-update-the-controller-10-minutes--130):

```ruby
@comment = @content.comments.create!(comment_params.merge(user: current_user))
```

**Comment by zonekid** [comment]
Ahh.  Great thats it!
