### ISSUE TITLE
many_to_many

### ISSUE THREAD

**Issue by zonekid** [ga-wdi-exercises/project2#879]
Guys this is the last issue I have.  Everything is functioning fine but this many to many is giving me mad headaches.  Im just confused on how it works for my project.  I think I would need someone to take a look at it whether today or tomorrow.  Up to you all.

**Comment by juancgarcia** [comment]
I recommend going over the [Many-To-Many lesson notes](https://github.com/ga-wdi-lessons/rails-many-to-many) once or twice, and also syncing up with some of the other students to talk it through. But if you'd like to go over concepts with us, you're more than welcome to sign-up for One-On-Ones or bring this up at live support tomorrow.

If there's a particular concern with how this relates to your project, try to come up with a pointed question and link us to the code in your repo with a new comment.
