### ISSUE TITLE
How to customize devise form css in rails

### ISSUE THREAD

**Issue by kwonih1020** [ga-wdi-exercises/project2#881]
https://github.com/kwonih1020/Project-2

Trying to working on css for devise part, i think it's not working at app/assets/stylesheets.

**Comment by jsm13** [comment]
Are there particular rules you are trying to apply but aren't seeing in the browser? The css in `app/assets/stylesheets` should apply to all views including those coming from Devise

**Comment by kwonih1020** [comment]
input box is working through app/assets/stylesheet but i can't move those input box to middle of website, also cannot customize the text "email" and "password" right above the input box.

**Comment by kwonih1020** [comment]
ok, i think i figured out how to move input box to the center, however, i still customizing the text "Email" and "Password" to move to right above input box.
