### ISSUE TITLE
Issue with Devise and User

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project2#883]
Am I able to just switch all of the devise parameters over to Doc(s), instead of User?  Is that advisable?

User functionality was working fine, and I've migrated : 
**devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable** 
over into my doc model.

this is the error i'm getting at the moment:
<img width="1013" alt="screen shot 2017-05-02 at 2 45 59 pm" src="https://cloud.githubusercontent.com/assets/16961196/25633718/1d905a6c-2f46-11e7-81a8-edca2d3289e1.png">

does this mean that I should just move the login (email and password) columns into docs?  and if not, how would you advise I create a relationship between User, Doc, and Project (doc has many projects, project belongs to doc)?

**Comment by juancgarcia** [comment]
If this was resolved by our in-person discussion, please go ahead and close the issue.

**Comment by edawson1980** [comment]
sorry, I forgot.  thanks again!
