### ISSUE TITLE
hiding the edit and delete links

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project2#884]
I'd like to have the edit and delete links visible only to the user who's associated with a post.  I have this code (similar code worked fine for the boards)

<div class="post-title"><%= @post.title %></div>

			<% if @post.user == current_user %>	
			<%= link_to "(edit post)", edit_board_post_path(@board, @post) %>
			<%= link_to "(delete post)", board_post_path(@board, @post), :method => :delete %>	
			<% end %>
			<div><%= link_to "(add note)", new_board_post_note_path(@board, @post) %></div>

but I get this error message:

undefined method `user' for #<Post:0x007fe05482bec8>

**Comment by jsm13** [comment]
I think you're just missing a `belongs_to :user` in your post model https://github.com/twelve13/studii/blob/master/app/models/post.rb

**Comment by twelve13** [comment]
yay that was it!
