### ISSUE TITLE
devise error

### ISSUE THREAD

**Issue by Fitssum** [ga-wdi-exercises/project2#889]
I tried to generate devise for users.
Migration aborted instead.
Detail of error message: PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.
: CREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")

My repo link is https://github.com/Fitssum/project-02.

**Comment by superbuggy** [comment]
What were the actions that triggered this error?

**Comment by Fitssum** [comment]
rails db:migrate (after I finished with rails g devise User)

**Comment by superbuggy** [comment]
I just cloned down your repo and successfully ran your migrations.

what happens when you run `rails db:drop db:create db:migrate`? 

`rails db:drop` will delete your data.

**Comment by Fitssum** [comment]
It's working! thanks!!
