### ISSUE TITLE
Adding second key to the select form 

### ISSUE THREAD

**Issue by tarkzc** [ga-wdi-exercises/project2#890]
I want to add product’s :price key to my select form on the browser next to product names. I added next to :name key on the new_form view but it didn’t show up on browser. What should I do?
<img width="1680" alt="screen shot 2017-06-13 at 1 53 46 pm" src="https://user-images.githubusercontent.com/27385620/27097088-1d8fc66c-5041-11e7-9a3c-d3c826f2313c.png">

**Comment by superbuggy** [comment]
I think that `collection_select` is not the form helper method you want to customize what 'option-text' shows up in the dropdown menu. Instead, you want to use the `select` method.

> *from http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-options_from_collection_for_select*...

```rb
  select("post", "person_id", Person.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })
```

Right now, it's only going to show the `Person`'s name as the text of each dropdown menu option. Assume that each `Person` had a `title` (for example 'Dr.', 'Mr.', or 'Ms.'), and you wanted the dropdown to have each person's title along with their name. You could adapt the code above to that end like this...

```rb
  select("post", "person_id", Person.all.collect {|p| [ p.title + " " + p.name, p.id ] }, { include_blank: true })
```

**Comment by tarkzc** [comment]
<img width="1680" alt="screen shot 2017-06-13 at 2 58 43 pm" src="https://user-images.githubusercontent.com/27385620/27099412-d924ffc6-5048-11e7-984b-290993035a5f.png">

I tried that but form was disappeared right now I just can see "Product" word.

**Comment by amaseda** [comment]
What error were you getting when we talked earlier? Thought you had mentioned it might be a syntax thing.

**Comment by tarkzc** [comment]
I think at that time I just forgot to put hash in uncommented embedded ruby I think that's why I got that error.

**Comment by tarkzc** [comment]
<img width="1680" alt="screen shot 2017-06-13 at 3 14 33 pm" src="https://user-images.githubusercontent.com/27385620/27100155-1f4821c0-504b-11e7-8666-fa581000178b.png">

**Comment by superbuggy** [comment]
Can you try removing the `f.`?

**Comment by tarkzc** [comment]
This is the last error I just got.

**Comment by superbuggy** [comment]
actually hold off on removing the `f.`

You need to convert the price into a string.

**Comment by tarkzc** [comment]
<img width="942" alt="screen shot 2017-06-13 at 3 19 55 pm" src="https://user-images.githubusercontent.com/27385620/27100354-cfb55e56-504b-11e7-9dc6-687e7056ea02.png">

**Comment by tarkzc** [comment]
Sorry I was going to post this 
<img width="942" alt="screen shot 2017-06-13 at 3 21 07 pm" src="https://user-images.githubusercontent.com/27385620/27100411-f9262478-504b-11e7-8cdc-f84594c3bae6.png">

**Comment by superbuggy** [comment]
Try removing the first argument `"order"`

**Comment by tarkzc** [comment]
It worked! Thanks James!

**Comment by superbuggy** [comment]
Nice, the form builder already is concerned with the object (`form_for @product`), so you didn't need that initial argument. If you use select outside of the `form_for`, you'd need to add it.
