### ISSUE TITLE
best way to get database into my seed data

### ISSUE THREAD

**Issue by perryf** [ga-wdi-exercises/project2#893]
I'm trying to avoid writing stuff out by hand with the seed data
theres a database of info here (http://swapi.co/documentation#ruby), whats the best way to incorporate this into my seed data

**Comment by AndyWhitley** [comment]
Have you read through the Rubys-specific documentation:
https://github.com/emaraschio/swapi-ruby

**Comment by AndyWhitley** [comment]
And yes, you could use `eval` to evaluate the stringified hash to make it accessible. For example:
```rb
# seeds.rb

require "swapi"

10.times do |i|
  person = eval(Swapi.get_person(i + 1))
  Character.create({
      name: person[:name],
      etc...
  })
end
```

**Comment by AndyWhitley** [comment]
If you want more control over what data you are getting from the API, you could also look into using the HTTParty gem and hitting the API url directly:
HTTParty - https://github.com/jnunemaker/httparty
Example - https://github.com/ga-wdi-exercises/grumblr_rails_api/blob/master/db/seeds.rb

With that said, for now, I would build out the functionality of your app with a small set of seed data. Then, once the app works, you can look into hitting APIs for more data.

**Comment by AndyWhitley** [comment]
I'm going to close this for now. Re-open if you continue to have issues with seeding.
