### ISSUE TITLE
Trying to increase / decrease a score counter on-click.

### ISSUE THREAD

**Issue by jacobg1** [ga-wdi-exercises/project2#894]
Trying to increase / decrease a score counter on-click.  Have the following methods in my guess controller

```rb
class Guess < ApplicationRecord
  belongs_to :post

  def score_up
    self.score += 1
  end
  def score_down
    self.score -= 1
  end
end
```
in one of my views i have the following link

```rb
<%= link_to '(+)', post_guess_path(@post, guess)  %>
```

which sets off the following:

```rb
def show
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = Guess.find(params[:id])
    @guesses = Guess.all
    @guess.score_up
    @guess.save
  
    redirect_to place_post_path(@place, @post)
  end
```
This works for increasing the score but does not for decreasing the score since I can only use the guess show path once.  I'm thinking I should probably use javascript but am unsure how to even link a javascript file and unable to get a clear answer online.  Was also looking into drawing a custom route for decreasing the score but to no avail.  Is there a way to call a method from inside a helper link?  Looks like probably not.  Can I get a hint on how I might get going on this?

**Comment by jacobg1** [comment]
ps. was also looking into drawing a custom route for decreasing the score but to on avail

**Comment by AndyWhitley** [comment]
Hi Jacob. What you want to do for this functionality is to set up a separate route and controller action to increase or decrease the vote amount and then use JavaScript / jQuery to update the number the user is seeing on the front-end (if you don't want to refresh the page). Some sample code:

**Routes**
```rb
resources :guesses do
    member do
        post "increase_score"
        post "decrease_score"
    end
end
```
> Documentation: http://guides.rubyonrails.org/routing.html#adding-more-restful-actions

**View**
```html
<%= link_to "Increase", increase_score_path(guess), method: :post %>
<%= link_to "Decrease", decrease_score_path(guess), method: :post %>
````
> Documentation: https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

**Controller**
```rb
class GuessesController < ApplicationController

    def increase_score
         # do something...
    end

    def decrease_score
         # do something...
    end

end
```

**Comment by AndyWhitley** [comment]
One note: Since we don't want a page refresh for each update of the score, you won't redirect at the end of the controller actions (they will simply update your data and nothing more). Then add JS / jQuery to the front end to update the number on screen (make sure to use a `document.ready()` or an IIFE to prevent the code from running until after the DOM has loaded.

**Comment by jacobg1** [comment]
Hi Andy, this makes sense until the very last step. was able to find a work around that doesn't include javascript :)
closing this.
