### ISSUE TITLE
iterate through items

### ISSUE THREAD

**Issue by preese13** [ga-wdi-exercises/project2#897]
<%= link_to "Previous", "/items/1" %>
<%= link_to "Next", "/items/2" %>

in my controller, could I create a method 
def show
  @item = Item.find(params[:id])
@nexitem = item.find(params[:id]+1)
end

or something like that

**Comment by jsm13** [comment]
Something like this should work but there a few bits to make sure you have right. One thing we want to get away from is assuming that the next item will always have an id of the previous record plus one.

Consider the controller before the view. We have an item id in params we can use to grab the item with that id. The next item should also be retrieved and put in an instance variable at this time. There are a couple of options on how to do this but they'll follow the same general procedure.

Most of the time we use [find](http://guides.rubyonrails.org/active_record_querying.html#retrieving-a-single-object) to grab records from the database when we have an ID. 

We want something that behaves like this but grabs multiple records, starting with that one with the given ID.

We can do this using the active record relation `.where` method [to specify a condition](http://guides.rubyonrails.org/active_record_querying.html#conditions): `Item.where('id >= ?', params[:id])`

This is going to give us back a relation of all of the items where the id is equal to or greater than the id in the query params. Finally we take the first two results matching our condition and put them into an array using the `take` method.

All together, in the controller we'd have something like:

```ruby
# app/controllers/items_controller.rb

def show
  @items = Item.where('id >= ?', params[:id]).take(2)
end
```

Then in your view you can use `@items[0]` for what's on the page. You can use `@items[1]` with a link helper to link to the next item (making sure to check that item exists, if the array that comes back doesn't have a second entity, you know you're at the end of the list). Finally to get to the previous item, I would use the `link_to 'previous', :back` helper which will create a link for you that uses JS to just go back to the previous page.

This still has a fair amount of logic dependent on ids being in sequence -- something generally to be avoided (we want to think of ids simply as unique identifiers and nothing more).
