### ISSUE TITLE
project2 issue to resolve [school registrar] database

### ISSUE THREAD

**Issue by Gelmo890** [ga-wdi-exercises/project2#899]
https://github.com/Frewabebe/project2
courses |the join| table would not reset and does not out put when queried. Could not resolve disparity between migrate/CreateCourses and shcema.rb file.

**Comment by jsm13** [comment]
The migrations and models look good to me but wanted to note a couple things:
1. Name spaced properties: For the faculties and students tables, the properties `faculty_name` and `student_name` don't need the specifier of what kind of name it is. It can be inferred by the model. Instead, I would just use the property `name` for each.

2. You do not need the `course_number` property on a student, that can be retrieved by using the relationship with the class.

3. There is not a join table at play here yet. The migration currently describes a class as having one student (a course references a student) and one instructor (a course references an instructor). At least the student needs to be related to the class by way of a join table (a table called enrollments would make sense).

I would suggest you work on just implementing the Course, Enrollment, and Student models with a many to many relationship (Students have many Courses through Enrollments) using [this section from the active record associations chapter of the rails guide as a model](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association) where Students are equivalent to Patients, Enrollments are equivalent to Appointments, and Course are equivalent to Physicians.
