### ISSUE TITLE
Homework: userstories, erd and wireframes

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project2#9]
Completeness: 5
Comfort: 5

My idea was to create an app that would give you a programming shortcut a day. Andy has been telling us to learn one command a day. I have been doing that but I often need to know what I'm looking for. I thought it would be cool if there was an app that gave you a programming command a day kind of like a word of the day but for programmers. 

If that isn't what you are looking for I also thought an app that values antiques. My boyfriend and I have been cleaning his grandma's house now that she has moved in to a home and we don't know if its junk or valuable so I thought about an app that you can download a photo and a community can let you know if it is valuable. Below is the user stories for the first idea but I have this idea just in case. 

Repo: https://github.com/malissaromero/project_two_developer_tips

Wireframes: 
![img_9595](https://cloud.githubusercontent.com/assets/11203264/9028497/f14a45ca-3948-11e5-83ce-e8316af8d1ca.JPG)
![img_9594](https://cloud.githubusercontent.com/assets/11203264/9028498/f2970d78-3948-11e5-8e7f-517483232a2e.JPG)

**Comment by mattscilipoti** [comment]
Either sounds good.  Which one do you want to do?

**Comment by mattscilipoti** [comment]
Which one did you choose?

**Comment by malissaromero** [comment]
I chose the developer command hack one.
