### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project2#90]
Trying to have a home page that shows all recipes for all users (which is up) and then have a separate page(which is up, but blank) for user that is signed in to see the recipes that he/she created.  

Seems like the problem to me is when new recipes are created I can't attach the user_id to recipe b/c it's not in the params, but I can't figure out how to reroute this thing, (especially using resources), to do that.  Not sure if I have to include user as a nested route, but then it creates CRUD am not gonna use, right?

**Comment by RobertAKARobin** [comment]
If you've specified that a user has many recipes, and each recipe belongs to a user, then you can do:

```
current_user.recipes.create!(recipe_params)
```

That'll take care of associating them for you.

**Comment by jshawl** [comment]
a common pattern to associate the user when creating is to use the merge method:

``` rb
def create
  @post = Post.create(post_params.merge(user: current_user))
end
```

I don't think you need to change your resources. what about:
- home page > all posts by current user
- /posts > all posts by all users

**Comment by Ryan-321** [comment]
Worked!  Thanks fellas.
