### ISSUE TITLE
Trying to add "upvote" route to my Routes

### ISSUE THREAD

**Issue by sanjaywallah** [ga-wdi-exercises/project2#902]
I've tried looking this up, but I can't seem to find anything.  When I try this, the operation just aborts.

```ruby
Rails.application.routes.draw do

  root to: "cheerups#index"
  resources :cheerups do
    resources :votes
  end
  resources : cheerups do
    member do
      post 'upvote'
  end
end
```

**Comment by jsm13** [comment]
What is the exact error? Could you also link to your repo in its current state.

It looks like there's a space between the `:` and `cheerups` on the second top level resource.

**Comment by sanjaywallah** [comment]
Hi John:  I figure it out.  I was missing an end statement.
