### ISSUE TITLE
Review of my API set up

### ISSUE THREAD

**Issue by lizardbird** [ga-wdi-exercises/project2#903]
I'd like to use the Yelp API to help me seed my ramen restaurants. I am working under a new branch to do this, and found a gem that makes it easier (https://github.com/Yelp/yelp-ruby). 

I think I have things set up correctly, but I'm just not sure how to actually make the request to Yelp to get the access token needed to complete the set up and run the commands.

See my code at https://github.com/lizardbird/wdi-proj2-ramen-shaman/tree/yelpapi

**Comment by jsm13** [comment]
Really stoked you're looking into this. It will be a few steps.
1. You'll need to create a developer account with Yelp [here](https://www.yelp.com/developers) and register an application to get the keys through there developer portal
2. You want to create an [initializer file](http://guides.rubyonrails.org/configuring.html#using-initializer-files). Reference the second code block [here](https://github.com/Yelp/yelp-ruby#basic-usage) for the contents of that file.
**BEFORE YOU COMMIT**
3. Test that you can actually make the request hardcoding the keys into the initializer file you created
4. Use [figaro](https://github.com/laserlemon/figaro) following the steps in the readme or something similar to manage your API keys so you don't commit them to github

**Comment by lizardbird** [comment]
Excellent. I created my developer account with Yelp, got my client key, and installed the gem. However, Yelp says I need to get an access token in addition my client key and secret key by following the steps below. How do I make a POST call to the endpoint listed below WITH my client id and secret key?

Get an access token
To get an access token, make a POST call to the following endpoint using the client id and secret obtained from the former step. Then get the access token from the response body.

URL
https://api.yelp.com/oauth2/token

Source: https://www.yelp.com/developers/documentation/v3/authentication

**Comment by jsm13** [comment]
What you're going to want to do is use a tool like Postman to make a POST request to `https://api.yelp.com/oauth2/token`. Postman will give you the option to set the body type once you've chosen to make a post request. You'll want to choose `application/x-www-form-urlencoded` and add the body:
```
grant_type: client_credentials
client_id: (what you got from the yelp developer portal)
client_secret: (ditto)
```

Check out [this repo](https://github.com/Yelp/yelp-fusion) and specifically the [bearer_token method](https://github.com/Yelp/yelp-fusion/blob/master/fusion/ruby/sample.rb#L26-L95). I'm a little surprised the `yelp-ruby` gem doesn't account for this. It may be out of date.

**Comment by jsm13** [comment]
Subsequent requests to the endpoint need to use the token you get back from this but I'm thinking the yelp-ruby gem won't account for this. May be best to use the yelp fusion example

**Comment by lizardbird** [comment]
You are right. The gem was out of date and Yelp no longer authorizes that way. I switched to the Yelp Fusion example, copied the sample code into an initializer file ([yelp.rb](https://github.com/lizardbird/wdi-proj2-ramen-shaman/blob/yelpapi/config/initializers/yelp.rb)) for testing, and tried to run it in the console, but now I'm having issues actually returning any results. I get the following error:
```
ruby config/initializers/yelp.rb search --term=ramen --location="Washington DC"
Found  businesses. Listing 5:
config/initializers/yelp.rb:157:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)
```

Latest commit: https://github.com/lizardbird/wdi-proj2-ramen-shaman/tree/yelpapi

**Comment by lizardbird** [comment]
Spoke with Juan - turns out I was using an outdated client key. Resolved!
