### ISSUE TITLE
API Setup

### ISSUE THREAD

**Issue by kadkins4** [ga-wdi-exercises/project2#904]
repo: https://github.com/kadkins4/Project-2
gem: https://github.com/vinnicc/dota

I'm attempting to utilize the dota API via a gem and am having a hard time getting it connected to rails.  I am receiving an error message when trying to create the migration document.  I created the initialize filer for the gem and thought I input the key correctly, but maybe I'm not?!
<img width="792" alt="screen shot 2017-08-08 at 1 53 27 pm" src="https://user-images.githubusercontent.com/27822197/29087014-7d5efdd8-7c42-11e7-9e30-dcaf1e408fc9.png">
<img width="1243" alt="screen shot 2017-08-08 at 1 53 14 pm" src="https://user-images.githubusercontent.com/27822197/29087018-7f1ef1b4-7c42-11e7-8600-a83988661d17.png">
<img width="731" alt="screen shot 2017-08-08 at 2 05 44 pm" src="https://user-images.githubusercontent.com/27822197/29087098-bcbc93d2-7c42-11e7-8659-156d3b523fe7.png">

**Comment by kadkins4** [comment]
I did find this JSON version which I could use (build>heroes.json), would that be more beneficial? 
https://github.com/odota/dotaconstants

**Comment by jsm13** [comment]
Sorry, just popped out to check in and got overwhelmed with other issues. How's this going?

**Comment by kadkins4** [comment]
no worries, I'm going to table this until I finish the rest of the project

**Comment by juancgarcia** [comment]
@kadkins4 I'm going to close this issue for now. Feel free to re-open and add a new comment when you get back to the API.
