### ISSUE TITLE
Error on redirect_to :back within Favorites

### ISSUE THREAD

**Issue by lizardbird** [ga-wdi-exercises/project2#905]
I *think* my favorites many-to-many is working, but when I click on the &hearts;, it throws a error. 
```
undefined method `back_url' for #<BowlsController:0x007f96c7598c28>
```

I found guidance [online](https://stackoverflow.com/questions/44098584/rails-redirect-to-back-not-working) that says `redirect_to :back` is deprecated and instead to use ```redirect_back fallback_location: root_path``` but neither are working for me. Any help? Thx in advance!

**Comment by lizardbird** [comment]
To clarify - I believe it is still working because when I manually go back to the post in question, the heart reflects the appropriate "favorited" status.

**Comment by jsm13** [comment]
Hmm, I think that `redirect_to :back` might tell the browser to just use the last page that already loaded. See if:

```ruby
  def remove_favorite
    bowl = Bowl.find(params[:id]
    Favorite.find_by(user: current_user, bowl: bowl).destroy
    redirect_to bowl
  end
```
helps

**Comment by lizardbird** [comment]
Yeah, that was the example used in the lesson on favorites and redirecting. Either way, I ended up trying `bowl_path(@bowl)` and that worked. Resolved!
