### ISSUE TITLE
Displaying a form if a join table doesn't exist yet

### ISSUE THREAD

**Issue by TimGafvert** [ga-wdi-exercises/project2#908]
```erb
<% if @TABLE.JOINTABLE.include?(@TABLE.id) == false %>
// Im not sure how to ask the question: IF there exists a relationship already between these two
// things, DON'T display the form.

<%= render "form" %>

  <% else %>

  <%= link_to "Delete".html_safe, remove_proficiency_skill_path, method: :delete, class: "Delete" %>
  
<% end %>
```

**Comment by juancgarcia** [comment]
@TimGafvert This is a bit too abstract of a question. Please add/commit/push either to master or a feature branch and then link to the specific view where you'd like to implement this.


Example:

My project: https://github.com/TimGafvert/Project2

Link to file in question:
https://github.com/TimGafvert/Project2/blob/master/app/views/skills/edit.html.erb

**Comment by TimGafvert** [comment]
https://github.com/TimGafvert/Project2

https://github.com/TimGafvert/Project2/blob/master/app/views/skills/show.html.erb

the "form_proficiency" should only show if the user doesn't have that proficiency yet. So I want to make an IF statement that would check if you had, for example  current_user has PROFICIENCY in SKILL. I am not sure how to perform that check because I cant seem to properly reference the relationship.
