### ISSUE TITLE
Help with route structure in four model app

### ISSUE THREAD

**Issue by petergcutler** [ga-wdi-exercises/project2#91]
Working on building a view that reflects many shallow nested models. Hitting some roadblocks here. Is someone available to talk through this?

![screen shot 2015-08-04 at 2 04 59 pm](https://cloud.githubusercontent.com/assets/11398019/9068614/42cedc7a-3ab2-11e5-9935-22382457b39f.png)
![screen shot 2015-08-04 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/11398019/9068615/42cfd71a-3ab2-11e5-84c5-1ed314a9cd36.png)
![screen shot 2015-08-04 at 2 05 52 pm](https://cloud.githubusercontent.com/assets/11398019/9068613/42ce2d5c-3ab2-11e5-8d10-af968dd1435e.png)

**Comment by RobertAKARobin** [comment]
Can you be more specific about the errors you're getting?

**Comment by petergcutler** [comment]
Generally a method error for tropes/show

![screen shot 2015-08-04 at 2 15 22 pm](https://cloud.githubusercontent.com/assets/11398019/9068747/49396bce-3ab3-11e5-84d7-5ed4d6e7108c.png)

**Comment by RobertAKARobin** [comment]
Hmm. Did you specify in your Pane model that a pane has many Items? That `items` method should be working otherwise!

**Comment by petergcutler** [comment]
I did, yeah, not sure what's going on here.

**Comment by petergcutler** [comment]
![screen shot 2015-08-04 at 2 32 27 pm](https://cloud.githubusercontent.com/assets/11398019/9069168/b7694cca-3ab5-11e5-8e71-3fc9a40faad4.png)
