### ISSUE TITLE
Referencing if the User has a Proficiency with Skill

### ISSUE THREAD

**Issue by TimGafvert** [ga-wdi-exercises/project2#910]
https://github.com/TimGafvert/Project2

https://github.com/TimGafvert/Project2/blob/master/app/views/skills/show.html.erb

the "form_proficiency" should only show if the user doesn't have that proficiency yet. So I want to make an IF statement that would check if you had, for example current_user has PROFICIENCY in SKILL. I am not sure how to perform that check because I cant seem to properly reference the relationship.

**Comment by TimGafvert** [comment]
Nevermind about this one. I figured it out.

**Comment by juancgarcia** [comment]
Ok, closing.
