### ISSUE TITLE
Issue with creating a new pedal

### ISSUE THREAD

**Issue by basssamurai** [ga-wdi-exercises/project2#914]
I tried creating a new pedal. I expected the app to create a new pedal. It threw an error instead.
My repo link is https://github.com/basssamurai/Build-a-Pedalboard and my question is about lines 11-14 in pedals_controller.rb

![image](https://user-images.githubusercontent.com/30270485/30558423-4dd1d48e-9c7f-11e7-92f9-5f874bf744a8.png)

**Comment by aspittel** [comment]
```<%= form_for @pedal do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :style %>
  <%= f.text_field :style %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>

<% end %>
```
The new pedal needs to have the parent pedalboard attached to it -- either with a select for that pedalboard or by nesting the URLs so the parent is in the form like so: https://git.generalassemb.ly/ga-wdi-lessons/rails-routing#form-helpers

**Comment by basssamurai** [comment]
Thanks Ali!  So because the class Pedal ":belongs to" the class Pedalboard, there has to be a direct association with a specific pedalboard?  What if I wanted any given pedal to be associated with _any_ pedalboard?  I know that is a many to many relationship.  Would I need to nest my routes to accomplish this?

**Comment by superbuggy** [comment]
trying adding `optional: true` 

```rb
class Pedal < ApplicationRecord
  belongs_to :pedalboard, optional: true
end
```

> *from http://guides.rubyonrails.org/association_basics.html*...
```
If you set the :optional option to true, then the presence of the associated object won't be validated. By default, this option is set to false.
```

**Comment by superbuggy** [comment]
Closing for now!
