### ISSUE TITLE
Issue with editing pedals

### ISSUE THREAD

**Issue by basssamurai** [ga-wdi-exercises/project2#916]
I am trying to edit a pedal. I expected the edit form to appear when i clicked "edit". It threw an error instead.
My repo link is https://github.com/basssamurai/Build-a-Pedalboardand my question is about lines 20-22 in pedals_controller.rb

![image](https://user-images.githubusercontent.com/30270485/30561234-62610e98-9c88-11e7-873c-348514f88f85.png)

![image](https://user-images.githubusercontent.com/30270485/30561268-72ecc752-9c88-11e7-9bec-e66573498a25.png)

**Comment by aspittel** [comment]
The route in the error is `/pedal/2` but in the routes its `/pedals/2` plural  -- does that solve it?

**Comment by basssamurai** [comment]
I noticed that too but where would I adjust pedal to pedals?  Also, in the code below for create it works just fine.  It also works in my pedalboard controller as singular.

```rb
  def create
    @pedal = Pedal.create!(pedal_params)
    redirect_to pedal_path(@pedal)
  end
```

**Comment by superbuggy** [comment]
There's a link in your show view for pedals with the url as singular, the routes just define URL handling.

in `Build-a-Pedalboard/app/views/pedals/show.html.erb`...

```html/erb
<h2><%= @pedal.name %> <a href="/pedal/<%= @pedal.id %>/edit">(edit)</a></h2>
```

**Comment by superbuggy** [comment]
closing for now!
