### ISSUE TITLE
join table

### ISSUE THREAD

**Issue by dionadk** [ga-wdi-exercises/project2#918]
hey..I have a question..
can i have a join table like with the following conditions on my model

user has many likes
user has many pics

pic belongs to a user
pic has many likes

like belongs to a user
like belongs to a pic
>>>>>>>>>
Can i do this without a through: :like... because i don't want my pic to have many users through like(join table)

**Comment by superbuggy** [comment]
Ali mentioned she spoke with you yesterday. Closing for now, reopen if necessary.
