### ISSUE TITLE
Added devise and now db won't migrate.

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/project2#93]
I went through the steps to add devise and when looking at localhost:3000, the error message says to run a rake db:migrate.

```
ActiveRecord::PendingMigrationError
Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=development"
So when I do $rake db: migrate, it aborts after starting the migration (I saw a line of equals signs then tons of error msgs) "== 20150804145814 AddDeviseToUsers: migrating ================================= -- change_table(:users)
rake aborted!  StandardError: An error has occurred, this and all later migrations canceled:
PG::UndefinedTable: ERROR:  relation "users" does not exist"
```

So I went in and deleted my users_controllers.rb file because others said I can't have an already-created users_controller.rb file when trying to migrate. And now I have the same error, still without the ability to migrate the db.

**Comment by jshawl** [comment]
what is the output of `rake db:migrate`?

**Comment by RobertAKARobin** [comment]
You actually don't need to delete controllers to remigrate! If you get that error again, no need to change any files — just `rake db:migrate`, and if that doesn't seem to work and/or throws an error, `rake db:drop`, `rake db:create`, `rake db:migrate`.

**Comment by LauraWN** [comment]
Hello! me again. 
the database would not migrate after a reset of the computer and running through the rake db:migrate, rake db:drop, etc. 
It turns out that I had created a second user table migration with devise and that this migration table was not exactly the same as the original table. So, it was giving me errors with the user table. Next time, I should only create the table once and not confuse the rails.
