### ISSUE TITLE
Heroku fail

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#94]
Here's what happened when I just tried to push up to Heroku. Any ideas?

```
Jeremys-MacBook-Air:dcfuture JKoul$ git push heroku master
Total 0 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote: Verifying deploy....
remote: 
remote: !   Push rejected to dcfutureblog.
remote: 
To https://git.heroku.com/dcfutureblog.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/dcfutureblog.git'
```

**Comment by RobertAKARobin** [comment]
Is your Gemfile, app folder, db folder, etc., in the same directory as your `.git` folder?

**Comment by jkoul** [comment]
I actually just switched it all into there. Still getting the same error.

**Comment by RobertAKARobin** [comment]
Did you re-push to Heroku? If so, can you re-push to Github so I can see your code?

**Comment by jkoul** [comment]
Hang on.....I just merged back to my local master branch and I think it's working.....

**Comment by RobertAKARobin** [comment]
Oh! Good!

**Comment by jkoul** [comment]
Ran into a roadblock but at least it's a different one!

**Comment by RobertAKARobin** [comment]
Woooo

**Comment by jkoul** [comment]
It's just taking a good while to install a massive plugin called "ckeditor" that enables easy html entry into form fields and that I've yet to configure. Hopefully it isn't too terribly cumbersome.

**Comment by RobertAKARobin** [comment]
Uh oh. That's your call! I'm closing this, but re-open if anything comes up.

**Comment by jkoul** [comment]
Sounds good. I ran into an authentication issue and have to re-push, but that one was just an unforced error. Thanks for cheering me on! haha
