### ISSUE TITLE
issue with creating a favorites model

### ISSUE THREAD

**Issue by pdavies88** [ga-wdi-exercises/project2#96]
Trying to create a favorites model, controller, and view to add to my existing MVCs which are users, posts, and comments. I would like for a user to favorite a post and have that favorited post stored for a user on a favorited posts page. I looked at this http://stackoverflow.com/questions/13240109/implement-add-to-favorites-in-rails-3 and this http://stackoverflow.com/questions/7021026/ruby-on-rails-how-to-model-a-user-favorite-model#answers tried to implement but just confused more. Not sure what before filter :find_user does and how I can implement that. Would I need a sessionshelper? Still lost from adam's lesson early and not sure how I can translate that to my situation. Feel free to reply here with suggestions but if someone could pair with me for 10 min tomorrow I think that would be a little more beneficial since I am not sure if my models, migrations or controllers are causing the issue

**Comment by RobertAKARobin** [comment]
Sure, Preston! Just send your squad instructor a private Slack message when you get in.

**Comment by amaseda** [comment]
@pdavies88 Hey Preston, I'll come find you in a lil' bit and take a look.
