### ISSUE TITLE
issue with resources in routes

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project2#98]
I tried setting up my resources as two separate hierarchies instead of a single hierarchy of three resources. I expected this to avoid the creation of convoluted routes. Instead, I am having problems with  capturing the correct value in my resource of :stores.

I've searched the documentation I can find online for an answer as to how to best set up more than two resources in a hierarchy without excessive nesting, but don't understand enough to see whether there's a solution to my problem.

I feel that I'm making a poorly informed decision on something that will have an effect on the functionality of my project. Help!

```
Rails.application.routes.draw do
  # set up root route for devise to reroute to after successful login
  root 'stores#index'

  # alias user routes for account
  devise_for :users, :path => 'accounts'

  # next post resource under user
  resources :users do
    resources :stores
  end

  resources :stores do
    resources :items
  end

```

**Comment by RobertAKARobin** [comment]
Can you switch to having 3 nested routes?

That would mean updating your routes file, then going through your views to update the various `link_to`.

**Comment by adrianshep** [comment]
I can try it. I was avoiding it on account of what I'd read in documentation and heard from classmates warning against it. It's a situation of not knowing what I don't know. Thanks.

**Comment by RobertAKARobin** [comment]
Sure! It shouldn't be too rough. But you're undoubtedly going to run into situations where your app breaks because a `link_to` wasn't formatted correctly. Don't stress when that happens: just go into the view and fix the `link_to`. Ask if you need help!

**Comment by adrianshep** [comment]
Coming across broken links but following rake routes and fixing them. Thank you!

**Comment by adrianshep** [comment]
Clicking on edit link in store show page and expecting edit form, getting:

```
NoMethodError in Stores#edit
Showing /Users/adrianshepelavey/wdi/projects/price-parser/app/views/stores/edit.html.erb where line #3 raised:
undefined method `store_path' for #<#<Class:0x007...
```

The edit link in the show page:

```
<li><%= @store.name %></li> <%= link_to("Edit", edit_user_store_path(current_user, @store), :class => 'action edit') %>
```

(I redefined store path to edit_user_store_path as per rake routes.)

routes.rb is now:

```
resources :users do
    resources :stores do
      resources :items

```

**Comment by RobertAKARobin** [comment]
Can you show the contents of the `Stores#edit` action? I'm wondering how you're setting `@store`.

**Comment by adrianshep** [comment]
```
def edit
      @store = Store.find(params[:id])
end
```

**Comment by RobertAKARobin** [comment]
You know, come to think about it, you probably don't need a `users` resource at all. That would only be if you want to have `Users#show` and `Users#index` pages, which you probably don't — or probably shouldn't, anyway, since that's outside the scope of your MVP.

I'd say remove `resources :users` from your routes altogether, and instead just have:

```
resources :stores do
  resources :items
end
```

Then, to edit a store, you can just do:

```
<li><%= @store.name %></li> <%= link_to("Edit", store_path(@store), :class => 'action edit') %>
```

To find the current user's stores, it's just `current_user.stores`.

Does that make sense?

**Comment by adrianshep** [comment]
So you're saying Devise will allow me to get rid of users as a resource but will still give me access to current_user, correct?

**Comment by RobertAKARobin** [comment]
Yup!

**Comment by RobertAKARobin** [comment]
Sorry to not have caught that sooner!

**Comment by adrianshep** [comment]
No problem, and I just committed in preparation for the change.

**Comment by RobertAKARobin** [comment]
:+1: Good plan.

**Comment by adrianshep** [comment]
Looks like full CRUD on stores, praise Frigg! 
Thank you!

**Comment by RobertAKARobin** [comment]
Wooo!
